### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by sobi3ch** [build-trust/ockam#1017]
It looks like all links in below document are broken
https://github.com/ockam-network/ockam/blob/main/documentation/architecture/decisions/0001-record-architectural-decisions.md

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa

**Comment by mrinalwadhwa** [comment]
replace with this https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions

**Comment by etorreborre** [comment]
The link to the ADRs have been removed from the README (those files possibly need to be reviewed and updated now)
