### ISSUE TITLE
CLI for interacting with Ockam Hub

### ISSUE THREAD

**Issue by mjc** [build-trust/ockam#1068]
We need to build a CLI that authenticates with github and allows access to Ockam Hub, so that users can configure the resources we provide in Ockam Hub without using a browser.

https://docs.github.com/en/developers/apps/authorizing-oauth-apps#device-flow

**Comment by piiih** [comment]
Hi @mjc , I accessed the Ockam Hub but I only see the Ockam Hub Address when I did the Github's Authentication, so that CLI just need to do the authentication and return this address?

**Comment by mrinalwadhwa** [comment]
Hi @piiih, yes that would be a great start and would simplify some of our Getting Started examples.

**Comment by piiih** [comment]
@mrinalwadhwa I'm trying to push a branch, but I have no permission :(

**Comment by mrinalwadhwa** [comment]
Hi @piiih.

We accept pull requests from Github forks.

This is a good guide Github on forks
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

Also checkout our contributing guide
https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING

Please ask more questions if anything comes up.
Looking forward to our pull request!!

**Comment by piiih** [comment]
@mrinalwadhwa I don't know if I had a missunderstood, but the contributing guide tells to create new branch

**Comment by mrinalwadhwa** [comment]
> but the guide tells to create new branch.
Thanks for pointing that out, we should fix it. PRs [welcome](https://github.com/ockam-network/website/blob/develop/src/content/learn/how-to-guides/contributing/CONTRIBUTING.md#pull-requests).

@mjc can shed more light on the current api.

**Comment by piiih** [comment]
@mjc can you help me with the API? If there is a docs I can read, just send it to me :)

**Comment by piiih** [comment]
@mrinalwadhwa Well, I'll open the PR without the integration with your API, ok? :)

**Comment by mrinalwadhwa** [comment]
@piiih that would be great! Sorry for the slow response on this. A lot was changing this past week as we raced towards a series of releases.
