### ISSUE TITLE
Elixir: improve vault

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1090]
1. `ockam_vault_software` elixir application, currently, cannot be built independently .. it  has some relative path dependencies on ockam rust crates
2. the api exposed from `Ockam.Vault` and `Ockam.Vault.Software` that wrap around the NIF calls is not very nice. We should name the parameters properly and add some type spec to make things better for dialyzer.

**Comment by etorreborre** [comment]
@mrinalwadhwa has the first part of the issue been addressed?
