### ISSUE TITLE
Elixir - Rename Ockam.Message to Ockam.Routable

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1221]
The Ockam Routing Layer message in our Elixir implementation is defined by the abstract [`Ockam.Message` protocol](https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam/lib/ockam/message.ex).

A more descriptive name for this protocol would be `Ockam.Routable` we should use that instead.

This will require changing code in:
https://github.com/ockam-network/ockam/tree/develop/implementations/elixir

**Comment by hairyhum** [comment]
Reviewing the [PR](https://github.com/ockam-network/ockam/pull/1263) it seems like Ockam.Routable makes things more confusing, because we still use `handle_message` and `message_handler`, while renaming them to `handle_routable` and `routable_handler` doesn't look that descriptive.
WDYT?

**Comment by mrinalwadhwa** [comment]
Makes sense, closing.
