### ISSUE TITLE
Elixir - improve vault native functions

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1223]
[Ockam.Vault](https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam/lib/ockam/vault.ex) delegates to a specific Vault implementation module like [Ockam.Vault.Software](https://github.com/ockam-network/ockam/blob/mrinal/wwais/wire_decoder_raise_exp/implementations/elixir/ockam/ockam_vault_software/lib/vault_software.ex)

`Ockam.Vault.Software` delegates to a native functions (NIFs) that written in C ... these [C functions in turn delegate](https://github.com/ockam-network/ockam/blob/mrinal/wwais/wire_decoder_raise_exp/implementations/elixir/ockam/ockam_vault_software/native/vault/software/vault.c#L386) to the [Rust Vault implementation](https://github.com/ockam-network/ockam/tree/mrinal/wwais/wire_decoder_raise_exp/implementations/rust/ockam/ockam_vault) via the [Rust ffi](https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_ffi).

The code in [Ockam.Vault](https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam/lib/ockam/vault.ex) and [Ockam.Vault.Software](https://github.com/ockam-network/ockam/blob/mrinal/wwais/wire_decoder_raise_exp/implementations/elixir/ockam/ockam_vault_software/lib/vault_software.ex) currently uses `a, b, c` etc. as parameter names.

To makes the elixir APIs better, we need to uses the right variable names and define appropriate type specs.

**Comment by Maartz** [comment]
Hi !
Any more intel on this one ?

**Comment by SanjoDeundiak** [comment]
I think ffi is deleted in the new Identity implementation.
