### ISSUE TITLE
Multiple versions of same dependencies

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1431]
I noticed in recent build logs that multiple versions of the same dependencies are pulled.
We should look into why this happens and if it's avoidable. 

![Screen Shot 2021-05-27 at 2 11 56 PM](https://user-images.githubusercontent.com/159583/119897782-ccf7f800-bef5-11eb-9189-c892d6d7ae40.png)
![Screen Shot 2021-05-27 at 2 11 50 PM](https://user-images.githubusercontent.com/159583/119897784-cd908e80-bef5-11eb-9188-7973811b08ab.png)
![Screen Shot 2021-05-27 at 2 11 24 PM](https://user-images.githubusercontent.com/159583/119897785-ce292500-bef5-11eb-80d1-05b36047ff05.png)
![Screen Shot 2021-05-27 at 2 08 32 PM](https://user-images.githubusercontent.com/159583/119897787-ce292500-bef5-11eb-9be0-86669ff1e182.png)

**Comment by psinghal20** [comment]
There is one more dependency to add to this: `heapless` which requires both 0.6.1 and 0.7.1. While upgrading it in `signature_core`, I observed that it is an internal dependency for crate `bls12_381_plus` where it is required in `0.6.1` version whereas we have upgraded its version to `0.7.1`.

**Comment by etorreborre** [comment]
@mrinalwadhwa that happens because of transitive dependencies. It is actually hard to fully avoid other than:

 - using dependabot to make regular updates
 - sometimes making pull requests on some of our dependencies to upgrade their dependencies

So I propose that we close this issue for now
