### ISSUE TITLE
Create a Rust embedded vault implementation

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#150]
Can there be a pure rust vault implementation that talks to some peripheral cryptographically capable hardware module?

The vault interface has the following functions
https://github.com/ockam-network/ockam/blob/develop/implementations/c/include/ockam/vault.h

We've experimented with getting implementations of these functions from hardware cryptographic co-processors using C - can the same be done in pure rust?

### Related Issues

* #2555

**Comment by vlisivka** [comment]
I can take this ticket. I have Nordic Thingy:91, which has support for CyrpoCell. However, it looks like the code is changed a lot after creation of this ticket. @mrinalwadhwa , can you update ticket description, please?

**Comment by mrinalwadhwa** [comment]
Hi @vlisivka thank you for offering to spend time on this. I'll add some updated notes to the issue in the next few hours.
