### ISSUE TITLE
Create a bluetooth transport

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#153]

**Comment by mrinalwadhwa** [comment]
https://github.com/deviceplug/btleplug
https://github.com/dfrankland/bluster

https://crates.io/crates/bluetooth-hci/

**Comment by mrinalwadhwa** [comment]
@prax-dev and @krishnakumar4a4 offered to collaborate on this issue.

**Comment by mrinalwadhwa** [comment]
Some context:

This picture is a good way to visualize the functionality that we're building towards in Ockam.
The focus of this issue in the Bluetooth Transport in red.
![Screen Shot 2020-09-25 at 7 39 08 PM](https://user-images.githubusercontent.com/159583/94953062-c666cd00-049b-11eb-9890-cc734ed93db6.png)

- If Bluetooth Transport can work with the Routing layer, it will automatically work with the other parts of Ockam ... so we can focus on making a Bluetooth Transport that works with Ockam Routing.

- A simple sanity test case for this would be - can we make a message travel over **two hops** of bluetooth.

  - Imagine three devices `A`, `R` and `B`. 
  - `A` has a bluetooth connection to `R`
  - `B` has a bluetooth connection to `R`
  - `A` and `B` don't have a direct connection
  - Our goal is to move message from A to B via R

```
+-----+           +-----+            +-----+
|  A  | --------->|  R  |----------->|  B  |
+-----+           +-----+            +-----+
```

- We want this to be usable in both Rust and Elixir (later in C and other languages).

- We'll eventually want to support various Bluetooth hardware modules (like chips from Nordic etc.) but let's start with the Bluetooth support in major operating systems.

- The following Rust crates look interesting as a starting point
https://github.com/deviceplug/btleplug
https://github.com/dfrankland/bluster
https://crates.io/crates/bluetooth-hci/

- There are prototype implementations of the routing functionality in both Rust and Elixir.

This effort will likely involve:
- [ ] build bluetooth transport in Rust https://github.com/ockam-network/ockam/tree/develop/implementations/rust
- [ ] make this rust bluetooth transport work with ockam routing in rust
- [ ] expose an FFI, like we do for vaults https://github.com/ockam-network/ockam/tree/develop/implementations/rust/vault/src
- [ ] write a Erlang NIF layer, like we do for vaults https://github.com/ockam-network/ockam/tree/develop/implementations/elixir/ockam/ockam_vault_software/native
- [ ] call the NIF layer in Elixir to write an elixir idiomatic Bluetooth Transport
- [ ] make this elixir bluetooth transport work with ockam routing in elixir

Let's build this in small increments and merge pieces into `develop` as they get ready instead of waiting for the whole thing to be ready.

Hope this provides the context needed to start, please ask more questions.

**Comment by mrinalwadhwa** [comment]
Simple first steps to get started:

Using the 
1. Create a `bluetooth` crate with simple hello world function. https://github.com/ockam-network/ockam/tree/develop/implementations/rust
2. expose that function over FFI, C header, NIF
3. Create a `ockam_transport_bluetooth` elixir app at https://github.com/ockam-network/ockam/tree/develop/implementations/elixir/ockam
4. Call the hello world function in Elixir

The `vault` create and `ockam_vault_software` elixir app are good reference for this.

@SanjoDeundiak from our team is closely familiar with that setup and can help along the way.
@nilslice and I will help along the way with any other questions or process.

**Comment by nilslice** [comment]
👋   @prax-dev and @krishnakumar4a4 - nice to meet you both. Happy to help however I can to get you started. Let's use this issue as the primary point for discussion.
