### ISSUE TITLE
`ockam_vault_extern_error_t`'s definition/lack of documentation might encourage memory leaks.

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#1562]
When filing #1561, I noticed an issue which is plausibly a bit more serious. Specifically,  `ockam_vault_extern_error_t::domain` is allocated by `CString::into_raw` (which notes that it's C's responsibility to free https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_ffi/src/error.rs#L37), but no API to free resources managed by the `ockam_vault_extern_error_t` is provided, nor is the fact that it's needed documented.

Moreover, this field being a `const char*` parameter implies that it'd be invalid for the caller to free it. If I saw this in a C api, I'd probably expect that it's a pointer to a static error description string.

That said, fixing this is kind of a pain, and maybe it doesn't matter in practice, since errors should be rare — I'm only careful about noticing it since my background includes a lot of FFI work, including a [very similar](https://docs.rs/ffi-support/0.4.3/ffi_support/struct.ExternError.html) type.

**Comment by SanjoDeundiak** [comment]
Thanks @thomcc for submitting this issue. We used to have static strings for error domains, but it was impossible to use with our Actor model. More details here https://github.com/ockam-network/ockam/pull/967
Creating API for freeing memory is something that needs to be done and integrated into our ffi layer. If you're up to doing that, it would be great!

**Comment by etorreborre** [comment]
This was fixed with this PR: https://github.com/build-trust/ockam/pull/2138
