### ISSUE TITLE
Add type to PublicKey struct

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#1573]
Various Ockam protocols, like secure channels, key lifecycle, credential exchange, device enrollment etc. depend on a variety of standard cryptographic primitives or building blocks. Depending on the environment, these building blocks may be provided by a software implementation or a cryptographically capable hardware component.

In order to support a variety of cryptographically capable hardware we maintain loose coupling between our protocols and how a specific building block is invoked in a specific hardware. This is achieved using the [Vault traits](https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_core/src).

[SoftwareVault](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_vault/src/software_vault.rs) is in-memory, software only implementation of the Vault traits.

Currently PublicKey is defined like a [vector](https://github.com/ockam-network/ockam/blob/21b47e742de04c439947e50a46b4e0870d15094a/implementations/rust/ockam/ockam_vault_core/src/types.rs#L74) and doesn't have any info about cryptography it's used for. At the moment we have P256, Curve25519 and BLS type public keys, it would be great to be able to retrieve this type from PublicKey struct. This would allow us to remove workarounds like [this](https://github.com/ockam-network/ockam/blob/21b47e742de04c439947e50a46b4e0870d15094a/implementations/rust/ockam/ockam_vault/src/verifier_impl.rs#L15), where we assume PublicKey type depending on the key's length.

---
_If you would like someone to help / mentor / pair program with you as you work on your first Ockam issue, please leave a comment on [this discussion.](https://github.com/ockam-network/ockam/discussions/1081)_

**Comment by 0x00A5** [comment]
This seems completed already.
* Type is present under [`PublicKey`](https://github.com/build-trust/ockam/blob/07f0086d33ddcbd7d0515429230b163f9780c8ee/implementations/rust/ockam/ockam_core/src/vault/types.rs#L87-L90)
* And it's used by [`Vault::verify()`](https://github.com/build-trust/ockam/blob/07f0086d33ddcbd7d0515429230b163f9780c8ee/implementations/rust/ockam/ockam_vault/src/verifier_impl.rs#L15)

**Comment by mrinalwadhwa** [comment]
Thank you, finding issues we can close is every helpful!
