### ISSUE TITLE
Build an async test harness for Node and Worker testing

### ISSUE THREAD

**Issue by jdspdx** [build-trust/ockam#1576]
Writing tests for nodes and workers is complex due to their async nature. In tests we can't use the #[ockam::node] attribute, and instead use the method of

```rust
let (ctx, executor) = ockam::start_node()
executor.execute(async move { ...
```

This method has problems: if a test assertion fails inside of this async block, the test will not fail. Instead, the Node remains alive. I believe this is because the assertion is not propagating all of the way up somehow.

We'd like to improve and simplify this testing experience:

1. What can we use to improve async testing of nodes?
2. Can we make creating test nodes as easy as creating real nodes?
3. How can we get assertion failures to fail the whole test?
4. Where are there opportunities for mocks and fixtures?

**Comment by etorreborre** [comment]
Fixed with https://github.com/build-trust/ockam/pull/1904
