### ISSUE TITLE
Create a Go software vault implementation

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#166]

**Comment by sivachandran** [comment]
@mrinalwadhwa can you provide more context on this implementation? I understand it is about implementing Vault functions in Go code. But I don't get the context of why it needs to be done. Maybe I missed to read some docs, please point me.

**Comment by etorreborre** [comment]
@mrinalwadhwa should we close this issue now?

**Comment by mrinalwadhwa** [comment]
Yes, some of these really old ones can be closed
