### ISSUE TITLE
Compatibility with the smaller Cortex-M processors

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#172]

**Comment by fkouteib** [comment]
ARM supports Trust Zone on M-series based on [ARM v8-M](https://developer.arm.com/ip-products/security-ip/trustzone/trustzone-for-cortex-m) but not ARM v7-M. Is that what's being captured here versus ARM A-series trust zone work in #151? or do you envision another mechanism for vault support on older ARM M-series?

**Comment by mrinalwadhwa** [comment]
#1521 #541

**Comment by antoinevg** [comment]
#1831
