### ISSUE TITLE
Changes to `ockam_ffi` should trigger build/test of the Elixir `ockam_vault_software` package

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#1802]
I've noticed that https://github.com/ockam-network/ockam/pull/1801's batch of CI tasks doesn't include the Elixir code that uses the FFI bindings.

I think it would be good if changes to code inside https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_ffi would trigger running the relevant Elixir build/test, for https://github.com/ockam-network/ockam/tree/develop/implementations/elixir/ockam/ockam_vault_software at the very least.

**Comment by metaclips** [comment]
Merged https://github.com/build-trust/ockam/pull/2022
