### ISSUE TITLE
Switching to a Unified Rust Workspace

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#1815]
Right now, we don't use a cargo workspace. There are a number of reasons for this, and I didn't intend to fight it much since I didn't care much and the rationale seemed sound.

Unfortunately, it turns out that I have a... reason to care more than I expected.

As it is, rust-analyzer in the ockam repo uses at least 3GB of RAM, often as much as 5GB<sup>1</sup>. My work computer is an Apple M1 laptop with only 8GB of RAM, which means memory usage this high caused... significant problems.

(I had a vague theory that having a single workspace would improve this, since it's a single SourceRoot rather than one-per-crate — this turned out to be true)

I chatted with Sanjo about it, and he encouraged me to re-open the discussion here, so I spent some time today investigating if it's feasible (e.g. taking a stab at it, and seeing how much of a quagmire I got into).

on the list of things I wanted to look into for "significant changes" so I did a quick-ish check as part of the investigation for larger changes, since Sanjo also agreed it was worth opening.

You can take a peak in the thomcc/workspace-idea-wip branch, although it's worth noting that this was just an experiment to see if it would help my issue, and to see if any major issues stand in the way here. It isn't very cleaned up or completely finished.

### Build/Test/IDE Perf

So, I was right that this would help, and it has a bunch of other benefits around general build/test performance (and overall pleasantness when using less-powerful machines):

1. For the question I came in with: this reduces rust-analyzer's baseline memory usage on my machine to about ~1GB of ram (~800MB really), so over 3x less than when using the many linked projects approach.

2. It also reduces the disc usage of the repo after doing a build of the tests from 13GB to 3GB (after cleaning out now-unneeded target files).

   I remember hearing that github action caching wasn't really working well for us, and it seems highly likely that this will improve things.

   Longer term, if we pursue this, I suspect this might mean it's more beneficial to have CI parallelize things less than we do, since much of the build is redundant work that can be shared.

3. `cargo test` from the root can be used to run all of the tests over all the crates.

   Doing so completes in ~2 minutes on my machine, wheras previously invoking `pushd implementations/rust; ../../gradlew test; popd` took around 10 minutes. (Note: these numbers are from fully clean repos — either cargo clean, or completely nuking ever `target` folder by hand)

4. Running rust tests in gradle (at least, the way I've been doing: `pushd implementations/rust; ../../gradlew test; popd`) still works.

   From a fully clean build, this takes just under 3 minutes (as mentioned down from 10 minutes).

    - I haven't touched the gradle stuff, so I think at the moment `cargo test` is actually more thorough, but I could be wrong.
    - While this is running, my computer is actually usable, whereas previously the full gradle test would overwhelm things with build parallelism to the point where it would lock up.

5. There are a few other things I have a harder time quantifying. `rust-analyzer` has to index ~5x fewer crates on startup (now it indexes 1500, previously over 8000).

Also, note that this theoretically is doing more work now (we're building everything in `implementations/rust/ockam/ockam_examples/example_projects` too (see below), means there are several additional crates and dependencies).

### `implementations/rust/ockam/ockam_examples/example_projects` now gets built and checked.

Much of this folder had significantly bitrotted code, which (of course) is not something we want in the repo, especially for examples (having examples not compile correctly would be very discouraging for using a library).

I fixed<sup>3</sup> it in my draft linked above. Or at least, I fixed it when the fix was clear, and in other cases I either took a stab or just made it build and left a TODO/FIXME/XXX comment. That is: I'd appreciate some eyes on the changes inside that folder, sans one of the commits where I ran `rustfmt` (this is self contained in a dedicated commit), since those folders weren't getting it at all.

Anyway, this could still be done under the old scheme (e.g. without using a unified workspace, but it would add ~11 new crates to our workspace, which seems less than ideal). For this, I don't think it's noticable.

It was good to go through this anyway, since I got a lot of familiarity with different APIs, and have some... thoughts about how things are organized, at least: how they're divided into different crates. This is not a problem that's relevant to this issue, though.

### Various less conrete benefits

Having `cargo test` / `cargo build` work normally means tooling support is better and it's easier to onboard contributors. (... I'd have written more here if the concrete benefits were less convincing)

## Downsides

There's some downsides here too.

1. It's probably not *ideal* that dependency-heavy example code is being built by default. I had this problem when working at mozilla, and ended up coming up with / writing [this document][moz-test-faster] to describe how I hoped we'd avoid this problem in that workspace. That said, that approach is not without drawbacks, and the issue is much less pronounced in ockam for various reasons, so I think its not worth sweating.

    Given that the alternative to this seems to be that we end up with broken examples<sup>2</sup>... I think this is a net benefit, but it's probably worth finding a balance.

2. Cargo features become more of a hassle. We have various features which are mutually exclusive (e.g. you can't turn on `alloc` and `std` at the same time). This is a bad practice (and actually unnecessary in the std/alloc case, since `std` is a superset of `alloc`), and something I want to fix, but in my experiment, it didn't end up causing many problems the way I had expected.

   That said, if you do global `cargo build` or `cargo test` from the top level, it might turn on a feature you don't expect. This has a few solutions/workarounds:
    - cd into the directory of the project you need to be careful about features for before invoking the build.
    - build just the crate/package in question as `cargo build -p $pkgid` or `cargo build --manifest-path path/to/Cargo.toml`. These aren't equivalent, but for this they'll both work.

   That said, I expect this will hurt the no_std stuff in the pipe, and it might need to do things the way we do now (e.g. excluded from the workspace).

   Anyway it doesn't seem that bad, since in the worst case, we just do the same thing we do currently.

3. Every build target (which include examples, binaries, etc) needs to have a globally unique name in the workspace. This is annoying, since we have multiple examples named e.g. `bob` or `alice`. There's not really a workaround though, which means I had to rename several of the example executables to avoid collision

4. I need to think about how we manage stuff like `cargo deny` and dependency tracking. This decidedly makes the situation harder, since now our lockfile has many dependencies we don't care about at all, since they're only in examples.

    I have a few ideas about this, but nothing concrete yet and I need to figure out what we need here.

[moz-test-faster]: https://github.com/mozilla/application-services/blob/6586eb9533ca3c17d013ab48d67647c9d858c1a6/docs/design/test-faster.md

## Conclusion?

This seems like a clear win, and will only become more important (and harder to switch to) as ockam gets bigger/contains more crates, since the build time scales very poorly<sup>3<sup> under the current setup.

That said, I wasn't around last time this was discussed, so I don't know the full set of things that we're worried about (although, I suspect most of the concerns can be worked thorough)

#### Footnotes
1: It's pretty clear it would use more if it could too, since at 5GB I have no more free RAM, and it's constantly swapping.

2: And seemingly broken APIs if they have no other coverage — the way things were set up, I don't believe anything in `ockam::protocols::stream` was available, since its glob-import is shadowed by the actual `ockam::stream` module. I think this was just not noticed? (Note: I don't think my solution is ideal, I just wanted to get stuff building)

3: Under the current (fully separate) system, if we perform builds of two crates, even if they depend on eachother or have similar dependencies, no work is able to be reused. Also, since ockam crates usually depend on other ockam crates... this means that this will tend towards at worst `O(n^2)` build time with respect to how many crates we have.

(In practice it wouldn't be quite `n^2` for realistic project organization, but it could be (and is) pretty bad despite this)

**Comment by antoinevg** [comment]
I've had nightmares trying to support both `std` and `no_std` targets with Rust Workspaces the last time I tried but I don't think it's a problem here given we can always fall back to gradle. 

The performance improvements alone are probably worth an order of magnitude for community happiness, this is awesome!

**Comment by thomcc** [comment]
I'm very aware the headaches you're referring to, yeah.

There are a few problems around how we're using cargo features that make the issue worse than it needs to be (expect another github issue on this soon), but actual embedded chips... things don't work the way cargo wants, since there are dependencies you need only on no_std, which interacts... suboptimally with how features work.
