### ISSUE TITLE
Fix possible Worker deadlock

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#1853]
We have deadlock [here](https://github.com/ockam-network/ockam/tree/ockam_v0.27.0/implementations/rust/ockam/ockam_entity/src/worker/entity_worker.rs#L190) if spawn call is removed. The problem is that called function require interaction with the same worker that it's called from to succeed, but worker is busy and cannot respond, since it waits for that function to finish.

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak is this still relevant?
