### ISSUE TITLE
Docs: Update Ockam Crate Description

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1919]
- [ ]  Change [Ockam Crate Description](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam/src/lib.rs#L1-L4) to: 
```
End-to-end encryption and mutual authentication for distributed applications.
```
- [ ] Add [Hello Ockam](https://github.com/ockam-network/ockam#hello-ockam) example to the [Ockam Crate Description](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam/src/lib.rs#L1-L4)

**Comment by mrinalwadhwa** [comment]
Awesome! Thank you @pcopley ... let us know if you have questions.

**Comment by manavsiddharthgupta** [comment]
hey @mrinalwadhwa if no one is working on this.
i would love to work on this.

**Comment by mrinalwadhwa** [comment]
Hey @manavsiddharthgupta that would be awesome!!
Thank you. All yours.

Note I made minor edits to description text in the issue [description above](https://github.com/ockam-network/ockam/issues/1919#issue-1015400024)

**Comment by mrinalwadhwa** [comment]
Closing since this was updated. Thank you @manavsiddharthgupta & @pcopley
