### ISSUE TITLE
Example: End-to-End Encrypted communication between two Raspberry Pis

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#1929]
Use the code from one of these guides to create an example that involves devices talking to each other

End-to-End Encryption with Rust
https://github.com/ockam-network/ockam/tree/develop/documentation/use-cases/end-to-end-encryption-with-rust#readme

End-to-End Encryption of existing application without changing their code - with TCP Inlets and Outlets
https://github.com/ockam-network/ockam/tree/develop/documentation/use-cases/end-to-end-encrypt-all-application-layer-communication#readme

**Comment by nk7608** [comment]
Can I work on this issue?

**Comment by mrinalwadhwa** [comment]
Closing for now, we can reopen if someone wants to work on this.
