### ISSUE TITLE
Elixir implementation for TCP inlet-outlet tunnels (portals)

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#1961]
TCP tunnels allow to tunnel TCP traffic through Ockam Routing by wrapping TCP packets into Ockam Messages:
https://github.com/ockam-network/ockam/tree/develop/documentation/use-cases/secure-remote-access-tunnels

In Rust tunnels(portals) are implemented as following:

Setup:
Inlet Listener listens to incoming TCP connections on a port
Outlet Listener waits for an empty `ping` message from inlet and connects to predefined host:port for an outgoing connection
Inlet Listener knows a route to the outlet listener

Tunnel establishment:
When Inlet Listener receives a TCP connection, it creates an Inlet Worker for this connection.
Inlet Worker first sends a `ping` message to the outlet listener and waits for `pong` from the Outlet Worker
Outlet Listener when receiving the `ping` message from the Inlet Worker creates the Outlet Worker
Outlet Worker creates the outgoing connection and sends an `pong` to the Inlet Worker
After receiving the `pong` Inlet Worker starts to process TCP packets

TCP tunneling:
Inlet Worker stores a route to the Outlet Worker, which it gets from the `pong` message
Outlet Worker stores a route to the Inlet Worker, which it gets from the `ping` message
Inlet and Outlet workers wrap TCP messages into Ockam Routing messages and send them to these routes
Inlet and Outlet workers unwrap Ockam Routing messages and send them to the TCP connection

More on tunnels implementation here: https://github.com/ockam-network/proposals/tree/main/design/0012-portals

Elixir implementation should be Message Compatible with Rust implementation. Inlet created in Rust should be able to connect and forward wrapped messages to an Outlet in Elixir and vice versa.

**Comment by polvorin** [comment]
Hi @hairyhum , I'd like to work on this.  Got a couple of questions:
* I guess at this level, we don't need to worry and  can assume the worker-to-worker communication is reliable, and [absolutely ordered](https://github.com/ockam-network/ockam/blob/develop/documentation/architecture/messaging/Ordering.md)?  with wrappers workers implementing that functionality if the underling transport doesn't provide it (for example if inlet-outlet  communication happens via UDP)?
* Related to the previous one,  wonder if there is already a mean to detect that the other end is not responsible anymore?.  Lets say the inlet runs on host `A`,  and outlet on host `B`.   For some reason host `B` (or just the outlet worker on it) is restarted/crash/become unreachable.   How do the inlet worker on `A` detect this?.  Could implement some form of hearbeat/keepalive in the tunneling protocol, but feels this could be a common requirement that could already exists or make sense to provide as a [building block](https://github.com/ockam-network/ockam/tree/develop/documentation/architecture/messaging)  ?

**Comment by hairyhum** [comment]
Addressed in #2561
