### ISSUE TITLE
Automate production of elixir FFI universal binary (for macOS)

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2012]
A while ago, to produce the prebuilt universal binary for elixir, I had to manually perform the build on an intel macbook, and send the resulting binary to @hairyhum. It would be nice to automate this (I'd like not to have to produce the next one) — there's no reason that it can't be done from a mac machine on either arm or intel.

Without cmake, the rough process is https://gist.github.com/thomcc/186bfed22c3f41aa675bac5464af1ed2. That code hasn't been exhaustively tested, but is pulled from something I did manually, so is the basic idea. It also notes a bunch of limitations.

I think there's probably a way to make it work with cmake, but I didn't try — my experience with cmake and cross compilation has been... bad.

I also don't think replacing cmake with a random shell script would be a step forward, so this should integrate into one of the existing build systems we use here (of which there are several).

**Comment by thomcc** [comment]
Hm, in principal, although normal `cc` on macOS can cross compile/link in this case just as easily, and last time I checked `zig cc`'s ability to cross-link on macOS was experimental. Also, I don't know that it has an equivalent to `lipo`, at the moment.

That said eventually `zig cc` could probably allow much more robust cross compilation in general — definitely a thing I'm keeping an eye on.

**Comment by hairyhum** [comment]
@thomcc using your script with some changes: #2274 I've recreated the lib, but it's quite big (15MB). I think we need to reduce the size before we add a new one to the repo.

**Comment by thomcc** [comment]
Are they stripped? We might need to strip things, I can look on monday, I'm not sure I did reasonable things with debuginfo in that script.

**Comment by hairyhum** [comment]
I don't know if it's stripped or not.
I believe we need some parameters here: https://github.com/ockam-network/ockam/pull/2274/files#diff-406af3a2533c90d15641c34640b9691dc1ded9b7c265c5d996fde5d3843b719cR45
