### ISSUE TITLE
Fix RUSTSEC-2020-0071 and RUSTSEC-2020-0159 (Time 0.2.23 fails to determine local offset and Potential segfault in `localtime_r` invocations)

### ISSUE THREAD

**Issue by jdspdx** [build-trust/ockam#2025]
A [vulnerability](https://rustsec.org/advisories/RUSTSEC-2020-0071.html) has been retroactively updated and has been shown to impact users of the `chrono` crate.

At this time (Oct 18, 2021) there is no fix available. The issue has been shown to cause[ problems in production](https://github.com/time-rs/time/issues/296#issuecomment-734801026).

We should continue to monitor the situation and apply a fix when it becomes available, or find a workaround.

**Comment by etorreborre** [comment]
This vulnerability has been fixed as part of https://github.com/build-trust/ockam/pull/3502
