### ISSUE TITLE
Some mechanism for performing all CI tasks on a PR

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2225]
It would be nice if there were a way to run all CI tasks prior to landing (I'd have used it on #2221, for example).

There may be a way to have actions you can manually trigger, which seems ideal.

There are also other ways to achieve this, such as a file you can modify which triggers all of CI. Other options I've seen in other projects are triggering this sort of thing with a bot (rust-lang/rust uses this option), or with a special commit message you push to a fake branch (which is used by mozilla-central, but... would be a bit involved to set up)

**Comment by mrinalwadhwa** [comment]
Recent PRs have added `workflow_dispatch` triggers to workflows.
So this mechanism could be some script based on `gh workflow list` and `gh workflow run`

**Comment by metaclips** [comment]
> It would be nice if there were a way to run all CI tasks prior to landing
I believe we have this support with GitHub merge queue as `all CI tasks` are run after PR branch is rebased for a merge.
