### ISSUE TITLE
Fix Gradle tasks on Windows

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2250]
In #2245 an attempt was made to fix our gradle tasks on Windows. Unfortunately, it ended up being partially reverted due to issues it caused with the elixir build, meaning we currently don't work on Windows.

At some point, it would be nice to fix this, but this issue documents the non-working status.

CC @BlackHoleFox who wrote the original PR (but no pressure to continue if you don't have the time/interest)

**Comment by mrinalwadhwa** [comment]
https://github.com/ockam-network/ockam/pull/2308 started work in this direction.
`./gradle tasks --all` now succeeds on windows.

Now the windows build will likely fail on missing tools. We should add a grace full check for required tools.

**Comment by mrinalwadhwa** [comment]
We have enough of nix + make environment to start removing gradle. Closing this in favor of that plan
