### ISSUE TITLE
Consider merging ockam_*_core creates into ockam_core

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#2263]

**Comment by thomcc** [comment]
Yes, we should move these. I think ockam_vault_core also needs a bit of a rework.

**Comment by mrinalwadhwa** [comment]
Here's one reason for why we should do this:

```
» cargo tree --package ockam_core --depth 1
ockam_core v0.40.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_core)
├── async-trait v0.1.51 (proc-macro)
├── core2 v0.3.2
├── futures-util v0.3.17
│   [build-dependencies]
├── hashbrown v0.11.2
├── heapless v0.7.8
├── hex v0.4.3
├── ockam_macro v0.1.0 (proc-macro)
├── ockam_message_derive v0.1.0 (proc-macro) (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_message_derive)
├── rand v0.8.4
├── serde v1.0.130
└── serde_bare v0.5.0
```

```
» cargo tree --package ockam_vault_core --depth 1
ockam_vault_core v0.34.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_vault_core)
├── cfg-if v1.0.0
├── ockam_core v0.40.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_core)
├── serde v1.0.130
├── serde-big-array v0.3.2
└── zeroize v1.4.3
```

```
» cargo tree --package ockam_key_exchange_core --depth 1
ockam_key_exchange_core v0.32.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_key_exchange_core)
├── ockam_core v0.40.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_core)
├── ockam_vault_core v0.34.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_vault_core)
└── zeroize v1.4.3
```

There seems to be no dependency loose coupling win from keeping `ockam_key_exchange_core` & `ockam_vault_core` separate from `ockam_core`

**Comment by mrinalwadhwa** [comment]
For contrast, this is a crate we shouldn't merge into `ockam_core` .. at least not in its current state. 

```
» cargo tree --package signature_core --depth 1
signature_core v0.30.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/signature_core)
├── blake2 v0.9.2
├── bls12_381_plus v0.5.2
├── digest v0.9.0
├── ff v0.10.1
├── group v0.10.0
├── hashbrown v0.11.2
├── heapless v0.7.8
├── rand_core v0.6.3
├── serde v1.0.130
├── serde-big-array v0.3.2
├── subtle v2.4.1
└── typenum v1.14.0
[dev-dependencies]
├── rand v0.8.4
└── serde_json v1.0.71
```

It seems to tightly coupled to bls and blake2 in its current state.

**Comment by mrinalwadhwa** [comment]
This one is interesting:

```
» cargo tree --package ockam_transport_core --depth 1
ockam_transport_core v0.14.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_transport_core)
├── ockam_core v0.40.0 (/Users/mrinal/Workspace/ockam-network/ockam/implementations/rust/ockam/ockam_core)
└── tracing v0.1.29
```

@SanjoDeundiak mentioned recently that we can extract common parts of `ockam_transport_tcp` & `ockam_transport_websocket` into `ockam_transport_core` ... those common parts I suspect won't overlap enough with `ockam_transport_ble` that @antoinevg has been working on.

The parts that can be shared across all transports, std & no_std, posix & no posix ... I think should end up in `ockam_core`.
The parts that only overlap within posix / tokio environments likely need a different name than `ockam_transport_core`

**Comment by thomcc** [comment]
The fundamental abstractions for transports should be in ockam_core, part of this includes address type numbers (which I think should also be a newtype, e.g. `pub struct AddressType(pub u8)`), probably some errors, etc.

But I think ockam_transport_core, assuming it should exist, should just he shared code that abstracts away as much of the transport-agnostic parts, so that implementing a new transport is effectively just about implementing the code for that transport, and not about hooking it into the rest of ockam, as much as possible.

**Comment by adrianbenavides** [comment]
I think we can close this. Most of the `*_core` crates were removed some time ago, and we only have the `ockam_transport_core` crate now, which was out of this conversation.
