### ISSUE TITLE
Could ockam_channel & ockam_entity move to the ockam crate?

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2276]
We don't plan to have two implementations of these protocols.
We may want to keep the ability to turn some of them off - which could be done with feature flags.

What could be some benefits (that I'm not thinking of) of keeping them in separate crates vs separate folders in the ockam crate?

**Comment by thomcc** [comment]
I actually want to move more things out of the core `ockam` crate. It's rather monolithic, and as it implies use with `ockam_node`, it seems less than ideal to move things into it in the future decoupled-node world.

I think ideally, the ockam crate would just be a reexport of the other ockam crates, largely for convenience.
