### ISSUE TITLE
Worker relay ctrl channel is triggered during regular Worker stop

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#2283]
[This](https://github.com/ockam-network/ockam/blob/0d94740199209147509591fec703cbb9ab96b298/implementations/rust/ockam/ockam_node/src/relay/worker_relay.rs#L143) control channel was designed to be used during node shutdown, however during Worker stop the other side of control channel gets dropped by Router, which will make .recv() function return with `None`. Sometimes, recv_message() will return first, because messages channel is also dropped, so it's a race condition. I don't think it causes any real-world problem, but doesn't work as intended as well.

**Comment by spacekookie** [comment]
I think this issue was resolved in #2667. Closing for now.
