### ISSUE TITLE
Crate readme and rustdoc description of ockam_vault_sync_core

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2285]
Crate readme and rustdoc description of ockam_vault_sync_core does not match

https://github.com/ockam-network/ockam/blob/23b3c5d4d1c7501858fd34293bcd0f18a1174bfd/implementations/rust/ockam/ockam_vault_sync_core/src/lib.rs#L1-L5

https://github.com/ockam-network/ockam/blob/b5cb97aa858de1ba547951db66346ab8d68c50ad/implementations/rust/ockam/ockam_vault_sync_core/README.md#L11-L12

**Comment by etorreborre** [comment]
@mrinalwadhwa this crate does not exist anymore, can we close this issue?

**Comment by adrianbenavides** [comment]
☝️  @mrinalwadhwa

**Comment by metaclips** [comment]
I'll be closing this issue now as this crate no longer exist, @mrinalwadhwa please reopen if needed.
