### ISSUE TITLE
Move the `ockam_key_exchange_core` create into `ockam_core`.

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2291]
This is essentially the same as #2288, but for `ockam_key_exchange_core`.

We're trying to reduce the number of crates, and part of that is moving `ockam_key_exchange_core` into a new `key_exchange` submodule of `ockam_core`. I think this basically looks like:

1. Make a new `pub mod key_exchange;` in [`ockam_core`](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_core/src/lib.rs).
    - Note: unlike the [other modules](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_core/src/lib.rs#L54-L60), I think we shouldn't `pub use key_exchange::*` from the root here, since we'd like to move away from this.

2. Move the code from `ockam_key_exchange_core/src/lib.rs` to `ockam_core/src/key_exchange.rs`.

3. Update the [doc comments](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_key_exchange_core/src/lib.rs#L1-L7) so that it says "this module" rather than "this crate" and such. (Ask if you need help wording this).

4. Change uses of `ockam_key_exchange_core::Foo` and such to use `ockam_core::key_exchange::Foo` across our crates.

5. Delete the `ockam_key_exchange_core` crate, and any references to it (be sure to check `.github/workflows`, and to do a search for `ockam_key_exchange_core`).

That's the basic idea anyway (I may have missed something). Feel free to ask questions if anything is unclear.

**Comment by fade2black** [comment]
Can I help somehow?

**Comment by thomcc** [comment]
Absolutely! I'll assigned the issue to you, feel free to ask any questions here.

**Comment by fade2black** [comment]
Hi @thomcc. It is my first contribution to ockam. As far as I understand (from the task description) it is a sort of simple code  reorganisation rather than cryptography programming. Right?

**Comment by mrinalwadhwa** [comment]
@fade2black yes that's right, only a code reorganisation.

**Comment by fade2black** [comment]
@thomcc @mrinalwadhwa I removed all refs to the create, but we have a file `rust_test_ockam_ockam_key_exchange_core.yml` in the workflow folder. May I delete it?

**Comment by mrinalwadhwa** [comment]
yes please delete it

**Comment by fade2black** [comment]
I guess `rust_build_ockam_ockam_key_exchange_core.yml` and `rust_lint_ockam_ockam_key_exchange_core.yml` too?

**Comment by mrinalwadhwa** [comment]
Yes * ockam_ockam_key_exchange_core.yml can be deleted

**Comment by fade2black** [comment]
@mrinalwadhwa  I'm struggling with 
```rust
use ockam_vault_core::Secret;
use zeroize::Zeroize;
```
inside the `keyexchange.rs`.  It says `unresolved import `ockam_vault_core`. Any idea?

**Comment by mrinalwadhwa** [comment]
@fade2black I think the simplest approach would be to wait for https://github.com/ockam-network/ockam/pull/2324 to land. Where @totsteps is moving ockam_vault_core as per https://github.com/ockam-network/ockam/issues/2288
