### ISSUE TITLE
Improving our Build/CI times

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2342]
There's a pretty good blog post about improving Rust build times https://matklad.github.io/2021/09/04/fast-rust-builds.html. After the work in #2340, I figured it was worth finding and taking a look at again to see if there's anything about improving CI times.

The answer: Yes, it does. I've summarized some of the easier parts in the post, as well as some bits that it doesn't cover, but that I'm familiar with due to my time trying to optimize the build of various projects (which I've done a lot)

### Low Hanging Fruit

Here are some of the easiest. See the blog I linked  which ah CI focused things, which are very actionable. Most of these are focused on making the GitHub Actions Cache more effective, since by default it's is not great for Rust.

1. Prior to uploading the cache, delete artifacts which cannot be meaningfully cached from the `target` folder. Specifically: all of the builds of our own crates, because CI will just rebuild anyway. This is the trickiest thing, but also pretty important.

	The blog post referenced https://github.com/Swatinem/rust-cache (although I'm unsure we want to add a GHA tool), and https://github.com/rust-analyzer/rust-analyzer/blob/94d9fc2a28ea5d97e3a9293b9dac05bdb00304cc/xtask/src/pre_cache.rs#L30-L53, but note that we need to modify the approach to work in our repo[^modify].

2. Disable debug info in CI, because it's enormous (which bloats the GHA cache), and not useful in CI. We should just set `RUSTFLAGS="-Cdebuginfo=0"` in CI (and only in CI).

3. Disable incremental builds in CI. That is, set `CARGO_INCREMENTAL=0` in the CI environment — incremental builds are faster if you have a full build and only a single changed file, but slower for full rebuilds. Also, incremental builds prevent the use of something like `sccache` (more on it below)

[^modify]: For example: ather than `"./crates/"` we would need to check `"./implementations/rust/ockam/"`.

Beyond that, there's a lot of good information about how to cut up your dependency tree, and making sure dependencies aren't  bottlenecks by using `cargo +nightly build -Ztimings`, which is a build-time profiler[^ztimings].

This is definitely something we need to be using eventually, even if not for CI. That is, at some point we need to be checking what the build times for the code that uses ockam is. (This can be measured by using `-Ztimings` on some of the examples)

[^ztimings]: This requires nightly, but is built into cargo. It spits out a pretty HTML graph — I've spent a lot of time with this, so I can probably answer questions anybody has about it.

### Some additional notes

Largely speaking this is not stuff from that blog, and only the first of them is focused on CI.

1. We use a docker image, so we should probably set up sccache on it if we have not already, as the largest downside to using sccache is that `cargo install sccache` is about as slow as you expect.

	This can help a lot, but requires we have our caching set up for the sccache directory (`~/.caches/sccache` on linux, I think?), and a few env vars (`RUSTC_WRAPPER=sccache` and `CARGO_INCREMENTAL=0`, although step 3 above covers this). Often you want to set `SCCACHE_CACHE_SIZE` to something custom too, but I don't know what a good value for GHA (or ockam) is.

	This can alleviate the need to cache the target directory too, and vice versa, although it's worth noting that sccache is a more robust cache — cargo will sometimes discard build artifacts which are sill needed.

2. The same author has a separate post on being careful about not making your examples and integration tests eat the entire build time: https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html.

	This is something that is very easy to do accidentally — I ended up writing a guide on avoiding it at a previous job: https://github.com/mozilla/application-services/blob/main/docs/design/test-faster.md... It's a bit of a footgun. I don't think we have any cases that are *too* bad here, but haven't really looked.

3. Investigate a "workspace-hack" (For example [rustc](https://github.com/rust-lang/rust/tree/master/src/tools/rustc-workspace-hack)'s, [firefox](https://searchfox.org/mozilla-central/source/build/workspace-hack/Cargo.toml)'s...), which can help build times out *enormously*.

	I've never seen one of these on a project that is published to crates.io (because you don't want to have `foo-workspace-hack` in users dependency graph, but supposedly https://crates.io/crates/cargo-hakari solves this issue, and allows them to be used for a case like ours. This would be great, but needs investigation.

**Comment by mrinalwadhwa** [comment]
https://github.com/ockam-network/ockam/pull/2410 disables debuginfo and incremental builds in CI

**Comment by thomcc** [comment]
More good info on improving the build: https://fasterthanli.me/articles/why-is-my-rust-build-so-slow

I'll... need some time to go through that one. fasterthanlime's blogs are always full of great info, but quite long.
