### ISSUE TITLE
Reduce the features that the `ockam_macros` crate requires from `syn`

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2357]
In the `ockam_macros` crate, we require basically every feature of `syn` (by way of requiring `full` and `extra-traits`): https://github.com/ockam-network/ockam/blob/5a84ea59fd9d8a67b8e0585a6be312c6d54fc906/implementations/rust/ockam/ockam_macros/Cargo.toml#L32

This is probably more than we need, and slows down our build. It would be great if someone did some experimentation and figured out a more minimal feature-set for `syn`. I don't have a great suggestion for how to do this beyond trial and error, unfortunately.

**Comment by pro465** [comment]
sorry, but some of them require only "full" (like `syn::Pat`), and others "extra-traits" (like `syn::Type: Debug`). so unfortunately, they can't be removed.

**Comment by adrianbenavides** [comment]
We recently updated `syn` to version 2.0 and we still need the `full` feature.
