### ISSUE TITLE
Prometheus metrics collection for ockam/ockam_hub services

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#2445]
Prometheus is becoming a de-facto standard for metrics collection in modern services.

With https://github.com/deadtrickster/prometheus.erl we can set up the metrics collection API and use existing telemetry integration of `ockam` and `ockam_hub` applications to create a prometheus plugin for ockam which will handle telemetry events and report them into `prometheus.erl`.

This could be a separate application e.g. `ockam_metrics_prometheus`.

**Comment by polvorin** [comment]
https://github.com/ockam-network/ockam/pull/2717 added the  `/metrics`   endpoint to `ockam_cloud_node`,   but nothing is consuming these yet.

**Comment by hairyhum** [comment]
Addressed in #2717
