### ISSUE TITLE
Ockam Layer 1 library development roadmap Q1

### ISSUE THREAD

**Issue by spacekookie** [build-trust/ockam#2458]
## "Layer 1" layers

 - Runtime and core
   - (Transport mechanisms)
 - Encoding & messaging
 - Messaging service integrations
 
## Tasks

 - Encoding & messaging (January -> mid Feb)
   - Metadata encoding prototypes
   - Re-addressable worker prototypes
   - Pipe & Stream combinators integration with Elixir
   - ~~"firewall" basic design ?~~

- Runtime & core stability (mid feb -> mid march)
   - Worker lifecycle managament
   - Stability testing/ fuzzing?/ protocol & transport resilience
   - Worker supervision
   - Logging & monitoring integrations

- High-level service APIs (mid march -> deadline)
   - UX studies for pipes/ streams/ channels
   - Stabilise any user-facing APIs for the GA milestone
   - "firewall" implementation?

## Work pipelining

 - Encoding & messaging
   - Design dependency: on Rust & Elixir code lining up in terms of
     scopes and implementation.
   - Daniil and I work on messaging and encoding mechanisms in January
   - Async-implement this in Rust and Elixir against a common set of tests

- Runtime & core stability
   - Dependency: Thom's error refactoring, context decoupling?
   - Feedback interactions: from Sanjo, Thom, and Jared (and other
     users of ockam libs.  Ockam cloud?)

- High-level service APIs
   - Incorporate feedback from Jared, Thom, and Sanjo
   - Add polish and draw the rest of the owl

## Feedback

 - Restrict messaging routes/ authorisation schemes
 - Ockam "firewall"/ capabilities system

**Comment by hairyhum** [comment]
There is a message encoding discussion happening in https://github.com/ockam-network/ockam/issues/2496
