### ISSUE TITLE
Check on CI that no_std build is no_std

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#2510]
Currently we check that our lib builds successfully with no_std enabled, but we don't check that it doesn't bring std dependency. Possible solution could be building for a platform that doesn't have std

**Comment by SanjoDeundiak** [comment]
@thomcc @antoinevg thoughts?

**Comment by metaclips** [comment]
Artifacts repo runs ockam no_std example using QEMU. Closing now.
