### ISSUE TITLE
ci: Remove cargo audit ignore for `RUSTSEC-2020-0159`

### ISSUE THREAD

**Issue by antoinevg** [build-trust/ockam#2541]
The [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159.html) advisory identifies a vulnerability in the [`chrono`](https://crates.io/crates/chrono) crate due to a call to `localtime_r`.

Time to resolution is indefinite.

More information:

* https://github.com/chronotope/chrono/issues/499

**Comment by antoinevg** [comment]
Can we please leave this open as a reminder to remove the deny check when it's no longer needed? :-)

**Comment by thomcc** [comment]
My bad, it got auto-closed.

**Comment by antoinevg** [comment]
> I'm unsure ignoring this one is appropriate, since its a vulnerability that in (real world) multithreaded use can cause memory corruption (in an often crashy way).

Just a quick reference for why we managed to get away with it this time: 

* https://github.com/ockam-network/ockam/pull/2542#issuecomment-1055630787

**Comment by metaclips** [comment]
We no more have this in cargo deny
