### ISSUE TITLE
CI commit check doesn't seem to catch all merge commits.

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2547]
Our CI script attempts to check if merge commits are present in the output here: https://github.com/ockam-network/ockam/blob/develop/.github/workflows/commits.yml#L85. However, it didn't seem to catch a merge commit in #2545 that almost snuck in.

The code looks right to me, so I'm not exactly sure what the deal is. That said, this might be easily to repro if someone makes a branch and manually forces a merge commit to be present.

**Comment by mrinalwadhwa** [comment]
🤔  If @adrianbenavides hasn't deleted his branch yet. It would be good to have a failing test case.
