### ISSUE TITLE
Handle nonce overflow in ockam_secure_channel

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2556]
In `ockam_secure_channel`, when the nonce overflows we begin returning an error: https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_channel/src/secure_channel_worker.rs#L142-L144. I don't think anything handles this error higher up (it's not specific enough to really be handled in that way).

Instead, this should rekey, so that you can send more than `u16::MAX` messages.

**Comment by mrinalwadhwa** [comment]
I was re-reading the noise paper again today and they recommend not resetting n across rekeys so we may have to send the full 8-byte nonce over the wire.

> Note that rekey only updates the cipherstate’s k value, it doesn’t reset the cipherstate’s n value, so applications performing rekey must still perform a new handshake if sending 264 or more transport messages.

**Comment by mrinalwadhwa** [comment]
```elixir
Vault.aead_aes_gcm_encrypt(vault, k1, (:math.pow(2, 64) - 1), <<>>, <<0::size(256)>>)
```
This didn't work from elixir.

> REKEY(k): Returns a new 32-byte cipher key as a pseudorandom function of k. If this function is not specifically defined for some set of cipher functions, then it defaults to returning the first 32 bytes from ENCRYPT(k, maxnonce, zerolen, zeros), where maxnonce equals 264-1, zerolen is a zero-length byte sequence, and zeros is a sequence of 32 bytes filled with zeros.

**Comment by thomcc** [comment]
I'm not 100% sure this explains what you're seeing, but FWIW we also seem to have an issue that the Erlang bindings don't check the size of `nonce` is [within the range of a uint16_t](https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam_vault_software/native/vault/software/vault.c#L481) before [passing them to a function that takes a u16](https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam_vault_software/native/vault/software/vault.c#L511), ([c header](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_ffi/include/ockam/vault.h#L209), [rust definition](https://github.com/ockam-network/ockam/blob/develop/implementations/rust/ockam/ockam_ffi/src/vault.rs#L339-L351)). C will silently truncate an `unsigned int` passed to a function that accepts a `uint16_t` like this.

We should fix this, and audit the FFI interface for other similar issues, but I think it's not related per-se to the issue. I am not 100% sure this is responsible for what you describe, though.

**Comment by polvorin** [comment]
https://github.com/build-trust/ockam/pull/4756 adds periodically rekeys to secure channel,  plus fixes the error when encrypting with nonces > 2^16 from elixir.   
To exhaust the nonce space,  now the channel need to go over 2^64-1  messages,  so while the issue of how to graceful handle that failure remains, it's a _much_ lesser concern

**Comment by SanjoDeundiak** [comment]
Fixed by https://github.com/build-trust/ockam/pull/6774
