### ISSUE TITLE
Improve CI build times by moving `cargo-deny` into the docker image (or something).

### ISSUE THREAD

**Issue by thomcc** [build-trust/ockam#2585]
Our CI lately has been taking a long time to run `cargo deny` checks, most of it spent building `cargo deny` itself.

Can we move this into the docker image? Alternatively, there are other methods for installing it in advance.

**Comment by metaclips** [comment]
We already install in docker https://github.com/ockam-network/ockam/blob/acb5fda427d9c69a810b79418d2337a9b9b50e74/tools/docker/builder/Dockerfile#L69
I'll be removing installation from CI
