### ISSUE TITLE
Revisit `ockam_transport_websocket` crate 

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#2588]
As of now, the reference transport crate is `ockam_transport_tcp` and we want the other transport crates to have a similar internal structure and public API.

The `ockam_transport_websocket` has not been modified for a long time and it needs some work. Here are the main issues we should address:

## Basic issues to stabilize the crate
* https://github.com/ockam-network/ockam/pull/2598:
   * [x] refactor file structure to match that of `tcp`/`ble` crates
   * [x] add test for basic usage like the `send_receive` test from the `tcp` crate

* https://github.com/ockam-network/ockam/pull/2607:
   * [x] evaluate if WebSocketError is necessary: it's only used internally to map `tungstenite` errors. It only contains two errors on top of `TransportError` and they could be transferred there, but maybe we should wait until we have a better abstraction of the different transports. For example, `tcp/smol/ws` are all ip-based transports and will have some shared similarities and error types, while `ble` will probably not. 
   * [x] revisit docs

The following items are specific tasks of the GA analysis, that must also be addressed:

* [x] 🤔 Should this file exist?
* [x] ❤️ Is the Public API friendly? 
* [x] 📚 Are all Public functions documented? 
* [x] 🪂 Do public functions have rust doc examples? 
* [x] 🆗 Do all functions return the correct errors?
* [x] 🛃 Are all error results returned inside the implementation being handled correctly?
* [x] ✅ Do all modules have sufficient test coverage?
* [x] 🪵 Is there sufficient logging and are the correct levels being used?
* [x] 🛌 Are all modules ready for use on embedded?
* [x] 📦 Are we using the correct Cargo features in all files and `Cargo.toml`?
* [x] ☣️ Has all `unsafe` code been audited?

## Missing functionalities
Most of the following items will be easier to add once https://github.com/ockam-network/ockam/pull/2213 is merged. It's also important to note that any of them are critical as they don't affect the public API.

* https://github.com/ockam-network/ockam/pull/2598:
   * [x] heartbeats
   * [x] clusters, which will lead to the removal of `ArcBool`
* [ ] handle reconnections: add changes from https://github.com/ockam-network/ockam/pull/2606 once it lands
* [ ] inlets/outlets: should this be a shared transport trait? or only for IP-based transport protocols (UDP, TCP, WS)?

### Common stuff that could be moved to `ockam_transport_core`
* Workers + Router: as specified in https://github.com/ockam-network/ockam/pull/2598, there is a difference in how the `tcp` connection is initialized
   * The aforementioned difference is being discussed on https://github.com/ockam-network/ockam/pull/2611
* utilities: `parse_socket_addr`

## Questions
* Can we use a more generic type to define a addresses[^1] instead of using `SocketAddr`? That would allow us to use a single type for all kind of transports
* `WorkerPair`: could we rename it to something more meaningful? 

[^1]: We currently use `SocketAddr`, which is bound to IP addresses types. We could use a protocol-agnostic type like https://docs.libp2p.io/concepts/addressing/ but I'm not sure yet about the impact it would have on other crates.

**Comment by thomcc** [comment]
> utilities: parse_socket_addr

I actually don't know why we aren't using https://doc.rust-lang.org/nightly/std/net/trait.ToSocketAddrs.html for this. (It's reasonable (and common) in the ecosystem for stuff to fail for multiple addresses if appropriate).

That said, perhaps you're right and somethign like your link to <https://docs.libp2p.io/concepts/addressing/> is better long-term.
