### ISSUE TITLE
Add `async_trait` alias for `processor`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#2620]
In `ockam_core` there is an alias for `worker` so that the client code can write:

```rust
#[worker]
impl Worker for MyWorker {
...
}
```

There should also be an alias for `processor`s so that the client code can write `#[processor]` instead of `#[async_trait::async_trait]`:

```rust
#[processor]
impl Processor for MyProcessor {
...
}
```

If we do this, the user could either use `worker` or `processor` to impl `Worker` or `Processor` as it's just wrapping `async_trait`.

We should decide wether we want to continue the current approach (using our wrappers which would seem that gives more context/meaning but can be misused + we'd have to add new aliases for new types requiring `async_trait), or remove the `worker` alias and just use `async_trait`.

**Comment by 0x00A5** [comment]
This seems fun, can I grab it?

**Comment by mrinalwadhwa** [comment]
@0x00A5 awesome, all yours.

**Comment by 0x00A5** [comment]
This issue seems already finished after [`this commit`](https://github.com/build-trust/ockam/commit/dfad29c4c660f9a3282813b4854bdaf6614a9e84) authored by @adrianbenavides .

**Comment by mrinalwadhwa** [comment]
Ah, thanks @0x00A5 🙏
