### ISSUE TITLE
Implement function Request/Response pattern 

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#2628]
We have a lot of places following this pattern:
```
let mut child_ctx = ctx.new_context(Address::random(0)).await?;
child_ctx.send(address, msg).await?;

let response = child_ctx
    .receive::<T>()
    .await?
    .take()
    .body();
```

Would be great to have function on `Context` type doing that

**Comment by hairyhum** [comment]
A bit of inspiration from Erlang OTP toolbox: https://www.erlang.org/doc/design_principles/gen_server_concepts.html#synchronous-requests---call

**Comment by neil2468** [comment]
Hi. I'm new to Rust and would like to try some API design. Can I be assigned this issue?

**Comment by neil2468** [comment]
The below is what I have so far. What do you think? Is it like what you were thinking of?

4c5c544e14465cb953dd162886c24a27500a3460

Thanks in advance :smile:

**Comment by SanjoDeundiak** [comment]
@neil2468 looks almost perfect! Why don't you submit a PR?
