### ISSUE TITLE
Investigate failed CI run

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2663]
https://github.com/ockam-network/ockam/runs/6044667215?check_suite_focus=true

**Comment by thomcc** [comment]
I believe this is just a spotty test we get from time to time. @metaclips mentioned having seen it before too.

**Comment by thomcc** [comment]
Hmm, it does seem more common now than it used to: https://github.com/ockam-network/ockam/runs/6083267968?check_suite_focus=true.
