### ISSUE TITLE
Secure channel compatibility between Elixir and Rust implementations

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#2682]
Currently Rust implementation of secure channels is ahead of Elixir and supports more functionality.

This makes it currently not possible to establish secure channels between Rust and Elixir nodes.

Elixir secure channels need to be reviewed and made compatible with the current Rust protocols.

**Comment by hairyhum** [comment]
The scope of this issue is to ensure that the base encryption layer of secure channels is compatible, identity layer would be described in #2686

**Comment by hairyhum** [comment]
Implemented in #2789

**Comment by mrinalwadhwa** [comment]
Did we test this? We should have CI check this.
