### ISSUE TITLE
Topology configuration to be used in CLI tool.

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#2683]
Currently Ockam provides a number of tools to create messaging topologies, such as secure channels, forwarders, streams etc. represented in examples.

In order to combine those building blocks we currently use Rust or Elixir code using Ockam library. 

Since most of this code serves just to combine those building blocks, it would be possible to break down topology creation into some composable actions to be used as CLI commands or some declarative configurations.
This way a user can create new topologies and build their messaging pipelines without a need to write Rust or Elixir code.

**Comment by thomcc** [comment]
So, my notes on this are along the following lines. This boils down to two categories:

1. Configuration of local topology, which is largely going to be spawning child-processes. This can all be done from within the ockam command, and even the child processes can be the ockam command spawning itself with special arguments. There's still 

2. Configuration of remote topology, which I imagine will mostly be making requests to the ockam cloud, along the lines of the API described in the API doc.

I think there's open questions around both of these, though.
