### ISSUE TITLE
Elixir CBOR support

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#2687]
CBOR encoding is proposed in #2496 

There are BEAM libraries supporting CBOR encoding: https://github.com/galdor/erl-cbor https://github.com/scalpel-software/cbor

We need to chose one to use and make sure it can work well with the Rust implementation.

@twittner can you please provide some reference Rust code encoding data structures in order to test the Elixir implementations?

We can even make a test/demo suite, which is going to encode/decode some reference data structures on both implementations, as mentioned before by @spacekookie

**Comment by hairyhum** [comment]
@twittner  In the example for encoding/decoding request-response structures there is an optional body, which is encoded as an additional tail structure.

This is a bit confusing because it's not a part of the data structure of Request/Response. It breaks decoding process and forces us to mix decoding/encoding with the logic. What's the purpose of using it this way?

**Comment by twittner** [comment]
So the idea behind it was to have a completely generic header, essentially mimicking the HTTP model, which would allow us to have bodies differently encoded or even transmitted in chunks (aka streaming). Decoding would proceed by first decoding the header and then basing subsequent decoding decisions on it (which is what you meant with "mixing decoding/encoding with logic" I think).

**Comment by hairyhum** [comment]
Addressed in #2711
