### ISSUE TITLE
High memory usage/Memory leak in TCP

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#2728]
I noticed high memory usage on the outlet side while testing inlets-outlets scenario for transferring files (Mbytes).
![Screenshot 2022-05-05 at 14 58 23](https://user-images.githubusercontent.com/6513916/167448411-1dcbeadd-9db6-4428-aaa2-46a12649aec9.png)
AFAIK it can be reproduced in simple scenario with two nodes on the same machine connected to each other using loopback TCP, without secure channel.

**Comment by twittner** [comment]
Try reproducing this with https://github.com/build-trust/ockam/pull/2725.

**Comment by spacekookie** [comment]
This issue _should_ no longer happen now that #2762 is merged. So I'm closing this
