### ISSUE TITLE
Try to speed up CI by splitting testing of crates

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2819]
[Rust - Test](https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml#L126) & [Rust - Nightly Test](https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml#L217) jobs take significantly more time than the other jobs in the Rust workflow.

<img width="1344" alt="Screen Shot 2022-06-02 at 11 55 28 PM" src="https://user-images.githubusercontent.com/159583/171803397-36d2f479-5126-4bfe-b53e-09050bba7a7b.png">

It would be interesting to try if we had one job per crate that did this.

```
cd implementation/rust/ockam/{crate_name} && cargo test
```
And the [rust workflow](https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml) ran them in parallel. 

Would it speed up time spent in CI?

**Comment by Shreyan11** [comment]
Would you mind assigning this task to me?

**Comment by mrinalwadhwa** [comment]
@Shreyan11 that would be amazing. Thank you for picking it up 🙏

**Comment by mrinalwadhwa** [comment]
`nextest` prints a nice report https://github.com/build-trust/ockam/issues/2924 and I noticed that a big chunk of time spent in the Rust Test job is spent testing our examples, so splitting that into a separate job/s should reduce time significantly https://github.com/build-trust/ockam/tree/develop/examples/rust

**Comment by adrianbenavides** [comment]
@metaclips should we close this?

**Comment by metaclips** [comment]
No, [we still limit concurrency](https://github.com/build-trust/ockam/blob/f2e399804652c8afe0ffaa82feedb94ebde743a0/tools/nextest/.config/nextest.toml#L7) when running the examples, we will need to revisit the example code.

**Comment by metaclips** [comment]
https://github.com/build-trust/ockam/issues/3005

**Comment by metaclips** [comment]
I am closing this issue in favour of https://github.com/build-trust/ockam/issues/3619 and https://github.com/build-trust/ockam/issues/3005
