### ISSUE TITLE
Try the mold linker to speed up Rust builds in CI and in the builder image.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2822]
Mold linker:
https://github.com/rui314/mold#readme
https://twitter.com/wezm/status/1532513816063655936
https://twitter.com/wezm/status/1532515498222845952

This will require changing the ockam-builder docker file
https://github.com/build-trust/ockam/blob/develop/tools/docker/builder/Dockerfile

All jobs in our Rust workflow are run using this image
https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml

**Comment by neil2468** [comment]
Can I be assigned this?

I assume our goal would be to use mold on CI builds, but leave things as-is for developers' local builds (ie. not require developers to have mold installed and running)?

Also, I might choose to roll out changes bit by bit - I really don't want to bring the CI to a halt for everyone. Hope that's okay.

**Comment by mrinalwadhwa** [comment]
@neil2468 awesome, you got it!

> I assume our goal would be to use mold on CI builds, but leave things as-is for developers' local builds (ie. not require developers to have mold installed and running)?

Yes, exactly. 

Note that CI jobs run inside [this](https://github.com/build-trust/ockam/blob/develop/tools/docker/builder/Dockerfile) docker image 

https://github.com/build-trust/ockam/blob/be54d1f5611883db501a86473f595d9c36495dfe/.github/workflows/rust.yml#L98-L99

And that image is changing a bit in https://github.com/build-trust/ockam/pull/2880 which will likely merge in the next couple of days.

> Also, I might choose to roll out changes bit by bit - I really don't want to bring the CI to a halt for everyone. Hope that's okay.

Cool, let us know if you have questions. @metaclips and I are here to help.

**Comment by neil2468** [comment]
@mrinalwadhwa, @metaclips 

I see the `ockam/tools/docker/builder` Dockerfile targets `amd64`, `arm64` or `armhf`.

Mold can be built from source and has pre-built releases for `x86_64-linux` and `aarch64-linux`.

- Mold README with build instructions: [here](https://github.com/rui314/mold/blob/main/README.md)
- Mold releases: [here](https://github.com/rui314/mold/releases)

Seeing as there is no mold pre-built for `armhf`, would it be okay if I modify the Dockerfile to build mold from source for all targets? 🤔

**Comment by mrinalwadhwa** [comment]
I don't think we need to support the builder image for 32bit targets. It's fair to assume dev machines and CI machines are 64bit. So my suggestion would be to remove the `armhf` section altogether and introduce mold pee-built binaries

The image we do want to support on 32-bit arm is `ockam` command image - but I imagine the builder image will cross compile that binary.

**Comment by neil2468** [comment]
@mrinalwadhwa, @metaclips

I've created PR #2928 which updates the `builder` Dockerfile to include mold.

But I do not know how to get a new `builder` docker image built and uploaded to `https://ghcr.io`. Can you give me some pointers? Thanks!

**Comment by neil2468** [comment]
> But I do not know how to get a new `builder` docker image built and uploaded to `https://ghcr.io`. Can you give me some pointers? Thanks!

Ah. I see, as if by magic, a new Docker image has appeared in `ghcr.io`. 🎉 🚀 

Thanks.

**Comment by mrinalwadhwa** [comment]
We have this awesome build pipeline @metaclips has put together - its magic ✨
