### ISSUE TITLE
Investigate CI Rust Nightly check ran for ~6hrs

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2836]
https://github.com/build-trust/ockam/runs/6769053318?check_suite_focus=true

**Comment by mrinalwadhwa** [comment]
This happened again
https://github.com/build-trust/ockam/runs/7264866857?check_suite_focus=true

**Comment by mrinalwadhwa** [comment]
Another case:
https://github.com/build-trust/ockam/runs/7265288541?check_suite_focus=true

It seems to be the same test everytime:
```
test cloud::project::tests::basic_api_usage has been running for over 60 seconds
```

**Comment by mrinalwadhwa** [comment]
It's one of these tests
https://github.com/build-trust/ockam/search?q=basic_api_usage

**Comment by mrinalwadhwa** [comment]
@adrianbenavides would love your thoughts on why this may be happening.

**Comment by adrianbenavides** [comment]
I'll be working on these tests this week, so I'll make sure to check this out!

**Comment by adrianbenavides** [comment]
This issue can be closed after the following issues are solved:
* https://github.com/build-trust/ockam/issues/2996
* https://github.com/build-trust/ockam/issues/3054
