### ISSUE TITLE
publish on hex.pm

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#284]

**Comment by etorreborre** [comment]
@hairyhum we have a first version published: https://hex.pm/packages/ockam. Should we automate this in our release process?

**Comment by hairyhum** [comment]
@etorreborre yes. It's our long-term plan of making elixir version usable by the opensource community.

**Comment by mrinalwadhwa** [comment]
This is not on the roadmap for sometime. Closing for now.
