### ISSUE TITLE
Users understand, and can control, which interface(s) we bind to when a node is started by ockam command

### ISSUE THREAD

**Issue by antoinevg** [build-trust/ockam#2849]
New nodes created by the Ockam command listen on all network interfaces by default:

    tcp.listen(format!("0.0.0.0:{}", c.port)).await?;

While this makes deployment easier in trusted environments it can also result in unexpected consequences if the user is not intending to expose the node outside the host machine.

One idea:

1. If we don't already have it, add a `--listen` command-line parameter to specify the interface to listen on.
2. Output a debug message when a node starts that looks something like:

     `Node started. Accepting connections on: 127.0.0.1:4000, 192.168.20.226:4000, 192.168.20.225:4000`

3. Reference this message in both the getting started and deployment guides along with instructions on how to bind to a specific interface

**Comment by mrinalwadhwa** [comment]
💯 let's add a `--listen` with a default value of `127.0.0.1` and in environments like the `ockam` docker image where we need it to listen everywhere explicitly set `0.0.0.0`

**Comment by pro465** [comment]
this seems to be fixed, albeit using different name than `--listen`:

https://github.com/build-trust/ockam/blob/696e3da5fec8c992ae3c47f0838647ceb0a96e3a/implementations/rust/ockam/ockam_command/src/node/create.rs#L43-L45

**Comment by pro465** [comment]
(made in [this commit](https://github.com/build-trust/ockam/commit/ee3919eaf07ed0bb6c02171cfa05e9970101a3d8) by @Handschrift)

**Comment by mrinalwadhwa** [comment]
Yes it is. Thank you for pointing it out. Closing.

**Comment by mrinalwadhwa** [comment]
There's some good ongoing discussion about tcp-listener command UX here https://github.com/build-trust/ockam/discussions/3143
