### ISSUE TITLE
ockam_command fails on crate publish

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#2861]
ockam_command fails to publish to crates.io with failure 
```
The remote server responded with an error: missing or empty metadata fields: description. Please see https://doc.rust-lang.org/cargo/reference/manifest.html for how to upload metadata
```
We have an empty [description](https://github.com/build-trust/ockam/blob/774e140c931fa6d04be2ad773ec9b81e1676a5fd/implementations/rust/ockam/ockam_command/Cargo.toml#L11) value, and no definition for `categories`,  `keywords`, and `readme`.

**Comment by mrinalwadhwa** [comment]
@metaclips could you check that #3057 fixes this so we don't need to skip this crate in the next release.

**Comment by mrinalwadhwa** [comment]
Re-opening until @metaclips can confirm that this is fixed.
