### ISSUE TITLE
ockam cli: fix minicbor encoding/decoding of projects

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#2871]
https://github.com/build-trust/ockam/blob/01f088ec554e636eda2820a567f26b329dd26337/implementations/rust/ockam/ockam_api/src/cloud/project.rs#L24 `Vec<u8>`  gets encoded as cbor array,  instead of bytes(). 

Should use `ByteSlice` instead, like here https://github.com/build-trust/ockam/blob/01f088ec554e636eda2820a567f26b329dd26337/implementations/rust/ockam/ockam_api/src/auth/types.rs#L1 

This currently prevent the listing of projects,  and other projects related commands to work

**Comment by adrianbenavides** [comment]
I'll get into this as soon as https://github.com/build-trust/ockam/pull/2855 and https://github.com/build-trust/ockam/pull/2856 get merged. I'll also check other types that might be changed to bytes.
