### ISSUE TITLE
build failed when follow readme.md

### ISSUE THREAD

**Issue by elderbig** [build-trust/ockam#2881]
build example follow readme.md
```bash
cargo new --lib hello_ockam && cd hello_ockam && mkdir examples &&
  echo 'ockam = "*"' >> Cargo.toml && cargo build
```

got error:
```
   Compiling ockam_node v0.58.0
error[E0599]: no method named `metrics` found for struct `Arc<Runtime>` in the current scope
  --> ockam_node-0.58.0/src/metrics.rs:68:25
   |
68 |         let m = self.rt.metrics();
   |                         ^^^^^^^ method not found in `Arc<Runtime>`

```

evvionment
* Linux nuc 5.10.102-1-MANJARO  SMP PREEMPT Wed Feb 23 14:44:40 UTC 2022 x86_64 GNU/Linux
* rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.62.0-nightly (ecd44958e 2022-05-10)`

**Comment by mrinalwadhwa** [comment]
@elderbig Thank you for reporting this 🙏 
We're working on a fix in https://github.com/build-trust/ockam/pull/2882 and will post an update about a new release with a fix later today.

**Comment by mrinalwadhwa** [comment]
@elderbig We just published a new release. The above should be fixed.
Could you try:

```
cargo new --lib hello_ockam && cd hello_ockam && mkdir examples &&
  echo 'ockam = "0.62.0"' >> Cargo.toml && cargo build
```
