### ISSUE TITLE
Use nextest to run Rust tests in CI

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2924]
`nexttest` is [faster](https://nexte.st/book/benchmarks.html) that `cargo test` and it could possibly help make our CI test workflows faster https://github.com/build-trust/ockam/issues/2819

This will require changing the ockam-builder docker file
https://github.com/build-trust/ockam/blob/develop/tools/docker/builder/Dockerfile

Rust workflows are run using this image
https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml

**Comment by mrinalwadhwa** [comment]
Related https://github.com/build-trust/ockam/issues/2923

**Comment by neil2468** [comment]
Can I be assigned this? Thanks.

**Comment by mrinalwadhwa** [comment]
Of course! Thank you for picking it up
