### ISSUE TITLE
Rename `identity_keypair` in secure channel to avoid confusion with identity channel

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#2926]
Secure channel argument `identity_keypair` used in https://github.com/build-trust/ockam/blob/e595cd38b985771812425c3e7878e029ba6928f3/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex#L69 does not have anything to do with identity keys from identity channel and should be removed to something more meaningful like `static_keypair`

**Comment by saputkin** [comment]
Hi, I would like to help

**Comment by etorreborre** [comment]
Hi @saputkin, please do!
