### ISSUE TITLE
Improve accepted routes format in ockam-command

### ISSUE THREAD

**Issue by spacekookie** [build-trust/ockam#2931]
When starting a node with an API port at `0.0.0.0:4000` a route that wants to incorporate this connection needs to explicitly contain the bind and port (`/ipv4/0.0.0.0/4000`). A better approach would be to be able to support lookup via the node name and the config.

* `/ipv4/0.0.0.0/4000` would become `/node/outlet-node`
* Example: `ockam portal create tcp-inlet /node/outlet-node/local/outlet-address`

**Alternatively**, the CLI is already being passed the API node via a parameter, routes could implicitly prepend the first hop.

**Comment by SanjoDeundiak** [comment]
@spacekookie I think this should be considered on per-command basis. For example, I think that send message command definitely should support providing node name as a first hop either as multiaddr piece `/node/{NODE_NAME}` or as a node name argument like `-n {NODE_NAME}`. I vote multiaddr approach here
Not sure about other commands

**Comment by adrianbenavides** [comment]
Done/oudated
