### ISSUE TITLE
Ockam command required UX improvements

### ISSUE THREAD

**Issue by spacekookie** [build-trust/ockam#2939]
We have a demo which uses inlet/ outlets, secure-channels, and forwarding addresses in the new command structure.
Some of the commands don't use the same formats for inputs and outputs which makes setting up a system harder than it needs to be.

Here's a list of small improvements that could be made to make the user experience much more streamlined:

* `forwarder` command - returns the address name, **should be** address in MultiAddr format (`/ockam/<address>`)
* `secure-channel` - returns nothing, **should be** address in MultiAddr format
* `portal` - returns route to portal, from the CLI node, **should be** address in MultiAddr format.
* `transport` - returns route as legacy route format, **should be** route in MultiAddr format

This way a user can setup a transport, forwarder, secure-channel, and portal, and copy and paste different aspects of the route into a single MultiAddr which can then be used to initialise the portal inlet

**Comment by spacekookie** [comment]
To replicate this demo:

## control_plane node (outlet)

```
$ ockam node create control_plane -p 6666
$ ockam transport create -a control_plane tcp-connector <your personal node address> (not in multiaddr)
$ ockam identity create -a control_plane
$ ockam forwarder create -n control_plane <your personal node address> (in MultiAddr also -n needs to change to -a!)
$ ockam secure-channel create -a control_plane listener <your-listener-address>
$ ockam portal create -a control_plane tcp-outlet <ip address to connect to> (returns a MultiAddr route to the outlet. Only use the last segment of the route)
```

## control_plane node (inlet)

```
$ ockam node create edge_plane -p 4444
$ ockam transport create -a edge_plane tcp-connector <your personal node address> (not in multiaddr)
$ ockam identity create -a edge_plane
$ ockam secure-channel create -a edge_plane connector /dnsaddr/your-ockam-node/<forwarder-address>/<your-listener-address> (returns secure channel address)
$ ockam portal create -a edge_plane tcp-inlet <bind address and port> /<secure channel address>/<tcp outlet address> 
```

**Comment by mrinalwadhwa** [comment]
Closing since this is now quite old and command has progressed further.
