### ISSUE TITLE
Rename `-m, --message-format <MESSAGE_FORMAT>` to `-f, --format <OUTPUT_FORMAT>`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2990]
Ockam Command has an option that indicates the output format.
Calling it message format is confusing since we use `message` as a specific noun with its own command.

We should just call this option `--format`

The help output currently is:

```
-m, --message-format <MESSAGE_FORMAT>    [default: plain] [possible values: plain, json]
```

It should be:

```
-f, --format <OUTPUT_FORMAT>    [default: plain] [possible values: plain, json]
```

**Comment by mrinalwadhwa** [comment]
The option is defined here
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/lib.rs#L101-L102

**Comment by tmuro17** [comment]
I would like to take a look at this one.  Would it be preferred to change the name of the underlying enum as well, or just the flag exposed in the CLI?

**Comment by mrinalwadhwa** [comment]
@tmuro17 awesome thank you.

> Would it be preferred to change the name of the underlying enum as well, or just the flag exposed in the CLI?

Yes to `OutputFormat`

But before you start ..

@edbastelli mentioned a [few days ago](https://github.com/build-trust/ockam/discussions/1081#discussioncomment-3227139) that they would like to pick it up. If they still have time to work on this ... then I would love to add a few more issues over the next hour that @tmuro17 may find interesting.

**Comment by tmuro17** [comment]
Absolutely, happy to leave it to @edbastelli if they are interested.

**Comment by edbastelli** [comment]
Hi @tmuro17, @mrinalwadhwa, yes I am working on it. thanks

**Comment by mrinalwadhwa** [comment]
Awesome! looking forward to it!

**Comment by mrinalwadhwa** [comment]
Closed in https://github.com/build-trust/ockam/pull/3073
