### ISSUE TITLE
Diagnose `Cannot drop a runtime ...` error in rust nodes 

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#2996]
This error shows up often

```
thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/shutdown.rs:51:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by pro465** [comment]
hi I'm back! you probably don't remember me but i contributed before at least 1 time :)

anyways, can i get a backtrace? (cuz compiling this will take a looong time)

**Comment by mrinalwadhwa** [comment]
Hey @pro465 welcome back! Of course I remember. Thank you for looking into this.

The error doesn't happen deterministically but I suspect it happens around node shutdown.

In an attempt to reproduce, I did this:

```
for i in {1..9}; do RUST_BACKTRACE=1 cargo run --quiet --bin ockam node create "n$i" --port "660$i"; done
```

then:

```
for i in {1..20}; do RUST_BACKTRACE=1 cargo run --quiet --bin ockam node list; done
```

to create a situation where lots of nodes are being created and stopped.
and got 

```
thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/shutdown.rs:51:21
```

not sure why I didn't get the whole trace, will explore more.

**Comment by pro465** [comment]
hmm interesting, perhaps i will need to build this to investigate quicker..

**Comment by mrinalwadhwa** [comment]
got a somewhat better trace (by removing `--quiet` from the cargo commands above)

```
thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
Checking state for node 'n5'
   0: std::panicking::begin_panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:616:12
   1: tokio::runtime::blocking::shutdown::Receiver::wait
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/shutdown.rs:51:21
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:193:12
   3: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:210:9
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
   5: core::ptr::drop_in_place<tokio::runtime::Runtime>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
   6: alloc::sync::Arc<T>::drop_slow
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/sync.rs:1093:18
   7: <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/sync.rs:1689:13
   8: core::ptr::drop_in_place<alloc::sync::Arc<tokio::runtime::Runtime>>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
   9: core::ptr::drop_in_place<ockam_node::context::Context>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
  10: core::ptr::drop_in_place<ockam_node::delayed::DelayedEvent<ockam_transport_tcp::workers::sender::TcpSendWorkerMsg>::schedule::{{closure}}::{{closure}}>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:70:13
  11: core::ptr::drop_in_place<core::future::from_generator::GenFuture<ockam_node::delayed::DelayedEvent<ockam_transport_tcp::workers::sender::TcpSendWorkerMsg>::schedule::{{closure}}::{{closure}}>>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
  12: core::ptr::drop_in_place<futures_util::abortable::Abortable<core::future::from_generator::GenFuture<ockam_node::delayed::DelayedEvent<ockam_transport_tcp::workers::sender::TcpSendWorkerMsg>::schedule::{{closure}}::{{closure}}>>>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
  13: core::ptr::drop_in_place<tokio::runtime::task::core::Stage<futures_util::abortable::Abortable<core::future::from_generator::GenFuture<ockam_node::delayed::DelayedEvent<ockam_transport_tcp::workers::sender::TcpSendWorkerMsg>::schedule::{{closure}}::{{closure}}>>>>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
  14: tokio::runtime::task::core::CoreStage<T>::set_stage::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:218:35
  15: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  16: tokio::runtime::task::core::CoreStage<T>::set_stage
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:218:9
  17: tokio::runtime::task::core::CoreStage<T>::drop_future_or_output
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:184:13
  18: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:170:13
  19: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  22: ___rust_try
  23: std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  24: std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  25: tokio::runtime::task::harness::poll_future
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  26: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  27: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  28: tokio::runtime::task::raw::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  29: tokio::runtime::task::raw::RawTask::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  30: tokio::runtime::task::LocalNotified<S>::run
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:376:9
  31: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:435:13
  32: tokio::coop::with_budget::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  35: tokio::coop::with_budget
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  36: tokio::coop::budget
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  37: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:434:9
  38: tokio::runtime::thread_pool::worker::Context::run
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:401:24
  39: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:386:17
  40: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  41: tokio::runtime::thread_pool::worker::run
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:383:5
  42: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:362:45
  43: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs:42:21
  44: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  45: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  46: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  47: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  48: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  49: std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  50: ___rust_try
  51: std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  52: std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  53: tokio::runtime::task::harness::poll_future
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  54: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  55: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  56: tokio::runtime::task::raw::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  57: tokio::runtime::task::raw::RawTask::poll
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  58: tokio::runtime::task::UnownedTask<S>::run
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:413:9
  59: tokio::runtime::blocking::pool::Task::run
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:91:9
  60: tokio::runtime::blocking::pool::Inner::run
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:325:17
  61: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mrinalwadhwa** [comment]
@spacekookie, @SanjoDeundiak & @antoinevg maybe have some guesses on where in our code to look for the source/reason of this error. My guess is somewhere in the [ockam_node](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_node) crate.

**Comment by pro465** [comment]
> The error doesn't happen deterministically but I suspect it happens around node shutdown.

if its not deterministic its probably some subtle issue, one of those timing bugs that happens only when the executor makes specific decisions at specific times...

**Comment by pro465** [comment]
```
thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/mrinal/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
Checking state for node 'n5'
   0: std::panicking::begin_panic
```

that's quite interesting. i suspect you are running the commands in parallel, because normally `(e)println!` messages don't show up after a panic, much less in the middle of them. am I right?


*EDIT*: i think i'm wrong here, as it spawns a worker immediately after the `println!` with `connect_to`

**Comment by pro465** [comment]
```
   9: core::ptr::drop_in_place<ockam_node::context::Context>
```
i suspect it's the `async fn`s that take a (owned) `Context` but why does it not happen every time?

**Comment by pro465** [comment]
hello, quick question: do you know if it's happening in the `list` subcommand or the `create` subcommand?

**Comment by pro465** [comment]
assuming it is `list`, i thought it must be `query_pid`, but because of this:
https://github.com/build-trust/ockam/blob/e44e1f122a4f2ae5ebcb86134815f23e5ade571f/implementations/rust/ockam/ockam_node/src/executor.rs#L99-L112

i think it guarantees that `rt.strong_count()` is > 1 for at least until `query_pid` finishes. which means it should be out of our list of suspects...


unless we have a bug in `block_on` that didn't actually block the future until completion, which is unlikely but idk.

**Comment by mrinalwadhwa** [comment]
Yesterday when I reproduced it, it was in the `list` command.
However I have seen it in other situations. I'll try to reproduce in some other situation .. maybe that will help narrow things down.

**Comment by pro465** [comment]
well, if you have seen that in other situations then that points to a bug somewhere on ockam_node, so i guess i agree with your initial guess.

**Comment by pro465** [comment]
https://github.com/pro465/ockam/tree/diagnose

so i tried to reproduce the bug in GA to debug it. and it seems that the panics are not from `ockam node list`? it seems the panics are occuring in between the loop in `query_pids`, when no `async` is created or executed.

so i think it must be `ockam node create`...

**Comment by SanjoDeundiak** [comment]
Hey @pro465 , I think the bug is in `ockam_node` and happens sometimes during node shutdown, it doesn't depend on which command you run, because almost all commands:
1. Spawn a node
2. Do something
3. Shutdown the node

Also, I think it's connected to how we implement `Drop` for `Context` type, it has some tricks because `Drop` is sync, and we needed to do async stuff there. Could you please take a look there?

**Comment by pro465** [comment]
@SanjoDeundiak you are right! but not that something weird is happening in the drop itself:

 https://github.com/pro465/ockam/runs/7517120144?check_suite_focus=true

specifically it seems that somewhere in an async context, `Context` is being dropped with it being the last reference to its `Arc<Runtime>`. but i will have to figure out *where*?

**Comment by pro465** [comment]
@mrinalwadhwa @SanjoDeundiak i think i have found the issue: `Executor::execute`'s `block_future` call to "join" user code does not seem to be working, and so the user code can continue executing even after the executor is dropped. when the `Context` is dropped in those user code, since it is in an async context AND the executor is already dropped (i.e, it is the last one to have the reference to `Arc<Runtime>`), it panics.

evidence:
https://github.com/pro465/ockam/runs/7518405635?check_suite_focus=true#step:6:359

**Comment by pro465** [comment]
> assuming it is `list`, i thought it must be `query_pid`, but because of this:
> 
> https://github.com/build-trust/ockam/blob/e44e1f122a4f2ae5ebcb86134815f23e5ade571f/implementations/rust/ockam/ockam_node/src/executor.rs#L99-L112
> 
> i think it guarantees that `rt.strong_count()` is > 1 for at least until `query_pid` finishes. which means it should be out of our list of suspects...
> 
> unless we have a bug in `block_on` that didn't actually block the future until completion, which is unlikely but idk.

well it seems my last paragraph is true 😅 (albeit for `block_future` which is what i meant when i mistyped `block_on`)

**Comment by mrinalwadhwa** [comment]
> Executor::execute's block_future call to "join" user code does not seem to be working, and so the user code can continue executing even after the executor is dropped. when the Context is dropped in those user code, since it is in an async context AND the executor is already dropped (i.e, it is the last one to have the reference to Arc<Runtime>), it panics.

Interesting so this doesn't work:

https://github.com/pro465/ockam/blob/7a43c112eeeb740ac552353a3e09be8a07ad3939/implementations/rust/ockam/ockam_node/src/executor.rs#L120-L122

as seen [here](https://github.com/pro465/ockam/runs/7518405635?check_suite_focus=true#step:6:359) 

Maybe @spacekookie @antoinevg @SanjoDeundiak have some thoughts on why that may be.

**Comment by pro465** [comment]
> Interesting so this doesn't work:
> 
> https://github.com/pro465/ockam/blob/7a43c112eeeb740ac552353a3e09be8a07ad3939/implementations/rust/ockam/ockam_node/src/executor.rs#L120-L122
> 
> as seen [here](https://github.com/pro465/ockam/runs/7518405635?check_suite_focus=true#step:6:359)

yes, exactly

**Comment by pro465** [comment]
though i must say i don't know enough about tokio to be qualified to comment on why is it not working

**Comment by pro465** [comment]
so i was trying to get more info and... it seems `block_future` is working correctly?
https://github.com/pro465/ockam/runs/7537633541?check_suite_focus=true#step:6:522

it seems something else is going on here: there's some additional contexts created beyond `ockam_command` (since any context created in `util::emedded_node` will have name `util`, and the niodes to list them will be named `n[0-9]`).

so i will have to find all the places `Context` is created.

**Comment by pro465** [comment]
https://github.com/pro465/ockam/runs/7539189372?check_suite_focus=true#step:6:558

`ProcessorRelay::run` is (sometimes?) involved, altho i could not find where is it called in following the functions called by `ockam node list`. perhaps it is the issue in the background-running `ockam node create`?

**Comment by pro465** [comment]
`WorkerRelay::run` is also sometimes involved:
https://github.com/pro465/ockam/runs/7539189372?check_suite_focus=true#step:6:527

(note: both are from the same GA log)

**Comment by pro465** [comment]
@mrinalwadhwa could you tell me where is WorkerRelay and ProcessorRelay being created and called in `ockam node list`? or is it the background `ockam node create`?

**Comment by SanjoDeundiak** [comment]
@pro465 `Context` is a pretty basic building block in our Worker system. So, `Worker`s and `Processor`s are some entities that run in the background.  Each has corresponding `WorkerRelay` or `ProcessorRelay` to actually **run** it. And `Context` is an entity responsible for interacting with a runtime/sending messages. Each `Context` instance has its own reference to the runtime and an address. Each `Worker` and `Processor` has their instance of `Context` that they own, also you can create `detached` `Context` instances, that are not attached to any `Worker` or `Processor`.
That been said, because `Context` is so basic block, it's probably created many times during even simplest scenario (like `ockam node list`), and many of those instances are dropped during node shutdown, which is where probably issue is
Is that helpful?

**Comment by pro465** [comment]
@SanjoDeundiak thank you for the detailed documentation! and yes its helpful

**Comment by pro465** [comment]
Q: does `TcpRouter::register` stop the `Worker` spawned by the call to `Context::start_worker` before dropping its `ctx` in its drop glue?

https://github.com/pro465/ockam/blob/eea2a1114f138f43fd48df5781cafd618fb6af39/implementations/rust/ockam/ockam_transport_tcp/src/router/tcp_router.rs#L45-L46

**Comment by SanjoDeundiak** [comment]
@pro465 I don't think so. All Workers should be shut down by the main Router during node shut down though.

**Comment by pro465** [comment]
@SanjoDeundiak it does seem to be the case. however it seems like Executor is not correctly waiting for the Worker to actually get dropped before returning?

https://github.com/pro465/ockam/runs/7593023573?check_suite_focus=true#step:6:488


perhaps its because the WorkerRelay sends stop ACK **BEFORE** dropping, while the `.await` makes the tokio context-switch to the Executor, drop it, and then come back and drop it (the WorkerRelay) AFTER the Executor has already dropped, causing it to be the last ref, and therefore dropping its Runtime in an async context?

note: this potential situation should also (not) work in multi-threaded scenarios, but im not sure. 

note 2: this problem is in quite a lot a places, and the large number of situations causing panics (where Contexts were being dropped in async contexts) supports my hypothesis.

**Comment by pro465** [comment]
@mrinalwadhwa i think i've found the problem

**Comment by mrinalwadhwa** [comment]
@pro465 very interesting! I'm back at work tomorrow, I'll ask more people on the team to share thoughts/ideas on a gaining confidence in that hypothesis and possible fixes. In the meantime, do you have thoughts on what a fix might look like?

**Comment by pro465** [comment]
im not sure if it will work, but i'll share a potential solution:
```diff
    /// Build and spawn a new worker relay, returning a send handle to it
    pub(crate) fn init(rt: &Runtime, worker: W, ctx: Context, ctrl_rx: SmallReceiver<CtrlSignal>) {
        let relay = WorkerRelay::<W, M>::new(worker, ctx);
-       rt.spawn(relay.run(ctrl_rx));
+       rt.spawn(async move {
+             relay.run(ctrl_rx).await;
+             // send stop ACK here (**after** the `relay` is consumed and dropped) 
+       });
    }
```

(and removing the `send_stop_ack` call in the `run` fn, of course)

**Comment by pro465** [comment]
i think the change, if it works, should also be applied to similiar places, such as `ProcessorRelay`.

**Comment by mrinalwadhwa** [comment]
If you want to send a quick PR with that change .. I'm happy to test it and see if the problem goes away for the cases were with a few repetitions I can reproduce the problem. Like the `node list` case above.

**Comment by pro465** [comment]
i'm sorry to say i won't be able to do that right now, because i am feeling quite sleepy and it's nighttime here.

**Comment by mrinalwadhwa** [comment]
of course, no rush at all, thank you for exploring this!
I'll try to gather more ideas/inputs on this over the next day or so.

**Comment by pro465** [comment]
thank you!

question: since we are moving the `ctx` into `relay`, we need to somehow clone the `ctx` before dropping the `relay`, to be able to call `ctx.send_stop_ack().await`. does cloning a `ctx` have unintended consequences?

**Comment by pro465** [comment]
i think we can use `&mut Context` (or even `&Context`) for WorkerRelay to avoid this.


edit: oh wait that means `Context` won't still be dropped before `ctx.send_stop_ack()`

**Comment by pro465** [comment]
so basically, problem: we can't call `ctx.send_stop_ack()` after dropping `ctx`, because Rust.

**Comment by pro465** [comment]
so it seems detached contexts also have the problem:

https://github.com/pro465/ockam/runs/7605174163?check_suite_focus=true#step:6:106


but im not sure how to solve that, because the fields are dropped AFTER the struct's Drop impl is called, but we need to drop the fields BEFORE notifying the AsyncDrop. perhaps `Option<Arc<Runtime>>` and `self.rt.take();` in drop?

**Comment by mrinalwadhwa** [comment]
Thank you @pro465 👏

**Comment by antoinevg** [comment]
Awesome work @pro465! 🏅

**Comment by pro465** [comment]
@antoinevg and @mrinalwadhwa thank you so much! especially many thanks to @SanjoDeundiak who helped me in the internal details of how ockam works, and @twittner who actually fixed the issue!
