### ISSUE TITLE
Add commands `ockam node start` and `ockam node stop`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3014]
We currently have [node commands](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/node)

```
ockam node create green
```

and

```
ockam node delete green
```

We also need

```
ockam node start
```

and

```
ockam node stop
```

so that a node can be started and stopped without losing its identity and other state.

**Comment by BeenzSyed** [comment]
@spacekookie, should this be reassigned to someone else on the team? I remember you had completed the Rust side of starting and stopping a node and it's unblocked for it to be added to the Ockam CLI.

**Comment by spacekookie** [comment]
I think this issue is basically done, see #3111
