### ISSUE TITLE
Remove `ockam node purge` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3028]
`ockam node purge` and `ockam node delete --all` have very similar behavior.

We want to keep `ockam node delete --all`

- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs
- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/purge.rs

**Comment by PrajwalBorkar** [comment]
I like to work on this. Should I remove the purge.rs file?

**Comment by mrinalwadhwa** [comment]
@PrajwalBorkar 👋 That's great. Thank you.

> Should I remove the purge.rs file?

Yes and the locations where its referenced https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/mod.rs

**Comment by mrinalwadhwa** [comment]
fixed in https://github.com/build-trust/ockam/pull/3030
