### ISSUE TITLE
CI doesn't run rust doc tests

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#3033]
Currently CI doesn't run doc tests, presumably after switching to `nextest`

**Comment by SanjoDeundiak** [comment]
Hey @neil2468, do you want to take a look?

**Comment by neil2468** [comment]
Hi @SanjoDeundiak 

I can take this on if you're okay to wait till 5th August; I'm away on holiday right now. 

Thanks!

**Comment by SanjoDeundiak** [comment]
@neil2468 that would be great!
