### ISSUE TITLE
Replace `-p, --port` option with `-a, --api-address` in `ockam node create` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3039]
When we create a node with `ockam node create` it [starts a TCP Transport](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs#L144-L145) that is listens on `0.0.0.0:62526`

The IP is currently hardcoded, and the PORT is provided by an option on the `ockam node create` command:

```
-p, --port <PORT>                        Specify the API port [default: 62526]
```

We want to remove the `-p, --port <PORT>` option and replace it with an `-a, --api-address` that has a default value of `127.0.0.1:62526`

Source code of the create command is here:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Handschrift** [comment]
Hello! 
You can assign this issue to me if you like to and I will take a look at it later.

**Comment by mrinalwadhwa** [comment]
@Handschrift 👋 thank you for picking it up!

**Comment by mrinalwadhwa** [comment]
closed by https://github.com/build-trust/ockam/pull/3044 thank you @Handschrift
