### ISSUE TITLE
Missing commit message conventions.

### ISSUE THREAD

**Issue by Handschrift** [build-trust/ockam#3045]
In the pull request template there is a check called 
"All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages)."

The link leads to the contributing.md but there is no section called  "commit-messages".

That could lead to misunderstandings and additional effort  for new contributors.

**Comment by mrinalwadhwa** [comment]
@Handschrift thank you for pointing this out. We moved some pages around in the past few weeks and broke this link. Added https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages
