### ISSUE TITLE
Rename secure channel create commands

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3051]
Currently we have:

```
ockam secure-channel create connector
```

and 

```
ockam secure-channel create listener
```

We want to change it to:

```
ockam secure-channel create
```

and 

```
ockam secure-channel create-listener
```

where `...create connector` is changed to `...create` and `create listener` is changed to `create-listener`

https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs

**Comment by tmuro17** [comment]
@mrinalwadhwa I'd like to take a shot at this one, if that's ok?

**Comment by mrinalwadhwa** [comment]
@tmuro17 👋 that would be awesome, please do.

**Comment by mrinalwadhwa** [comment]
added in https://github.com/build-trust/ockam/pull/3062
