### ISSUE TITLE
Add --node option to message send command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3053]
# Current Behavior:

We can create ockam nodes using `ockam` command as follows:

```bash
# Create three ockam nodes
» ockam node create "n1" --api-address "127.0.0.1:6001"
» ockam node create "n2" --api-address "127.0.0.1:6002"
» ockam node create "n3" --api-address "127.0.0.1:6003"
```

Each node gets a tcp transport that is listening on the above `--api-address` and then we can [route messages](https://github.com/build-trust/ockam/tree/develop/documentation/guides/rust/get-started/03-routing) over multiple TCP hops as follows to an uppercase worker on the last node n3.

```bash
» ockam message send \
   /ip4/127.0.0.1/tcp/6001/ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase "hello"
HELLO
```

This is defined here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/message/send.rs

---

Various `ockam` subcommands allow delegating actions to an already created node.
For example:  `ockam identity create --node n1`

https://github.com/build-trust/ockam/blob/1cd357cb76d9193c36a66b915c0b11a610701405/implementations/rust/ockam/ockam_command/src/identity/create.rs#L11-L14
https://github.com/build-trust/ockam/blob/1cd357cb76d9193c36a66b915c0b11a610701405/implementations/rust/ockam/ockam_command/src/identity/create.rs#L33-L57

---

# Desired Behavior:

We would like to have a `--node` option on the `ockam message send` command, so that this will work:

```bash
» ockam message send --node n1 /ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase "hello"
HELLO
```

**Comment by mrinalwadhwa** [comment]
@tmuro17 I just added some notes on this issue.
What do you think about picking this one up?

**Comment by selectiveduplicate** [comment]
Hi!
Been looking at this; the desired behavior seems to be working:

```sh
;; cargo run -- node create "n1" --api-address "127.0.0.1:6001"
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `/home/sakib/Documents/Programming/Rust_stuff/ockam/target/debug/ockam node create n1 --api-address '127.0.0.1:6001'`
Node: n1, Status: [✓], Worker count: 19, Pid: 29578, Transport count: 1
;; cargo run -- node create "n2" --api-address "127.0.0.1:6002"
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `/home/sakib/Documents/Programming/Rust_stuff/ockam/target/debug/ockam node create n2 --api-address '127.0.0.1:6002'`
Node: n2, Status: [✓], Worker count: 19, Pid: 29633, Transport count: 1
;; cargo run -- node create "n3" --api-address "127.0.0.1:6003"
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `/home/sakib/Documents/Programming/Rust_stuff/ockam/target/debug/ockam node create n3 --api-address '127.0.0.1:6003'`
Node: n3, Status: [✓], Worker count: 19, Pid: 29681, Transport count: 1
;; cargo run -- message send --node n1 /ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase "hello to ockam"
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `/home/sakib/Documents/Programming/Rust_stuff/ockam/target/debug/ockam message send --node n1 /ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase 'hello to ockam'`
HELLO TO OCKAM
``` 
I only added a `NodeOpts` member to the `SendCommand` struct; is that all or am I missing something? 😅
The previous way of doing it still works though:

```shell
» ockam message send \
   /ip4/127.0.0.1/tcp/6001/ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase "hello"
HELLO
```
Do we deprecate that?

Thanks.

**Comment by justinvzyl** [comment]
Can you perhaps create a PR then we can have a look?

**Comment by mrinalwadhwa** [comment]
Ah, I should've been more clear about the desired behavior.

The desired behavior is

e --> n1 --> n2 --> n3

e here is the command embedded node. We want an api request from e to n1 asking n1 to send a message 


What would work without any changes is

e --> n2 --> n3

Which is what you see above.

(If this still seems confusing, I'll draw a better explanation in my morning)

**Comment by mrinalwadhwa** [comment]
@selectiveduplicate @justinvzyl thank you both for thinking about this. Maybe this picture will help better understand the behavior we're going for. (The picture is a simplification but I hope it helps get the idea across.)

We want an api request from e to n1 asking n1 to send a message instead of e sending the message directly (which is the current behavior.)

```mermaid
sequenceDiagram
    autonumber

    participant E    as   (E) Command Embedded Node
    participant N1   as   (N1)
    participant N2   as   (N2) 
    participant N3   as   (N3) 

    E  -->> N1: RequestToSendMessage("/ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase", "hello")
    N1 -->> N2: "hello"
    N2 -->> N3: "hello"
    N3 -->> N2: "HELLO"
    N2 -->> N1: "HELLO"
    N1 -->> E : ResponseToSentMessage("HELLO")

```

This request/response code would be similar to the create identity code [here](https://github.com/build-trust/ockam/blob/5903b5b9c9a39a40bcea46a5044e49b1f8401135/implementations/rust/ockam/ockam_command/src/identity/create.rs#L33-L57)

https://github.com/build-trust/ockam/blob/1cd357cb76d9193c36a66b915c0b11a610701405/implementations/rust/ockam/ockam_command/src/util/api.rs#L84-L89

https://github.com/build-trust/ockam/blob/1cd357cb76d9193c36a66b915c0b11a610701405/implementations/rust/ockam/ockam_command/src/util/api.rs#L422-L431

Please let me know if you have questions.

**Comment by selectiveduplicate** [comment]
Ok I understand the desired behavior. But I'm not sure where and how to start changing stuff for it.
Btw the following works?! (unless I'm doing something stupid):

```sh
;; cargo run -- message send --node n1 /ip4/127.0.0.1/tcp/6001/ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase "hello to me"
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `/home/sakib/Documents/Programming/Rust_stuff/ockam/target/debug/ockam message send --node n1 /ip4/127.0.0.1/tcp/6001/ip4/127.0.0.1/tcp/6002/ip4/127.0.0.1/tcp/6003/ockam/uppercase 'hello to me'`
HELLO TO ME
```

**Comment by mrinalwadhwa** [comment]
> Ok I understand the desired behavior. 

Awesome.

> But I'm not sure where and how to start changing stuff for it.

I think it looks something like this:

1. Add `send_message_request` and `send_message_response` CBOR schemas to [this document](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/schema.cddl).
2. Define a `message` service [here](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_api/src) and [here](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_api/src/nodes/service), (use identity service as a reference, the message service would be simpler because it only handles `send_message_request`)
3. Make sure the `message` service is started [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L171-L182) by the node manager.
4. Call the `message` service with `send_message_request` from the `message send` command. Similar to [this](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/api.rs#L84-L89) and [this](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/create.rs).

The actual sending of the "hello" message will then happen in the api handler that is handling the `send_message_request`.

I'm sure you'll have more questions, so if you want to explore this in a draft PR, please do. We can help suggest next steps on the PR

As I write this, I realize I shouldn't have called this a `good first issue` 😬.
If you want to take on something simpler first, I think https://github.com/build-trust/ockam/issues/3056 is a simpler change in the same commands call api services space. Let me know.

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa I'm not sure we need a dedicated service to do the job here. Or maybe you confused services (identity, authenticated, vault) with functionality that `NodeManager` provides. I think send message behaviour could be achieved by adding another endpoint to `NodeManager`

**Comment by mrinalwadhwa** [comment]
@adrianbenavides added this in https://github.com/build-trust/ockam/pull/3154
@selectiveduplicate @justinvzyl Thank you, sorry this turned out to be more elaborate than I expected.
