### ISSUE TITLE
Make async tests not hang if test function panics

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#3054]
Currently async tests just hang whenever panic occurs.
Possible solution may be using [catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html). Below you can find a working prototype

```rs
async fn test_fn(mut ctx: Mutex<Context>) -> Result<()> {
    let _ctx = ctx.get_mut().unwrap();
    panic!("PANIC")
}

#[test]
fn test() {
    use core::time::Duration;
    use ockam_node::{compat::tokio::time::timeout, NodeBuilder};

    let (mut ctx, mut executor) = NodeBuilder::without_access_control().build();
    executor
        .execute(async move {
            let child_ctx = Mutex::new(ctx.new_detached(Address::random_local()).await.unwrap());
            match timeout(Duration::from_millis(1000), test_fn(child_ctx).catch_unwind()).await {
                Ok(r) => match r {
                    Ok(r) => match r {
                        Err(err) => {
                            ctx.stop().await.unwrap();
                            Err(err)
                        }
                        Ok(_) => Ok(()),
                    },
                    Err(_) => {
                        ctx.stop().await.unwrap();
                        panic!("Test panic")
                    }
                },
                Err(_) => {
                    ctx.stop().await.unwrap();
                    panic!("Test timeout")
                }
            }
        })
        .expect("Executor should not fail")
        .expect("Test function should not fail");
}

```

**Comment by Retamogordo** [comment]
Hi, I would like to take this.

**Comment by mrinalwadhwa** [comment]
@Retamogordo That would be awesome! Thank you, all yours.

**Comment by adrianbenavides** [comment]
To add more details about what needs to be done.

We use the `ockam_macros::test`(or `ockam::test`) to write async tests that need to set up a node - i.e. tests that need to use a `Context` instance to create transports, workers, send/recv messages, etc.

We have tests that use that macro that randomly hangs from time to time, but we don't know exactly why. @SanjoDeundiak has been investigating the issue and the prototype described in the description is what the `ockam_macros::test` macros should output. So, to apply that fix, we should modify the [`ockam_macros::test`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_macros/src/node_test_attribute.rs) macro.

Potentially, we should check if a similar issue could also be occurring in the [`ockam_macros::node`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_macros/src/node_attribute.rs) macro.

Finally, the tests from `ockam_node/src/delayed.rs` and `ockam/ockam_node/src/tests.rs` should be rewritten using the `ockam_macros::test` macro. (related PR: https://github.com/build-trust/ockam/pull/3079)

**Comment by Retamogordo** [comment]
So, at first glance, the procedure to fix it is like so:
1) rewrite ockam_node/src/delayed.rs and ockam/ockam_node/src/tests.rs and possibly, some other files, to rely ockam_macros::test
2) witness that  tests indeed hang upon panic
3) modify the proc macro, so it catches panicking
?

**Comment by SanjoDeundiak** [comment]
@Retamogordo I think `3` is the key here. You can recheck that panic hangs tests, but that behaviour is what I verified and that is what lead me to creating this issue. `1` would be the cherry on top if you could do that. Tnx!

**Comment by adrianbenavides** [comment]
Regarding `3`, you have here some tips that might be helpful: https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_macros#develop

The macro itself has decent documentation, but let me know if you need help with anything!
