### ISSUE TITLE
Rename NodeMan to NodeManager

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3055]
We want to rename NodeMan to NodeManager along with changing all the places it is used:

https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service/services.rs#L12

**Comment by Guileas** [comment]
@mrinalwadhwa seem's easy, can I take this one?

**Comment by mrinalwadhwa** [comment]
@Guileas that would be amazing, please do!

**Comment by Guileas** [comment]
Ok, I'm on it!

Doest this also apply to : ```pub const NODEMAN_ADDR: &str = "_internal.nodeman";``` 
Or the ```NODEMAN_ADDR``` const stay as it is?

**Comment by mrinalwadhwa** [comment]
Awesome, yes it does
