### ISSUE TITLE
Make `--api-address` option of `ockam node create` default to `127.0.0.1:0`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3063]
# Current Behavior

```
ockam node create
```

define here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs

currently has a default `--api-address` value of `127.0.0.1:62526`

This means that the second time `ockam node create` is run a new address must be specified.

# Desired Behavior

We want it to be possible to:

```
ockam node create
ockam node create
ockam node create
ockam node create
```

where a new port is automatically picked for each node.

**Comment by tmuro17** [comment]
Would love to take a crack at this one

**Comment by mrinalwadhwa** [comment]
@tmuro17 awesome, thank you .. a few quick notes:

We can't simply change the value to `127.0.0.1:0`
https://github.com/build-trust/ockam/blob/ee3919eaf07ed0bb6c02171cfa05e9970101a3d8/implementations/rust/ockam/ockam_command/src/util/mod.rs#L16

since the TCP listen is done by the spawned node and the command embedded node needs to know the address to speak with the spawned node

https://github.com/build-trust/ockam/blob/20da0a4112c9ffd6a08ff37d48ec0f544d5018d9/implementations/rust/ockam/ockam_command/src/node/create.rs#L154-L156

The only way I can think of is to create a function that does a TcpListener::bind on `127.0.0.1:0` to find an unused port and then immediately stops listening. Then pass that port along when spawning a node.

**Comment by tmuro17** [comment]
@mrinalwadhwa You answered the question before I had time to look at the code and ask it.  And I like your solution to find an open port.

**Comment by mrinalwadhwa** [comment]
added in https://github.com/build-trust/ockam/pull/3064
