### ISSUE TITLE
Make `ockam message send ...` support `-` to represent STDIN in its addr argument

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3068]
## Current Behaviour:

Here are two example commands:

```
» ockam node create

Node Created!

Node:
  Name: 7ad4e471
  Status: Running
  API Address: 127.0.0.1:53552
  ...
```

then:

```
» ockam message send /ip4/127.0.0.1/tcp/53552/ockam/uppercase "hello"
HELLO
```

## Desired Behaviour:

We want the following to work (note the hyphen)

```
» echo "/ockam/uppercase" | ockam message send /ip4/127.0.0.1/tcp/53552/- "hello"
HELLO
```

also

```
» echo "/ip4/127.0.0.1/tcp/53552/" | ockam message send -/ockam/uppercase "hello"
HELLO
```

`ockam message send ...` should inspect `addr` (its first argument) to see if contains `-`, if it does, replace the hyphen with piped input read from STDIN

This will allow us to chain various `ockam` commands

The code for this is here:
https://github.com/build-trust/ockam/blob/0df0d9658b44b772d24e7ac3ea95313f61c15c21/implementations/rust/ockam/ockam_command/src/message/send.rs#L8-L12

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by pro465** [comment]
would like to take this up tomorrow after exams

**Comment by mrinalwadhwa** [comment]
@pro465 that would be awesome!!
good luck with your exams.

**Comment by mrinalwadhwa** [comment]
In https://github.com/build-trust/ockam/pull/3116 @leonzchang added support for this. However we learnt that clap confuses `-` at the beginning of the string with an option. So we have to say:

```
» echo "/ip4/127.0.0.1/tcp/53552/" | ockam message send -- -/ockam/uppercase "hello"
HELLO
```

Instead of what we were going for:

```
» echo "/ip4/127.0.0.1/tcp/53552/" | ockam message send -/ockam/uppercase "hello"
HELLO
```

Since it's okay for us to do this replace across commands for multaddr/route values .. I wonder if there is a way to replace `-/` or `/-` in the entire std::env::args before clap even starts to parse.

**Comment by mrinalwadhwa** [comment]
Some more improvements to explore:

Currently, this works:

```
echo "/ip4/127.0.0.1/tcp/64005/" | ockam message send -- -/ockam/uppercase "hello"
```

but this fails:

```
» echo "/ip4/127.0.0.1/tcp/64005" | ockam message send -- -/ockam/uppercase "hello"
Error invalid digit found in string
```

we should make that less fragile

**Comment by leonzchang** [comment]
@mrinalwadhwa I fix this in [#3120](https://github.com/build-trust/ockam/pull/3120)

**Comment by adrianbenavides** [comment]
Another improvement we could do here is to encapsulate this string parsing behavior in a struct, so we can reuse it on other commands. Maybe it could be called `HyphenatedMultiAddr`, or something like that? I'm thinking about something along these lines:

```rust
#[derive(Clone, Debug, Args)]
pub struct SendCommand {
    #[clap(flatten)]
    addr: HyphenatedMultiAddr,
    message: String,
}

#[derive(Clone, Debug, Args)]
struct HyphenatedMultiAddr {
    addr: String
};

impl HyphenatedMultiAddr {
    fn new(addr: &str) -> Self {
        HyphenatedMultiAddr {
            addr: addr.to_string()
        }
    }

    fn multiaddr(&self) -> Result<MultiAddr> {
        let addr = match self.0 {
            ...
        };
        MultiAddr::from_str(&addr)?
    }
}
```

**Comment by mrinalwadhwa** [comment]
To deal with the problem from [this comment](https://github.com/build-trust/ockam/issues/3068#issuecomment-1206063564).

I'm wondering if we could use `parse_from` https://docs.rs/clap/latest/clap/trait.Parser.html#method.parse_from
Instead of `parse` here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/lib.rs#L245

and give parse_from std::env::args that have already be processed to replace `-/` or `/-` with STDIN

**Comment by pro465** [comment]
working on a fix using `parse_from`..

**Comment by mrinalwadhwa** [comment]
@pro465 Awesome 🥳

**Comment by pro465** [comment]
sorry i messed up the branch, it it showing it is 446 commits ahead of bouild-trust:patch-1 branch

**Comment by mrinalwadhwa** [comment]
I can fix it for you if you want ... look like I have access to it. Should I?

**Comment by leonzchang** [comment]
@adrianbenavides thank you for the advice, I have refactored it in [#3123](https://github.com/build-trust/ockam/pull/3123)
@mrinalwadhwa I will dive into [it](https://github.com/build-trust/ockam/issues/3068#issuecomment-1206213038)

**Comment by pro465** [comment]
@leonzchang oh well now one of us will have to fix merge conflicts

**Comment by pro465** [comment]
@mrinalwadhwa perhaps. I don't seem to be able to install `gpg`, so...

**Comment by mrinalwadhwa** [comment]
@leonzchang @pro465 Thank you both!!
That was awesome open source collab on making the feature work 🏆
