### ISSUE TITLE
Refactor `ockam transport ...` commands into `ockam tcp-...` commands

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3076]
# Create

We currently have

```
ockam transport create tcp-connector ...
ockam transport create tcp-listener ...
```

We want to change to:

```
ockam tcp-connection create ...
ockam tcp-listener create ...
```

Without changing their behavior.

# List

We currently have 

```
ockam transport list --node n1
```

This will list both tcp listeners and tcp connection.

We want to change it to

```
ockam tcp-connection list --node n1
```

to list connections, and

```
ockam tcp-listener list --node n1
```

to list listeners

# Delete

We currently have 

```
ockam transport delete --node n1 <TRANSPORT_ID>
```

which will delete either connections or listeners.

We want to change it to:

```
ockam tcp-listener delete --node n1 <TRANSPORT_ID>
```

and

```
ockam tcp-connection delete --node n1 <TRANSPORT_ID>
```

# Code

The code for these commands is here:
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/transport

---
Related: #3077 #3078

**Comment by mrinalwadhwa** [comment]
@spacekookie what are your thoughts on the above?

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa @spacekookie 
How about
```
ockam tcp connect ...
ockam tcp listen ...
ockam tcp create inlet ...
ockam tcp create outlet ...
```

**Comment by adrianbenavides** [comment]
This looks cleaner/simpler to me.
> @mrinalwadhwa @spacekookie How about
> 
> ```
> ockam tcp connect ...
> ockam tcp listen ...
> ockam tcp create inlet ...
> ockam tcp create outlet ...
> ```

I'd also add:
```
ockam tcp delete <id>  // (internally it could find out if it's a connector or a listener)
```

To list connectors and listeners we could either:
```
ockam tcp listeners
ockam tcp connectors
```

or to keep it more similar to what we have: 
```
ockam tcp list listeners
ockam tcp list connectors
```

Just throwing a couple of ideas!

**Comment by mrinalwadhwa** [comment]
I think the structure we want to have is consistently `ockam NOUN VERB` otherwise discovery of sub commands becomes a challenging UX... for example in the suggestion from @SanjoDeundiak above the fact that `create` has sub commands becomes not so obvious

**Comment by SanjoDeundiak** [comment]
Is it better this way?
```
ockam tcp connect ...
ockam tcp listen ...
ockam tcp inlet create ...
ockam tcp outlet create ...
```

**Comment by mrinalwadhwa** [comment]
In that suggestion, how would we delete/stop connection/listener?

**Comment by SanjoDeundiak** [comment]
Ok, I see your point, what about
```
ockam tcp connection create/stop/list
ockam tcp listener create/stop/list
ockam tcp inlet create/stop/list
ockam tcp outlet create/stop/list
```

**Comment by mrinalwadhwa** [comment]
Both of these have pluses and minuses - `ockam NOUN VERB` or `ockam NOUN_CATEGORY NOUN VERB`.

1. `ockam NOUN VERB` is more verbose in the top level help. `ockam NOUN_CATEGORY NOUN VERB` is less verbose
1. `ockam NOUN VERB` is more intuitive/consistent in structure. So people would have to check help less often
1. Supporting `ockam NOUN_CATEGORY NOUN VERB` means we'll have some commands that are 1 level deep (ockam node create) and others that are 2 level deep (this could be okay but three levels would really unintuitive).
1. Adding a hyphen between `NOUN_CATEGORY-NOUN` can give us a consistent `ockam NOUN VERB` structure


```
ockam tcp-connection create/stop/list
ockam tcp-listener create/stop/list
ockam tcp-inlet create/stop/list
ockam tcp-outlet create/stop/list
```

or

```
ockam tcp connection create/stop/list
ockam tcp listener create/stop/list
ockam tcp inlet create/stop/list
ockam tcp outlet create/stop/list
```

**Comment by mrinalwadhwa** [comment]
@anuvratsingh as you look into this, please note this comment about structure
https://github.com/build-trust/ockam/issues/3077#issuecomment-1206568753

**Comment by mrinalwadhwa** [comment]
https://github.com/build-trust/ockam/issues/3077#issuecomment-1206568753

So we're going for:

```
ockam_command/
  src/
    tcp/
      mod.rs
      connection/
        mod.rs
        create.rs
        delete.rs
      listener/
        mod.rs
        create.rs
        delete.rs
      inlet/
        mod.rs
        create.rs
      outlet/
        mod.rs
        create.rs
```

**Comment by lameferret** [comment]
Thanks @mrinalwadhwa. I will follow the given dir structure, and sorry for confusion. Also.
- Can I get some test, as I'm not able to figure out what kind of address `transport` supports (like `/ip4/127.0.0.1/tcp/6001/{w or w/o(service/api)}` doesn't work).
- IMO rather than using a bland error([example](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_command/src/transport/create.rs#L86)), it should specify what format it expects (where applicable). If I do it should, I create a new PR for most of `ockam_commands`? 
- What should be done about [ CreateTransport](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L14) and [DeleteTransport](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L42) as it feel to me that both tcp-listener/connection would use the same function. So should I let it be or rename it to something for consistency?.
- Can [`unwrap()`](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_command/src/transport/create.rs#L143) be replaced with 

    ```rust 
    let multiaddr = match route_to_multiaddr(&r) {
        Some(addr) => addr,  
        None => {
            eprintln!("Couldn't convert given address into `MultiAddr`");
            std::process::exit(-1)
        }
    };
    ```

**Comment by mrinalwadhwa** [comment]
Sure, give me 15 mins or so, I'll write some notes with example.

**Comment by mrinalwadhwa** [comment]
Here's an example that will currently work:

```
> ockam node create n1 --api-address "127.0.0.1:6001"
> ockam node create n2 --api-address "127.0.0.1:6002"
> ockam transport create tcp-listener "127.0.0.1:7001" --node n2
> ockam transport create tcp-connector "127.0.0.1:7001" --node n1
> ockam message send "hello" --to /dnsaddr/localhost/tcp/6001/ip4/127.0.0.1/tcp/7001/service/uppercase
HELLO
```

there is lot of improvements possible in this but let's start with getting this to work:

```
> ockam node create n1 --api-address "127.0.0.1:6001"
> ockam node create n2 --api-address "127.0.0.1:6002"
> ockam tcp-listener create "127.0.0.1:7001" --node n2
> ockam tcp-connection create "127.0.0.1:7001" --node n1
> ockam message send "hello" --to /dnsaddr/localhost/tcp/6001/ip4/127.0.0.1/tcp/7001/service/uppercase
HELLO
```

**Comment by mrinalwadhwa** [comment]
> IMO rather than using a bland error([example](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_command/src/transport/create.rs#L86)), it should specify what format it expects (where applicable). If I do it should?

That's a great idea. I think each command should have examples defined in a const and then we can show them on error and we can add them to the HELP_TEMPLATE. I'll create a new issue for it. In the issue we can collect some examples to add and then sure, would love a PR ❤️

**Comment by mrinalwadhwa** [comment]
> What should be done about [CreateTransport](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L14) and [DeleteTransport](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L42) as it feel to me that both tcp-listener/connection would use the same function. So should I let it be or rename it to something for consistency?.

We should rename them for consistency to be like the other commands
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs#L30 
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L26

Repetition here is okay as these will evolve to have somewhat separate implementations.

**Comment by mrinalwadhwa** [comment]
> Can [unwrap()](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_command/src/transport/create.rs#L143) be replaced with

```rust
let multiaddr = match route_to_multiaddr(&r) {
    Some(addr) => addr,  
    None => {
        eprintln!("Couldn't convert given address into `MultiAddr`");
        std::process::exit(-1)
    }
};
```

Yes absolutely!!

**Comment by lameferret** [comment]
> We should rename them for consistency to be like the other commands
"""
> Repetition here is okay as these will evolve to have somewhat separate implementations.

@mrinalwadhwa These are `ockam_api`'s Create/Delete Transport, you might be confusing them with `ockam_command`'s Create/Delete Transport 
```rust 
#[derive(Debug, Clone, Decode, Encode)]
#[rustfmt::skip]
#[cbor(map)]
pub struct CreateTransport<'a> {
    #[cfg(feature = "tag")]
    #[n(0)]
    tag: TypeTag<1407961>,
    /// The type of transport to create
    #[n(1)] pub tt: TransportType,
    /// The mode the transport should operate in
    #[n(2)] pub tm: TransportMode,
    /// The address payload for the transport
    #[n(3)] pub addr: Cow<'a, str>,
}
```
So `tcp_listener/connection` both uses this function. But Transport in the name will create confusion, having two functions with different names, but exact same functionality in the same file wouldn't cut it, so what it should be renamed into?

**Comment by mrinalwadhwa** [comment]
Ah yes, I did confuse them.

I think what you did here is okay for the time being 👍 
https://github.com/build-trust/ockam/blob/a71ee8c3e930a056d4e6bf6f12167117baa6f0f6/implementations/rust/ockam/ockam_command/src/util/api.rs#L31-L86

**Comment by mrinalwadhwa** [comment]
@anuvratsingh I realized you were suggesting something different from what I was:

> IMO rather than using a bland error([example](https://github.com/build-trust/ockam/blob/abd49a5da516c30aa567e92d3633ec911798bd2c/implementations/rust/ockam/ockam_command/src/transport/create.rs#L86)), it should specify what format it expects (where applicable). If I do it should, I create a new PR for most of ockam_commands?

If you want to, please go ahead and create PRs for errors like [this one](https://github.com/build-trust/ockam/issues/3076#issuecomment-1207274351) in all commands. That would be a great improvement in errors.

I'll separately think about how to make errors friendlier with examples.

**Comment by lameferret** [comment]
@mrinalwadhwa, I created #3143 to further discus this.

**Comment by mrinalwadhwa** [comment]
Awesome! Thank you for starting the discussion.
I'll leave some notes on it soon.
