### ISSUE TITLE
Refactor `ockam portal ...` commands into `ockam tcp-...` commands

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3077]
We currently have:

```
ockam portal create tcp-inlet ..
ockam portal create tcp-outlet ...
```

We want to change these to:

```
ockam tcp-inlet create ...
ockam tcp-outlet create ...
```

Without changing their behavior.

These commands are defined here:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/portal/create.rs

---
Related: #3076 #3078

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mrinalwadhwa** [comment]
@spacekookie what are your thoughts on the above?

**Comment by Hwatwasthat** [comment]
Hi I'd be interested in trying to do this. Would this require reworking the portal subcommand (by removing it?) would this mean creating tcp-inlet and tcp-outlet folders in the ockam_command/src folder? as the portal subcommand is being removed (as the only enum is used to point to the create command for these two right now).

**Comment by mrinalwadhwa** [comment]
@Hwatwasthat thank you for taking this on 🥳 

> Would this require reworking the portal subcommand (by removing it?) 

Yes

> would this mean creating tcp-inlet and tcp-outlet folders in the ockam_command/src folder? as the portal subcommand is being removed (as the only enum is used to point to the create command for these two right now).

Let's create:

```
ockam_command/
  src/
    tcp/
      mod.rs
      inlet/
        mod.rs
        create.rs
      outlet/
        mod.rs
        create.rs        
```

We want to keep the folders because we'll add other commands soon.
Keeping them under a `tcp/` folder would be nice because we want to in the near future make TCP functionality a plugin so all of them living in one folder would be helpful.

this also applied to `tcp-connection` and `tcp-listener` in https://github.com/build-trust/ockam/issues/3076

**Comment by mrinalwadhwa** [comment]
@Hwatwasthat note in https://github.com/build-trust/ockam/pull/3140 for https://github.com/build-trust/ockam/issues/3076 @anuvratsingh started the `ockam_command/src/tcp/*` directory structure.

The `inlet` & `outlet` directories for `tcp-inlet` & `tcp-outlet` command will live there as well. Let me know in case you have any questions.

**Comment by lameferret** [comment]
Hey @mrinalwadhwa, there is a [TODO: Add delete, list, show subcommands](https://github.com/build-trust/ockam/blob/9ba3e4e7ea179f182e029620d8e6b27f802207cb/implementations/rust/ockam/ockam_command/src/portal/mod.rs#L4), which I might be able to do, so should I do that in `tcp inlet/outlet` or in portal which would be refactored later on?

**Comment by mrinalwadhwa** [comment]
@anuvratsingh I think if you create them directly under tcp/inlet and tcp/outlet then it would lead to less conflicts irrespective of the order in which the PRs are created

**Comment by mrinalwadhwa** [comment]
@Hwatwasthat 👋 checking back to see if you need help with this or have any questions about the issue? If you don't have time to work on it, that's okay too, we'll open it up for others to explore.

**Comment by Hwatwasthat** [comment]
Hey, yeah I've gotten a bit busier than expected! I'll keep an eye on it
and do out anyway for the practice but open it up so it might get done
faster if I can't find the time to do it.

**Comment by mrinalwadhwa** [comment]
Thank you, when you have time to do some for practice / get familiar with the code. Have a look at the new issue in the https://github.com/build-trust/ockam/labels/good%20first%20issue label.
