### ISSUE TITLE
Refactor `ockam secure-channel create-listener` into `ockam secure-channel-listener create`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3078]
We currently have 

```
ockam secure-channel create-listener ...
```

defined here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L28-L38

we want to change it to:

```
ockam secure-channel-listener create ...
```

to align with the `ockam NOUN VERB ...` form.

---
Related: #3076 #3077

**Comment by lameferret** [comment]
Meanwhile #3080, can I do this too?

**Comment by mrinalwadhwa** [comment]
Of course, go for it!

**Comment by lameferret** [comment]
@mrinalwadhwa Sorry, I should have asked earlier. As this is a `noun verb` refactor, that means creating a new `noun` `secure_channel_listener`, separating it from `secure_chanel`, or it implies something else?

**Comment by mrinalwadhwa** [comment]
> that means creating a new noun secure_channel_listener, separating it from secure_channel

yes, that's exactly what I wanted to convey
also, please ask as many questions as you needs.
