### ISSUE TITLE
Display a node's default identifier in output of `ockam node create | show | list` commands

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3100]
# Current Behaviour

Currently if you run `ockam node create | show | list` you see status output that looks like this:

```
> ockam node create

Node Created!

Node:
  Name: 2f92103a
  Status: Running
  API Address: 127.0.0.1:60942
  Pid: 62535
  Worker count: 19
  Transport count: 1
  Log Path: /Users/mrinal/Library/Application Support/io.ockam.ockam-cli/node-2f92103a/2f92103a.log

```

When a node is created it also gets a default identity, which you can display as follows:

```
> ockam identity show --node 2f92103a
P5ea32d08fc46d8176abf6e0e80ba9b8b9604c24b3093f84131624f19e7e57b71
```

# Desired Behavior

We would like to change this to:

```
> ockam node create

Node Created!

Node:
  Name: 2f92103a
  Status: Running
  API Address: 127.0.0.1:60942
  Default Identity: P5ea32d08fc46d8176abf6e0e80ba9b8b9604c24b3093f84131624f19e7e57b71
  Pid: 62535
  Worker count: 19
  Transport count: 1
  Log Path: /Users/mrinal/Library/Application Support/io.ockam.ockam-cli/node-2f92103a/2f92103a.log

```

Code for this is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/show.rs#L33-L74

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by SkoogJacob** [comment]
Tried submitting a pull request for the issue here
https://github.com/build-trust/ockam/pull/3113

**Comment by mrinalwadhwa** [comment]
Merged, thank you @SkoogJacob 🙏
