### ISSUE TITLE
Start a secure channel listener at address `api` when a command node is created

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3101]
# Current Behaviour 

```
> ockam node create blue

Node Created!

Node:
  Name: blue
  Status: Running
  API Address: 127.0.0.1:58515
  Pid: 61985
  Worker count: 19
  Transport count: 1
  Log Path: /Users/mrinal/Library/Application Support/io.ockam.ockam-cli/node-blue/blue.log

```

```
> ockam secure-channel-listener create --node blue 'api'
Secure Channel Listener created at 0#api!
```

# Desired Behaviour 

```
> ockam node create blue

Node Created!

Node:
  Name: blue
  Status: Running
  API Address: 127.0.0.1:58515
  Secure Channel Listener Address: /ockam/api
  Pid: 61985
  Worker count: 19
  Transport count: 1
  Log Path: /Users/mrinal/Library/Application Support/io.ockam.ockam-cli/node-blue/blue.log
```

**Comment by lameferret** [comment]
So here the requirement is to merge `secure-channel-listener create` into `node create`, but what about `secure-channel-listener` in itself, should be removed or left as it is?

**Comment by mrinalwadhwa** [comment]
@anuvratsingh thank you for looking into it.

> secure-channel-listener in itself, should be removed or left as it is?

That command stays as is.

The listener should be started here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L171-L181

**Comment by lameferret** [comment]
I have added [create_secure_channel_listener_impl](https://github.com/build-trust/ockam/blob/d7e4041eb5a101254ee032c3c60b73b5ecd7882b/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L88) in [initialize_defaults](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L171-L181).

Now, how can I test if `secure channel listener` is being created? As it doesn't have `show/list` and can be created a number of times with different ID's. 

And as for output, there isn't an address being provided, so adding `Secure Channel Listener Address: /ockam/api` in [query_status](https://github.com/build-trust/ockam/blob/d7e4041eb5a101254ee032c3c60b73b5ecd7882b/implementations/rust/ockam/ockam_command/src/node/show.rs#L80) would be just fine as default `ockam/api`? Probably be used only if `secure-channel-listener` doesn't mutate it, If it does, where can I get it (from `ockam::Context`?)

OT: Is there an ockam internal design/architecture doc, unlike user focused `docs.rs/ockam` and `get-started-guides`?

**Comment by mrinalwadhwa** [comment]
Awesome, here's a test.
Note the comment in this code snippet

```bash
» ockam node create n1 --api-address 127.0.0.1:6001

» ockam node create n2 --api-address 127.0.0.1:6002

# This line is needed before your change and can be skipped after your change
» ockam secure-channel-listener create --node n2 "api"

» ockam secure-channel create --node n1 /ip4/127.0.0.1/tcp/6002/ockam/api
/ockam/3687bc44aee8486c7c9692bab875d492

» ockam message send /ip4/127.0.0.1/tcp/6001/ockam/3687bc44aee8486c7c9692bab875d492/ockam/uppercase "hello"
HELLO
```

> And as for output, there isn't an address being provided, so adding Secure Channel Listener Address: /ockam/api in [query_status](https://github.com/build-trust/ockam/blob/d7e4041eb5a101254ee032c3c60b73b5ecd7882b/implementations/rust/ockam/ockam_command/src/node/show.rs#L80) would be just fine as default ockam/api

Yes


> Probably be used only if secure-channel-listener doesn't mutate it, If it does, where can I get it (from ockam::Context?

Currently it can't mutate it. It is possible delete the listener but I think we have some work to do to make it easy to get that information. i.e channel worker need some kind of management api.

> OT: Is there an ockam internal design/architecture doc, unlike user focused docs.rs/ockam and get-started-guides?

This is a bit all over the place, sorry about that. We're planning a docs refresh soon. The content in this guide should offer some insight https://github.com/build-trust/ockam/tree/develop/documentation/guides/rust#build-end-to-end-encrypted-and-secure-messaging-channels

**Comment by lameferret** [comment]
@mrinalwadhwa 
> ockam secure-channel create --node n1 /ip4/127.0.0.1/tcp/6002/ockam/api `branch develop`
Returns: error: Invalid value "/ip4/127.0.0.1/tcp/6002/ockam/api!" for '<ADDR>': unregistered protocol prefix "ockam"
anything after 6002 returns with same error

> ockam secure-channel create --node n1 /ip4/127.0.0.1/tcp/6002
Returns: encountered an error in command handler code

Feels like "Works on my machine".

IMO, docs for structs like `MultiAddr` should contain some examples.

**Comment by mrinalwadhwa** [comment]
@anuvratsingh things are changing quickly in this area :)
`/ockam/` was changed to `/service/` earlier today https://github.com/build-trust/ockam/pull/3121

Please try:

```
ockam secure-channel create --node n1 /ip4/127.0.0.1/tcp/6002/service/api
```

---

> IMO, docs for structs like MultiAddr should contain some examples

💯 agree.

**Comment by mrinalwadhwa** [comment]
If you can create a draft PR, I can help test as well

**Comment by lameferret** [comment]
> things are changing quickly in this area :)

Is there a more synchronous channel to keep up with it, unlike discussions?

**Comment by mrinalwadhwa** [comment]
no, just github for the time being.
