### ISSUE TITLE
Removing `.local/share/ockam-cli` directly, results in `encountered an error in command handler code` for most CLI commands.

### ISSUE THREAD

**Issue by lameferret** [build-trust/ockam#3131]
This is more of a misuse by me and this issue is for documenting it as I wasn't able to find it.

TLDR: Use `ockam node delete --all` rather than deleting files.

Ockam creates two folders; `/.local/share/ockam-cli` for storing node data and `/.config/ockam-cli` for `config.json` storing details about all nodes.

Trying to debug, I had a lot of nodes and was out of colour name. Rather than reading documentation, I deleted `.local/share/ockam-cli`, which lead to almost all commands outputting general Err `encountered an error in command handler code`.

So use `delete --all`.

**Comment by mrinalwadhwa** [comment]
@anuvratsingh thank you for reporting this.
We should show a better error here. I also added https://github.com/build-trust/ockam/issues/3132 which will help cleanup.

**Comment by mrinalwadhwa** [comment]
Closing this since the way this now works has evolved quite a bit. Thank you @anuvratsingh.
