### ISSUE TITLE
Make identity show output to STDOUT instead of STDERR 

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#3171]
`identity show` currently is writing to stderr instead of stdout,  making scripting/pipelining. This makes pipelining/scripting a bit harder than it should be.

The code for this is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/show.rs#L34

Sidenote: Should also review the rest of the commands and check we are not doing the same on others.

**Comment by lameferret** [comment]
[`Line 51`](https://github.com/build-trust/ockam/blob/ff33156d541624d38a7c9edea221024bfae2bb69/implementations/rust/ockam/ockam_command/src/identity/show.rs#L51) and [`Line 71`](https://github.com/build-trust/ockam/blob/ff33156d541624d38a7c9edea221024bfae2bb69/implementations/rust/ockam/ockam_command/src/identity/show.rs#L71) should be `println!` to output it to STDOUT?.

What about [`vault::create#52`](https://github.com/build-trust/ockam/blob/ff33156d541624d38a7c9edea221024bfae2bb69/implementations/rust/ockam/ockam_command/src/vault/create.rs#L52), here output is confirmation should it also print to STDOUT?
