### ISSUE TITLE
Make services information displayed with `ockam node create | show` command more dynamic.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3177]
After https://github.com/build-trust/ockam/pull/3176

`ockam node create` displays:

```
> ockam node create

Node Created!

Node:
  Name: 6d3b9f7d
  Status: Running
  Services:
    Service:
      Type: TCP Listener
      Address: /ip4/127.0.0.1/tcp/60465
    Service:
      Type: Secure Channel Listener
      Address: /service/api
      Route: /ip4/127.0.0.1/tcp/60465/service/api
      Identity: P4842f385c9934b15e1cf0a4b09be9d1dddc407cb400a2c86bc6bd0fba09aaf6f
      Authorized Identities:
        - P4842f385c9934b15e1cf0a4b09be9d1dddc407cb400a2c86bc6bd0fba09aaf6f
    Service:
      Type: Uppercase
      Address: /service/uppercase
    Service:
      Type: Echo
      Address: /service/echo
```

This is also displayed on `node show` and `node list`

A part of this info is currently hardcoded so various demos become more easy to understand for new users:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/show.rs#L66-L88

and roughly maps to services started here
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L186-L215

This information would be incomplete after someone run commands like `ockam secure-channel-listener create` or `ockam tcp-listener create`.

We should make this a dynamically generated list of services.

This is also related to the `ockam service` subcommand that @SanjoDeundiak started developing here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/service

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by lameferret** [comment]
What does dynamic means here? 
I imagine something like:
```rust
struct NodeOutput(String);

impl NodeOutput {
    fn new() -> NodeOutput {
        NodeOutput(String::new())
    }

    fn name(mut self, name: &str) -> Self {
        let name = format!("Node name: {}\n", name);
        self.0.push_str(&name);
        self
    }

    fn build(self) -> String {
        self.0
    }
}

fn main() {
    let nodeoutput = NodeOutput::new()
        .name("service one")
        .name("service two")
        .build();
    println!("{:?}", nodeoutput);
}
```
*memory allocations can be improved

**Comment by mrinalwadhwa** [comment]
Thank you for looking into this.

> What does dynamic means here?

I meant to say that, this list displayed here is populated from what is in the registry. So as we add new services they are all displayed. Instead of this hardcoded output.

https://github.com/build-trust/ockam/blob/f12c604bb2d31482104be97cdf02324fe2822509/implementations/rust/ockam/ockam_command/src/node/show.rs#L39-L61

Your output sketch looks good.

**Comment by lameferret** [comment]
Alright then, I would create a PR based on the sketch in `ockam_commad/util`.

**Comment by lameferret** [comment]
Hey @mrinalwadhwa, what is the scope of this issue? Should it be limited to `node create | list` or be a companion to #3241 's output, part and replace `println!` usage for output?

**Comment by mrinalwadhwa** [comment]
@anuvratsingh I suggest we keep this issue decoupled from the bigger refactor in https://github.com/build-trust/ockam/issues/3241. This one can just be about the output.

What you have in https://github.com/build-trust/ockam/pull/3223 seems close enough to land. I think another interesting piece of this is getting the list of services from the node api.
