### ISSUE TITLE
Update README files of each crate to show usage with `cargo add`

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3181]
All crates in this folder have readme files https://github.com/build-trust/ockam/tree/2ea26c64036e61669181f17c92b0906a6a434a79/implementations/rust/ockam

We currently update our Readme files using [cargo-readme](https://github.com/livioribeiro/cargo-readme) readme generator. To generate/update readme files across all crates, 
- [We have a template](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/README.tpl) which we use to generate readme
- We then call a [Gradle task that updates all readme files](https://github.com/build-trust/ockam/blob/cea0380ecb91b74c5e8c4aae5050ea57b530e20e/implementations/rust/build.gradle#L172-L184) 

We want to update our templates to also add `cargo add` feature, preferably updating https://github.com/build-trust/ockam/blob/cea0380ecb91b74c5e8c4aae5050ea57b530e20e/implementations/rust/ockam/README.tpl#L15 to `Add this to your Cargo.toml or call cargo add crate@version:`

Link to [cargo add](https://doc.rust-lang.org/nightly/cargo/commands/cargo-add.html) command.

**Comment by lameferret** [comment]
Hey, I was looking into other major rust projects like tokio, most of them use current format:
```toml
[dependencies] 
"crate-name" = "major version" 
"crate-name" = "*"
```

This format also allows better representation of features used (if any), and rust book also uses it.

**Comment by mrinalwadhwa** [comment]
@anuvratsingh Interesting point about features.
@metaclips Maybe we should stay with the old format for now. Just add the places where the instructions are missing.

At the top level when introducing new people, in examples/guides etc, we can start with `cargo add`.

**Comment by lameferret** [comment]
For examples: `cargo run --example <example-name>` doesn't help, it just shows how to run the example.
Better approach would be: [Tokio example](https://github.com/tokio-rs/tokio#example).

**Comment by metaclips** [comment]
> Hey, I was looking into other major rust projects like tokio, most of them use current format:
> 
> ```toml
> [dependencies] 
> "crate-name" = "major version" 
> "crate-name" = "*"
> ```
> 
> This format also allows better representation of features used (if any), and rust book also uses it.

Thanks @anuvratsingh . `Cargo add` also has the [feature options](https://doc.rust-lang.org/nightly/cargo/commands/cargo-add.html#dependency-options). I'm in support to stay with the old format till `cargo add` is widely known. As @mrinalwadhwa stated, we should ensure all crates readme include in them, `usage instructions`.

**Comment by mariannegoldin** [comment]
Hi there, I am working with some new contributors to open source (and ockam) and wondering if you would be open to us working on this issue?

**Comment by mrinalwadhwa** [comment]
@mariannegoldin that would be great 👍

**Comment by metaclips** [comment]
~I don't think this is needed as we now use `cargo-readme` to generate readme files cc @etorreborre @mrinalwadhwa~

**Comment by metaclips** [comment]
I updated the issue to use cargo-readme instead to update readme files

**Comment by metaclips** [comment]
Closing now. Thanks everyone
