### ISSUE TITLE
Implement the `ockam secure-channel list` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3188]
# Currently:

```
> ockam node create n1 --tcp-listener-address 127.0.0.1:6001
> ockam node create n2 --tcp-listener-address 127.0.0.1:6002
```

Since `n2` gets a secure channel listener at `/ip4/127.0.0.1/tcp/6002/service/api`
We can create secure channels from n1 to this listener

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
/service/9a87006896ec1920da7fdbb233449d24
```

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
/service/0310c30702062f70bfb6dcf671791b8b
```

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
/service/8655c4bd3d20a8760d854220437d6673
```

These secure channels are stored in a service registry when they are created:
https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L42-L44

The command to create the secure channels is defined here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/secure_channel

# Desired:

We want to add a `ockam secure-channel list --at n1` command that would show the list of secure channels currently in the service registry.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by lameferret** [comment]
Can I give this a shot?

**Comment by mrinalwadhwa** [comment]
Of course, all yours 🙏

**Comment by lameferret** [comment]
Hey @mrinalwadhwa, I have some questions:
1. Would `list` return one node's secure listeners or all the secure listeners like `node list`.
2. What should be `SecureChannelList` model?
      - Right now I have it like this(heavily inspired from [TransportList](https://github.com/build-trust/ockam/blob/85d766acf47d5f199a721d1ef6fe2bcdb361def3/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L151) and [TransportStatus](https://github.com/build-trust/ockam/blob/85d766acf47d5f199a721d1ef6fe2bcdb361def3/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L113) :
          ```rust
          #[derive(Debug, Clone, Decode, Encode)]
          #[rustfmt::skip]
          #[cbor(map)]
          pub struct SecureChannelsResponse<'a> {
              #[cfg(feature = "tag")]
              #[n(0)] tag: TypeTag<7524823>,
              #[n(1)] pub addr: Cow<'a, str> 
          }

          impl<'a> SecureChannelsResponse<'a> {
              pub fn new<S: Into<Cow<'a, str>>>(addr: S) -> Self {
                  Self {
                      #[cfg(feature = "tag")]
                      tag: TypeTag,
                      addr: addr.into(),
                  }
              }
          }

          #[derive(Debug, Clone, Decode, Encode)]
          #[rustfmt::skip]
          #[cbor(map)]
          pub struct SecureChannelList<'a> {
              #[cfg(feature = "tag")]
              #[n(0)] tag: TypeTag<1551367>,
              #[n(1)] pub list: Vec<SecureChannelsResponse<'a>>,
          }

          impl<'a> SecureChannelList<'a> {
              pub fn new(list: Vec<SecureChannelsResponse<'a>>) -> Self {
                  Self {
                      #[cfg(feature = "tag")]
                      tag: TypeTag,
                      list,
                  }
              }
          }
          ```

**Comment by mrinalwadhwa** [comment]
@anuvratsingh great question. One node's secure channels. So it should be:

```
> ockam secure-channel list --at n1
```

_Sidenote: Secure Channels and [Secure Channel Listeners](https://github.com/build-trust/ockam/issues/3192) are different things - Secure Channels are like clients, Secure Channel Listeners are like servers._
