### ISSUE TITLE
TypedCBOR: `encode` wrapping exception does not return `{:ok ...}` tuple

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3189]
There are two functions defined in `Ockam.TypedCBOR` for encoding: `encode` and `encode!`.

Former is calling `wrap_exception(&encode!...` which will return `{:error, reason}` if there is an exception in `encode!` instead of throwing the exception.

But if there is no exception, the return value is `binary()` and not `{:ok, binary()}` and the function return value is used directly in the code.

This means that if we encounter exception, there will be `{:error, reason}` tuples in the data instead of encoded values because it's not checked anywhere.

As a solution we can switch all current usage of `encode` to `encode!` and fix the function to return `{:ok, binary()}` on success instead of `binary()` so we can use `encode` in the future code.

**Comment by SarvarVanoo** [comment]
Hey @hairyhum, this issue looks interesting and I have some experience in Elixir, can i pick this issue and start working it ?

**Comment by mrinalwadhwa** [comment]
@SarvarVanoo of course, all yours.

**Comment by SarvarVanoo** [comment]
Thankyou @mrinalwadhwa for letting me contribute.
