### ISSUE TITLE
Implement the `ockam secure-channel delete` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3190]
# Currently:

```
> ockam node create n1 --tcp-listener-address 127.0.0.1:6001
> ockam node create n2 --tcp-listener-address 127.0.0.1:6002
```

Since `n2` gets a secure channel listener at `/ip4/127.0.0.1/tcp/6002/service/api`
We can create secure channels from n1 to this listener

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
/service/9a87006896ec1920da7fdbb233449d24
```

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
/service/0310c30702062f70bfb6dcf671791b8b
```

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
/service/8655c4bd3d20a8760d854220437d6673
```

These secure channels are stored in a service registry when they are created:
https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L42-L44

The command to create the secure channels is defined here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/secure_channel

# Desired:

We want to add a `ockam secure-channel delete` command that would delete a secure channel currently in the service registry.

Related #3188 #3159 

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mrinalwadhwa** [comment]
@Retamogordo offered to work on this.

**Comment by Retamogordo** [comment]
Hello !
What would be the signature of the command ?
Is it like
```
ockam secure-channel delete /service/8655c4bd3d20a8760d854220437d6673
```
or
```
ockam secure-channel delete --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api
```
or something else ?

**Comment by mrinalwadhwa** [comment]
It would be:

```
ockam secure-channel delete /service/8655c4bd3d20a8760d854220437d6673
```

Also please note @adrianbenavides's simplification in this PR as an example to simplify some of the interaction with services from commands https://github.com/build-trust/ockam/pull/3267

**Comment by Retamogordo** [comment]
Hi @mrinalwadhwa !
Could you enlight me about how do you guys debug spawned nodes ? Are there log files anywhere ?

**Comment by mrinalwadhwa** [comment]
@Retamogordo sure.

There are two ways.

1. Run a node in the foreground with verbose traces:
```
ockam node create n1 --foreground -vvv
```

2. Nodes that are spawned and run in the background write logs to 
```
~/Library/Application\ Support/io.ockam.ockam-cli/node-n1/n1.log
```
On macos

On linux this would be in $XDG_CONFIG_HOME or ~/.config

**Comment by Retamogordo** [comment]
Awesome, thank you !

**Comment by Retamogordo** [comment]
@mrinalwadhwa, a couple of questions:
1) I came to this command syntax eventually:
``` 
./ockam secure-channel delete a8187fd55c8a4281ee33e365acc04592 --from n2 
```
is this ok with you ?
2) if the channel is not in registry, I return "not found 404", which I doubt is the most suitable choice here
3) I only delete the channel from the registry of "from" node, should be the "to" node be somehow notified about ?

**Comment by mrinalwadhwa** [comment]
@Retamogordo great!

1. `--at {node}` would be better.
2. lets start with something like "channel with address `a8187fd55c8a4281ee33e365acc04592` not found"
3. also do a `ctx.stop_worker(channel_address)` although that is less that ideal as mentioned in https://github.com/build-trust/ockam/issues/3159#issuecomment-1220100953

**Comment by Retamogordo** [comment]
Hi @mrinalwadhwa,
I took a chance to modify also channel creation code as required by #3267,
if you think it's ok, I could proceed with further testing and hopefully pull requesting.

**Comment by mrinalwadhwa** [comment]
@Retamogordo that sounds great, looking forward to the PR

**Comment by mrinalwadhwa** [comment]
Fixed in https://github.com/build-trust/ockam/pull/3287
Thank you @Retamogordo 🎊
