### ISSUE TITLE
Implement the `ockam secure-channel show` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3191]
# Currently:

```
> ockam node create n1 --tcp-listener-address 127.0.0.1:6001
> ockam node create n2 --tcp-listener-address 127.0.0.1:6002

Node:
  Name: n2
  ...
    Service:
      Type: Secure Channel Listener
      Address: /service/api
      Route: /ip4/127.0.0.1/tcp/6002/service/api
      Identity: P7dc502c795201c2d816749ea45ff51a416dce16ef0fe1b65ab4a642899e3b4d8
      Authorized Identities:
        - P7dc502c795201c2d816749ea45ff51a416dce16ef0fe1b65ab4a642899e3b4d8
  ...
```

Since `n2` gets a secure channel listener at `/ip4/127.0.0.1/tcp/6002/service/api`
We can create secure channels from n1 to this listener

```
> ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api \
     --authorized-identifier P7dc502c795201c2d816749ea45ff51a416dce16ef0fe1b65ab4a642899e3b4d8
/service/9a87006896ec1920da7fdbb233449d24
```

The created secure channel has the following properties:

1. an address /service/9a87006896ec1920da7fdbb233449d24
2. a route to the secure channel listener that it connects to /ip4/127.0.0.1/tcp/6002/service/api
3. the identifier it uses for itself
4. a list of identifiers that are authorized to be presented by the secure channel listener.  

Some of this secure channel info is stored in a service registry when they are created. Some of it is not.
https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L42-L46

The command to create the secure channels is defined here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/secure_channel

# Desired:

We want to add a `ockam secure-channel show` command that would show info of a secure channel given its address with all of the above details.

Related #3188

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Retamogordo** [comment]
Hi @mrinalwadhwa,
is this still active ?

**Comment by mrinalwadhwa** [comment]
@Retamogordo yes and all yours if you would like to spend time on it.

**Comment by Retamogordo** [comment]
Nice, thank you,
I would like to know what is meant by
3. the identifier it uses for itself
As for
4. a list of identifiers that are authorized to be presented by the secure channel listener.
This data is now consumed by the DecryptorWorker, I would probably need to slightly modify some signatures which are not directly related to the this task. I think this would not lead to a major impact on the existing code though.

**Comment by Retamogordo** [comment]
Hi @mrinalwadhwa,
one more thing, I face troubles on creating a channel:
```
./ockam secure-channel create --from n1 --to /ip4/127.0.0.1/tcp/6002/service/api --authorized P7dc502c795201c2d
```
it hangs with the output on the n1 node side:
```
2022-08-31T22:56:30.956798Z  INFO ockam_channel::secure_channel_decryptor: Started SecureChannel initiator at local: 0#9ccefeff2fef480a55bbfbd68c326cb7, remote: 0#04f99a53e9c9f3dd479161700b834cfe
2022-08-31T22:56:30.981767Z  INFO ockam_identity::channel::decryptor: Initiator verified SecureChannel from: P43df00258c39ba93d266ab03414285abf25da28d3ad32e94aaf50632c77c54b2
2022-08-31T22:56:30.981991Z ERROR ockam_node::relay::worker_relay: Error encountered during '0#076e02c3b8156e6d11e2c0f053c22f33' message handling: SecureChannelTrustCheckFailed
```
I think I succeeded to create a channel once, since then I'm stuck on this thing. Maybe I need to clean up some file somewhere ?

**Comment by mrinalwadhwa** [comment]
> ...what is meant by
> 3. the identifier it uses for itself

This identity is of type [Identity](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/identity.rs#L25) which has an [identifier](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/identity.rs#L26)
https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L27

**Comment by mrinalwadhwa** [comment]
> 4. a list of identifiers that are authorized to be presented by the secure channel listener.
This data is now consumed by the DecryptorWorker, I would probably need to slightly modify some signatures which are not directly related to the this task. I think this would not lead to a major impact on the existing code though.

Could you share a bit more about your approach.
I was thinking we could remember this Vec that we have before the channel is created 
https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L18

We could maybe store it the registry here
https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L42-L44

**Comment by mrinalwadhwa** [comment]
This error that you saw above `SecureChannelTrustCheckFailed` has to do with authorized identities. Could you try this simpler example. Does it work?

```
$ ockam node delete --all --force

$ ockam node create n1
$ ockam node create n2
$ ockam secure-channel create --from /node/n1 --to /node/n2/service/api
```
 
In the above case we assume the same shared identity in all nodes and all nodes and their default secure channel listeners at /api trust this shared identity.

**Comment by Retamogordo** [comment]
> > 4. a list of identifiers that are authorized to be presented by the secure channel listener.
> >    This data is now consumed by the DecryptorWorker, I would probably need to slightly modify some signatures which are not directly related to the this task. I think this would not lead to a major impact on the existing code though.
> 
> Could you share a bit more about your approach. I was thinking we could remember this Vec that we have before the channel is created
> 
> https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L18
> 
> We could maybe store it the registry here
> 
> https://github.com/build-trust/ockam/blob/c397c97078dc4962d29d0180d32e579d3ca633c3/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L42-L44

Hi @mrinalwadhwa,
yes this Vec, wrapped by Arc, so we have a sync ref to it (the Arc introduces that signature change in ```TrustMultiIdentifiersPolicy``` that currently uses an unwrapped owned Vec:
```
pub struct SecureChannelInfo {
    // Target route of the channel
    route: Route,
    // Local address of the created channel
    addr: Address,
    authorized_identifiers: Option<Arc<Vec<IdentityIdentifier>>>,
}
```

**Comment by Retamogordo** [comment]
> This error that you saw above `SecureChannelTrustCheckFailed` has to do with authorized identities. Could you try this simpler example. Does it work?
> 
> ```
> $ ockam node delete --all --force
> 
> $ ockam node create n1
> $ ockam node create n2
> $ ockam secure-channel create --from /node/n1 --to /node/n2/service/api
> ```
> 
> In the above case we assume the same shared identity in all nodes and all nodes and their default secure channel listeners at /api trust this shared identity.

Yes, but it would be interesting to test how the authorized list printout works.
In this case the authorized list would always be empty, wouldn't it ?

**Comment by Retamogordo** [comment]
Hi @mrinalwadhwa,
not related to this issue, I face this phenomenon when running a ```list``` command:
```
Secure channels for node `n1`:
  0#8adc96fabbc63086052a14564486339b
  0#8adc96fabbc63086052a14564486339b
```
Do you want me to check if the key already exists in registry prior to channel creation ? I already have this file checked out.

**Comment by Retamogordo** [comment]
Hi @mrinalwadhwa,
not related to this issue, I face this phenomenon when running a ```list``` command:
```
Secure channels for node `n1`:
  0#8adc96fabbc63086052a14564486339b
  0#8adc96fabbc63086052a14564486339b
```
I think that this happens because when a channel is created they store it twice under different keys, but the list command outputs just everything. Maybe can be fixed by using a HashSet instead of Vec when producing the output of the list command ?

**Comment by mrinalwadhwa** [comment]
@Retamogordo thank you, would you mind filing a new issue for it?

**Comment by mrinalwadhwa** [comment]
> In this case the authorized list would always be empty, wouldn't it ?

It shouldn't be empty. But it's possible the current implementation doesn't handle this.
It should show the one shared identity's identifier as the only authorized identifier

**Comment by mrinalwadhwa** [comment]
> yes this Vec, wrapped by Arc, so we have a sync ref to it (the Arc introduces that signature change in TrustMultiIdentifiersPolicy that currently uses an unwrapped owned Vec

Ah, I think that should be okay cc: @SanjoDeundiak

**Comment by Retamogordo** [comment]
> @Retamogordo thank you, would you mind filing a new issue for it?

If you consider this an issue maybe I could see what can be done about it right away, or you prefer to process it in a new thread ?

**Comment by Retamogordo** [comment]
> > In this case the authorized list would always be empty, wouldn't it ?
> 
> It shouldn't be empty. But it's possible the current implementation doesn't handle this. It should show the one shared identity's identifier as the only authorized identifier

This is not quite clear to me as I am not acquainted with the business logic of channel creation. I have a draft of the command implemented:
```
./ockam secure-channel show 8adc96fabbc63086052a14564486339b --at n1
```
which outputs:
```
• Channel:  /service/8adc96fabbc63086052a14564486339b
 	•      Route:  1#127.0.0.1:6002 => 0#api
 	• Identifier:  P43df00258c39ba93d266ab03414285abf25da28d3ad32e94aaf50632c77c54b2
 	• Authorized:  none

```
for the sequence you provided to me. The are no authorized identifiers. From the code I can just guess that ```TrustEveryonePolicy``` execution branch is taken in this case of channel creation. ??

**Comment by mrinalwadhwa** [comment]
> I have a draft of the command

if you could push what you have so far in a draft pr, I'll try it our and share more thoughts/pointers there.

> I could see what can be done about it right away,

that would be great, no need for a separate issue then. can be part of the same PR but maybe a separate commit.

**Comment by Retamogordo** [comment]
Two different commits on the same git branch ? One after another ?

**Comment by mrinalwadhwa** [comment]
Yes exactly.

**Comment by SanjoDeundiak** [comment]
@Retamogordo 

> I think that this happens because when a channel is created they store it twice under different keys, but the list command outputs just everything. Maybe can be fixed by using a HashSet instead of Vec when producing the output of the list command ?

I also think it's strange, so it'll be fixed here https://github.com/build-trust/ockam/pull/3397

> yes this Vec, wrapped by Arc, so we have a sync ref to it (the Arc introduces that signature change in TrustMultiIdentifiersPolicy that currently uses an unwrapped owned Vec:

I don't think we need to be able to modify this list after Secure Channel or Listener is started, so no need to wrap in an Arc, just clone the thing

**Comment by mrinalwadhwa** [comment]
Implemented in https://github.com/build-trust/ockam/pull/3403
Thank you @Retamogordo 🥳
