### ISSUE TITLE
Make cli command use exit code to signal success/failures

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#3199]
In most/all of the commands, there are cases where the command fail,  we print the error,  but we return with a success code anyway., like here:
https://github.com/build-trust/ockam/blob/b80b36bcb407a2b23cdf54618e9ac8f4162fffe3/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L98-L103
(in that case,  the exit code will come from the last  `stop_node(ctx).await`  result)-

Instead, commands must be adapted so that they exit with a non-success code if they fail.   Even better if we could use more specific error codes for different scenarios.   Related docs: https://rust-cli.github.io/book/in-depth/exit-code.html

**Comment by lameferret** [comment]
Hey, which of the [suggestion](https://rust-cli.github.io/book/in-depth/exit-code.html) should be used, personally [exitcode](https://docs.rs/exitcode/latest/exitcode/) looks the easiest and cleanest, but would it be alright to add another dependency?

**Comment by mrinalwadhwa** [comment]
@anuvratsingh we would avoid an external dependency here.

Since https://docs.rs/exitcode/latest/exitcode/ is Apache licensed let's [copy parts of this file that we need](https://github.com/benwilber/exitcode/blob/master/src/lib.rs) into our repo and give the authors attribution in our [NOTICE](https://github.com/build-trust/ockam/blob/develop/NOTICE) file for their work.

**Comment by lameferret** [comment]
This look simple enough, can I try it? Also, would it be alright to just copy [`exitcode::lib.rs`](https://github.com/benwilber/exitcode/blob/master/src/lib.rs) or I have to use it as "inspiration" or something?

**Comment by mrinalwadhwa** [comment]
Great! please do!

You can simply copy it.
We'll give them proper attribution. This approach is allowed under the Apache license.
