### ISSUE TITLE
Improve `ockam secure-channel create` to support` --from /node/NAME` syntax

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3205]
# Currently 

```
> ockam node create n1
...
> ockam node create n2
...
> ockam secure-channel create --from n1 --to /node/n2/service/api
```

# Desired

We also want to support `--from /node/n1`

```
> ockam node create n1
...
> ockam node create n2
...
> ockam secure-channel create --from /node/n1 --to /node/n2/service/api
```

The code for the `ockam secure-channel create` is:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa 

I am assuming the input `node name` will always be in end of the protocol

Eg:
`/node/n1`
`/node/test_node`

If this is true,

## sample code

![image](https://user-images.githubusercontent.com/38526063/184646212-949172a2-c7ab-46e4-917a-57adcad914d6.png)

## output:

![image](https://user-images.githubusercontent.com/38526063/184645799-b388e1fe-9e9c-4f01-b282-20c057a0a49b.png)




do you have other ways on how to approach this?

**Comment by mrinalwadhwa** [comment]
@michealkeines thank you for looking into this!

Your approach above is a great place to start 👍 
Could you turn this into a helper function and place it [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/mod.rs)

Multiple other commands have options that take NODE values and we'll want to update all of them to support the /node/n1 syntax.

I'll create a list of all the commands that need this in a separate issue shortly.

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa,
- Created the helper function
- Updated secure-channel create command to use the helper function

Please review my PR https://github.com/build-trust/ockam/pull/3243

**Comment by mrinalwadhwa** [comment]
@michealkeines Thank you, while I look into merging https://github.com/build-trust/ockam/pull/3243. 

Issues https://github.com/build-trust/ockam/issues/3244, https://github.com/build-trust/ockam/issues/3203, https://github.com/build-trust/ockam/issues/3245, https://github.com/build-trust/ockam/issues/3246, https://github.com/build-trust/ockam/issues/3247 and https://github.com/build-trust/ockam/issues/3248 are all the same in case you want to send a follow on PR for those.

**Comment by michealkeines** [comment]
Sure, I will add them, separate PRs for all issues or should i add them all in one?

**Comment by mrinalwadhwa** [comment]
In the same PR should good 👍

**Comment by mrinalwadhwa** [comment]
Added in https://github.com/build-trust/ockam/pull/3243

**Comment by mrinalwadhwa** [comment]
@michealkeines I wanted to show your change in a demo so I ended up making all the changes I suggested up. If you're interested in picking something else, have a look at some of the new issues we [posted today](https://github.com/build-trust/ockam/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

Thank you for send the above PR!
