### ISSUE TITLE
Setup configuration storage for projects, spaces, etc

### ISSUE THREAD

**Issue by spacekookie** [build-trust/ockam#3208]
In #3197 we added a configuration module for looking up aliases and mapping them to more complex values ([ockam_api/src/config/lookup.rs](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/config/lookup.rs)). Additionally we have a [cleanup function](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/util.rs#L14-L38) which must be invoked on any `MultiAddr` that is accepted from the user that contains such lookup-values.

Currently this system is only used to lookup `"/node/<node-name>"` aliases to actual addresses, and only does so for certain commands (`ockam message send` and `ockam secure-channel create` have been tested).

Next up we would like to expand this behaviour to other commands and other lookup values.

## tcp-connection create — [code link](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs#L27)

Currently this command doesn't accept a `MultiAddr` address. An open question about this command is whether accepting a `MultiAddr` here makes sense. Potentially we will want to change this, and thus need to clean the MultiAddr to support alias lookups. Thoughts @mrinalwadhwa?

## forwarder create — [code link](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/forwarder/create.rs#L17)

This command creates a forwarder worker on the cloud node. It accepts `MultiAddr` via the `--at` parameter, which needs to be cleaned to support alias lookups (for example: `ockam forwarder create --for green --for /node/blue/service/uppercase my_path_to_uppercase`

## tcp-inlet create — [code link](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs#L16)

This command creates a TCP inlet portal, meaning that all traffic flowing into this endpoint need to be tunneled to a destination worker/ address.  This address is communicated via the `--to` parameter, which already accepts a `MultiAddr` and just needs to be cleaned.

## space create — [code link](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/space/create.rs#L17)

This command creates a new Space on the cloud node. It already accepts `MultiAddr` addresses for the cloud node, which could just be `/node/<node name>` (which is not specific to this command, but all commands that interact with a cloud node).

More importantly when creating a space, the name/ route to the space should be stored in the lookup table under `/space/<space name>`, mapping to some sensible value. This includes augmenting the [storage type]() for the lookup mechanism.

## project create — [code link](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/create.rs#L17)

This is very similar to the `space create` command, except that we want to keep track of projects (via the key `/project/<project name>`

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa can i work on this?

**Comment by mrinalwadhwa** [comment]
@michealkeines thank you for continuing to spend time on our project!!

the configuration layer is in a bit of flux at the moment so I think picking this up will cause code change conflicts. I'll be creating some new issues later today so hopefully you can instead take something from that list that is interesting

**Comment by adrianbenavides** [comment]
Outdated
