### ISSUE TITLE
Space and project create commands should generate names if none was provided

### ISSUE THREAD

**Issue by spacekookie** [build-trust/ockam#3209]
Currently the `name` argument is required for both `ockam space create` and `ockam project create`. This should be changed to be optional and generate a random UUID name if none was provided.

**Comment by leonzchang** [comment]
Hi @spacekookie , can you show the example using `ockam space create` ?
I try to  test `ockam space create` but the error occurs `No such node available.  Run 'ockam node list' to list available nodes`.
