### ISSUE TITLE
Add error information to 'node create' when using --tcp-listener-address option

### ISSUE THREAD

**Issue by BeenzSyed** [build-trust/ockam#3217]
# Current

When a user would like to create a node using the -t or --tcp-listener-address option and enter an option that returns an error, I see only that the node is DOWN.

Ex. Under status, I see that it's down but I don't know why or what to do from here.
```
s-mbp ockam % ockam node create -t 127.0.0.1:5000 purple

Node Created!

Node:
  Name: purple
  Status: DOWN
  Services:
    Service:
      Type: TCP Listener
      Address: /ip4/127.0.0.1/tcp/5000
    Service:
      Type: Secure Channel Listener
      Address: /service/api
      Route: /ip4/127.0.0.1/tcp/5000/service/api
      Identity: N/A
      Authorized Identities:
        - N/A
    Service:
      Type: Uppercase
      Address: /service/uppercase
    Service:
      Type: Echo
      Address: /service/echo
  Secure Channel Listener Address: /service/api
```

# Desired

When a user would like to create a node using the -t or --tcp-listener-address option and enter an option that returns an error, I can see why it's down so that I can recreate the node with another port or take the next step to make sure the node is in the up state.

I believe there can be multiple solutions - maybe the error can be added next to the status or as a separate attribute.

**Comment by michealkeines** [comment]
Hi, @mrinalwadhwa  I am not sure if this issue is open for contributors,

I was checking the code 

currently, we have a check to if the provided port is used by other nodes before creating the new Node and if there is no other node registered with the port, we proceed to create the new node, but in case if some other service was using the same port we wouldn't know it, the newly created node will fail to bind to that port resulting in status DOWN

```rust
port_is_used(input_port);

pub fn port_is_used(&self, port: u16) -> bool {
    let inner = self.inner.readlock_inner();
    inner.nodes.iter().any(|(_, n)| n.port == port)
}
```

Simple fix would be to add a bind check to see if the port is not used by any other services.

```rust
cfg.port_is_used(&address)

pub fn port_is_used(&self, address: &SocketAddr) -> bool {
    let port = address.port();
    let ip = address.ip();
    match std::net::TcpListener::bind((ip, port)) {
        Ok(_) => {
            let inner = self.inner.readlock_inner();

            inner.nodes.iter().any(|(_, n)| n.port == port)
        },
        Err(_) => true
    }
}
```

Fixed Output:

![image](https://user-images.githubusercontent.com/38526063/185792542-c251045c-ab7c-49ce-81c7-d3c9c14b85ff.png)

**Comment by mrinalwadhwa** [comment]
@michealkeines Thank you for looking into this. The change looks great! We would love a pull request!

I think we should also add the same check to `tcp-listener create`, `tcp-inlet create` and `tcp-outlet create` in addition to `node create` so best would be add that function to the util module and call in all these commands.

**Comment by michealkeines** [comment]
Hi, @mrinalwadhwa  I have a doubt

This bind check will only work for local private IPs, is it possible to pass remote IPs to `tcp-inlet create or tcp-outlet create` commands?

I am not exactly sure about the use cases of `tcp-inlet` and `tcp-outlet`

**Comment by mrinalwadhwa** [comment]
@michealkeines great question.

In `tcp-outlet` it could be any IP:PORT so we shouldn't do the check there (I was wrong to mention that in my above comment).

`node create`, `tcp-listener create`, `tcp-inlet create` are all binding to a local IP:PORT

**Comment by michealkeines** [comment]
Please review the PR(https://github.com/build-trust/ockam/pull/3298)

**Comment by phillyphil91** [comment]
can this issue be closed?
