### ISSUE TITLE
`ockam completion --shell {bash|zsh|fish}` command for shell completion

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3220]
# Current Behaviour

Users have to type the full `ockam` commands

# Desired Behaviour

Generate shell completion scripts for various shells

```
ockam completion --shell {bash|zsh|fish}
```

This would require adding the completion command here:
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src

Clap Complete seems to have everything we need for this.
https://github.com/clap-rs/clap/tree/master/clap_complete

After this command exists we can also look at adding it to our homebrew formula
https://github.com/build-trust/homebrew-ockam/blob/main/ockam.rb

Github's `gh completion` command seems good to model `ockam completion` behavior after
https://cli.github.com/manual/gh_completion

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by datdhruv** [comment]
Hi!, Can this be assigned to me?

**Comment by mrinalwadhwa** [comment]
@datdhruv of course, all yours. Looking forward to the pull request. Let us know if you have questions along the way.

**Comment by mrinalwadhwa** [comment]
@datdhruv checking in to see if you still have time to work on this issue or do you have any questions.

If you're busy that's completely okay. We can open this issue for someone else to pick up and then whenever you're available again I'd be happy suggest other issues you could contribute to.

**Comment by datdhruv** [comment]
Hey, should be ready with a commit today

**Comment by mrinalwadhwa** [comment]
Awesome, looking forward to the PR 🐰

**Comment by datdhruv** [comment]
One question,

clap_complete has a method generate which expects the shell, a reference to a Clap::App, the name of the bin file and output stream.
```rust
generate(Shell::Bash, &mut ockam_command, "ockam", &mut io::stdout())
```
From what i gather we dont use a clap::App in the classical sense

(classic sense => something like this)
```rust
pub fn make_subcommand<'help>() -> App<'help> {
    App::new("init")
        .about("Creates the boilerplate structure and files for a new book")
        // the {n} denotes a newline which will properly aligned in all help messages
        .arg(arg!([dir]
            "Directory to create the book in{n}\
            (Defaults to the Current Directory when omitted)"
        ))
        .arg(arg!(--theme "Copies the default theme into your source folder"))
        .arg(arg!(--force "Skips confirmation prompts"))
        .arg(
            Arg::new("title")
                .long("title")
                .takes_value(true)
                .help("Sets the book title")
                .required(false),
        )
        .arg(
            Arg::new("ignore")
                .long("ignore")
                .takes_value(true)
                .possible_values(&["none", "git"])
                .help("Creates a VCS ignore file (i.e. .gitignore)")
                .required(false),
        )
}
```
from https://github.com/rust-lang/mdBook/blob/4c303c3b1dde1cbdf2f593b05687340915b93417/src/cmd/init.rs#L12

How would I create a reference to the clap::app? (right now ockam_command is of type struct:OckamCommand

**Comment by mrinalwadhwa** [comment]
@datdhruv I found this on the Clap discussions group https://github.com/clap-rs/clap/discussions/3671#discussioncomment-2672374

> Deriving Parser also derives the trait CommandFactory which has the [CommandFactory::command function](https://docs.rs/clap/latest/clap/trait.CommandFactory.html#method.command).

**Comment by datdhruv** [comment]
#3326 and #3327 should take care of this, so we can close this
