### ISSUE TITLE
Create a `default` pointer in command configuration that stores the first created node.  

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3232]
We want to add the first created node as `default: {node: NODE_NAME}` to the config file and layer read that value when executing any command.

We also want to add new commands to modify that value (`ockam configuration set-default-node {NODE_NAME}` and `ockam configuration get-default-node`).

**Comment by michealkeines** [comment]
Hi, can i work on this issue? @mrinalwadhwa

**Comment by mrinalwadhwa** [comment]
@michealkeines of course, thank you for spending time on it.
I just updated the description above for more clarity and specifics.

Please let me know if you have any questions.

**Comment by mrinalwadhwa** [comment]
Closing since this now exists. Thank you @michealkeines
