### ISSUE TITLE
Node fails to restart after stopping

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3234]
The following works:

```bash
node create ...
node stop ...
node start ...
```

But if we stop and start the same node again, it fails and the node never starts.

**Comment by pro465** [comment]
hi @adrianbenavides! could you tell what error does it fail with?

**Comment by mrinalwadhwa** [comment]
@pro465 thank you for looking into this.
I think there are multiple things that are broken / not-yet-handled in this area.

Here's one example I can reproduce. But I suspect there are more cases.

```
» ockam node create n1

Node Created!

Node:
  Name: n1
  Status: UP
  Services:
    Service:
      Type: TCP Listener
      Address: /ip4/127.0.0.1/tcp/63746
    Service:
      Type: Secure Channel Listener
      Address: /service/api
      Route: /ip4/127.0.0.1/tcp/63746/service/api
      Identity: Pd4a7aba84b6b9d8d4457c1ea52c1468aa9b0ef939ed43eaec381dcaf1509a048
      Authorized Identities:
        - Pd4a7aba84b6b9d8d4457c1ea52c1468aa9b0ef939ed43eaec381dcaf1509a048
    Service:
      Type: Uppercase
      Address: /service/uppercase
    Service:
      Type: Echo
      Address: /service/echo
  Secure Channel Listener Address: /service/api
```

```
» ockam message send hello --to /node/n1/service/uppercase
HELLO
```

```
» ockam node stop n1
```

```
» ockam node start n1
Attempting to restart node 'n1'
Running: start node ...ok!
```

This hangs:

```
» ockam message send hello --to /node/n1/service/uppercase
^C
```

```
» ockam node show n1

Node:
  Name: n1
  Status: UP
  Services:
    Service:
      Type: TCP Listener
      Address: /ip4/127.0.0.1/tcp/63746
    Service:
      Type: Secure Channel Listener
      Address: /service/api
      Route: /ip4/127.0.0.1/tcp/63746/service/api
      Identity: Pd4a7aba84b6b9d8d4457c1ea52c1468aa9b0ef939ed43eaec381dcaf1509a048
      Authorized Identities:
        - Pd4a7aba84b6b9d8d4457c1ea52c1468aa9b0ef939ed43eaec381dcaf1509a048
    Service:
      Type: Uppercase
      Address: /service/uppercase
    Service:
      Type: Echo
      Address: /service/echo
  Secure Channel Listener Address: /service/api
```

**Comment by pro465** [comment]
@mrinalwadhwa trying to reproduce this in GA led to:
https://github.com/pro465/ockam/runs/7873283378?check_suite_focus=true#step:8:403
so `startup::stop` somehow is failing in GA, while in your machine it is not?

**Comment by mrinalwadhwa** [comment]
@pro465 interesting, I just tried again and it didn't happen on my machine.

**Comment by pro465** [comment]
so, it seems `kill` call is succeeding:

https://github.com/pro465/ockam/runs/7873805002?check_suite_focus=true#step:8:403

that means there is a bug in the check in `StartCommand::run`

**Comment by pro465** [comment]
@mrinalwadhwa perhaps you have an older version of ockam or nix?

**Comment by pro465** [comment]
`ockam node show n1` correctly shows that the node is down, however somehow `kill` still succeeds:
https://github.com/pro465/ockam/runs/7877043154?check_suite_focus=true#step:7:725

it's puzzling me, how is this even possible?

**Comment by Retamogordo** [comment]
Hi,
I inserted a few printouts into the code, I could see something that perhaps is kind of a relevant thing.
This code
```
startup::start(&command.node_name, &cfg, &start_cfg);
```
searches for a start up config json, which on my machine looks like so:
```
{
  "commands": []
} 
```
So on the surface, it looks like there is no command to run upon the node startup.
And the printout after a list (or send) command, for example:
```
sending: route: 1#localhost:6001 => 0#_internal.nodemanager
ERROR: Failed to process request
```
Just to try something dirty I explicitly connected the node in the startup code by:
```
connect_to(6001, (cfg.clone(), command.node_name), query_status);

```
which produced no apparent effect.

**Comment by neil2468** [comment]
The abandoned PR #3456 determined that..
* The node does not restart its 'default services' because `--skip-defaults` is used when re-starting a node, and that this is the desired behaviour.
* To re-start 'default services' the node should record in a config file when it starts services, and then when a node starts it should read that config to re-start its services. 
* The CLI (`ockam_command`) has the `startup.json` functionality, but this was not fully rolled out and its believed that it should be the node (`ockam_api`) that re-starts its services (not `ockam_command`)

Next steps...
- [ ] Remove `startup.json` functionality from `ockam_command`.
- [ ] Add `startup.json` infrastructure code to `ockam_api`.
- [ ] Node to restart the 'default services' when node starts up.
- [ ] Node to restart other 'things' (e.g. TCP inlets and outlets) when node starts up.

@mrinalwadhwa: Can I be assigned to this issue, please?

**Comment by mrinalwadhwa** [comment]
@neil2468 of course, all yours.

**Comment by neil2468** [comment]
@adrianbenavides commented (https://github.com/build-trust/ockam/pull/3533#issuecomment-1260682593)...

> ... just wanted to let you know that I'm currently working on a substitute for this startup.json functionality.
> 
> In a nutshell, we want to be able to define the commands that must be executed when a node is created and after it's restarted. You can find some details here: https://github.com/build-trust/ockam/pull/3519 (note that it's still a WIP feature, and could change quite a bit in the coming days/weeks). Let me know if you think this would be enough to tick your Node to restart other 'things' (e.g. TCP inlets and outlets) when node starts up. checkbox or if you had something else in mind.
> 

The #3519 feature could work to fix this issue. 👍 

However its adoption would mean.. 🤔 
* It would be `ockam_command` and not `ockam_api` that keeps track of what has been started within a node.
* Adding `ockam service start` commands for the node's "default" services (e.g. uppercase & echoer).
* Removing the node's starting of non-essential services when it starts. 
* Removing the '--skip-defaults' feature when starting a node.
* Modifying the `commands.bats` test script to explicltly start needed services. 
* Modifying help and user documents to explicitly start needed services.

@adrianbenavides , @SanjoDeundiak Thoughts? Is this how Ockam would like the CLI to develop?

**Comment by mrinalwadhwa** [comment]
@neil2468 Thank you for continuing to look into this.
I will try to write a longer thread on this soon, but in the meantime a quick point ... we don't want users to have to start all services. So there should be default list of services that are started when a node starts. Configuration should allow overriding this default list.

**Comment by adrianbenavides** [comment]
As I commented on https://github.com/build-trust/ockam/pull/3832#issuecomment-1324680687, the code related to this issue is being heavily refactored and probably this issue will be solved when we finish that task.

I'll keep this thread updated as we progress.

**Comment by davide-baldo** [comment]
@adrianbenavides I cannot reproduce the issue, i think we can close this

**Comment by adrianbenavides** [comment]
Sure, thanks for the heads up!
