### ISSUE TITLE
Ockam enroll should work without having to specify the node or Ockam Controller URL

### ISSUE THREAD

**Issue by BeenzSyed** [build-trust/ockam#3238]
Ockam enroll enrolls the identity of a node to the Ockam Orchestrator. It should work without having to specify the node as an argument or the Controller URL.

# Current behavior

```ockam enroll --auth0 $CONTROLLER -n blue```

$CONTROLLER will be hard coded into the Ockam Command binary and the identity of the node will be a global known identity so both of those values can be derived and do not need to be specified by the user.

# Desired behavior
```ockam enroll --auth0```

**Comment by adrianbenavides** [comment]
Shouldn't this be just `ockam enroll`. Currently, the default enrollment method is email, but AFAIR we wanted to switch the default to auth0.

**Comment by polvorin** [comment]
done
