### ISSUE TITLE
Unify error handling, node req/res handling, and output

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3241]
* [x] Develop a set of helpers to simplify commands logic ([PR](https://github.com/build-trust/ockam/pull/3168))
* [x] Apply to `configuration` commands
* [x] Apply to `enroll` commands
* [x] Apply to `forwarder` commands
* [x] Apply to `identity` commands
* [x] Apply to `message` commands
* [ ] Apply to `node` commands
* [x] Apply to `project` CRUD commands
* [x] Apply to `project` enroller/member/credential commands
* [x] Apply to `secure_channel` commands
* [x] Apply to `secure_channel_listener` commands
* [x] Apply to `service` commands
* [x] Apply to `space` commands ([PR](https://github.com/build-trust/ockam/pull/3168))
* [ ] Apply to `tcp` commands
* [x] Apply to `vault` commands
* [x] Create async runtime at the top level and remove the `node_rpc` + `rpc` functions from all commands and just call the `run_impl` method

**Comment by RajivTS** [comment]
@mrinalwadhwa I would like to apply the new request handling pattern to `identity` commands if that's ok?

**Comment by mrinalwadhwa** [comment]
@RajivTS that would be great! Let us know if you have any questions.

**Comment by adrianbenavides** [comment]
@RajivTS I've created separated issues with reduced scope for the `identity` commands, in case you want to check them out:
- https://github.com/build-trust/ockam/issues/3562
- https://github.com/build-trust/ockam/issues/3561

I'm closing this issue for now.
