### ISSUE TITLE
Add examples section to `ockam message send` command's help

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3257]
# Current Behaviour

```
ockam message send --help
```

does not display any examples

# Desired Behaviour

As part of the help show the following examples section:

```bash
EXAMPLES

    # Create two nodes
    > ockam node create n1
    > ockam node create n2

    # Send a message to the uppercase service on node n1
    > ockam message send hello --to /node/n1/service/uppercase
    HELLO

    # Send a message to the uppercase service on node n1 from node n1
    > ockam message send hello --from /node/n2 --to /node/n1/service/uppercase
    HELLO

    # Create a secure channel from node n1 to the api service on node n1
    # Send a message through this encrypted channel to the uppercase service
    > ockam secure-channel create --from /node/n1 --to /node/n2/service/api \
        | ockam message send hello --from /node/n1 --to -/service/uppercase
    HELLO

LEARN MORE
```

# References

Here's an example of command that currently shows examples

```
ockam node create --help
```

Here's the code for the `ockam node create` command
https://github.com/build-trust/ockam/blob/498198251ecac0336041c06cc7f1a2e5785ad06d/implementations/rust/ockam/ockam_command/src/node/create.rs#L33-L54

Here's the code for the `ockam message send` command
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/message/send.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by chrischiedo** [comment]
Hi @mrinalwadhwa,

I've just submitted a [draft PR](https://github.com/build-trust/ockam/pull/3291) addressing this issue.

A few things to note:

- This is my very first contribution to the project. Any feedback, especially on the general quality of the PR would be much appreciated.
- If this PR satisfies your quality bar, then I can go ahead and work on the other two issues that are closely related to the current one (#3265 and #3266 )

Thank you!

**Comment by mrinalwadhwa** [comment]
@chrischiedo welcome to the project and congratulations on your very first contribution!! Left a suggestion on your [draft](https://github.com/build-trust/ockam/pull/3291) after that we can merge!
