### ISSUE TITLE
Refactor `ockam message send` command to use the new simpler utility functions.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3279]
In https://github.com/build-trust/ockam/pull/3168 @adrianbenavides introduced some simplifications to how various ockam commands interact with other ockam nodes.

We would like to change `ockam message send` to use this newer style.
The code for `ockam message send` is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/message/send.rs

Here's a PR that did a similar refactor of `ockam secure-channel-listener list`
https://github.com/build-trust/ockam/pull/3267/files

Related #https://github.com/build-trust/ockam/issues/3241

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa 

I checked the new Rpc abstraction,

```rust
let mut rpc = Rpc::new(...)?;
rpc.request(...).await?;
rpc.check_response()?;
println!("Success");
Ok(())
```

```rust

    pub async fn request<T>(&mut self, req: RequestBuilder<'_, T>) -> anyhow::Result<()>
    where
        T: Encode<()>,
    {
        let buf = req.to_vec()?;
        let mut rte = connect(self.ctx, &self.cfg).await?;
        self.buf = self
            .ctx
            .send_and_receive(rte.modify().append(NODEMANAGER_ADDR), buf)
            .await?;
        Ok(())
    }
```

The `rpc.request` method is using `send_and_receive()`, this defaults to `30 sec` timeout, for our `ockam message send` command we need the timeout feature right?

can i add extra methods to that Rpc or do you have any suggestions?

**Comment by adrianbenavides** [comment]
I'll be landing a PR soon with that functionality. It should be ready in the next couple of days!

**Comment by Retamogordo** [comment]
Hi, 
is this a right place to comment on Rpc struct api and implementation details?

**Comment by mrinalwadhwa** [comment]
@Retamogordo sure, go for it.
