### ISSUE TITLE
Error on enroll,   wait for default project creation

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#3303]
On enroll

`Project created. Waiting until it's operative.........thread 'tokio-runtime-worker' panicked at 'Project should have identity set', implementations/rust/ockam/ockam_command/src/enroll/auth0.rs:327:14
`
https://github.com/build-trust/ockam/blob/a5ac07e3c6185346eee1c85df64d2cf166cee871/implementations/rust/ockam/ockam_command/src/enroll/auth0.rs#L327

(it _is_ waiting for the project' route to be there,  but the `default_project` is not updated)

**Comment by adrianbenavides** [comment]
Fixed here: https://github.com/build-trust/ockam/pull/3300
