### ISSUE TITLE
Improve handling of command configuration files across versions

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3323]
If a config file from a previous version exists, using it with a new version often fails:

```
thread 'main' panicked at 'failed to parse config.  Try deleting /Users/mrinal/Library/Application Support/io.ockam.ockam-cli/config.json', /Users/mrinal/Workspace/build-trust/ockam/implementations/rust/ockam/ockam_api/src/config/mod.rs:68:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa 

Currently we try to parse the contents of the config file using `serde_json::from_str(&buf)` this will fail if all the fields in the struct is not present in the json file

Possible solutions:

- check if it has all the fields and set default values for fields that not present
- discard that config and set default values for all fields

 do you have any expected solution or suggestions?

**Comment by mrinalwadhwa** [comment]
@michealkeines thank you for looking into this.

I think this would be the better solution here:

> check if it has all the fields and set default values for fields that not present

**Comment by michealkeines** [comment]
@mrinalwadhwa 

serde provides a default value option

```rust

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OckamConfig {
    // reducted
    #[serde(default = "default_node")]
    pub default: Option<String>,
}

fn default_node() -> Option<String> {
    None
}
```

Here, while parsing json to struct, if the `default` field is not present it will take the default value

can we go with this solution?

only problem is that the config file will only be updated with default value when the user set the default node again, until then it will default to None

## output:

![default parsing](https://user-images.githubusercontent.com/38526063/186944165-43084e31-c0ef-4e73-b933-2864d6ca9189.gif)

**Comment by mrinalwadhwa** [comment]
Nice! that sounds like a good solution 👍

**Comment by michealkeines** [comment]
Please review my PR(https://github.com/build-trust/ockam/pull/3356)
