### ISSUE TITLE
Diagnose error in `ockam configuration get-default-node`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3325]
In https://github.com/build-trust/ockam/pull/3321 [michealkeines](https://github.com/michealkeines) added `get-default-node` and `set-default-node` but there maybe some issue there 

```
ockam node create n1
ockam node create n2

» ockam configuration get-default-node
Current Default Node: n1

» ockam configuration set-default-node n2

» ockam configuration get-default-node
Current Default Node: n1

```

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa, I have added the fix in this PR(https://github.com/build-trust/ockam/pull/3337), Please review it
