### ISSUE TITLE
Rename `ockam project add-member` command to `ockam project enroll`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3370]
Without changing any of the logic/arguments we want to change `ockam project add-member ...` to `ockam project enroll ...`

The source for the command is here:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/add_member.rs

**Comment by michealkeines** [comment]
Hi, @mrinalwadhwa 

Please review my PR(https://github.com/build-trust/ockam/pull/3386)

**Comment by mrinalwadhwa** [comment]
@michealkeines thank you 🥳
