### ISSUE TITLE
Make `ockam secure-channel delete` accept inputs of form `/service/3c54b81...`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3380]
Make `ockam secure-channel delete` accept inputs of form `/service/3c54b81...`

so it is consistent with other commands

```bash
$ ockam node create n1
$ ockam node create n1

$ ockam secure-channel create --from /node/n1 --to /node/n2/service/api

  Created Secure Channel:
  • From: /node/n1
  •   To: /node/n2/service/api (/ip4/127.0.0.1/tcp/51120/service/api)
  •   At: /service/aead55d3cd882fc02d35ad264db91e81

$ ockam secure-channel delete 09738b73c54b81d48531f659aaa22533 --at n1
```

The code for the command is here
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/delete.rs

**Comment by michealkeines** [comment]
Hi, @mrinalwadhwa 

do you mean like `ockam node delete /service/3c54b81` should delete the service running in any node or a particular node?

and what is the use case in passing a service address to `node delete`?

**Comment by mrinalwadhwa** [comment]
@michealkeines sorry I miss typed the issue .. I meant `ockam secure-channel delete` instead of ~`ockam node delete ..`~ sorry about that confusion

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa, Please review my PR(https://github.com/build-trust/ockam/pull/3407)

**Comment by mrinalwadhwa** [comment]
Merged in https://github.com/build-trust/ockam/pull/3407.
Thank you @michealkeines 🙏
