### ISSUE TITLE
Investigate why shell completion scripts in homebrew formula show a permissions error on macos

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3382]
We had to remove the completions scripts from the formula
https://github.com/build-trust/homebrew-ockam/pull/34/files

**Comment by memark** [comment]
What permissions error was generated by the completions? I find no closed issue on the topic, and no info in the linked PR. (What's the easiest way to reproduce?)

**Comment by mrinalwadhwa** [comment]
@memark thank you for looking into this!

The error at the time on @metaclips' machine looked like this. (I was seeing the same)

![image](https://user-images.githubusercontent.com/159583/196884441-a5bcc418-0336-4afc-8acf-60aa299b37c7.png)

which looking at the error doesn't seem like it was the completion scripts but removing them did make everything work.




the easiest way to reproduce may be to try:

```
brew tap build-trust/ockam
brew edit build-trust/ockam/ockam
```

and change the formula ruby file to have the completion parts we removed here
https://github.com/build-trust/homebrew-ockam/pull/34/files

then try

```
brew install build-trust/ockam/ockam
```

Does the work / break for you?

**Comment by memark** [comment]
Thanks for the repro. Editing back the autocomplete sections to the formula gives me the same error. Now I have something to work with.
