### ISSUE TITLE
Improve output of `ockam secure-channel list` command for formatting, color, and json

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3391]
# Current:

To see the current outputs run:

```
$ ockam node create n1
$ ockam node create n2

$ ockam secure-channel create --from /node/n1 --to /node/n2/service/api
...

$ ockam secure-channel list --node n1

$ ockam secure-channel list --node default
Secure channels for node `n1`:
  0#a0d17e26a17a5917bfd90036c8b5bead
  0#a0d17e26a17a5917bfd90036c8b5bead
```

# Desired:

We want the output of `secure-channel list` it to be similar to the output from [secure-channel create](https://github.com/build-trust/ockam/blob/e74fe2d40a0aa6af548606850058da7c83949251/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L85-L141)

on stdout, if tty

```
$ ockam secure-channel list --node default
/service/a0d17e26a17a5917bfd90036c8b5bead
```

on stderr

```
$ ockam secure-channel list --node default

Secure Channels

  Secure Channel:
    • From: /node/n1
    •   To: /node/n2/service/api (/ip4/127.0.0.1/tcp/50303/service/api)
    •   At: /service/a0d17e26a17a5917bfd90036c8b5bead
```

And also handle json and color, similar to the setup [secure-channel create](https://github.com/build-trust/ockam/blob/e74fe2d40a0aa6af548606850058da7c83949251/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L85-L141)

The code for the `secure-channel list` command is here:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/list.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by sanjayts** [comment]
I'm interested in picking this up :)

Though I'm not able to replicate the output highlighted above:
```
> cargo run --release --bin ockam -- secure-channel list --node n1   
error: Found argument '--node' which wasn't expected, or isn't valid in this context

        If you tried to supply `--node` as a value rather than a flag, use `-- --node`

USAGE:
    ockam secure-channel list [OPTIONS] --at <NODE>

For more information try --help
```

Similar error when trying to list the channel for default --node. I'm assuming this is the correct command:

```
> cargo run --release --bin ockam -- secure-channel list --at n1  
Secure channels for node `n1`:
  0#f16eef69ffd2fd26541b86c8398f72bb
```

Assuming I create another node n3 and create a new channel from n3 to n2 (along with the one from n1 to n2), the output is something like:
```
> cargo run --release --bin ockam -- secure-channel list --at n3                                    
Secure channels for node `n3`:
  0#92331445f768a0e1d85fa2ad527a5dc0
  0#1b6e1762c87efce2d625e0b3614d0039
```

I believe this needs to look something like the below; is my understanding correct here?
```

Secure Channels
    
    Secure Channel:
    • From: /node/n3
    •   To: /node/n1/service/api (/ip4/127.0.0.1/tcp/60313/service/api)
    •   At: /service/1b6e1762c87efce2d625e0b3614d0039
    
    Secure Channel:
    • From: /node/n3
    •   To: /node/n2/service/api (/ip4/127.0.0.1/tcp/60321/service/api)
    •   At: /service/92331445f768a0e1d85fa2ad527a5dc0
    
```

**Comment by sanjayts** [comment]
I was able to figure out how to retrieve From (`/node/{cmd.at}`) and At (`route_to_multiaddr(&route![addr])`) but not sure where I could get the "To" from? Would that involve a separate RPC call?

**Comment by mrinalwadhwa** [comment]
@sanjayts Thank you for spending time on this!

Looks like you're on the right track, have a look at the show command for how to get the To field:
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/show.rs#L37

**Comment by sanjayts** [comment]
@mrinalwadhwa Awesome! I've made some good progress (calling RPCs in a loop is not simple!). Off the top of your head, would you know how I could convert the route string representation return by ShowSecureChannelResponse (1#127.0.0.1:60321 => 0#api) to something like (/node/n2/service/api (/ip4/127.0.0.1/tcp/60321/service/api)?

**Comment by mrinalwadhwa** [comment]
`route_to_multiaddr` is likely what you're looking for. Feel free to push a draft PR and we can help with suggestions to improve it.

**Comment by sanjayts** [comment]
Created a WIP PR -- https://github.com/build-trust/ockam/pull/3467

There are a few more things to be done here but would appreciate your feedback, cheers!

**Comment by sanjayts** [comment]
@mrinalwadhwa Wondering if you had a chance to look at the PR and if the approach seems reasonable?

**Comment by mrinalwadhwa** [comment]
@sanjayts Sorry about the slow feedback on this. everyone on the team was working towards a release this week. I'll have a look today and leave some comments
