### ISSUE TITLE
Improve output of `ockam tcp-connection create` command for formatting, color, and json

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3392]
Current:

```
$ ockam node create n1 --tcp-listener-address 127.0.0.1:6001
$ ockam node create n2 --tcp-listener-address 127.0.0.1:6002

» ockam tcp-connection create --from /node/n1 --to 127.0.0.1:6002
Tcp connection created! You can send messages to it via this route:
`/dnsaddr/localhost/tcp/6001/ip4/127.0.0.1/tcp/6002`
```

Desired: 

We want the output of secure-channel list it to be similar to the output from [secure-channel create](https://github.com/build-trust/ockam/blob/e74fe2d40a0aa6af548606850058da7c83949251/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L85-L141)

```
» ockam node create n1
» ockam node create n2

» ockam secure-channel create --from /node/n1 --to /node/n2/service/api

  Created Secure Channel:
  • From: /node/n1
  •   To: /node/n2/service/api (/ip4/127.0.0.1/tcp/51290/service/api)
  •   At: /service/71460ad747b0b2f5d2079dc64bb5df03

```

So it output for `tcp-connection create` should look like:

```
» ockam tcp-connection create --from /node/n1 --to 127.0.0.1:6002

  Created TCP Connection:
  • From: /node/n1
  •   To: 127.0.0.1:6002 (/ip4/127.0.0.1/tcp/6002)

```

And also handle json and color, similar to the setup [secure-channel create](https://github.com/build-trust/ockam/blob/e74fe2d40a0aa6af548606850058da7c83949251/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L85-L141)

The multiaddr that is currently printed can be ignored.

The code for `tcp-connection create` is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mrinalwadhwa** [comment]
fixed in https://github.com/build-trust/ockam/pull/3426
thank you @leonzchang 🥳

**Comment by leonzchang** [comment]
anytime.
