### ISSUE TITLE
Reduce the amount of information that we show at Project Creation

### ISSUE THREAD

**Issue by BeenzSyed** [build-trust/ockam#3393]
# Currently we see

```
» ockam enroll

Enroll Ockam Command's default identity with Ockam Orchestrator:
! First copy your one-time code:  CCZT-GFSF
> Then press enter to open https://account.ockam.io/activate in your browser...
> Opening: https://account.ockam.io/activate
> Tokens received, processing...

Space
  Id: a0f5c1d9-dad4-4f22-aa06-d5d2e9a5e8a4
  Name: 2024000c
  Users: ...

Establishing secure channel...
Project
  Id: 6ee618f3-77b8-4328-9517-28943bae8987
  Name: default
  Users:
  Services:
  Access route: /dnsaddr/a4e562a7c92894a86a7c6be95dacc107-57cfc2b5c9137176.elb.us-west-1.amazonaws.com/tcp/6252/service/api
  Identity identifier: P8d2b4d4fe9990e4ebe4c6270ce34801846cbd4406fb99a046cc6384521081024
  Authority access route: Some(CowStr("/dnsaddr/a4e562a7c92894a86a7c6be95dacc107-57cfc2b5c9137176.elb.us-west-1.amazonaws.com/tcp//service/api"))
  Authority identity: 011d66869dfcf7f0cbe05818495cc34a2bb2e315cc9bebf73641f4118769a141d4010000084f434b414d5f524b00030120000000000000002000e703224639e380b9d370a6a747dc929cb096f86da7c4916ae8bdc092475897034037f7679b8a4cfc7074b107378870721442019673333ee2305d3c34df7add7d74436e5f808f32e43daaddd1f2c71ee791232815f9da278aae8be6fff6fcf19f05b9154549a381303a93dd12a27e173d7f366f1597ca282dace84737fcfb3fa282010140068ba8d818bdd0689c777e339ee36ee569eaf8dc4f6d763fb97fb265f2e5345ceb95ad0b2ba8f02c79d4f6b1685630190d31230a58e5a59001ed8de62551e10c
```

# Desired

Under the Project information, we can remove Identity Identifier, Authority access route and Authority Identity.

```
» ockam enroll && bats implementations/rust/ockam/ockam_command/tests/commands.bats

Enroll Ockam Command's default identity with Ockam Orchestrator:
! First copy your one-time code:  CCZT-GFSF
> Then press enter to open https://account.ockam.io/activate in your browser...
> Opening: https://account.ockam.io/activate
> Tokens received, processing...

Space
  Id: a0f5c1d9-dad4-4f22-aa06-d5d2e9a5e8a4
  Name: 2024000c
  Users: ...

Establishing secure channel...

Project
  Id: 6ee618f3-77b8-4328-9517-28943bae8987
  Name: default
  Access route: /dnsaddr/a4e562a7c92894a86a7c6be95dacc107-57cfc2b5c9137176.elb.us-west-1.amazonaws.com/tcp/6252/service/api
  Identity identifier: P8d2b4d4fe9990e4ebe4c6270ce34801846cbd4406fb99a046cc6384521081024
```

The code for the project create is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/create.rs

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this?

**Comment by mrinalwadhwa** [comment]
@mohitsaxenaknoldus yes absolutely, all yours. Let us know if you have any questions.

**Comment by Abhicodes-crypto** [comment]
@mohitsaxenaknoldus Are you still working on this ? If not, I would like to take this up :)

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus Are you still working on this ? If not, I would like to take this up :)

Go for it!

**Comment by Abhicodes-crypto** [comment]
Okay. I'm taking this up.

**Comment by Abhicodes-crypto** [comment]
Hi @BeenzSyed , In the desired output code , you have Identity identifier, but you have mentioned 
> we can remove Identity Identifier, Authority access route and Authority Identity.

So do you want the Identity Identifier to be in the output or not ? (I have the changes ready will PR as soon as this is clarified)

Also, the solution that I have figured out is changing the output implementation of project. Please confirm if this is the right approach. 

This is how the output looks after my changes :
```
Space
  Id: 8ba51435-87ff-4387-a045-2825de93e14d
  Name: 5edec447
  Users: abhi.codes10@gmail.com

Establishing secure channel...
Project
  Id: 90c11b4e-5a8f-4b31-95e8-d321ab14986a
  Name: default
  Users: 
  Services: 
  Access route: /dnsaddr/k8s-hub-n7443499-47829f5960-92b10b1b8f955a81.elb.us-west-1.amazonaws.com/tcp/6252/service/api
  ```
