### ISSUE TITLE
Improve help for `ockam space` subcommand

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3413]
# Currently:

<img width="900" alt="Screen Shot 2022-09-03 at 2 56 56 AM" src="https://user-images.githubusercontent.com/159583/188265593-06f31030-6f1d-49d8-b6cd-0a967c067e98.png">

Note the location of where the help subcommand is displayed.

# Desired:

We want to make help for `ockam space` look more like `ockam secure-channel`

<img width="805" alt="Screen Shot 2022-09-03 at 3 01 04 AM" src="https://user-images.githubusercontent.com/159583/188265722-4057535d-57db-4d99-baf4-0d803c4c9c84.png">

Note how help is the last command shown and has the message "Print help information".

To do this we'll need to set display_order and mut_subcommand the help command.

See this snippet from `ockam secure-channel` command.

https://github.com/build-trust/ockam/blob/0f620b38d7e5801056553e55e2542973944ea3a5/implementations/rust/ockam/ockam_command/src/secure_channel/mod.rs#L139-L162

The code for `ockam space` command is here 
https://github.com/build-trust/ockam/tree/0f620b38d7e5801056553e55e2542973944ea3a5/implementations/rust/ockam/ockam_command/src/space

**Comment by RajivTS** [comment]
I can take this as well if that's ok?

**Comment by mrinalwadhwa** [comment]
Of course, thank you for spending time on this. All yours
