### ISSUE TITLE
Remove generated name in `ockam space create` help

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3414]
# Currently

Note the generated name next to the NAME argument 
<img width="640" alt="Screen Shot 2022-09-03 at 3 07 56 AM" src="https://user-images.githubusercontent.com/159583/188265944-bde33beb-4b2e-49eb-9cd7-598de5b2b390.png">

# Desired

We don't want to display the generated value (ex: e8218333) in help.

The code of `ockam space create` command is here
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/space/create.rs

**Comment by mrinalwadhwa** [comment]
@RajivTS all yours

**Comment by RajivTS** [comment]
Thanks @mrinalwadhwa. Do we need a test for this change or is this simple enough that we don't require a test?

**Comment by mrinalwadhwa** [comment]
This is simple enough 👍
