### ISSUE TITLE
Implement `ockam reset` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3454]
Currently, to do a complete reset we do:

```
ockam node delete --all --force
```

We want to add a new command `ockam reset` that will have the same behaviour as `ockam node delete --all --force`.

The command would prompt the user to confirm that really want a full reset. If they yes. Then delete everything. `ockam reset --yes|-y` would skip the prompt.

The code for  `ockam node delete --all --force` is here https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs

The command will be defined in [this folder ](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src)in `reset.rs`

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa, Please review my PR(https://github.com/build-trust/ockam/pull/3455)

**Comment by jdrachal** [comment]
I'm new here. Let me look at it :)

**Comment by mrinalwadhwa** [comment]
Added by @michealkeines in https://github.com/build-trust/ockam/pull/3455 🥳

**Comment by mrinalwadhwa** [comment]
@jdrachal if you're looking for a similar issue to contribute, have a look at https://github.com/build-trust/ockam/issues/3460 .. let me know if you have questions.
