### ISSUE TITLE
Implement `ockam status` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3460]
Create a new command `ockam status` at the root of the [`ockam_command`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src) crate that will show the identities that have been enrolled.

An identity is enrolled when running the `ockam enroll` command, and currently, it doesn't support passing a specific node, so it's able to enroll only the `default_identity`. This is a limitation on the `ockam enroll` command, so the `ockam status` should be generic and support showing the status of multiple identities.

This information can be written on the config file that is available on the `CommandGlobalOpts` (more info [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/lib.rs#L238)).

A possible solution would be to write into that file after the enroll has happened, [before exiting the command](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll.rs#L58).

This command could be further extended in another PR so it also shows a short version of `ockam node list`.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by thaodt** [comment]
hi, I didn't find the "state" directory or did you mean just write it somewhere in the fs?
Another question, its clear that enroll command initializes a default identity with Ockam Orchestrator. Which result should be displayed in this case? **Yes** in case the enrollment is already registered successfully and **No** in case it failed or it still didn't register yet or the enroll process is happening. Am i right?

Sorry for my naive questions.

**Comment by jdrachal** [comment]
@thaodt are you assigned to it already? If not I'd like to take this one.

**Comment by thaodt** [comment]
> @thaodt are you assigned to it already? If not I'd like to take this one.

No, just asked. Okay its yours 😁

**Comment by mrinalwadhwa** [comment]
@jdrachal thank you for picking this up, let us know if if you have any questions.

**Comment by adrianbenavides** [comment]
There is an open PR by @hargut, I'll assign this issue to him.
