### ISSUE TITLE
Write a `curl | sh` script to install precompiled ockam binaries

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3487]
We release precompiled binaries in every release. We want to have a curl | sh script to make it easy for people to install these binaries.

https://github.com/build-trust/ockam/releases/tag/ockam_v0.75.0

**Comment by danieled-it** [comment]
Hey @mrinalwadhwa , I'd like to work on this, can I get this issue assigned?

**Comment by metaclips** [comment]
> Hey @mrinalwadhwa , I'd like to work on this, can I get this issue assigned?

Done! Thanks 🚀

**Comment by danieled-it** [comment]
Forgot to ask before: got any preferences on where the new script should be located and what its name should be?

**Comment by metaclips** [comment]
> Forgot to ask before: got any preferences on where the new script should be located and what its name should be?

We can have the script [here](https://github.com/build-trust/ockam/tree/develop/tools/scripts). I think `release-installer.sh` sounds cool 😎but it’s left to you if you have a better name 😎.

**Comment by danieled-it** [comment]
Probably a very dumb question, but what implementation scope would you guys like to see in the commit message for this? 😃 
I got a first "working" copy on my machine but I don't want to get it wrong at commit time 😄

**Comment by metaclips** [comment]
😄 we can scope it under ci. `ci: add ockam release installer script` will be pretty neat 🥶

**Comment by mrinalwadhwa** [comment]
Added in https://github.com/build-trust/ockam/pull/3488
Thank you @danieled-it 🥳 🎈
