### ISSUE TITLE
Add a github workflow to run shellcheck on shellscripts

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3489]
Add shellcheck to the builder image https://github.com/build-trust/ockam/blob/develop/tools/docker/builder/Dockerfile

Add a new workflow here https://github.com/build-trust/ockam/tree/develop/.github/workflows
that will run whenever any shellscript in the repo is added or changed

**Comment by mrinalwadhwa** [comment]
Shellcheck also ships with an official container, if that is well maintained then we can just use that container instead of the ockam-builder image
https://github.com/koalaman/shellcheck

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this?

**Comment by mrinalwadhwa** [comment]
@mohitsaxenaknoldus of course, all yours. Let me know if you have any questions

**Comment by elpiel** [comment]
I've opened an PR for adding `shellcheck` to the CI.

**Comment by mrinalwadhwa** [comment]
Added in https://github.com/build-trust/ockam/pull/3689, thank you @elpiel
