### ISSUE TITLE
Investigate switch to clap v4.0

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3506]
Clap now has a new release candidate

https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating
https://epage.github.io/blog/2022/09/clap4/

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mrinalwadhwa** [comment]
https://github.com/build-trust/ockam/issues/3434 has some good discussion on why we need it.

**Comment by hargut** [comment]
Hi all,

I've started to look a bit into the first steps of the upgrade, and linked a wip PR to the ticket. In case anyone wants to continue from here the first steps available.

Best regards,
Harald

**Comment by hargut** [comment]
@mrinalwadhwa 
Is there anything else within this ticket that should be investigated or can it be closed?

Best regards,
Harald

**Comment by mrinalwadhwa** [comment]
clap v4 was released a couple of days ago https://github.com/clap-rs/clap/releases
@hargut thanks to your fantastic PR last week, I think the final switch from the release candidate to the released version should be pretty simple.

**Comment by adrianbenavides** [comment]
I've created a new issue to address the upgrade to v.4.0 https://github.com/build-trust/ockam/issues/3556
