### ISSUE TITLE
clang not found

### ISSUE THREAD

**Issue by karl-cardenas-coding** [build-trust/ockam#3521]
When attempting to go through the hello work example on my Mac (M1 Monterey 12.6) I keep getting the same error of `clang not found`. Regardless of the number of times I try to install clang through the automated prompt, the software is not found.

Below is a snipped out of the error output:

```
          sh: line 1:  1592 Abort trap: 6           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find clang 2> /dev/null
          cc: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find clang 2> /dev/null' failed with exit code 34304: (null) (errno=Invalid argument)
          xcode-select: Failed to locate 'clang', requesting installation of command line developer tools.


error: linking with `cc` failed: exit status: 72
```

This error occurs when the `cargo build` command is invoked. 

## Solution

I am sharing the solution here in case others stumble into this error when getting started. It seems like every time the OS version is upgraded, Xtools preference location is not linked to the latest. You can read more about this issue in this [thread](https://apple.stackexchange.com/questions/415563/repeatedly-being-asked-to-install-command-line-tools).

Issue the following command in your Terminal session to resolve the issue:

```bash
sudo xcode-select -switch /Library/Developer/CommandLineTools
```

**Comment by mrinalwadhwa** [comment]
@karl-cardenas-coding thank you for creating the issue, if someone else faces the same problem, this'll be helpful.

**Comment by karl-cardenas-coding** [comment]
@mrinalwadhwa happy to help. I have some ideas on how we can get around this issue all together with containers.

A really quick and easy way is to have people use the latest Rust container and do all exercises inside the container. That's what I did and it worked great.

Long-term, using a platform like Instruqt would probably be the best user experience. That way the user don't have to install anything and can simply go through all exercises in a provided environment.  Anyway just some ideas, happy to help explore them.

**Comment by mrinalwadhwa** [comment]
Good ideas, there is container image currently that has all our build tools.

Give it a try:
```
docker run --rm -it -e HOST_USER_ID=$(id -u) --volume $(pwd):/work ghcr.io/build-trust/ockam-builder:latest bash
```

**Comment by karl-cardenas-coding** [comment]
Oooo that's even better. Adding some introductory text to each lesson wouldn't be to bad of a task. @mrinalwadhwa would you be okay if I opened a PR that provided instructions on how to use the docker image for each lesson?

**Comment by mrinalwadhwa** [comment]
@karl-cardenas-coding not at all, we would love to get a PR.

**Comment by etorreborre** [comment]
fixed with https://github.com/build-trust/ockam/pull/3523
