### ISSUE TITLE
Improve NodeManager resource management

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#3524]
Currently [NodeManager](https://github.com/build-trust/ockam/blob/120869c0efe687aff97011a11d19d6f4afa57992/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L86) plays 2 roles:
1. Being a worker that responds to requests
2. Owning node's main resources

That creates some complications, (e.g. mentioned in [this thread](https://github.com/build-trust/ockam/pull/3497#discussion_r977747449)).

My suggestion is:
1. Rename `NodeManager` to `NodeManagerWorker` and let it only handle requests
2. Move all state to a separate structure (name `NodeManager` is still good here)
3. Make possible having shared access to `NodeManager` by either wrapping the whole structure in `Arc<Mutex<_>>` or replacing its internals with thread-safe shared access options (like `RwLock`)

`3` would be great as a separate PR

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa can i work this?

**Comment by SanjoDeundiak** [comment]
@michealkeines sure

**Comment by mrinalwadhwa** [comment]
@michealkeines of course, all yours

**Comment by michealkeines** [comment]
Hi @SanjoDeundiak , I read the comments you mentioned.

from my understanding, i can rename the `NodeManager` to `NodeManagerWorker`, this `NodeManagerWorker` will impl `ockam::worker` which in turn will handle the requests

```rust
#[ockam::worker]
impl Worker for NodeManagerWorker {
    async fn handle_message(&mut self, ctx: &mut Context, msg: Routed<Vec<u8>>) -> Result<()> {
        handle_request();
        // rest
    }
}
```

```rust
impl NodeManagerWoker {
     async fn handle_request(
        &mut self,
        ctx: &mut Context,
        req: &Request<'_>,
        dec: &mut Decoder<'_>,
    ) -> Result<Vec<u8>> {
        // all requests
    }
}
```

regarding the second one,

`Move all state to a separate structure (name NodeManager is still good here)`

if i move some state values into `NodeManager`, then `NodeManagerWorker` itself has to hold an reference to `NodeManager` right?

```rust
struct NodeManagerWorker {
    node_manager: Arc<Mutex<NodeManager>>,
    // rest of the request related feilds
}
``` 

i am not sure, if i have understood it correctly, please describe a bit more, if i am wrong.

thank you.

**Comment by SanjoDeundiak** [comment]
@michealkeines Yes, perfect!

**Comment by michealkeines** [comment]
@SanjoDeundiak the [PR](https://github.com/build-trust/ockam/pull/3548) is a sample, i had a hard time understanding which fields to move from old `NodeManager` into `NodeManagerWorker`, please check it out and let me know what else should be added.

Thankyou

**Comment by michealkeines** [comment]
Hi @SanjoDeundiak is there anything else needs to be added for this issue?

**Comment by SanjoDeundiak** [comment]
No, I think we're fine. Thank you @michealkeines !
