### ISSUE TITLE
Refactor `NodeManager` constructor

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#3527]
Currently `NodeManager::create` function takes 10 arguments. It's time to move those arguments into into one or few structures

https://github.com/build-trust/ockam/blob/92943069471cd6eface5bf0e64be5531394ded09/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L136-L151

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by vncsalencar** [comment]
Hi, @SanjoDeundiak. Do you think this is a `good-first-issue` candidate? I'd like to give this a go if so.

**Comment by mrinalwadhwa** [comment]
@vncsalencar I think so. Go ahead an give it a try, if you get stuck, please don't hesitate to ask questions, we're here to help.
