### ISSUE TITLE
Improve `CowStr` Display

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#3531]
Currently, we have some user-facing output that includes [CowStr](https://github.com/build-trust/ockam/blob/e4bea07f319dddbb0dbbcbaeee015f5eaceb0031/implementations/rust/ockam/ockam_core/src/cbor_utils/cow_str.rs), for example output of `ockam enroll` command looks something like this:
 
![Screenshot 2022-09-27 at 16 16 37](https://user-images.githubusercontent.com/6513916/192536866-e022ee2f-ca2f-44aa-a694-3ca1e97a050f.png)

I think `CowStr("")` part is not needed while displaying such string, as it doesn't carry any useful information

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by twittner** [comment]
I would add that the `Some` bit should also not show up here. If the authority access route is missing, [N/A](https://en.wikipedia.org/wiki/N/A) would be a suitable value.

**Comment by twittner** [comment]
To clarify I do not think that the `Debug` impl of `CowStr` should change as it should not be used at all for this purpose. Instead `fmt::Display` should be used.

**Comment by akki1306** [comment]
Hi, would like to work on this. Could you assign it to me? line no. 105 to 107 in output.rs needs to be updated as below. Please provide your input.

` write!(
            w,
            "\n  Authority access route: {}",
            self.authority_access_route.as_deref().unwrap_or_else("N/A")
        )?;`

**Comment by mrinalwadhwa** [comment]
@akki1306 great all yours

**Comment by mrinalwadhwa** [comment]
addressed in https://github.com/build-trust/ockam/pull/3543 by @akki1306 🥳
