### ISSUE TITLE
The `project delete` command should work with projects that failed to start

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3539]
When a user wants to delete a project from the CLI they have to pass the project name. The CLI will try to resolve the project's access route to communicate with the orchestrator. To do that translation we just need the `id` field. This information will be retrieved from the `lookup` table from the config file. If it's not found the command will try to fetch the project from the orchestrator.

Currently, the `project delete` command will fail if a project failed to start (i.e. the `Project::is_ready()` never returned `true`). 

We can mitigate this by storing the project data into the config file right before the first loop from `project::util::check_project_readiness()`, at [this line](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/util.rs#L135). This way, we will be able to resolve projects id's given their names even if the project failed to start and the user will be able to delete them.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by sanjayts** [comment]
I'd be interested in picking this up.

**Comment by mrinalwadhwa** [comment]
@sanjayts awesome. all yours

**Comment by sanjayts** [comment]
I had a quick look at this and would appreciate some clarification. IIUC, the concern here is readiness check can fail and we want to persist the `project` before doing the readiness check. But trying to persist (`config::set_project(&opts.config, &project).await?;`) before the project is ready results in an error **"Project is not ready yet, wait a few seconds and try again"**.

Commenting out this check results in another failure which is **"Project should have identity set"** -- so I assume the persistence can't happen here before the project is ready? What are your thoughts on this -- should we persist the project in config file after it is ready but before it is reachable etc. or should we look into somehow persisting the project without it being ready?

**Comment by adrianbenavides** [comment]
We want to keep the current `set` method as it is. What I'd rather do is to create another method called `set_unchecked` which will do exactly the same as `set` but without the `!project.is_ready()` check and without unwrapping the `project.identity`. To do this you'll need to refactor a little the `ProjectLookup` structure so it matches the types from `Project`. More specifically, `ProjectLookup`'s `node_route` and `identity_id` should be `Option`s so you can just leave them as `None` when the project is not ready yet.

Let me know if that makes sense to you!

**Comment by sanjayts** [comment]
Thanks; this definitely makes sense -- I was under the impression that all fields need to be populated before storing the config, but that doesn't seem to be the case. I've created a rough draft PR -- do you mind taking a look so that I know I'm on the right track? I'll clean up the unwraps and use error handling once you give your go-ahead.

https://github.com/build-trust/ockam/pull/3635/files
