### ISSUE TITLE
Validate project and space names

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#3540]
# Current

[Project](https://github.com/build-trust/ockam/blob/39195e8039d61422286fff7002deac2750918a48/implementations/rust/ockam/ockam_command/src/project/create.rs#L23) and [space](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/space/create.rs#L18) creation commands currently accept any string as a valid project|space names. But in reality *not* all strings are valid: orchestrator will reject the creation if the space name contains whitespaces, etc.

# Desired

Enforce on the CLI interface that project and space names follow these rules:
* Contains only alphanumeric characters  and the '-', '_'  and '.'  separators
* Separators _must_ occur between alphanumeric characters. This implies that separators can't occur at the start or end of the name, nor they can occur in sequence.
  
You can consider this regexp 
`/^[a-zA-Z0-9]+([a-zA-Z0-9-_\.]?[a-zA-Z0-9])*$/`

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by windlessStorm** [comment]
Hi, I would like to take pick this up.

**Comment by mrinalwadhwa** [comment]
@windlessStorm awesome. All yours
