### ISSUE TITLE
File transfer between sender to multiple receiver nodes.

### ISSUE THREAD

**Issue by yashwanthsinghm** [build-trust/ockam#3544]
Hi we are trying to securely  transfer file between multiple nodes. We tried Ockam file transfer example  and tested few scenario and we have encountered some issues, we need some clarity on that.
  
1. When we transfer a file between 2 nodes we have noticed that data is flowing via Ockam pubic nodes (1.node.ockam.network). So wont that be any traffic of data at the public node when multiple nodes are sending large data?
2. Is there any way to communicate between nodes without orchestrater ? Like direct communication between 2 public IP address.
3. Can we exchange forward address between sender and receiver without manually exchanging it? 
4. Does Ockam has any Official Chat room to discuss?

**Comment by mrinalwadhwa** [comment]
@yashwanthsinghm @sarath3192 @imrank03 👋 I assume from your questions in the last couple of days that maybe all of you are on the same team. Are you?

Sorry about the slow response. I am out of office this week and next.

1. The public nodes are setup for demo purposes. To get scalable nodes, you need a project in Ockam Orchestrator account. 
2. If two IPs are public on the Internet. Then they can exchange data without needing Orchestrator. However this is rarely the case, usually the machines that are communicating are behind NATs. If the are, then you need a Relay/Forwarder in Orchestrator or UDP NAT Puncturing (which is planned feature, currently in development.)
3.

**Comment by mrinalwadhwa** [comment]
@yashwanthsinghm @sarath3192 @imrank03 👋 I assume from your questions in the last couple of days that maybe all of you are on the same team. Are you?

1. The public nodes are setup for demo purposes. To get scalable nodes, you need a project in Ockam Orchestrator. 

2. If two IPs are public on the Internet. Then they can exchange data without Orchestrator Relays. However this is rarely the case, usually the machines that are communicating are behind NATs. If they are, then you need a Relay/Forwarder in Orchestrator or UDP NAT Puncturing (which is a planned feature, currently in development.)

3. Yes, in latest deployments for Orchestrator (not available in the demo node 1.node.ockam.network) we have static forwarding. This allows a fixed named forwarding address to be registered. The other party can simply know that is the address.

However the more important information that must be communicated is - the basis of trust -  either public keys of the secure channel listener/initiator or the public key of a credential authority that both parties trust. Orchestrator Projects come with a managed Credential Authority that can remove the need for any manual transfer of such information.

4. We don't have a chat room. If you have more specific questions, please feel free to email me at `mrinal@ockam.io`

We would love to learn more about what you're building and get you a production Orchestrator account.

**Comment by yashwanthsinghm** [comment]
Hi @mrinalwadhwa,
Thank you for the response.
Yes we are from same team , we work on rustBoot project from Bosch. 

We are building secure firmware update, so we looked into that file transfer example. But in our case we will have multiple nodes and we don't want data to flow via Orchestrator which sitting in middle, do you have any suggestions for this?

**Comment by sarath3192** [comment]
Hi @mrinalwadhwa,
Thank for your time and elaborate answers, 
Can you clarify this a bit

1. We know that Orchestrator helps in establishing trust between the nodes. After that, does the data also flows though Orchestrator ? **OR** Is there separate channel for the data flow between the nodes ?

**Comment by mrinalwadhwa** [comment]
@yashwanthsinghm @sarath3192 Sorry about the slow responses. I'm on vacation till the end of this week. 

Data doesn't need to flow through Relays in Orchestrator.
There are multiple ways to set this up based on your needs: 

1. Expose a TCP Listener to the the internet. See [this example](https://github.com/build-trust/ockam/tree/develop/documentation/guides/rust/get-started/04-transport#transport), you'll have to adapt the route from the file transfer example to take a single TCP hop.
- This option requires that you expose a TCP port to the Internet and manage scaling, uptime, load balancing, ddos protection etc. of this TCP listener.

3. Another option is by using UDP NAT puncturing (also call hole punching), where Orchestrator is used to negotiate a UDP path but after that data transfer is direct between the two communicating Ockam Nodes. This is currently in development.
- A tradeoff of this option is that NAT puncturing is dependent on how the NATs are setup and doesn't always succeed in creating a successful connection.

4. The last option Orchestrator Relays have the benefit that they always work in any network that allows outgoing TCP connections. They are a great fallback for UDP NAT puncturing.
- End-to-End Encrypted data is moved through the Relay and Ockam manages scaling, uptime, load balancing, ddos protection etc. and provides throughput and latency SLAs.

I would love to learn more about your deployment topology. That would help us advise on the best setup. Let's have a call next week when I'm back from my vacation.

**Comment by mrinalwadhwa** [comment]
Closing since these questions have been addressed. Let us know in case you have more questions.
