### ISSUE TITLE
`node` subcommands that act on existing nodes should not hide the `node_name` default value

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3552]
## Current

`node` subcommands have `node_name` as the first argument. The commands that act on existing nodes should default to the "default" node and should not hide this value.

Currently, this is only done correctly in the `node show` command.

## Desired

The following commands should not have the `hide_default_value = true` attribute in the `node_name` argument (take the `node show` command as reference):

- `node delete`

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by akki1306** [comment]
Hey, I am interested to work on this, could you assign me?

**Comment by mrinalwadhwa** [comment]
@akki1306 great, it's all yours. Thank you
