### ISSUE TITLE
Code Coverage Tool Errors

### ISSUE THREAD

**Issue by BeenzSyed** [build-trust/ockam#3553]
# Current
We use [grcov](https://github.com/mozilla/grcov) as the code coverage tool for the Rust libraries. How to run the tool is located in [DEVELOP.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/DEVELOP.md#code-coverage). 

When running the second line: `env CARGO_INCREMENTAL=0 RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort --cfg tokio_unstable" RUSTDOCFLAGS="-Cpanic=abort" cargo +nightly test`, it throws `internal compiler errors`.

These need to be looked into to see what is going on and how to fix them.

# Desired
When running the [code coverage tool](https://github.com/build-trust/ockam/blob/develop/implementations/rust/DEVELOP.md#code-coverage), we receive a report about what our code coverage looks like.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Overflow0xFFFF** [comment]
I'll take this one! I've been poking around and think I may have found a fix.
