### ISSUE TITLE
Upgrade clap to v4.0

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3556]
## Current

We recently upgraded from v.3 to one of the latest v4's release candidates at https://github.com/build-trust/ockam/issues/3506 

## Desired

The first stable v.4.0 has been released, so we want to upgrade the `clap` dependency and make the needed changes to adapt the code to it.

The version on `cargo.toml` should be `version = "4.0"`.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
@adrianbenavides 
In case this is not urgent, I can have a look within the next days.

**Comment by adrianbenavides** [comment]
Sure, all yours @hargut, thanks!

**Comment by mrinalwadhwa** [comment]
Closed in https://github.com/build-trust/ockam/pull/3573
