### ISSUE TITLE
Refactor `configuration get` command to stop mapping errors manually

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3557]
Command: [`configuration get`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/configuration/get.rs)

## Current

The current implementation is calling `std::process::exit`, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails. 

## Desired

- `run` method (main entry point of the subcommand) should contain a single line of code calling a function (run_impl/rpc/...) that returns a `crate::Result<()>`
- `std::process::exit` should not be used manually to map the errors of the command's logic
- `run` method will return `()`, and will unwrap the result like it's done [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L24) (note that there is a single call to `std::process::exit` at the command's `run` method and with the error `code` derived from the error returned by the `run_impl` method)

You can take the [`node delete`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L23) command as a reference.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by kriogenia** [comment]
I have a bit of free time, enough to do this easy refactoring. I'll have the PR soon.
