### ISSUE TITLE
Refactor `configuration set-default-node` command to stop mapping errors manually

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3560]
Command: [`configuration set-default-node`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/configuration/set_default_node.rs)

## Current

The current implementation is calling `std::process::exit`, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails. 

## Desired

- `run` method (main entry point of the subcommand) should contain a single line of code calling a function (run_impl/rpc/...) that returns a `crate::Result<()>`
- `std::process::exit` should not be used manually to map the errors of the command's logic
- `run` method will return `()`, and will unwrap the result like it's done [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L24) (note that there is a single call to `std::process::exit` at the command's `run` method and with the error `code` derived from the error returned by the `run_impl` method)

You can take the [`node delete`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L23) command as a reference.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by AntoniosBarotsis** [comment]
Hello! I'd like to work on this!

I'm relatively new to Rust and a bit confused with the issue. If you want `run` to return `()` then how are you going to bubble the error up?

Haven't opened a PR yet because I'm unsure how to continue but my code so far looks like this

```rs
[...]

impl SetDefaultNodeCommand {
    pub fn run(self, options: CommandGlobalOpts) {
        // Currently ignoring the return value
        run_impl(&options);
    }
}

fn run_impl(options: &CommandGlobalOpts) -> crate::Result<()> { ... }
```

The unwrapping example you link still ends up using `std::process::exit`. 

Thanks in advance!

**Comment by adrianbenavides** [comment]
Hey @AntoniosBarotsis, thanks for the comment! Let me clarify.

We have two kinds of commands:
1. Commands that need an async runtime and an `ockam::Context`. This is where no `std::process::exit` should be used explicitly, as it's handled internally by the `rpc` abstraction (like in the [subscription command](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L57))
2. Commands that don't need the `ockam::Context`. In this case, we will have a single call to `std::process::exit` at the command's `run` method and with the error `code` derived from the error returned by the `run_impl` method.

In this issue, we are in the second case. This command should look pretty much the same as the [`node delete`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L24) command.

I'll update the issue description in a bit with more details. Let me know if that solved your questions!

**Comment by AntoniosBarotsis** [comment]
Makes sense now, thanks! Opened a PR.
