### ISSUE TITLE
Refactor `vault create` command to use `rpc` abstraction and to stop mapping errors manually

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3564]
Command: [`vault create`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/vault/create.rs)

## Current

The current implementation is calling `std::process::exit`, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails.

It's also using the `connect_to` function, which can be simplified by using the `Rpc` utils. Check out how this is done in the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands, for example.

## Desired

- `run` method (main entry point of the subcommand) should contain a single line of code calling a function (run_impl/rpc/...) that returns a `crate::Result<()>`
- `std::process::exit` should not be used manually to map the errors of the command's logic
- `run` method will return `()`. The error will be internally handled within the `node_rpc` function 
- If you need to replace an `std::process::exit` by an actual error, you can use something like `Err(crate::error::Error::new(exitcode::..., anyhow!(...))`
- Use `rpc` abstraction instead of `connect_to`

You can take the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands as a reference.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by kriogenia** [comment]
Hi, I would like to try to contribute with this one if it's ok

**Comment by mrinalwadhwa** [comment]
@kriogenia awesome, all yours. Let us know if you have any questions
