### ISSUE TITLE
Update `ockam service start` clap command to have consistent UX when providing address

### ISSUE THREAD

**Issue by neil2468** [build-trust/ockam#3566]
`ockam service start` has different UX for different services. 

## For example...
* `vault`, `identity`, and `authenticated`, take the address as an argument...

```shell
> ockam service start vault my_vault --node n1
```

* `verifier`, `credentials`, and `authenticator` take the address as an option...

```shell
> ockam service start verifier --addr my_verifier --node n1
```

**Comment by elpiel** [comment]
I can look into this but which one is the preferred one in this case?

**Comment by neil2468** [comment]
Hi @elpiel. Thanks for reaching out :wave:

I'd vote for options (the 2nd case). I feel it makes the commands more descriptive and allows flexibility in ordering vaules. However, I don't know the bigger picture (ie. how the commands are used in practice or the UX Ockam would prefer across the board).

@mrinalwadhwa, any thoughts? 

Thanks!

**Comment by etorreborre** [comment]
@CAOakleyII can you please confirm that this issue is contained in the overall review plan for command line options? (and maybe close this issue if it is already covered via another piece of work). Thanks

**Comment by caoakleyii** [comment]
This is an issue that we should still keep and in scope for our upcoming UX improvements. @etorreborre
