### ISSUE TITLE
Remove git-cliff config file from root directory

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3567]
We currently have git-cliff configuration in this [toml file](https://github.com/build-trust/ockam/blob/develop/cliff.toml) in the `root path`, we should move the config file to `./tools/cliff` and set the [changelog generation script](https://github.com/build-trust/ockam/blob/127df6de454784813cb69c785faf2e627afa41c5/tools/scripts/release/changelog.sh#L14) to use the `updated` config path ( passing `--config` git-cliff option )

**Comment by goverdhan07** [comment]
Heya! working on this issue, pls assign it to me, Thanks

**Comment by metaclips** [comment]
All yours 🚀
