### ISSUE TITLE
Lint crago.lock file when updated

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3572]
When a PR updates `Cargo.lock` file, we should ensure that the lock file was generated by `cargo command` and not tampered with. This could entail a CI that
- Gets the current SHA of `Cargo.lock` generated by PR/user.
- Deleting the current `Cargo.lock`
- Generating a new `Cargo.lock`, possibly calling `cargo check` command.
- Getting the SHA of the new lock file
- Ensure the SHA generated by `user PR` is same as that of `CI`

**Comment by elliotwutingfeng** [comment]
Can I try this?

**Comment by mrinalwadhwa** [comment]
@elliotwutingfeng that would be great! let us know if you have questions along the way.

**Comment by elliotwutingfeng** [comment]
Thanks! I believe this can be closed now.
