### ISSUE TITLE
Split schema.cddl

### ISSUE THREAD

**Issue by twittner** [build-trust/ockam#3575]
[`schema.cddl`](https://github.com/build-trust/ockam/blob/127df6de454784813cb69c785faf2e627afa41c5/implementations/rust/ockam/ockam_core/src/schema.cddl) contains schema definitions for various API types. It was originally located in `ockam_api` but as use of API types spread it was moved to `ockam_core` along with supporting infrastructure (e.g. [to assert some CBOR value matches a certain rule](https://github.com/build-trust/ockam/blob/127df6de454784813cb69c785faf2e627afa41c5/implementations/rust/ockam/ockam_core/src/api.rs#L521-L561)). However this single file still contains all rules, even for types outside of `ockam_core`. Ideally each crate has its own schema file, containing only those rules that apply to its own types and not those of other crates.

Assuming those files exist their contents must nevertheless be merged as every API interaction contains a mixture of types from different crates (e.g. `Request` from `ockam_core` and `Project` from `ockam_api`). The existing functions `assert_request_match` and `assert_response_match` could accept an additional parameter, implementing cddl-cat's [`LookupContext`](https://docs.rs/cddl-cat/0.6.1/cddl_cat/context/trait.LookupContext.html) and instead of using `cddl_cat::validate_cbor_bytes` they use [`cddl_cat::validate_cbor`](https://docs.rs/cddl-cat/0.6.1/cddl_cat/fn.validate_cbor.html). Before using those assertion functions a crate needs to merge the contexts of its dependent crates. For example:

## `ockam_core::api`

```rust
pub const SCHEMA: &str = core::include_str!("schema.cddl");

pub fn schema() -> Result<BasicContext, MyValidationError> {
    let cddl = cddl_cat::parse_cddl(SCHEMA)?;
    let cddl = flatten(&cddl)?;
    Ok(BasicContext::new(cddl))
}
```

## `ockam_node::api`

```rust
pub const SCHEMA: &str = core::include_str!("schema.cddl");

pub fn schema() -> Result<BasicContext, MyValidationError> {
    let mut ctx = ockam_core::api::schema()?;
    let cddl = cddl_cat::parse_cddl(SCHEMA)?;
    let cddl = flatten(&cddl)?;
    for (k, v) in cddl {
        match ctx.rules.entry(k) {
            Entry::Vacant(e) => {
                e.insert(v);
            }
            Entry::Occupied(e) => {
                return Err(MyValidationError::Duplicate(e.key().to_string()))
            }
        }
    }
    Ok(ctx)
}
```

The resulting `BasicContext` (probably wrapped in a newtype) could then be used to validate requests/responses.

**Comment by phillyphil91** [comment]
Hi.
I'm not familiar with CBOR or CDDL but I would like to give this issue a try. Will definitely require some help though :sweat_smile:

**Comment by phillyphil91** [comment]
If I understand correctly, at the moment every crate that wants to assert correct CBOR data, needs to call `ockam_core::api::assert_request_match` which compares against the CDDL thats stored in `schema.cddl`? Now the new approach should be that every crate needs to have its' own CDDL file but also create the validation schema from its' own CDDL and the crates it depends on.
So as in the example:
`ockam_node::api` needs to call the `schema()` function of `ockam_node::core` to include the core CDDL in its' own `schema()` function as well and then this can be used for validation in `assert_request_match` for example?

I will create a first Draft for this.

**Comment by phillyphil91** [comment]
I think this can be closed as of now, right?
