### ISSUE TITLE
Test ockam command release across various architectures in CI

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3576]
On new Github release, we should test our ockam binary across various OSs in CI.
- macos
- ubuntu-latest
- ubuntu-18.04
- ubuntu-20.04

**Comment by memark** [comment]
Which tests are we talking about here? All the tests [in here](https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml#L125)?

Also, do note that `ubuntu-latest` == `ubuntu-20.04` (that will change later this year).

**Comment by memark** [comment]
@metaclips How was this implemented? (I wanted to help out, but never got any answer to my question.)

**Comment by metaclips** [comment]
Thanks @memark. I created a more detailed issue [here](https://github.com/build-trust/ockam/issues/3829) that test binaries when they are draft instead of production as I thought that makes more sense. Apologies for not responding 🙏

**Comment by memark** [comment]
Ok, no worries!
