### ISSUE TITLE
Refactor `tcp connection delete` command to use `rpc` abstraction and to stop mapping errors manually

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3594]
Command: [`tcp connection delete`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs)

## Current

The current implementation is calling `std::process::exit`, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails.

It's also using the `connect_to` function, which can be simplified by using the `Rpc` utils. Check out how this is done in the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands, for example.

## Desired

- `run` method (main entry point of the subcommand) should contain a single line of code calling a function (run_impl/rpc/...) that returns a `crate::Result<()>`
- `std::process::exit` should not be used to manually map the errors of the command's logic
- `run` method will return `()`. The error will be internally handled within the `node_rpc` function 
- If you need to replace an `std::process::exit` by an actual error, you can use something like `Err(crate::error::Error::new(exitcode::..., anyhow!(...))`
- Use `rpc` abstraction instead of `connect_to`

You can take the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands as a reference.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Abhicodes-crypto** [comment]
I would like to take this up

**Comment by divyank-aggarwal** [comment]
Hi @adrianbenavides 

I've refactored the code but is there a test which I can run or write that'd let me check a successful refactor. Would also appreciate it if you can help me with [this](https://github.com/build-trust/ockam/issues/3601#issuecomment-1282365076) issue.

Thanks for the help!

**Comment by adrianbenavides** [comment]
> Hi @adrianbenavides
> 
> I've refactored the code but is there a test which I can run or write that'd let me check a successful refactor. Would also appreciate it if you can help me with [this](https://github.com/build-trust/ockam/issues/3601#issuecomment-1282365076) issue.
> 
> Thanks for the help!

Hey @divyank-rs, you could write a simple test with the following commands:

```rust
ockam node create n1
ockam tcp-connection list
// -> check that the output does NOT include "127.0.0.1:8080"
ockam tcp-connection create --from n1 --to 127.0.0.1:8080
ockam tcp-connection list
// -> check that the output does include "127.0.0.1:8080"
```

**Comment by h20220145** [comment]
Hey @adrianbenavides , can i be assigned this issue ?

**Comment by adrianbenavides** [comment]
> Hey @adrianbenavides , can i be assigned this issue ?

All yours! Take this PR as a reference: https://github.com/build-trust/ockam/pull/3753

And you can add a new test to the commands.bats file with the contents I posted in my previous comment.

Let me know if you need any help!

**Comment by h20220145** [comment]
Hey, @adrianbenavides, I'm having some trouble running the commands.bats tests, compilation using cargo went fine. I need to run the tests to see if my work is okay. I tried the solution given in (https://github.com/build-trust/ockam/discussions/3733#discussion-4502666),

Sorry if it's a dumb question, but do I need to be on windows to run a .bats test? Currently using a macOS(arm) system.

Also, Sorry for the delay in posting here. I didn't have free time during the past few weeks. Apologies for any delay it might have caused you and the team.

Thanks.

**Comment by metaclips** [comment]
> Hey, @adrianbenavides, I'm having some trouble running the commands.bats tests, compilation using cargo went fine. I need to run the tests to see if my work is okay. I tried the solution given in (https://github.com/build-trust/ockam/discussions/3733#discussion-4502666),
> 
> 
> 
> Sorry if it's a dumb question, but do I need to be on windows to run a .bats test? Currently using a macOS(arm) system.
> 
> 
> 
> Also, Sorry for the delay in posting here. I didn't have free time during the past few weeks. Apologies for any delay it might have caused you and the team.
> 
> 
> 
> Thanks.

Hello 👋. What error(s) do you get when running the bats test?

**Comment by h20220145** [comment]
tarunsingh@Taruns-MacBook-Pro ~ % OCKAM=“~/Desktop/ockam/target/debug/ockam” bats ~/Desktop/ockam/implementations/rust/ockam/ockam_command/tests/commands.bats
commands.bats

 ✗ create a node without a name
   (from function `setup' in test file Desktop/ockam/implementations/rust/ockam/ockam_command/tests/commands.bats, line 63)
     `setup() {' failed
   bats_load_safe: Could not find '/opt/homebrew/lib/bats-support/load.bash'[.bash]
   /Users/tarunsingh/Desktop/ockam/implementations/rust/ockam/ockam_command/tests/commands.bats: line 70: “~/Desktop/ockam/target/debug/ockam”: No such file or directory

The same error repeats, failing all 34 tests.

Apologies again; I'm new to Rust and contributing to open-source projects. 

Thanks.


Update: 
Found out the problem , the tests are running fine now.

Will send a PR tomorrow.

**Comment by h20220145** [comment]
Figured it out , removing the "" from the ockam binary directory fixed it.

**Comment by mrinalwadhwa** [comment]
@h20220145 no need to apologize. Its awesome that you figured out the problem 👏 👏 
Looking forward to the PR!

**Comment by h20220145** [comment]
Can you please look at this and see if this is okay ? 
(https://github.com/h20220145/ockam/commit/4c6b8f1310e92596afc647fd0164c0f57127c589).
I tried to replace std::process::exit  with an Err, but couldn't find out an appropriate if condition, I left that part in comments in run_impl.

**Comment by adrianbenavides** [comment]
I think it looks great @h20220145! Feel free to submit a PR with those changes after cleaning up the comments :+1:

**Comment by h20220145** [comment]
So , I should remove the commented code , right ?

**Comment by adrianbenavides** [comment]
> So , I should remove the commented code , right ?

Yeah, that's right. Also, make sure to run `cargo clippy --all-targets` and `cargo fmt --all` to fix any potential lint error.
