### ISSUE TITLE
Refactor `tcp listener create` command to use `rpc` abstraction and to stop mapping errors manually

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3597]
Command: [`tcp listener create`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs)

## Current

The current implementation is calling `std::process::exit`, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails.

It's also using the `connect_to` function, which can be simplified by using the `Rpc` utils. Check out how this is done in the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands, for example.

## Desired

- `run` method (main entry point of the subcommand) should contain a single line of code calling a function (run_impl/rpc/...) that returns a `crate::Result<()>`
- `std::process::exit` should not be used to manually map the errors of the command's logic
- `run` method will return `()`. The error will be internally handled within the `node_rpc` function 
- If you need to replace an `std::process::exit` by an actual error, you can use something like `Err(crate::error::Error::new(exitcode::..., anyhow!(...))`
- Use `rpc` abstraction instead of `connect_to`

You can take the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands as a reference.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Abhicodes-crypto** [comment]
I would like to take this up

**Comment by h20220145** [comment]
Would like to take this issue up .

**Comment by adrianbenavides** [comment]
@Abhicodes-crypto all yours! Let us know if you need any help :+1:

**Comment by Abhicodes-crypto** [comment]
@adrianbenavides I need help , in line 61 https://github.com/Abhicodes-crypto/ockam/commit/00cb0597c127c2e551912bf83d27b094b78a63ee Should I use embedded or background and with which function should I replace connect_to (I tried using `route_impl` but it is private and I tried `request` but it needs parameter `req` which I don't have) 
Also please check rest of the code if I am going in right direction.

**Comment by adrianbenavides** [comment]
> @adrianbenavides I need help , in line 61 [Abhicodes-crypto@00cb059](https://github.com/Abhicodes-crypto/ockam/commit/00cb0597c127c2e551912bf83d27b094b78a63ee) Should I use embedded or background and with which function should I replace connect_to (I tried using `route_impl` but it is private and I tried `request` but it needs parameter `req` which I don't have) Also please check rest of the code if I am going in right direction.

This command creates a new listener on an existing node (the `at` argument). Therefore, you'll want to use the `Rpc::background` variant to connect to that node. Also note that you won't need the node's `port`.

The request itself is happening in the `create_listener` function. The internals of this function is what you can replace with the `rpc` abstraction. Check out this PR as an example: https://github.com/build-trust/ockam/pull/3753/files

I'd recommend you to open a PR with what you have and we can go from there!

**Comment by Abhicodes-crypto** [comment]
Hi @adrianbenavides , I've raised a PR as you said, I need help in how to get baseroute and multiaddr and alternative to route_to_mulitaddr function.
