### ISSUE TITLE
Refactor `node show` command to use `rpc` abstraction and to stop mapping errors manually

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3601]
Command: [`node show`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/show.rs)

## Current

The current implementation is calling `std::process::exit`, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails.

It's also using the `connect_to` function, which can be simplified by using the `Rpc` utils. Check out how this is done in the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands, for example.

## Desired

- `run` method (main entry point of the subcommand) should contain a single line of code calling a function (run_impl/rpc/...) that returns a `crate::Result<()>`
- `std::process::exit` should not be used to manually map the errors of the command's logic
- `run` method will return `()`. The error will be internally handled within the `node_rpc` function 
- If you need to replace an `std::process::exit` by an actual error, you can use something like `Err(crate::error::Error::new(exitcode::..., anyhow!(...))`
- Use `rpc` abstraction instead of `connect_to`

You can take the [`subscription`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) commands as a reference.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Abhicodes-crypto** [comment]
I would like to take this up.

**Comment by divyank-aggarwal** [comment]
Hi @adrianbenavides 

Any chance I can take this up? I see that there is already a test for it in the commands.bats test file and that should be sufficient to test a successful refactor.

**Comment by mrinalwadhwa** [comment]
@divyank-rs of course. thank you and let us know if you have any questions.

@Abhicodes-crypto sorry, it seems we missed your comment above, are you still exploring https://github.com/build-trust/ockam/issues/3597? let us know if you have any questions.

**Comment by divyank-aggarwal** [comment]
Hi @adrianbenavides, I'm almost done with the issue but I ran into a rust problem. I'm initializing an rpc to use for the multiple methods we need to call and get info about the node but when I use the [print_node_info](https://github.com/build-trust/ockam/blob/65a3e23b0785cff93f5ed5897d653d459da908af/implementations/rust/ockam/ockam_command/src/node/show.rs#L54) method to print, the compiler gives me the error `cannot borrow `rpc` as mutable because it is also borrowed as immutable` 

In understand the error but I'm unable to think how do I navigate around it. Cloning the inlets/outlets doesn't work and curiously I'm only running into the problem with these 2.

My code is [here](https://github.com/divyank-rs/ockam/blob/20cfd3ea47e27dad8e6aa3cb84186a8396cc01a3/implementations/rust/ockam/ockam_command/src/node/show.rs#L91). Would really appreciate any suggestions on this!

**Comment by adrianbenavides** [comment]
Hey @divyank-rs, my bad! I wasn't aware of this detail when creating the issue and I didn't add the proper context.

An `Rpc` instance can only be used to run a **single** request. After you parse a request's response, the rpc instance is consumed and you can't use it again.

What you need here is to create new Rpc's for every request reusing the same TcpTransport to the node. You can achieve this using the `RpcBuilder` as follows:

```rust
// Right after entering the `else` block, you create a TcpTransport like this:
let tcp = TcpTransport::create(&ctx).await?;

// After that, you create the first rpc for the "short id" request
let mut rpc = RpcBuilder::new(&ctx, &opts, &node_name).tcp(&tcp)?.build();
let req = Request::post("/node/identity/actions/show/short");
...

// Then, at line 76:
let mut rpc = RpcBuilder::new(&ctx, &opts, &node_name).tcp(&tcp)?.build();
rpc.request_with_timeout(req, duration).await?;
...

// And you keep creating new rpc instances before executing a new request.
```

Let me know if that makes the trick!
