### ISSUE TITLE
Command `message send` deletes node's config directory

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3609]
When executing the `message send` command, the `from` node's directory is deleted, no matter the command result.

### How to reproduce

```rust
ockam node create blue
ockam node create green
ockam message send hello --from /node/green --to /node/blue/service/echo
```

Then, blue's directory is there, but green's is not.

**Comment by mrinalwadhwa** [comment]
Closed in https://github.com/build-trust/ockam/pull/3615
