### ISSUE TITLE
Github Action for Semgrep Rules

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3617]
Semgrep is static analysis tool to lint code for patterns we want to forbid in our code.
https://github.com/returntocorp/semgrep

It has an official docker container.
https://github.com/returntocorp/semgrep#getting-started

We want to create a Github Actions workflow that would evaluate a series of semgrep rules on every new pull request. The rules will live in `tools/semgrep/rules` directory.

This Actions workflow could look very similar to the EditorConfig workflow
https://github.com/build-trust/ockam/blob/develop/.github/workflows/editorconfig.yml

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by galbwe** [comment]
Hi! Can I pick up this issue?

**Comment by mrinalwadhwa** [comment]
@galbwe of course, all yours.
Let us know if you need help or have any questions.

**Comment by galbwe** [comment]
Sweet. Thanks! I do have some questions.

- Which files do you want semgrep to include? Are there any file patterns you want ignored in `.semgrepignore`?
- What kinds of rules do you want defined in `tools/semgrep/rules` to start?
- Do you want the workflow to run on all pull requests, or only for specific branches?

**Comment by mrinalwadhwa** [comment]
Great, answers below:

> Which files do you want semgrep to include? Are there any file patterns you want ignored in .semgrepignore?

It can include everything for now.
If possible, we'll want to keep the `.semgrepignore` file in `tools/semgrep/.semgrepignore` instead of in the repo root. We're trying to limit the number of files in the repo root.

> What kinds of rules do you want defined in tools/semgrep/rules to start?

For now, let's start with some very basic hello world type rule. I'll think about rules we need over the next couple of days.

> Do you want the workflow to run on all pull requests, or only for specific branches?

All pull requests. The following triggers would be great `on: [workflow_dispatch, pull_request, push]`
