### ISSUE TITLE
Move `cargo release` config file to `tools/scripts/release`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3625]
We use `cargo release` to release rust crates.

This is called in scripts that live in this folder [`tools/scripts/release`](https://github.com/build-trust/ockam/tree/develop/tools/scripts/release)

The config file for `cargo release` is currently in the root of our repo [release.toml](https://github.com/build-trust/ockam/blob/develop/release.toml).

We want to keep the number of files in the repo root as small as possible so we would like to move it to `tools/scripts/release`

`cargo release` supports a `--config` parameter https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#configuration

**Comment by constantinosgeorgiou** [comment]
I can create a fix for this issue. Please assign it to me.

**Comment by mrinalwadhwa** [comment]
@constantinosgeorgiou great! all yours.

**Comment by constantinosgeorgiou** [comment]
Created PR #3630

**Comment by mrinalwadhwa** [comment]
Merged in https://github.com/build-trust/ockam/pull/3630, thank you @constantinosgeorgiou 🥳
