### ISSUE TITLE
Move `cross` configuration to Cargo.toml and `tools/cross`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3626]
We use [cross](https://github.com/cross-rs/cross) to cross compile ockam command binaries. 

Currently the configuration from cross lives in [Cross.toml](https://github.com/build-trust/ockam/blob/develop/Cross.toml), [Cross.Dockerfile.aarch64](https://github.com/build-trust/ockam/blob/develop/Cross.Dockerfile.aarch64) & [Cross.Dockerfile.armv7](https://github.com/build-trust/ockam/blob/develop/Cross.Dockerfile.armv7)

https://github.com/cross-rs/cross#configuration

1. We want to move the config in [Cross.toml](https://github.com/build-trust/ockam/blob/develop/Cross.toml) to [Cargo.toml](https://github.com/build-trust/ockam/blob/develop/Cargo.toml)
https://github.com/cross-rs/cross#option-1-configuring-cross-directly-in-your-cargotoml

2. We want to move [Cross.Dockerfile.aarch64](https://github.com/build-trust/ockam/blob/develop/Cross.Dockerfile.aarch64) & [Cross.Dockerfile.armv7](https://github.com/build-trust/ockam/blob/develop/Cross.Dockerfile.armv7) to `tools/cross` directory.
https://github.com/cross-rs/cross#dockerfiles

3. We want the FROM line in [Cross.Dockerfile.aarch64](https://github.com/build-trust/ockam/blob/develop/Cross.Dockerfile.aarch64) & [Cross.Dockerfile.armv7](https://github.com/build-trust/ockam/blob/develop/Cross.Dockerfile.armv7) to be pinned to the SHA of the base image

**Comment by duttaANI** [comment]
Hi @mrinalwadhwa . I wanted to confirm if the following is the base image https://hub.docker.com/r/kbushminkin/rust-aarch64-unknown-linux-musl since we have to calculate the SHA.

**Comment by mrinalwadhwa** [comment]
@duttaANI thank you for spending time on this.
No that is not the image.

The images are

- [ghcr.io/cross-rs/aarch64-unknown-linux-musl:0.2.4](https://github.com/cross-rs/cross/pkgs/container/aarch64-unknown-linux-musl/28076437?tag=0.2.4)
- [ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:0.2.4](https://github.com/cross-rs/cross/pkgs/container/armv7-unknown-linux-musleabihf/28076418?tag=0.2.4)

**Comment by duttaANI** [comment]
I am unable to resolve the following issue while running `$ cargo build`-

error: failed to parse manifest at `/home/aniruddha/Desktop/ockam/Cargo.toml`
Caused by:
  missing field `name` for key `package`
  
I have added the following lines to Cargo.toml -

[package.metadata.cross.target.aarch64-unknown-linux-musl]
dockerfile = "./tools/cross/Cross.Dockerfile.aarch64"
[package.metadata.cross.target.armv7-unknown-linux-musleabihf]
dockerfile = "./tools/cross/Cross.Dockerfile.armv7"

**Comment by mrinalwadhwa** [comment]
@duttaANI if you can create a draft PR with your changes, I can help diagnose why it may not be working.

**Comment by duttaANI** [comment]
Hi @mrinalwadhwa I have made a new review request with required changes [3714](https://github.com/build-trust/ockam/pull/3714)

**Comment by metaclips** [comment]
Do you want #3665 closed @duttaANI?

**Comment by duttaANI** [comment]
Hi @metaclips . I have created a new PR request [3714](https://github.com/build-trust/ockam/pull/3714) with the changes that you requested since 3665 was not up do date. Hence we can merge 3714 if this meets the requirements and close it.
