### ISSUE TITLE
Hacktoberfest - No Code - Try Ockam Command (CLI) and give user experience feedback

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3631]
We are trying to gather UX feedback on the first example of Ockam Command that is part of [our README](https://github.com/build-trust/ockam#readme).

Hacktoberfest is highlighting No Code contributions this year including testing and User Experience. We love that!

Here's how you can contribute to Ockam with user experience feedback.

1. Read [our README](https://github.com/build-trust/ockam#readme).
2. Try the below instructions.
3. Create a Github [Discussion](https://github.com/build-trust/ockam/discussions/new) adding an idea to improve the experience of using Ockam Command
4. Add yourself to Ockam [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.
5. We will mark this PR as `hacktoberfest-accepted` label to accept it as a hacktoberfest contribution.

Also try other sub commands but reading `ockam help`

---

# Give Feedback on User Experience

### Install Ockam Command

If you use Homebrew, you can install Ockam using `brew`.

```bash
brew install build-trust/ockam/ockam
```

Otherwise, you can download our latest architecture specific pre-compiled binary by running:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/build-trust/ockam/develop/install.sh | sh
```

After the binary downloads, please move it to a location in your shell's `$PATH`, like `/usr/local/bin`.

_The command only works on Linux and MacOS_

### End-to-End Trustful communication using Relays.

Let's build a solution for a very common topology. A application service and an application client running
in two private networks wish to communicate with each other without exposing ports on the Internet.

```bash
# Create a relay node that will relay end-to-end encrypted messages
ockam node create relay

# -- APPLICATION SERVICE --

# Start our application service, listening on a local ip and port, that clients
# would access through the cloud relay. We'll use a simple http server for our
# first example but this could be some other application service.
python3 -m http.server --bind 127.0.0.1 5000

# Setup an ockam node, called blue, as a sidecar next to our application service.
# Create a tcp outlet on the blue node to send raw tcp traffic to the application service.
# Then create a forwarder on the relay node to blue.
ockam node create blue
ockam tcp-outlet create --at /node/blue --from /service/outlet --to 127.0.0.1:5000
ockam forwarder create blue --at /node/relay --to /node/blue

# -- APPLICATION CLIENT --

# Setup an ockam node, called green, as a sidecar next to our application client.
# Then create an end-to-end encrypted secure channel with blue, through the relay.
# Then tunnel traffic from a local tcp inlet through this end-to-end secure channel.
ockam node create green
ockam secure-channel create --from /node/green --to /node/relay/service/forward_to_blue/service/api \
  | ockam tcp-inlet create --at /node/green --from 127.0.0.1:7000 --to -/service/outlet

# Access the application service though the end-to-end encrypted, secure relay.
curl 127.0.0.1:7000
```

If something breaks or if you'd like to start from the beginning as you try this example, please run `ockam reset`.

In this example, we enabled two applications, a python web server and a curl web client, to communicate with each other without exposing them to the internet and without any change to their code. These two applications can run in two separate private networks and communicate with each other over a relayed, end-to-end encrypted, mutually authenticated secure channel.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by h3athen** [comment]
Hello, I just posted a feedback and RP for this issue
PR: https://github.com/build-trust/ockam-contributors/pull/127
Discussion: https://github.com/build-trust/ockam/discussions/3638

**Comment by edelauna** [comment]
Very cool project, hoping to increase my Rust knowledge and contributions to open source community. 

Ran the example and posted my feedback: https://github.com/build-trust/ockam/discussions/3663
