### ISSUE TITLE
Remove deprecated set-output command in `Create Release Pull Request` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3644]
[Set-output command is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), we currently use said command in our workflow https://github.com/build-trust/ockam/blob/dd9088eb8ab7cb43da12896a66f16fdbfb81af1a/.github/workflows/create-release-pull-request.yml#L59 we should update command to [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

**Comment by Rishav-12** [comment]
Hey, can I pick this up?

**Comment by metaclips** [comment]
Sure 😀. Assigning you now.
