### ISSUE TITLE
Remove deprecated set-output command in `Documentation` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3645]
[Set-output command is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), we currently use said command in our workflow https://github.com/build-trust/ockam/blob/dd9088eb8ab7cb43da12896a66f16fdbfb81af1a/.github/workflows/documentation.yml#L62 we should update command to use [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

**Comment by bahelms** [comment]
I'd like to pick this up!

Do we want to move to using an environment variable or an [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)?

**Comment by metaclips** [comment]
> I'd like to pick this up!
> 
> Do we want to move to using an environment variable or an [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)?

Thanks @bahelms. Output parameter works just fine.

**Comment by metaclips** [comment]
I also updated the issue to indicate using output-parameter instead as that's much better
