### ISSUE TITLE
Remove deprecated set-output command in `Ockam Container Release` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3646]
[Set-output command is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), we currently use said command in our workflow here
https://github.com/build-trust/ockam/blob/dd9088eb8ab7cb43da12896a66f16fdbfb81af1a/.github/workflows/ockam-package.yml#L57 and here https://github.com/build-trust/ockam/blob/dd9088eb8ab7cb43da12896a66f16fdbfb81af1a/.github/workflows/ockam-package.yml#L129 we should update command to use [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

**Comment by Rishav-12** [comment]
Hey, can I take this one? 😃

**Comment by mrinalwadhwa** [comment]
@Rishav-12 of course, that would be great!
