### ISSUE TITLE
Remove deprecated set-output command in `Create Draft Release` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3647]
[Set-output command is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), we currently use said command in our workflow here
https://github.com/build-trust/ockam/blob/dd9088eb8ab7cb43da12896a66f16fdbfb81af1a/.github/workflows/release-binaries.yml#L159-L160  we should update command to use [output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

**Comment by bahelms** [comment]
I can pick this up :)
