### ISSUE TITLE
Elixir: refactor session options

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3653]
Currently we use `handshake` and `worker_mod` options to configure session workers for handshake and data stages in: 
https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam/lib/ockam/session/pluggable.ex
https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam/lib/ockam/session/pluggable/initiator.ex
https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam/lib/ockam/session/pluggable/responder.ex

This is inconsistent naming because both those options are modules.
We need to rename them in the init options passed to the session workers and in the internal state to something like `handshake_mod` and `data_mod`

Note: after https://github.com/build-trust/ockam/pull/3652 separate session is removed so this change is only relevant for `Ockam.Session.Pluggable.*` modules.

**Comment by davidag** [comment]
Hello! I was working on this issue but I'd like to make sure that you want to rename `worker_mod` to `data_mod`. I was wondering if `data_worker_mod` could be a better fit. I'm not familiar with the code, so I'll go with the option that you prefer @hairyhum. Thanks
