### ISSUE TITLE
ockam_abac docs build is failing

### ISSUE THREAD

**Issue by elpiel** [build-trust/ockam#3661]
It's seems that many if not all Docs.rs builds have failed to build ockam_abac due to missing `alloc`

> [INFO] [stderr] error[E0432]: unresolved import `alloc`
[INFO] [stderr]  --> src/policy.rs:6:5
[INFO] [stderr]   |
[INFO] [stderr] 6 | use alloc::vec;
[INFO] [stderr]   |     ^^^^^ help: a similar path exists: `std::alloc`

Here's the log from 0.10.0:
https://docs.rs/crate/ockam_abac/0.10.0/builds/633647

I haven't checked the source but I was going through the docs and found out about the issue.

**Comment by mrinalwadhwa** [comment]
@elpiel thank you for reporting this!!

**Comment by mrinalwadhwa** [comment]
For anyone looking into why this may be happening, the code of the crate is here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_abac

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa i will take this one

**Comment by mrinalwadhwa** [comment]
@michealkeines that would be great! Thank you

**Comment by michealkeines** [comment]
@mrinalwadhwa Please review my [PR](https://github.com/build-trust/ockam/pull/3666), Thank you

**Comment by elpiel** [comment]
> @elpiel thank you for reporting this!!

Always happy to help!

**Comment by elpiel** [comment]
> @elpiel thank you for reporting this!!

Always happy to help!

**Comment by adrianbenavides** [comment]
A potential fix was added https://github.com/build-trust/ockam/pull/3666 but it looks like it was not necessary.

**Comment by elpiel** [comment]
@adrianbenavides docs for abac still fails to build:

https://docs.rs/crate/ockam_abac/latest

Build logs from latest build (0.17) on 28th of March can be found here: https://docs.rs/crate/ockam_abac/0.17.0/builds/777415

```
compile_error!("NIST P-256 requires feature `rustcrypto`")
```

**Comment by SanjoDeundiak** [comment]
@elpiel, thanks for the contribution. We want to remove that feature at all for now, if you would like to pick that issue I described it here https://github.com/build-trust/ockam/issues/4704
