### ISSUE TITLE
CI: add commitlint to ockam-builder docker image and change commits github workflow

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3664]
Out commits workflow currently installs commitlint as part of the workflow and then uses it:

https://github.com/build-trust/ockam/blob/ac6bbb0e2add3485bd52e8021debf74d486aa2c5/.github/workflows/commits.yml#L76-L82

We want to move it to the ockam-builder docker image instead.
https://github.com/build-trust/ockam/blob/develop/tools/docker/builder/Dockerfile

Once it is part of the image, we'll want to change the [Lint Commit Messages workflow job](https://github.com/build-trust/ockam/blob/ac6bbb0e2add3485bd52e8021debf74d486aa2c5/.github/workflows/commits.yml#L76-L82) to run inside the builder image (like some of [our other workflow jobs](https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml#L95-L108))

**Comment by elpiel** [comment]
I'm going to pick this one up, because I'm already warmed up for CI :smile:

**Comment by metaclips** [comment]
Merged in https://github.com/build-trust/ockam/pull/3771
