### ISSUE TITLE
CLI commands to set ABAC policies for rust nodes.

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3671]
In order to control ABAC in Rust nodes we need to be able to create policies using this format: https://github.com/build-trust/ockam/pull/3639

Policies should have the rule definition and the action identifier for enforcement point to be able to find policy rules for a particular request.

Command would look something like this:
```
ockam policy set --action-id="echoer/handle_message" --rule="(= resource.something \"something\")" --on=node_green
ockam policy delete ...
```

@twittner please add more specifics about CLI command format and arguments

**Comment by twittner** [comment]
https://github.com/build-trust/ockam/pull/3695 has been opened to implement a basic CLI. The syntax is:

```
ockam policy get
    --at <node>
    -r | --resource <resource id>
    -a | --action   <action id>
```
It returns the policy expression or a 404 error.
```
ockam policy set
    --at <node>
    -r | --resource   <resource id>
    -a | --action     <action id>
    -e | --expression <policy expression>
```

Currently the set of possible resources and actions is static: As action only `handle_message` is meaningful and resources are supposed to be either `outlet` or `inlet`. This is an obvious limitation as one can imagine different policies for different outlets or inlets. However resource names can not always be derived from the current set of options (e.g. for inlets). Perhaps we want to allow a `resource` parameter to allow users to tag their resources?

**Comment by twittner** [comment]
https://github.com/build-trust/ockam/pull/3727 allows listing policies of a resource.
