### ISSUE TITLE
Add ockam sub command to create a vault without creating a node

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3683]
# Currently

We create a file based vault when a node is created.

```
ockam node create n1
cat ~/.config/ockam/vault.json
```

The json file contains serialized vault data.

This is how a simple file based vault can be created and then used to manage identities etc.

https://github.com/build-trust/ockam/blob/4659eed3b84d339d9590f9dca71d64dd62c15b90/implementations/rust/ockam/ockam_api/src/nodes/service/vault.rs#L38-L39

However currently we've set it up so a vault belongs to a node and is controlled by a service running in the node.

See:
- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs#L271-L276
- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service/services.rs#L21-L40

This is an artificial constraint created in the ockam_command and ockam_api crates. The `ockam` create allows creating any number of vaults - they can be file based or based on some cryptographic hardware.

# Desired

We want decouple management for vaults from nodes (when using ockam command)

```
ockam vault create v1
```

should create a new file based vault and place the file for it in

```
CONFIG_DIR/vaults/v1/vault.json
```

In separate issues we'll create commands to delete and list vaults, along with using vaults to create/manage identities and attaching vaults to a node.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa I will work on this one.

**Comment by mrinalwadhwa** [comment]
Awesome thank you! Let me know if you have any questions

**Comment by michealkeines** [comment]
Hi @mrinalwadhwa Please review my [PR](https://github.com/build-trust/ockam/pull/3716)
