### ISSUE TITLE
Add ockam sub command to create an identity without creating a node

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3684]
Related to #3683 

# Currently

We create a file based vault when a node is created.

```
ockam node create n1
ockam identity show --node n1

cat ~/.config/ockam/vault.json
cat ~/.config/ockam/identity.json
```

The json file contains serialized vault and idenity data.

This is how a simple file based vault can be created and then used to manage identities etc.

https://github.com/build-trust/ockam/blob/4659eed3b84d339d9590f9dca71d64dd62c15b90/implementations/rust/ockam/ockam_api/src/nodes/service/vault.rs#L38-L39

https://github.com/build-trust/ockam/blob/01e90778abb6a1c53afc6dcb47feafecfc972c90/implementations/rust/ockam/ockam_api/src/nodes/service/identity.rs#L32-L33

# Desired

After #3683 is addressed.

We want decouple management for identities from nodes (when using ockam command)

```
ockam vault create v1
ockam identity create i1 --vault v1
```

should create a new file based vault and place the file for it in

```
CONFIG_DIR/vaults/v1/vault.json
```

and then create an identity and place the file for it in:

```
CONFIG_DIR/vaults/v1/i1.json
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Abhicodes-crypto** [comment]
I would like to work on this issue.

**Comment by mrinalwadhwa** [comment]
This was added https://github.com/build-trust/ockam/pull/3773 thank you @Abhicodes-crypto
