### ISSUE TITLE
Add sub command `ockam authority create`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3688]

**Comment by JatinSingh08** [comment]
Hey @mrinalwadhwa , Can you please assign this to me. I would love to work on this.

**Comment by mrinalwadhwa** [comment]
@JatinSingh08 sorry we seemed to have missed your message. If you're still interested in contributing, we have many good first issues here https://github.com/build-trust/ockam/contribute

**Comment by mrinalwadhwa** [comment]
This command now exists
