### ISSUE TITLE
Remove hash bang multiple parameter in script

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3693]
Using multiple parameters in hashbang has been indicated as error prone across multiple platforms, more here https://www.shellcheck.net/wiki/SC2096 we should follow due practice across all our scripts. Bash scripts that use multiple parameters are
 https://github.com/build-trust/ockam/blob/01e90778abb6a1c53afc6dcb47feafecfc972c90/tools/scripts/release/crates-to-publish.sh#L1
https://github.com/build-trust/ockam/blob/01e90778abb6a1c53afc6dcb47feafecfc972c90/tools/scripts/release/changelog.sh#L1
https://github.com/build-trust/ockam/blob/01e90778abb6a1c53afc6dcb47feafecfc972c90/tools/scripts/release/crate-bump.sh#L1
https://github.com/build-trust/ockam/blob/01e90778abb6a1c53afc6dcb47feafecfc972c90/tools/scripts/release/crate-publish.sh#L1

**Comment by HyperNova114** [comment]
I would like to work on this

**Comment by mrinalwadhwa** [comment]
Closed in https://github.com/build-trust/ockam/pull/3697
Thank you @HyperNova114 🥳
