### ISSUE TITLE
Check the provider okta certificate when making https requests,  both on client and server code

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#3694]
We have the okta' tenant certificate available both on the server side i[dentity provider worker](https://github.com/build-trust/ockam/blob/f454b4a711c19dbb163acee45a1c34274b6be75a/implementations/rust/ockam/ockam_api/src/okta/mod.rs#L20) as well as in[ the client ](https://github.com/build-trust/ockam/blob/f454b4a711c19dbb163acee45a1c34274b6be75a/implementations/rust/ockam/ockam_command/src/service/config.rs#L66) .  But when contacting the okta' endpoint we aren't checking it

**Comment by adrianbenavides** [comment]
Do we know how do we want to do this (@mrinalwadhwa)? Some context here would be really helpful for me :pray:

**Comment by polvorin** [comment]
There is an implementation on https://github.com/build-trust/ockam/pull/3709  , but maybe can use some simplifications @adrianbenavides   (also,  would be ideal to check that all three things are correct `tenant` ,  `client_id`  and  `certificate`  on the config  command,  before sending it to the server,  to help users when configuring their project.  Let a TODO comment for that on the code).
@mrinalwadhwa   see the comments on that PR,   It requires we provide the *full*  certificate chain for pinning,  it is not enough to give the last one.
