### ISSUE TITLE
Add github action workflow to test our homebrew formula in multiple architectures / operating systems

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3696]
The homebrew formula lives here https://github.com/build-trust/homebrew-ockam

We want to run a workflow on new PRs to that repo that would check that the formula works in all 4 supported arch / os combinations.
https://github.com/build-trust/homebrew-ockam/blob/main/ockam.rb

It would be useful in PRs like this one.
https://github.com/build-trust/homebrew-ockam/pull/41

**Comment by memark** [comment]
I'll jump on this one.

~~Should this be a separate workflow? Or part of an existing? (The workflow structure is not clear to me.)~~
Never mind, it should reside in the other repo of course.
