### ISSUE TITLE
Configure Rust nodes to support Elixir ports

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3701]
Elixir Ockam nodes sometimes use Rust nodes to fill the gaps in the implementation. For example Identity and Credential Verifier services are delegated to Rust nodes.

Currently this means that there should be TCP-accessible Rust node deployed next to the Elixir node and there needs to be some orchestration to manage them. This if fairly simple if Elixir nodes are deployed with orchestration (like k8s), but makes it more challenging to do more portable deployments.

Elixir has [Ports](https://hexdocs.pm/elixir/1.13/Port.html) as a tool to integrate with external programs. This tool allows to start external programs from Elixir code and also lets Elixir processes to link with them, so they can be a part of the supervision trees.

We can start a Rust node from the Port, but currently when Port terminates the Rust node does not. This is because termination of the Port is communicated to external program by sending it the `EOF`.
The idea behind Ports is that they communicate with Elixir on `STDIN` and `STDOUT`. 

If we could have an argument we can add to the Rust node creation so it will monitor `STDIN` and terminate on `EOF` it should be easy enough to integrate Rust "sidecar" nodes as a part of Elixir nodes, simplifying deployment.

Another thing we can do is to add a `STDIN/STDOUT` transport protocol to leverage the Ports even more.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hairyhum** [comment]
I think the first step would be to add an argument to the `node create` command to make it listen on `STDIN` and terminate after receiving `EOF`, this argument should be probably somehow related to the `foreground` argument since it doesn't make much sense for background nodes.

**Comment by phillyphil91** [comment]
hey @hairyhum is this a rust only issue? if so, I would like to work on this

**Comment by mrinalwadhwa** [comment]
@phillyphil91 yes the following part is Rust only:

> I think the first step would be to add an argument to the node create command to make it listen on STDIN and terminate after receiving EOF, this argument should be probably somehow related to the foreground argument since it doesn't make much sense for background nodes.

I think the simple solution is when `ockam node create --foreground` then start reading from on STDIN and stop the node if `EOF` is received. We may not need an additional argument.

**Comment by phillyphil91** [comment]
thanks @mrinalwadhwa that sounds doable. let me have a look :smile:
