### ISSUE TITLE
Change references to new ockam-builder image

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3702]
The ockam-builder images is pinned by hash in many places in the code.

- https://github.com/build-trust/ockam/blob/develop/.devcontainer/Dockerfile#L1
- https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml#L45
etc.

There is now a new version of this image with sha256:

```
sha256:2b53a00493005871ab31c3e1e4e979fa76e21cd20bbc96773f25bd6b73d2a068
```

https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder/46609472?tag=latest

We have to find and replace all shas with the new one.

**Comment by Dark-Knight11** [comment]
I would like to work on this issue

**Comment by mrinalwadhwa** [comment]
@Dark-Knight11 awesome, all yours! let me know if you have questions.

**Comment by Dark-Knight11** [comment]
I have replaced the `e43dd94652096b03cc472a3c709c7335e8b166cab77b7a7b56f88fa38f3d24cc` hash with `2b53a00493005871ab31c3e1e4e979fa76e21cd20bbc96773f25bd6b73d2a068`

but this [link](https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder/46609472?tag=latest)  shows some other hashes. I'm little confused buy that, so lmk if I have to replace those hashes with some other value

**Comment by metaclips** [comment]
> I have replaced the `e43dd94652096b03cc472a3c709c7335e8b166cab77b7a7b56f88fa38f3d24cc` hash with `2b53a00493005871ab31c3e1e4e979fa76e21cd20bbc96773f25bd6b73d2a068`
> 
> but this [link](https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder/46609472?tag=latest) shows some other hashes. I'm little confused buy that, so lmk if I have to replace those hashes with some other value

Thanks @Dark-Knight11. The other hashes are used when you want to pull for a specific OS. We do not need to indicate the OS SHA as docker should pull for the right platform automatically.
<img width="688" alt="Screenshot 2022-10-22 at 12 13 18 AM" src="https://user-images.githubusercontent.com/31141573/197303810-b4d91afa-9c59-4098-9f9b-4baffd42438c.png">
