### ISSUE TITLE
Format all bash scripts using `shfmt`

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3722]
Bash scripts in our repositories currently fail [`shfmt`](https://github.com/mvdan/sh), we should properly format all script files. A working command is
```bash
shfmt -d ./**/*.sh | git apply
```
This should format all files automatically

**Comment by Dark-Knight11** [comment]
I'll like to work on this

**Comment by metaclips** [comment]
Thanks @Dark-Knight11. This issue already has a PR https://github.com/build-trust/ockam/pull/3726. Can you look into other CI issues?
