### ISSUE TITLE
Secure channel workers termination

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3731]
Currently secure channel responders stay alive even if initiator terminates. This means that a node which runs a secure channel listener spawning responders will have a lot of stale responders after a while.
Initiators may also stay around if responders terminate, but it's usually the node with responders which keeps accumulating them.

This is not too expensive resource-wise, but still uses some memory and makes it harder to manage workers.

We could implement some explicit termination signal, but it would not be triggered if a remote node terminates.
Alternatively we can introduce some sort of idle timeout, after which channel workers should terminate.

Cloud node has a cleanup tool which can do that, but it's not specific for secure channels: https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam_cloud_node/lib/cloud_node/cleanup.ex

**Comment by polvorin** [comment]
current secure channels have an idle_timeout after which they are terminated.   It's a workaround we will go for now
