### ISSUE TITLE
Fix `node_name` argument value on `ockam_command`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3732]
## Current

The `NodeOpts`'s `api_node` argument has the `id` attribute set, which also modifies the value name. Currently, a command's help using this argument looks like this:

```bash
$ ockam identity show --help
Options:
  -n, --node <node>
```

## Desired

We want to set the `value_name` to `NODE` so it's consistent with the rest of the arguments. To do that, we must add the `value_name` attribute to the `api_node` argument of the `NodeOpts` struct so it looks like:

```bash
$ ockam identity show --help
Options:
  -n, --node <NODE>
```

**Comment by Ashish0z** [comment]
I can work on this issue

**Comment by adrianbenavides** [comment]
All yours @Ashish0z !

**Comment by Mo-Fatah** [comment]
There has been no update for a while,  I wonder if I can work on this @adrianbenavides .

**Comment by etorreborre** [comment]
I was just preparing a PR for it :-)

**Comment by Mo-Fatah** [comment]
Great! I haven't started anyway. Good luck :smile:
