### ISSUE TITLE
Show "help" output when no args passed on `tcp connection` commands

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3740]
## Current

The `tcp connection` commands throw an error when no argument is passed showing to the user the missing fields.

## Desired

We want every command to be consistent and show the help output when no arguments are passed. To do that, the following attribute must be added to the [tcp-connnection commands](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection). For example:

```rust
#[command(arg_required_else_help = true)]
pub struct DeleteCommand {
...
}
```

**Comment by mushahidq** [comment]
Hi!

I would like to work on this. Do I need to just add the attribute to all the commands as shown in the example?

**Comment by adrianbenavides** [comment]
That's right! All yours :+1:
