### ISSUE TITLE
Hide `ExportCommandArgs` on short help output

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3741]
## Current

The arguments from `ExportCommandArgs` are always printed in the "help" output. These arguments may be of interest only under certain circumstances, so they end up cluttering the output most of the time.

## Desired

We want to reduce the amount of information shown in the short "help" output. To do that. the `hide_short_help(true)` must be added to all [`ExportCommandArgs`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/lib.rs#L223) arguments, so they are only printed on the long "help" output.

**Comment by Ill1** [comment]
Hi @adrianbenavides , I'm looking into this one.
