### ISSUE TITLE
Extract function to process `MultiAddr` on `forwarder|inlet create` commands

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3742]
## Current

On both [`forwarder create`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/forwarder/create.rs#L58-L71) and [`inlet create`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs#L65-L82) commands, we have a duplicated section of the code that modifies the `to` argument. This piece of code process a `MultiAddr` so that it replaces the node's names with their addresses or leaves them as they are if it's another type of address.

Examples: 

- if we have a node called `n1` and has the `127.0.0.1:1234` address associated, this code will return a new `MultiAddr` with value `/ip4/127.0.0.1/tcp/1234`
- now, if the input is `/project/p1` it will return `/project/p1`
- it also works with more complex addresses: `/project/p1/node/n1/serivce/echo` will return `/project/p1/ip4/127.0.0.1/tcp/1234/serivce/echo`

## Desired

- [ ] Extract the functionality into a static function on [./utils/mod.rs, after `extract_address_value`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/mod.rs#L487)
- [ ] Document function
- [ ] Add tests (you can use the [`extract_address_value` tests](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/mod.rs#L594) as reference) 

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Mo-Fatah** [comment]
Hi, can I work on this ?

**Comment by Mo-Fatah** [comment]
Can I work on this ?

**Comment by mrinalwadhwa** [comment]
@Mo-Fatah of course, all yours. Let us know if you have any questions.
