### ISSUE TITLE
CI - Fix shellcheck errors

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#3754]
In #3689 @elpiel added a shellcheck workflow. This is workflow is merged but currently disabled because it returns a lot of errors.

We want to fix this

```
shellcheck $(find . -iname "*.sh")
```

outputs:

https://github.com/build-trust/ockam/actions/runs/3334646032/jobs/5517818354

**Comment by akai54** [comment]
Should be closed ?

**Comment by mrinalwadhwa** [comment]
@akai54 ah yes, thank you for catching it.
