### ISSUE TITLE
Add tests for `vault create` command when `vault_name` arg is passed

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3763]
## Current

We have some tests covering the command when creating a vault for a given node (passing the `node` argument). We recently added a new argument `vault_name` that creates a vault that is not attached to any node.

## Desired

We want to add a test on the [commands.bats](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/tests/commands.bats#L150) file to cover this case.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by miles170** [comment]
Shouldn't `ockam vault create --vault-name` throw an error if a vault with the same name exists?

https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/vault/create.rs#L61

**Comment by adrianbenavides** [comment]
> Shouldn't ockam vault create --vault-name throw an error if a vault with the same name exists?

I've just saw your changes on your PR, it makes total sense to return that error :+1:
