### ISSUE TITLE
Missing crate repository for `signature_bls`

### ISSUE THREAD

**Issue by pinkforest** [build-trust/ockam#3864]
Re: https://github.com/fission-codes/fission-cli/issues/21

I was looking for crate `signature_bls` repository

Crate repository points here:
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/signature_bls

But this gives:
The 'build-trust/ockam' repository doesn't contain the 'implementations/rust/ockam/signature_bls' path in 'develop'.

I suspect the crate name has changed too considering this has changed around:
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam

All these new paths start with ockamn_ and maybe the crate has been renamed too ?

Reason I was looking for it as I was going to see if the `bls12_381_plus` could be bumped to ^0.7 so I can avoid transient dependency duplication with another crate that brings the latest at ^0.7

Maybe the new crate has bumped it but I can't seem to find a new crate for `signature_bls` ?

**Comment by pinkforest** [comment]
It still mentioned in some docos:

foobar@foobar-MS-7C77:~/play/ockam$ grep -R signature_bls *
```
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls [color=darkred];
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls -> signature_bbs_plus [color=darkred];
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls -> signature_ps [color=darkred];
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls -> ockam [color=darkred];
```

$ grep -R bls *
```
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls [color=darkred];
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls -> signature_bbs_plus [color=darkred];
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls -> signature_ps [color=darkred];
documentation/architecture/diagrams/ockam-crate-use.dot:signature_bls -> ockam [color=darkred];
implementations/rust/ockam/ockam_core/CHANGELOG.md:- Add ockam_core/bls feature and small fixes
implementations/rust/ockam/ockam_vault/CHANGELOG.md:- Remove bls support
implementations/rust/ockam/ockam_vault/CHANGELOG.md:- Add ockam_core/bls feature and small fixes
implementations/rust/ockam/ockam_ffi/CHANGELOG.md:- Remove bls support
implementations/rust/ockam/ockam_ffi/CHANGELOG.md:- Add ockam_core/bls feature and small fixes
implementations/rust/ockam/ockam_ffi/CHANGELOG.md:- clean up `ockam_ffi`'s handling of `bls` feature
implementations/rust/ockam/ockam_identity/CHANGELOG.md:- Add ockam_core/bls feature and small fixes
NOTICE:| bls12_381_plus                | Apache-2.0 OR MIT                                    | https://github.com/mikelodder7/bls12_381_plus                             |
```

It seems that the `signature_bls` crate has been abandoned going by "Remove bls support" ?

**Comment by mrinalwadhwa** [comment]
@pinkforest sorry about that confusion .. we didn't realize someone downstream was depending on it. As I mentioned https://github.com/decentralized-identity/did-key.rs/issues/38 and https://github.com/fission-codes/fission-cli/issues/21#issuecomment-1327989430 ... we're not maintaining it currently, what would be the best way to help you and your team?

**Comment by pinkforest** [comment]
Thanks - I've circled back at did-key: https://github.com/decentralized-identity/did-key.rs/issues/38#issuecomment-1327989962

**Comment by etorreborre** [comment]
Great, I am closing this issue then. Thanks @pinkforest for reporting it!
