### ISSUE TITLE
Configure node with CLI arguments instead of files

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3895]
Currently to set up node launch configuration for `ockam node create --launch-config=...` command there needs to be a JSON file pointed by the `--launch-config` argument.

In some setups of orchestration it could not be easy to create a file at location readable by the node.

The launch config file contains the JSON string, so it should be possible to pass this string as an argument to the node instead like this:

`ockam node create --launch-config-json="{\"startup_services\": ...}"

This should make it easier to use just the arguments to provision nodes with configuration.

**Comment by ebrightfield** [comment]
What do you think of this as a possible solution? In this fork: https://github.com/build-trust/ockam/compare/develop...ebrightfield:ockam:refactor/config_json_string

I chose to evaluate the `--launch_config` into an `Option<Config>` directly from the arguments, using a custom `value_parser`. The relevant part is at line 145 of the `create.rs`:
```
fn parse_launch_config(config_or_path: &str) -> anyhow::Result<Config> {
    let maybe_config: anyhow::Result<Config> = serde_json::from_str(config_or_path)
        .map_err(|_| anyhow!("Not a launch config JSON string"));
    if maybe_config.is_ok() {
        return maybe_config;
    }
    let path = PathBuf::from_str(config_or_path).map_err(|_| anyhow!("Not a valid path"))?;
    println!("{:?}", path);
    Config::read(path)
}
```
So far I've only tested it with an empty JSON object, but it worked.

**Comment by adrianbenavides** [comment]
Hey @ebrightfield, I think that's a pretty good solution! A small change that I'd do is to match the `serde_json::from_str(config_or_path)` to make the code easier to read, like:

```rust
fn parse_launch_config(config_or_path: &str) -> anyhow::Result<Config> {
    match anyhow::Result<Config> = serde_json::from_str(config_or_path)
        .map_err(|_| anyhow!("Not a launch config JSON string")) {
        Ok(c) => c,
        Err(_) => {
            let path = PathBuf::from_str(config_or_path).map_err(|_| anyhow!("Not a valid path"))?;
            Config::read(path)
        }
    }
}
```

Also, I'd say you can replace `.map_err(|_| anyhow!("..."))` by `.context("...")`.
