### ISSUE TITLE
`ockam_api`: refactor `request_controller` function to accept an optional `Identity`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3903]
## Current

The `request_controller` function creates a `secure_channel` to the passed `cloud_route`, but it's always using the node's default identity.

## Desired

In future PR's, the `ockam_api::cloud` endpoints will be modified so they include an optional `Identity`. For this PR, we'll just focus on adding a new argument to the `request_controller` to pass an optional `Identity`, which will be hardcoded to `None` for now. Then, in the `controller_secure_channel` function, it will prioritize the passed optional `Identity` if available, or default to the `self.identity()` if not.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
If there are no takers, I'd like to give this a shot.

**Comment by mrinalwadhwa** [comment]
@nidnogg that's awesome, all yours. Let us know if you have any questions.

**Comment by nidnogg** [comment]
Sweet! Quick newbie question that could expedite this:
Where exactly do I test `request_controller`? I'm still grokking ockam as a whole.

**Comment by nidnogg** [comment]
Added a [PR](https://github.com/build-trust/ockam/pull/3967) with some changes. Let me know if it's more or less an OK idea to solve the issue.

I had to rebase once and do some extra commits for `cargo fmt` for some failed checks. I can add a cleaner PR if it's the way to go - or the commits could be squashed instead.
