### ISSUE TITLE
`ockam_command`: add optional `--identity` argument to `CloudOpts`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3904]
Depends on: https://github.com/build-trust/ockam/issues/3903

## Desired

The scope of this issue is to just add a new argument to all the commands using the `CloudOpts`.
This argument will be named `identity`, of type `Option<String>`, and represents the alias/name
of an identity. It's basically the same `identity` argument we use in the `node create` command.

In future PR's, we will modify the requests' payloads to include this new field and use it on the
commands.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
Considering I picked up the #3903 issue, I figured I might take this as well to follow up if there isn't anyone onto it.

**Comment by mrinalwadhwa** [comment]
@nidnogg awesome. all yours.

**Comment by nidnogg** [comment]
I've added a [PR](https://github.com/build-trust/ockam/pull/3976) with proposed changes, although I'm not sure this is the actual scope of the issue as it seems very tiny to me. Fingers crossed for the checks 🤞

**Comment by adrianbenavides** [comment]
This issue has a small scope because it's the foundation for a series of follow-up issues like [this one](https://github.com/build-trust/ockam/issues/3905). The benefit of keeping it small is that those follow-up issues could be done in parallel without conflicts.

I'll review the PR shortly, thanks!
