### ISSUE TITLE
`command/api`: add field to `CreateProject` request to pass an optional identity name

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3905]
Depends on: https://github.com/build-trust/ockam/issues/3904

## Desired

Add a field called `identity_name` of type `<Option<String>` to the `CreateProject` struct. Then, on the `ockam_api/src/cloud/project::create_project` function replace the hardcoded `None` passed to the `request_controller` function with an `identity` build from the  `identity_name` field of the request using the `CliState`.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
I'll try my hand at following up on this from #3903 and #3904

**Comment by nidnogg** [comment]
Added a [PR](https://github.com/build-trust/ockam/pull/3977) with a possible fix to this. Let me know how it goes. Also, Merry Christmas! 🎄
