### ISSUE TITLE
add optional `--identity` argument to `secure-channel create` and modify implementation on `ockam_api`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3906]
## Desired

Add a new optional `--identity` argument to the `secure-channel create` command. This argument must be of type `Option<String>` (the identity name) and it will be sent "as is" to the node as part of the request, which must be modified to include this new field.

Additionally, the request handler on `ockam_api` must be refactored so it prioritizes the passed optional `Identity` if available, or default to the `self.identity()` if not.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Mo-Fatah** [comment]
I can work on this

**Comment by mrinalwadhwa** [comment]
@Mo-Fatah awesome, all yours.

**Comment by Mo-Fatah** [comment]
@adrianbenavides here 
> and it will be sent "as is" to the node as part of the request, which must be modified to include this new field.

I assume by the "request" you mean the [`api::create_secure_channel`](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L166), right ?

Also, the [request handler](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs#L39) on `ockam_api`  (correct me if I lost my way) , I couldn't find where exactly should I use the `identity` option from the request

**Comment by adrianbenavides** [comment]
> I assume by the "request" you mean the [`api::create_secure_channel`](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L166), right ?

Correct, it's the request struct that is used by that function: [CreateSecureChannelRequest](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs#L30). You could actually remove the `api::create_secure_channel` function and build the request in the command directly (we've been doing similar changes to other commands).
 
> Also, the [request handler](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs#L39) on `ockam_api` (correct me if I lost my way) , I couldn't find where exactly should I use the `identity` option from the request

So, you have to add a new argument to `CreateSecureChannelRequest` (the `identity_name` of type `Option<CowStr<'a>>`). Then, you have to modify the [create_secure_channel_impl ](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L87) method to use the request optional if passed, instead of always using the `self.identity()`.

Let me know if you have more questions!

**Comment by Mo-Fatah** [comment]
I am stuck at getting the identity - if provided - from the the `identity_name`. Specifically [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L87), I added the `identity_name : Option<CowStr<'_>>` parameter, but I couldn't figure out how to lookup an identity by it's name.

**Comment by adrianbenavides** [comment]
You need to use the [CliState](https://github.com/build-trust/ockam/blob/4036a7cdfe0de3e59ccb0cd6fd8a58970c9643e9/implementations/rust/ockam/ockam_api/src/cli_state.rs#L247): `CliState::new()?.identities.get(&identity_name)?;`. Is that what you need?

**Comment by Mo-Fatah** [comment]
This will get the `IdentityState` of this identity, while the required here is the `Identity<Vault>` type. Is there a direct  way to get the `Identity<Vault>` value from the `identity_name`, or from the `IdentityState` ? 

I tried poking around and I found the [`get`](https://github.com/build-trust/ockam/blob/4036a7cdfe0de3e59ccb0cd6fd8a58970c9643e9/implementations/rust/ockam/ockam_api/src/cli_state.rs#L309) function maybe relevant I think ? but it requires a `Context` parameter which isn't present in the logic of [`create_secure_channel_impl`](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L87)

**Comment by adrianbenavides** [comment]
> I tried poking around and I found the [`get`](https://github.com/build-trust/ockam/blob/4036a7cdfe0de3e59ccb0cd6fd8a58970c9643e9/implementations/rust/ockam/ockam_api/src/cli_state.rs#L309) function maybe relevant I think ? but it requires a `Context` parameter which isn't present in the logic of [`create_secure_channel_impl`](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L87)

You have it available two layers above that, so you would have to include it [here](https://github.com/build-trust/ockam/blob/b9861eaaf1de7a73117c9cae18ede8546767d0bb/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L491) and pass it down.
