### ISSUE TITLE
add optional `--identity` argument to `secure-channel-listener create` and modify the implementation  on `ockam_api`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3907]
## Desired

Add a new optional `--identity` argument to the `secure-channel-listener create` command. This argument must be of type `Option<String>` (the identity name) and it will be sent "as is" to the node as part of the request, which must be modified to include this new field.

Additionally, the request handler on `ockam_api` must be refactored so it prioritizes the passed optional `Identity` if available, or default to the `self.identity()` if not.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Mo-Fatah** [comment]
I can work on this

**Comment by hweawer** [comment]
I would like to help with this

**Comment by hweawer** [comment]
Or perhaps this issue is stale since https://github.com/build-trust/ockam/pull/4018 was merged
