### ISSUE TITLE
Replace default value for `node` arguments on every command by the actual default node name

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3931]
All the commands accepting a `node` argument (or an argument that references a background node), have a hardcoded default value (`"default"`). We now have a mechanism to retrieve the name of the default node: https://github.com/build-trust/ockam/blob/94e430867a5cc2245ac23e38350c41c95aefd3de/implementations/rust/ockam/ockam_api/src/cli_state.rs#L347

From the command side it would look like: `opts.state.nodes.default().config.name`.

We want to replace the hardcoded value with a call function that will return the default node name. We can do that using the Clap attribute `default_value_t = default_node_name()` (example [here](https://github.com/build-trust/ockam/blob/5ad7c89df71230b2ea4016f08d6f08fd2042245f/implementations/rust/ockam/ockam_command/src/service/start.rs#L26)). The `default_node_name` function could be added in the `ockam_command/src/node/util.rs` file.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Mo-Fatah** [comment]
I am working on this right now

**Comment by adrianbenavides** [comment]
All yours @Mo-Fatah , let me know if you have any questions!

**Comment by adrianbenavides** [comment]
We can improve a little bit the work done at https://github.com/build-trust/ockam/pull/3948 with the changes proposed at: https://github.com/build-trust/ockam/pull/3948/files#r1056592882

**Comment by adrianbenavides** [comment]
@Mo-Fatah you can have this one too if you want. Let me know if you are interested to assign it to you!

**Comment by Mo-Fatah** [comment]
Yes definitely I would love to keep working on this

**Comment by adrianbenavides** [comment]
Perfect, all yours then, thank you 🙏
