### ISSUE TITLE
Add CLI command to delete an identity

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3934]
Add a new command to delete an identity given its name.

A new `delete` method must be implemented for IdentitiesState that will delete the identity files and the symlink if it's the default identity.

This command should prevent the user from deleting the identity if it's being used by a node. You will have to list the nodes, and check for each one its default_identity (`opts.state.nodes.list()` + `node.config.default_identity`).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by ebrightfield** [comment]
Going to take a crack at this one, since I nearly have a PR ready for the `identity list` command and it's a related issue. Will let you know if/when I run into questions, still new to the codebase.

**Comment by adrianbenavides** [comment]
Perfect, thanks @ebrightfield. Let me know if I can help with anything!
