### ISSUE TITLE
Add CLI command to delete a vault

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3936]
Add a new command to delete a vault given its name.

A new `delete` method must be implemented for VaultsState that will delete the vault files, the symlink if it's the default vault, and it will delete itself from the identities' config where it's referenced on the `vault_name` field.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0x00A5** [comment]
I'd like to give it a shot. Could you please assign this issue to me?

**Comment by adrianbenavides** [comment]
Sure, all yours! Let me know if you need any help.

**Comment by adrianbenavides** [comment]
BTW, you can use this as a reference (it's the `identity delete` command): https://github.com/build-trust/ockam/pull/3949/files#diff-43f11edab03f464ca7f7b2e24df435684aebcd22f432c8b23f7c070a212e71a8

**Comment by 0x00A5** [comment]
Hi @adrianbenavides, a few questions regarding the following
> it will delete itself from the identities' config where it's referenced on the `vault_name` field
1. When [creating an identity](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/create.rs#L34), it doesn't seem that the `value_name` is included as part of the `IdentityConfig`. Should I add it? Or am I missing someting?
2. When deleting a vault, we should also delete the identities that use the vault, correct?
3. Do you think it is worth letting the vault state to keep track of the identities that use it (so that we don't have to read all identities' configs)?

**Comment by adrianbenavides** [comment]
> Hi @adrianbenavides, a few questions regarding the following
> 
> > it will delete itself from the identities' config where it's referenced on the `vault_name` field
> 
> 1. When [creating an identity](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/create.rs#L34), it doesn't seem that the `value_name` is included as part of the `IdentityConfig`. Should I add it? Or am I missing something?

My fault! Ignore this part, we ended up not including this information on the identity.

> 2. When deleting a vault, we should also delete the identities that use the vault, correct?

Yes, that's right. There is a cascade of checks here:
- To check whether an identity must be removed, it must be able to be loaded using the vault you want to delete. If it fails to be loaded, then you just skip it.
- Before removing the identity, if it's being used by a node, then you must abort the delete operation and leave the state unmodified (no vaults or identities deleted). This is currently done [in the `identity delete` command](https://github.com/build-trust/ockam/blob/dd2a410c91ed9c64b7dc5cce1ec71dd735802943/implementations/rust/ockam/ockam_command/src/identity/delete.rs#L20-L30) but should be moved [to the `CliState` here](https://github.com/build-trust/ockam/blob/dd2a410c91ed9c64b7dc5cce1ec71dd735802943/implementations/rust/ockam/ockam_api/src/cli_state.rs#L308).

> 3. Do you think it is worth letting the vault state to keep track of the identities that use it (so that we don't have to read all identities' configs)?

We want to avoid having that coupling as it will only make things hard to maintain (i.e. you have to constantly watch for changes to keep the vaults' state updated, instead of just reading the information from the FS when you need it). We come from a configuration architecture where we had all the information in config files, and it was very easy to introduce bugs and to run into race-condition problems when reading/updating those files.
