### ISSUE TITLE
Refactor `identity show`  command to stop retrieving identity from background node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#3937]
Currently, the `identity show` command accepts a `node_opts` argument. This argument should be replaced with an argument called `name` that will reference an **identity** name.

Then, instead of doing an RPC call to a background node, this command will retrieve the given identity from the CLI state (`opts.state.identities.get(name)`) and build the response as it's done [here](https://github.com/build-trust/ockam/blob/9962c907994c3d1abf1d41ebd91b26744a0e0aad/implementations/rust/ockam/ockam_api/src/nodes/service/identity.rs
).

We also want to remove the request handlers related to `identities` from the NodeManager. This means removing the `ockam_api/src/nodes/service/identity.rs` file and the handlers at:

https://github.com/build-trust/ockam/blob/9962c907994c3d1abf1d41ebd91b26744a0e0aad/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L462-L467

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by miles170** [comment]
I'm working on this.

@adrianbenavides How do I determine the identity name of node? (`node show` not showing identity name)

**Comment by adrianbenavides** [comment]
Hey @miles170, I'm not sure I understand your question, but you don't need any information about the node. You can get the identity calling `opts.state.identities.get(name)` and build the response with what that method returns. Does that help?

**Comment by miles170** [comment]
If I have to change the following test code, I have to know the identity name of the node, right?

```
@test "create a node and show its identity" {
  run $OCKAM node create n1
  assert_success

  run $OCKAM identity show --node n1
  assert_success
  assert_output --regexp '^P'
}
```

**Comment by adrianbenavides** [comment]
Nope, the `--node` argument must be removed and add a new one to pass an identity name. So, to refactor that test, you first have to create an identity with an explicit random name, and then run the `show` command using that identity name.

To give you some context, the main idea behind this issue is to stop using a background node to fetch the information about an identity.

**Comment by miles170** [comment]
How about following test, would it need to know the identity name of the node?
Or just remove it?

```
@test "inlet/outlet example with credentials" {
  skip_if_orchestrator_tests_not_enabled

  $OCKAM project information default --output json > /tmp/project.json

  OCKAM_HOME=/tmp/ockam/green
  run $OCKAM node create green --project /tmp/project.json
  assert_success
  green_identifier=$($OCKAM identity show -n green)

  OCKAM_HOME=/tmp/ockam/blue
  run $OCKAM node create blue --project /tmp/project.json
  assert_success
  blue_identifier=$($OCKAM identity show -n blue)

  unset OCKAM_HOME
  run $OCKAM project enroll --member $blue_identifier --attribute role=member
  assert_success
  run $OCKAM project enroll --member $green_identifier --attribute role=member
  assert_success
}
```
