### ISSUE TITLE
Secure channel negotiation for stream service topics

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3965]
Follow up to https://github.com/build-trust/ockam/issues/3964

### Background
Ockam Forwarding mechanisms allow to connect remote endpoints using some predefined naming schema: https://github.com/build-trust/ockam/tree/develop/documentation/use-cases/secure-remote-access-tunnels
This allows nodes to negotiate secure channels using some predefined named routes.

In case of stream service messaging, there could be multiple endpoints consuming messages for different partitions of the topic.

### Scope
In stream messaging each partition of the topic is read by a consumer sequentially. If we assume that there is only one consumer reading from a topics partition (which is the case for stream ingress scenario), we can address consumer as a topic partition. This provides a good enough forwarder address schema to communicate between consumer and producer endpoints.

**Multiple consumers reading the same partitions is still a valid scenario, but is out of scope at least until secure channels can negotiate group keys**

### Addressing schema and secure channel discovery

We can use the following address schema for the forwarder aliases:
`<topic>:<partition>`
then if we have a static forwarding service with prefix `forward_to_` the forwarder addresses will be:
`forward_to_<topic>:<partition>`

For example when we're communicating via topic `mytopic` and partition 1, the forwarding alias would be `mytopic:1` and forwarding address would be `forward_to_mytopic:1`

### Application setup and channel negotiation

In a scenario when we need to communicate encryptor and decryptor for a topic `mytopic` and partitions `1` and `2` (for example for kafka message encryption https://github.com/build-trust/ockam/issues/3964)

- Consumer will need to start a secure channel listener for each partition it consumes from (in this case `mytopic:1` and `mytopic:2`)
- Consumer needs to create a forwarder on the cloud node for each secure channel listener it created with aliases `mytopic:1` and `mytopic:2`
- When producer needs to publish a message to `mytopic:1` it should negotiate a secure channel using the route to the cloud worker `forward_to_mytopic:1` (assuming default `forward_to_` prefix)
- This secure channel can be cached on the producer side as a secure channel for `mytopic:1` to send all this topic messages through the same channel

### Potential minor improvements

- There could be a separate forwarding service created for topics only with some meaningful prefix like `consumer_` instead of `forward_to_`

### Currently not addressed. TODO in the future

- Group key negotiation for multiple consumers reading from the same topic
- Message loss on secure channel interruptions (if secure channel key is lost)
- Secure channel restarts
- Separating consumers from secure channel negotiating nodes (to allow consumer restarts without secure channel interruption)

**Comment by hairyhum** [comment]
@davide-baldo I believe that was addressed. Can you confirm?

**Comment by davide-baldo** [comment]
Yes it's done!
