### ISSUE TITLE
Manage rust identity sidecar using Elixir ports

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#3988]
Follow-up to https://github.com/build-trust/ockam/issues/3701

Now when we have an option to run rust nodes as Elixir ports, we can use it to run identity service as a port to make it easier to provision Elixir nodes.

Currently there needs to be a rust node with services configuration: `{"startup_services":{"identity":{},"vault":{},"verifier":{}}}` to enable identity service and credential verifier service.

With Elixir port support #3701 , there can be a port started as `ockam node create --exit-on-eof -vv -f --tcp-listener-address=127.0.0.1:4100 --launch-config={"startup_services":{"identity":{},"vault":{},"verifier":{}}} sidecar` to run this node as a part of Elixir node.

**Comment by polvorin** [comment]
In the process of getting rid of identity sidecar
