### ISSUE TITLE
ockam secure-channel list command shows invalid route message

### ISSUE THREAD

**Issue by mszpakowski** [build-trust/ockam#3989]
After creating a secure channel from the inlet to the outlet through a forwarder (both on local and orchestrator node), the `ockam secure-channel list` command shows `Invalid route received from show channel response` message.

Steps to reproduce:
```bash
$ ockam node create relay

$ ockam node create blue
$ ockam tcp-outlet create --at /node/blue --from /service/outlet --to 127.0.0.1:5000
$ ockam forwarder create blue --at /node/relay --to /node/blue

$ ockam node create green
$ ockam secure-channel create --from /node/green --to /node/relay/service/hop/service/forward_to_blue/service/api \
    | ockam tcp-inlet create --at /node/green --from 127.0.0.1:7000 --to -/service/outlet

$ ockam secure-channel list --at green

> Secure Channels
Invalid route received from show channel response -- 1#127.0.0.1:59325 => 0#hop => 0#forward_to_blue => 0#api
```

**Comment by 0x00A5** [comment]
I can dig into this. Do you mind assigning this issue to me please?

**Comment by 0x00A5** [comment]
@mszpakowski, sorry for the delay, I just tried the commands in the issue description, and I only got
```
Failed to receive response from node

Caused by:
    0: deadline has elapsed
    1: deadline has elapsed
```
when creating the secure channel. 
Is the command correct in the description? (BTW, there seem to be an extra dash in the `secure-channel create` command in the description)

**Comment by mszpakowski** [comment]
@0x00A5 The implementation changed a little bit since I created the issue. I've updated the steps to reproduce.

> BTW, there seem to be an extra dash in the secure-channel create command in the description

The dash is there by design.

The first command's (`ockam secure-channel create --from /node/green --to /node/relay/service/hop/service/forward_to_blue/service/api`) stdout is the address to the secure channel:
https://github.com/build-trust/ockam/blob/6b9ea619cd3ab9563faa339a16cb498e3e5304dd/implementations/rust/ockam/ockam_command/src/secure_channel/create.rs#L93-L95

This value is piped to the second command as stdin. The dash in the second command substitutes the value from the stdin. 

So:
```
$ ockam secure-channel create --from /node/green --to /node/relay/service/hop/service/forward_to_blue/service/api \
    | ockam tcp-inlet create --at /node/green --from 127.0.0.1:7000 --to -/service/outlet
```
is equivalent to:
```
$ ockam secure-channel create --from /node/green --to /node/relay/service/hop/service/forward_to_blue/service/api
> /service/<address>
$ ockam tcp-inlet create --at /node/green --from 127.0.0.1:7000 --to /service/<address>/service/outlet
```
