### ISSUE TITLE
Use global default shell in `create-release-pull-request.yml` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3995]
To remove the need to repeat default shell declaration in our workflow, we should set a global default so that it is available across all jobs in https://github.com/build-trust/ockam/blob/cdf925aa2adb4439061449e5ea5f9ad774833e20/.github/workflows/create-release-pull-request.yml#L1 
More here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

**Comment by rghdrizzle** [comment]
Hey @metaclips I would like to work on this similar issue, also if there are any other workflow which does need to be changed the same way do let me know .

**Comment by metaclips** [comment]
@rghdrizzle please go ahead, assigned to you
