### ISSUE TITLE
Use global default shell in `documentation.yml` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#3997]
To remove the need to repeat default shell declaration in our workflow, we should set a global default so that it is available across all jobs in https://github.com/build-trust/ockam/blob/cdf925aa2adb4439061449e5ea5f9ad774833e20/.github/workflows/documentation.yml#L1 
More here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Miidoriya** [comment]
Hi, I'd like to help on this if possible. It would be my first contribution to open source

**Comment by metaclips** [comment]
> Hi, I'd like to help on this if possible. It would be my first contribution to open source

🎉 nice! Assigning task to you now. Do ping me if anything

**Comment by Miidoriya** [comment]
Thanks, quick question @metaclips . There appears to only be one shell declaration on line 50. Is the intention to create a default for this to use which subsequent jobs in this file may leverage?

**Comment by metaclips** [comment]
> Thanks, quick question @metaclips . There appears to only be one shell declaration on line 50. Is the intention to create a default for this to use which subsequent jobs in this file may leverage? 

💯 exactly

**Comment by Miidoriya** [comment]
Hey again @metaclips , I don't appear to have the correct perms for either creating a branch (in UI) or pushing changes locally from a newly created branch?

**Comment by mrinalwadhwa** [comment]
@Miidoriya thank you for taking time to contribute.

We follow the Github Fork and Pull Request workflow to accept contributions.

For this you don't need permissions on the main repo, your first fork the repo. You would then have full permissions on your fork where you can create a branch to work on this change.

When you're ready you can create a pull request to the main repo from a branch on your fork.

There are step by step instructions for this here
https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by Miidoriya** [comment]
Nice, thanks for sharing @mrinalwadhwa

**Comment by Miidoriya** [comment]
After a PR is created is there any prompting that needs doing by myself like marking this task as done for example? @metaclips @mrinalwadhwa

**Comment by metaclips** [comment]
Hello @Miidoriya I left reviews for you on your PR https://github.com/build-trust/ockam/pull/4169

**Comment by metaclips** [comment]
> After a PR is created is there any prompting that needs doing by myself like marking this task as done for example? @metaclips @mrinalwadhwa

You need to sign a CLA on the ockam-contributors repository https://github.com/build-trust/ockam-contributors, aside signing the CLA and PR review, you should be good for a merge.
