### ISSUE TITLE
Use global default shell in `ockam-package.yml` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4001]
To remove the need to repeat default shell declaration in our workflow, we should set a global default so that it is available across all jobs in https://github.com/build-trust/ockam/blob/cdf925aa2adb4439061449e5ea5f9ad774833e20/.github/workflows/ockam-package.yml#L1 
More here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

**Comment by rghdrizzle** [comment]
Hey @metaclips this issue is similar to the previous one which I worked , will I take on this too?

**Comment by metaclips** [comment]
Yup, go for it 🚀
