### ISSUE TITLE
Use global default shell in `semgrep.yml` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4008]
To remove the need to repeat default shell declaration in our workflow, we should set a global default so that it is available across all jobs in https://github.com/build-trust/ockam/blob/cdf925aa2adb4439061449e5ea5f9ad774833e20/.github/workflows/semgrep.yml#L1 
More here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

**Comment by rghdrizzle** [comment]
Hey @metaclips I would like to work on this .

**Comment by metaclips** [comment]
Nice @rghdrizzle. Seems this issue is outdated as we've collapsed this workflow into the [All - workflow](https://github.com/build-trust/ockam/blob/ac5f367a746a62f20d9e5657628e49ebe56d5274/.github/workflows/all.yml#L294). Want to take this issue up instead https://github.com/build-trust/ockam/issues/4005?

**Comment by mrinalwadhwa** [comment]
Fixed here https://github.com/build-trust/ockam/blob/develop/.github/workflows/all.yml#L294
