### ISSUE TITLE
Use global default shell in `shfmt.yml` workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4010]
To remove the need to repeat default shell declaration in our workflow, we should set a global default so that it is available across all jobs in https://github.com/build-trust/ockam/blob/cdf925aa2adb4439061449e5ea5f9ad774833e20/.github/workflows/shfmt.yml#L1 
More here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaults

**Comment by RishiKumarRay** [comment]
@metaclips can i go for all these issues, they looks to be similar to what i did?

**Comment by metaclips** [comment]
Thanks @RishiKumarRay. I'll assign this to you now and then we can take others up subsequently.

**Comment by RishiKumarRay** [comment]
@metaclips please review this 
https://github.com/build-trust/ockam/pull/4014

**Comment by RishiKumarRay** [comment]
@metaclips please help to review this PR against the issue 
set default shell to bash in shfmt workflow #4021
