### ISSUE TITLE
Kafka portals commands/service

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#4012]
In order to enable kafka portals https://github.com/build-trust/ockam/issues/3963 there needs to be a CLI command OR a service to start consumer and producer sides of the kafka portal.

It should be configured with:

Consumer:
- IP to listen on
- Port (or port range) to listen on, port range is used for [broker port mapping](https://github.com/build-trust/ockam/issues/4011)
- Forwarding address of the consumer on the project node (may use project prefix)
- (optional) route to tunnel client listener service, could use default if project is configured

Producer:
- IP to listen on
- Port (or port range) to listen on, port range is used for [broker port mapping](https://github.com/build-trust/ockam/issues/4011)
- Forwarding address of the consumer on the project node (may use project prefix)
- (optional) route to tunnel client listener service, could use default if project is configured

**Comment by adrianbenavides** [comment]
I initially thought that this issue also included the development of the services. Is there a separate issue for that?

**Comment by hairyhum** [comment]
> I initially thought that this issue also included the development of the services. Is there a separate issue for that?

There are components to be integrated in the service, which are not ready yet, https://github.com/build-trust/ockam/issues/3963 describes the base approach to develop those components.

Let's keep this issue open until we're ready to assemble them into a service which is started by these commands.

**Comment by hairyhum** [comment]
Addressed in #4105
