### ISSUE TITLE
`ockam_command`: show human-readable datetime format on `Identity` output

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4019]
https://github.com/build-trust/ockam/pull/3912/files#r1059714310

The `enrolled` timestamp is shown in POSIX format. We should consider changing this to a human-readable format.

**Comment by hargut** [comment]
Hi @adrianbenavides,

disabling default-features of the time crate resolved the problem with the no_std rust checks within the workflow.


Best regards,
Harald
