### ISSUE TITLE
Issue compiling on windows

### ISSUE THREAD

**Issue by waqasraz** [build-trust/ockam#4029]
I was trying to run an [example ](https://github.com/build-trust/ockam/tree/develop/documentation/use-cases/secure-remote-access-tunnels)on windows and got this.

```
error[E0433]: failed to resolve: could not find `unix` in `os`
   --> C:\Users\waqas\.cargo\registry\src\github.com-1ecc6299db9ec823\ockam_vault-0.66.0\src\storage\file_storage.rs:105:22
    |
105 |         use std::os::unix::prelude::*;
    |                      ^^^^ could not find `unix` in `os`

```

**Comment by mrinalwadhwa** [comment]
@waqasraz Thank you for filing this 🙏

A quick note for anyone looking into the issue.
* I think the minimal fix is we should only compile file storage in the vault crate only if we're on unix. The will make all our Rust example work on windows.
* A better fix would be to the file storage work across unix and windows.

**Comment by waqasraz** [comment]
I am still trying to figure out what I am doing, but doing this change is passing the tests. If this is okay, can I create a PR?

![image](https://user-images.githubusercontent.com/1761304/210689174-09c71871-6092-49ce-8cd8-bb5c69fc7675.png)
