### ISSUE TITLE
API to get Ockam Project node version

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4049]
Create an API on the Elixir side that retrieves the current Ockam project node version

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by lordB8r** [comment]
I'm an Elixirist and would love to contribute, if you think this would be a good place to start.

**Comment by hairyhum** [comment]
@lordB8r this issue involves some version management, we’re still considering our options on how we may want to expose project node versions.
Here are some better we to start with:
https://github.com/build-trust/ockam/issues/3988
https://github.com/build-trust/ockam/issues/3797 
https://github.com/build-trust/ockam/issues/3654
https://github.com/build-trust/ockam/issues/4238

**Comment by hairyhum** [comment]
Moved to https://github.com/build-trust/ockam-orchestrator/issues/1
