### ISSUE TITLE
command: add new CLI command to retrieve the project's version

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4050]
Depends on https://github.com/build-trust/ockam/issues/4062

We want to add a new command that retrieves the version of a given project.

- Add new command in [`ockam_command::project`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/project) named `ockam project version {name}` that sends a request to the API developed at https://github.com/build-trust/ockam/issues/4062 that outputs the project version
- Add test in the [`commands.bats`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/tests/commands.bats) file

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by bharattech** [comment]
Hi,

May I please start working on this issue?

**Comment by etorreborre** [comment]
Hi @bharattech yes, please do

**Comment by bharattech** [comment]
Hey @etorreborre ,

Thank you for the opportunity! 
I've already begun working on the issue and will keep you updated on the progress.

**Comment by bharattech** [comment]
Hey Eric @etorreborre ,

Need your help: Please take a look at function **get_project_version_response** from [/implementations/rust/ockam/ockam_api/src/cloud](https://github.com/build-trust/ockam/blob/8b5a46dc90355843593f44a568beb241b677aba9/implementations/rust/ockam/ockam_api/src/cloud/project.rs#L390C29-L390C57)

The Request get path is empty.

Let me know your thoughts

**Comment by etorreborre** [comment]
You need to try it out but it is possible that an empty path is valid and corresponds to [this endpoint definition on the Orchestrator side](https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam_services/lib/services/api/node_info_api.ex#L46).
