### ISSUE TITLE
command/api: add API endpoint to retrieve the Ockam Orchestrator version

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4052]
Depends on https://github.com/build-trust/ockam-orchestrator/issues/22

We want to add a new API endpoint to the `NodeManager` that retrieves the Ockam Orchestrator version.

- Add a new method at [`ockam_api::cloud`](https://github.com/build-trust/ockam/blob/adcdb411c5f9c086f17c78cee071a7eec68f4763/implementations/rust/ockam/ockam_api/src/cloud/mod.rs) to send a request to the Ockam Orchestrator to retrieve its version
- Add the API endpoint to the [`NodeManager`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L614) so it can be accessible from the CLI

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
Could this be done without solving the Elixir issue (https://github.com/build-trust/ockam-orchestrator/issues/22)? If so, I could take this one

**Comment by chanman3388** [comment]
@nidnogg You still wanting to have a stab at this?

**Comment by mariannegoldin** [comment]
Hello, I am working with a team who might be interested in picking up this issue - the caveat being that it might take us a little longer to complete it. Is it still available to take? Thanks!

**Comment by nidnogg** [comment]
hey there @chanman3388, sorry for the late ping! In the sibling elixir issue thread someone pinged me back regarding it was necessary so I moved on to other issues. This should be free for anyone to delve into

**Comment by paul-w42** [comment]
Hi, we have a small team that would like to take this on if it is still available.  Can you direct us though, where do we derive the Orchestrator version number from?  Is it the same as the Ockam Command Version?  

Thanks, Paul

**Comment by etorreborre** [comment]
Hi @paul-w42 there is a PR that was started for this: https://github.com/build-trust/ockam/pull/4617, and then a better draft here: https://github.com/build-trust/ockam/pull/4847. I am not sure if that's enough for you to get started though.

**Comment by paul-w42** [comment]
> Hi @paul-w42 there is a PR that was started for this: #4617, and then a better draft here: #4847. I am not sure if that's enough for you to get started though.

Thank you, we will take a look.

**Comment by mariannegoldin** [comment]
Hi @etorreborre thanks so much for taking the time to share these related PRs, the examples are useful.

I am providing some facilitation to the team working on this issue and wanted to get some clarification (@paul-w42 will be your point of contact for development). 

It looks like #4847 is the pre-requisite work, factoring out the orchestrator using the builder pattern; and then #4617 is using this improvement to print out some data to stdout (`println`) via the orchestrator ockam command CLI. 

My question is: does it make sense for the team to introduce some internal implementations for fetching the version in [NodeManager](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L614) as indicated in this feature description?

Some benefits to this:
* It would enable the Ockam API and CLI to return a version number
* It would follow single responsibility principle in enabling `NodeManager` to own reporting on its version number; it seems that we can then pass this info up via the context/other callers and return it in places like the Orchestrator CLI in #4617.

Lmk if this approach aligns with your goals. Thank you!

**Comment by etorreborre** [comment]
I would suggest for now to reuse the `OrchestratorApiBuilder` inside the `ockam_crate` command to at least get a first implementation to work. That would already be really helpful for our processes! 

Then we can always refactor the code to move it to `ockam_api` in a follow-up PR. At this stage I don't what that entails in terms of code dependencies and how much has to move.

**Comment by mariannegoldin** [comment]
Thanks! To make sure I understand our path forward, sounds like it is ok,
in that case, to use the two PRs referenced above in our PR against the
develop branch (meaning we won’t be rebasing off those PRs).

Please let me know if that’s not true / if we should rebase off the two PRs
above.

**Comment by etorreborre** [comment]
Yes exactly, take these PRs as an inspiration for your own :-)

**Comment by adrianbenavides** [comment]
We have the `project version --output json` command that outputs the orchestrator and project versions.
