### ISSUE TITLE
command/api: add field to `CloudRequestWrapper` struct to pass an optional identity name

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4056]
## Current

Currently, a `NodeManager` instance will use its internal identity/vault pair for every request it does to the cloud nodes (i.e. all the methods under [`ockam_api::cloud`](https://github.com/build-trust/ockam/tree/fa3728544bf0ceeb231fae61503b29a70f00cb70/implementations/rust/ockam/ockam_api/src/cloud)).

At https://github.com/build-trust/ockam/issues/3905 (solved at https://github.com/build-trust/ockam/pull/3977) the `identity_name` was added to the `CreateProject` struct, so we can use a custom identity on the `project create` command. We want to extend that behaviour to every cloud endpoint. 

## Desired

Instead of having to modify all the requests structs, we want to modify the higher-level [`CloudRequestWrapper`](https://github.com/build-trust/ockam/blob/fa3728544bf0ceeb231fae61503b29a70f00cb70/implementations/rust/ockam/ockam_api/src/cloud/mod.rs#L31) to include the optional `identity_name` field so we can access to it from every cloud endpoint.

To keep the scope of this issue limited, we'll just add the new field to `CloudRequestWrapper` and a new argument to [`BareCloudRequestWrapper::bare`](https://github.com/build-trust/ockam/blob/fa3728544bf0ceeb231fae61503b29a70f00cb70/implementations/rust/ockam/ockam_api/src/cloud/mod.rs#L60). In a future issue, we'll refactor those two types to improve the ergonomics.

Finally, we'll need to remove the `identity_name` field from the [`CreateProject`](https://github.com/build-trust/ockam/blob/fa3728544bf0ceeb231fae61503b29a70f00cb70/implementations/rust/ockam/ockam_api/src/cloud/project.rs#L266) struct to read the `identity_name` value from the `CloudRequestWrapper` instead.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
Hey there! Might as well keep going on this one. I'll have a shot at it later on today if nobody's started anything yet.

**Comment by adrianbenavides** [comment]
Sure, all yours! Let me know if you need help along the way

**Comment by nidnogg** [comment]
PR added with a possible solution: https://github.com/build-trust/ockam/pull/4113
