### ISSUE TITLE
command: add new CLI command to retrieve the Ockam Orchestrator version

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4063]
Depends on https://github.com/build-trust/ockam/issues/4052

We want to add a new command that retrieves the version of a given project.

- Add new command in `ockam_command::cloud` named `ockam cloud version` that sends a request to the API developed at https://github.com/build-trust/ockam/issues/4052 that outputs the Ockam Orchestrator version
- Add test in the [`commands.bats`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/tests/commands.bats) file

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by chanman3388** [comment]
@adrianbenavides May I take this one?

**Comment by adrianbenavides** [comment]
Unfortunately, this is not read to pick up yet, as it depends on a development that must be done on the cloud side.
