### ISSUE TITLE
`ockam node start` command: set default value to `node` argument using `Clap` attributes 

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4080]
Currently, the optional `node` field is an `Option<String>`. When is `None` (i.e. the argument is not passed), it defaults to the default node name. This is done [here](https://github.com/build-trust/ockam/blob/7511258aa3785056a7bfeadf22debd6033f43b40/implementations/rust/ockam/ockam_command/src/node/start.rs#L31-L34).

We want to change how the argument is set up so this transformation is done under the hood by `Clap`. This can be done by defining the argument as follows:

```rust
#[arg(default_value_t = default_node_name())]
node_name: String,
```

And modifying the `default_node_name` so it doesn't receive any argument and, instead, build a new `CliState::new()` instance to retrieve the default node name.

More context [in this comment](https://github.com/build-trust/ockam/pull/3948/files#r1056592882).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout issues labeled -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by raysonkoh** [comment]
Hey @adrianbenavides, is it okay if I take a stab at this issue? :)

**Comment by adrianbenavides** [comment]
Sure, all yours!

**Comment by raysonkoh** [comment]
To clarify, do you want to update the existing `default_node_name` function or create a new function that is similar to `default_node_name` but takes in 0 arguments. 

I think the former might be better as it is cleaner but it would require making changes not only to `node start` command but also to other commands that were modified in #3948.

**Comment by adrianbenavides** [comment]
> I think the former might be better as it is cleaner but it would require making changes not only to node start command but also to other commands that were modified in https://github.com/build-trust/ockam/pull/3948.

That's right, we need the 0 arguments function and refactor those commands to use it.
