### ISSUE TITLE
Diagnose and fix errors in `ockam status` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4096]
This command has three known issues that must be addressed.

### How to reproduce

```bash
ockam reset -y
ockam status
```

### Fix proposal

[This section of the code](https://github.com/build-trust/ockam/blob/7cbe20ebbeeb7515ae63aae6804581f0fbb20044/implementations/rust/ockam/ockam_command/src/status.rs#L39-L47) is incorrect because `list()` will return an empty list instead of an error where there are no nodes in the system. That part should be rewritten as follows:

```rust
let node_states = opts.state.nodes.list()?;  
if node_states.is_empty() {  
    return Err(anyhow!("No nodes registered on this system!").into());  
}
```

### How to reproduce

Note: the previous error must be solved to reproduce this one.

```bash
ockam reset -y
ockam status
```

### Fix proposal

Currently, when running `ockam status` on a fresh install the command exits successfully without showing any output. The command should return an error when there are no enrolled identities. Before calling the `print_status`, there should be a check like this:

```rust
if status_identities.is_empty() {  
    return Err(anyhow!("No enrolled identities found! Try passing the `--all` argument to see all identities.").into());  
}
```

### How to reproduce

```shell
ockam reset -y
ockam node create
ockam node create
ockam status
```

### Fix proposal

For every registered node, this command runs an `Rpc` request. Currently, it tries to create a new `TcpTransport` on each request, resulting in the following error:

```
» ockam status
Version 0.77.0, hash: 99c3431ec67affcdf80d393f75e40bd69575c33b
failed because router state: a router for this type already exists

Caused by:
    failed because router state: a router for this type already exists
```

To fix this, the `get_node_status` must be refactored so it accepts a `TcpTransport` reference as a parameter. The `TcpTransport` must be created before [the `node_states` loop](https://github.com/build-trust/ockam/blob/7cbe20ebbeeb7515ae63aae6804581f0fbb20044/implementations/rust/ockam/ockam_command/src/status.rs#L50).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels - https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hweawer** [comment]
Can I take it?

**Comment by adrianbenavides** [comment]
Sure! Ping me if you have any questions 👍
