### ISSUE TITLE
Unhide `ockam vault` command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4097]
## Currently

The `vault` commands are hidden from the user when running `ockam --help` because of the [following Clap attribute](https://github.com/build-trust/ockam/blob/7cbe20ebbeeb7515ae63aae6804581f0fbb20044/implementations/rust/ockam/ockam_command/src/vault/mod.rs#L13).

## Desired

Remove that attribute so the `vault` subcommand is shown when executing `ockam --help`.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels - https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
Hi @mrinalwadhwa,

I've added a PR to unhide the help for the vault subcommand.

Best regards,
Harald
