### ISSUE TITLE
Move the identities database to the `./identities/data` directory 

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4122]
## Currently

The identities database is currently stored right under `$HOME/.ockam/identities`.

## Desired

To match the structure we have on the vaults directory, the identities database should be moved to `$HOME/.ockam/identities/data`. [This function](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/cli_state.rs#L413) must return the updated path.

The [CliState test](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/cli_state.rs#L945) will have to be modified, [removing these two](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/cli_state.rs#L1012-L1013) lines.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
Hi @adrianbenavides,

I've added a PR addressing the move. Instead of removing the lines from the test I've adjusted them.

Best regards,
Harald
