### ISSUE TITLE
Refactor `update_enrolled_identity` to hide mutation behind a struct function

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4124]
## Currently

The [`update_enrolled_identity`](https://github.com/build-trust/ockam/blob/02750506eef6c07578967e61703f05ed0e036d0c/implementations/rust/ockam/ockam_command/src/enroll.rs#L363) function used in the `ockam_command` is updating the CliState externally, which forces the user to manually `save` the changes after a modification is done. 

## Desired

The modification logic should be exposed through a method on the [IdentityState](https://github.com/build-trust/ockam/blob/02750506eef6c07578967e61703f05ed0e036d0c/implementations/rust/ockam/ockam_api/src/cli_state.rs#L418):

- the `save` method should be renamed to `persist` and **should be private**.
- a new method `set_enrollment_status` should be added to modify this field and then call the internal `persist` method.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
Hi @adrianbenavides,

I've added a PR to address that parts.
