### ISSUE TITLE
Implement `ockam worker list` CLI command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4130]
Given a node name, send a request to the node that retrieves the workers addresses of its context:

- The worker should have the structure: `ockam worker list --node {name}`. As in other commands, the `node` argument should default to the default node. [Check this as a reference](https://github.com/build-trust/ockam/pull/4120).
- A new handler must be implemented in the [NodeManagerWorker](https://github.com/build-trust/ockam/blob/afac396fbf0f07d7bdd885691a821a35a20ec460/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L436) on the address `node/workers` and type `GET` that will return the result of calling `ctx.list_workers().await`.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
Hi @adrianbenavides,

please find attached a PR implementing the command for review.

Have a nice weekend.

Best regards,
Harald
