### ISSUE TITLE
Fix ockam enroll command to not require custom attributes

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#4135]
### Context
`ockam project enroll`
is the command an _enroller_ uses to enroll new _members_ into a project.

The enroller has two different workflows to add members:

* it can pass the identity identifier of the member to add  using the `--member`  option
* or if it doesn't give the identity of the member,   it get back an _enrollment token_   that the enroller can give the member to enroll into the project  (in this way, enroller doesn't need to know the actual member identity ahead of time)   

In both cases,  an enroller can set arbitrary key-value attributes on the new member using `--attribute`   for example:

`ockam project enroll --member $member_identity_id   --attribute location=boston  --attribute service=sensor` 

### Issue

If enrolling using the second flow  (through enrollment token),  the enroller is actually *required*  to provide attributes,  likely due to the way the command line arguments are parsed,  and this is *not* intended nor desired.    `ockam project enroll`  should be enough to get a token without any custom attributes,   but instead the command is not recognized: 

```
$ ockam project enroll
An authorised enroller can add members to a project

Usage: ockam project enroll [OPTIONS]

Options:
      --identity <IDENTITY>    
  -n, --node <NODE>            Override the default API node [default: default]
  -m, --member <MEMBER>        
  -t, --to <TO>                [default: /project/default/service/authenticator]
  -a, --attribute <ATTRIBUTE>  Attributes in `key=value` format to be attached to the member

Global Options:
  -h, --help        Print help information (-h compact, --help extensive)
  -q, --quiet       Do not print any trace messages
  -v, --verbose...  Increase verbosity of trace messages
```

The issue doesn't affect the other workflow,  as  `ockam project enroll --member $member_identifier`   do work as expected without providing any custom attribute.

**Comment by p-gentili** [comment]
Can I work on this? 😄

**Comment by mrinalwadhwa** [comment]
@p-gentili of course, all yours.. let us know if you have any questions
