### ISSUE TITLE
Diagnose and fix `ockam node delete --all` error

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4136]
## Expected Behavior

`ockam node delete --all` should not throw an error when a foreground node is stopped.

## Current Behavior

```
» ockam node create n1 --foreground
^C

» ockam node list

» ockam node delete --all
Version 0.78.0, hash: 7b1d00e8b11881d6b7c422f9e7acc4c77bbc7ba5
{code: 70, err: IO error}
```

## Steps to Reproduce

1. Start a foreground node `ockam node create n1 --foreground`
2. Then press `Ctrl-C` to exit it
3. `ockam node list` Will show an empty list of nodes
4. `ockam node delete --all` Will throw the error

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
Hi @mrinalwadhwa,

I've added a PR that should fix that issue.

Best regards,
Harald
