### ISSUE TITLE
Diagnose and fix `ockam node create /node/n1` error

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4137]
## Currently

Fails when passing a `MultiAddr` as a node name.

## Desired

This command only needs to extract the node name from the `node_name` argument (i.e. it doesn't need to transform it in any way). Currently, the command will take the command argument value as is, whereas we also need to support valid MultiAddr strings with the format `/node/{name}`.

To support both inputs, the argument type must be `String` so it can be processed with the [`extract_address_value` function](https://github.com/build-trust/ockam/blob/f1b551e0e69cefeaa52133c4dd84546d38cab4cb/implementations/rust/ockam/ockam_command/src/util/mod.rs#L450) function. You can check how this function works in the [unit tests](https://github.com/build-trust/ockam/blob/f1b551e0e69cefeaa52133c4dd84546d38cab4cb/implementations/rust/ockam/ockam_command/src/util/mod.rs#L542).

A potential solution would be to create a wrapper function around `extract_address_value` with the following logic:
- If the input string is a multiaddr, then check that it's of type `Node`. If it's not, then return an error saying that the input MultiAddr must follow the format `/node/{name}`. If it is, call the `extract_address_value` function
- else, return the input unprocessed

## How to reproduce the error

```bash
» ockam node create /node/n2
Version 0.78.0, hash: 7b1d00e8b11881d6b7c422f9e7acc4c77bbc7ba5
IO error

Caused by:
Read-only file system (os error 30)
```

**Comment by nidnogg** [comment]
I'll have a try at it

**Comment by adrianbenavides** [comment]
Great! Let me find an example where we do this double parsing thing. I'll update the issue description.

**Comment by adrianbenavides** [comment]
Description updated with more details @nidnogg, let me know if you have any questions!

**Comment by nidnogg** [comment]
Looks like a great starting point @adrianbenavides, thanks for the heads-up!

**Comment by nidnogg** [comment]
Added a [PR](https://github.com/build-trust/ockam/pull/4163) with a possible fix, fingers crossed that it'll do the trick
