### ISSUE TITLE
Automatically enroll a project admin as a member of the projects he as admin rights to

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#4139]
When an orchestrator user creates a project,   the identity from where it created the project automatically get the ability to enroll members to the project.   On the authority side,   this admin user is *not*  a member of the project. 

But it _can_  add members.     What we want to do is,  on the cli side after a project is created  (`ockam project create` )  or a new identity is authenticated with orchestrator (`ockam enroll`) ,  go over the list of projects and  add the own identity to the project (what through commands would be  `ockam project enroll --member $own_identity_id`

**Comment by adrianbenavides** [comment]
We have two options here:
1. We can spawn a new process executing the `ockam project enroll --member $own_identity_id`
2. We can extract part of the logic of the `project enroll` command into a function. It would roughly look like:

```rust
let to = create_secure_channel_to_authority(...).await?; // using the project's route that we just created
let req = Request::post("/members")
    .body(AddMember::new(id.clone()).with_attributes(self.cmd.attributes()?));
rpc.request(req).await?;
rpc.is_ok()?;
```

One question on method `2`: what would the attributes look like? Do we need to use any?

**Comment by polvorin** [comment]
good question regarding attribute,   I think right now is best to not set any attribute.

**Comment by mrinalwadhwa** [comment]
@adrianbenavides option 2 would be better unless you hit some unexpected roadblock with it.
