### ISSUE TITLE
Implement a function on the `NodeState` to check whether a node is running

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4174]
## Current

There is no explicit way to easily check if a node is running or is stopped without sending a message to it.

## Desired

There are two potential solutions: one involves messaging the node, and another checking the node's state. In either case, we need a function on the `NodeState` that checks a node status given its name.

### Messaging

This solution consists of sending a `short_identity` request to the node with a [short timeout](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_command/src/util/mod.rs#L160). If the request receives an Ok response, then the node is up, otherwise it's not.

### Node state

When a node is executing as a background process, [we store the `pid` in a file in its state directory](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_api/src/cli_state.rs#L702). This can be done by checking the existence of this file and, if possible, if the PID exists in the system. 

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by adrianbenavides** [comment]
@CAOakleyII @polvorin what do you think about the proposed solutions? any preference?

**Comment by andrescaroc** [comment]
I would like to try this one

**Comment by adrianbenavides** [comment]
Sure, all yours @andrescaroc. You can try implementing the second proposed solution:

> ### Node state
> When a node is executing as a background process, [we store the pid in a file in its state directory](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_api/src/cli_state.rs#L702). This can be done by checking the existence of this file and, if possible, if the PID exists in the system.

Let me know if you have any questions 👍

**Comment by andrescaroc** [comment]
@adrianbenavides Thank you so much.

I submitted my proposed solution, feel free to provide feedback and/or guidance if it is far from what is expected
