### ISSUE TITLE
`ockam tcp-connection create` should return the tcp-connection ID

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4177]
## Current

This command doesn't output the transport ID, and you have to list all transports to get it (e.g. when you want to delete one).

## Desired

Add the [transport ID](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs#L95) to the [command's output](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs#L48-L60).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
I'll have a shot at it if nobody's already adding it
