### ISSUE TITLE
Allow `ockam tcp-connection list` to run without any arguments

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4178]
## Current

Currently, the command has the [`arg_required_else_help = true`](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs#L12) attribute which forces the user to provide an argument. This is undesired, as the only argument that this command accepts is the `--node` argument, and it has a default value.

## Desired

Remove the [`#[command(arg_required_else_help = true)]`](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs#L12) attribute.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
Should be simple enough, I'll have a look at it later today

**Comment by nidnogg** [comment]
I tried testing it but I couldn't find any differences between using the default value when required vs removing the requirement and having the default value be used. 

I kept running into an error 70: `'default tcp transport' not found` though, is this how it's supposed to be working?

A PR that should technically solve this is available at https://github.com/build-trust/ockam/pull/4184.
