### ISSUE TITLE
Remove the `--force` argument from `ockam tcp-listener delete`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4180]
### Current

This command will return an error if the `force` argument is not passed, forcing the user to always pass that argument to actually delete the tcp-listener.

### Desired

Remove [the `force` argument](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs#L22) from the command and the check on the [NodeManager's API handler](https://github.com/build-trust/ockam/blob/6d21ff5e3a6180b6de486b75cd09d2ddfd645f54/implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs#L89).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by p-gentili** [comment]
Hi, can I work on this?

**Comment by mrinalwadhwa** [comment]
@p-gentili Thank you for taking time to contribute. Someone already started work on this one https://github.com/build-trust/ockam/pull/4197

Please have a look at one of the other open good first issues https://github.com/build-trust/ockam/labels/good%20first%20issue

**Comment by caoakleyii** [comment]
Completed with https://github.com/build-trust/ockam/pull/4197
