### ISSUE TITLE
When deleting all nodes, if one node cannot be deleted then the rest of the nodes can't be deleted

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4195]
When running `ockam node delete --all` we run in a loop, trying to delete all known nodes. However if one of them fails to be deleted, the loop is broken and the rest of the nodes cannot be deleted.

The relevant code is [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/util.rs#L223).

It would be nice to just collect the errors and report them at the end of the loop as one.

**Comment by sorin-florea** [comment]
Hello, I would like to take this issue if nobody else is working on it.
