### ISSUE TITLE
Broken link in docs.ockam.io

### ISSUE THREAD

**Issue by andrescaroc** [build-trust/ockam#4205]
I think the link to edit docs.ockam.io is broken.

If you are located in any of the pages of docs.ockam.io and you try to click the link "`Edit on GitHub`" on the right side panel, it will try to take you to the address: [https://github.com/build-trust/ockam-documentation/blob/main/examples/README.md](https://github.com/build-trust/ockam-documentation/blob/main/examples/README.md) which doesn't exist.

This could impact contributors that want to improve the documentation.

**Comment by mrinalwadhwa** [comment]
Thank you, great catch @andrescaroc

**Comment by etorreborre** [comment]
Thanks @andrescaroc, this is fixed now
