### ISSUE TITLE
Add `ockam node default [node_name]` command to set default node

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4212]
## Summary
A new subcommand `default` should be added to allow for users to set the specified node as `default`

Adding a new `default` subcommand would start with additions to the [node command found here.](https://github.com/build-trust/ockam/blob/c2b887f9fdc7ea3cc78e9d64a5071ff5a5aa0505/implementations/rust/ockam/ockam_command/src/node/mod.rs#L24-L62)

## Expected Behavior

```
ockam node default n1
Set node 'n1' as default
```

The default node is defined within the `CliState` defined [here](https://github.com/build-trust/ockam/blob/c2b887f9fdc7ea3cc78e9d64a5071ff5a5aa0505/implementations/rust/ockam/ockam_api/src/cli_state.rs#L56). 

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by murex971** [comment]
I'd like to work on this one.

**Comment by murex971** [comment]
@CAOakleyII  can you provide a review on this one ?
