### ISSUE TITLE
Add command `ockam worker list`

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4214]
## Summary

A new command `worker` should be added with a subcommand of `list`.

The `list` subcommand will have a `--node` flag, that accepts a node name or defaults to the default node.

This will list all workers and their addresses on the given node.

## Expected Behavior

```
ockam worker list --node n1
```

Worker list should be generated from [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_node/src/context.rs#L833-L846).

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hargut** [comment]
https://github.com/build-trust/ockam/issues/4130

**Comment by caoakleyii** [comment]
> #4130

Thank you!
