### ISSUE TITLE
Improve the error that is displayed when a `node create` is run for a node that already exists

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4215]
## Summary
Improve the error that is displayed when `node create` is run for a node that already exists

## Current Behavior

```
» ockam node create n1
...
» ockam node create n1
Version 0.79.0, hash: ba1461ec47a2334abbf9007ff592982c279999d4
IO error

Caused by:
    File exists (os error 17)
```

## Expected Behavior

```
» ockam node create n1
...
» ockam node create n1
Node with the name of 'n1' already exists
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hweawer** [comment]
I would like to help with this

**Comment by caoakleyii** [comment]
@hweawer  Sounds good! I'll assign it to you.

The `ockam node create` command is found [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs).


One starting approach would be to guard the implementation by checking if a node with the same name already exist within the state with `options.state.nodes.get()` and passing in a parsed node name

**Comment by adrianbenavides** [comment]
Partially fixed. We'll get revised as we update the output of all the existing commands in the coming weeks.
