### ISSUE TITLE
Create command `ockam tcp-outlet list` to list a nodes TCP Outlets

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4228]
## Summary

A node has set of TCP Outlets. This command should retrieve those outlets with information of:
* Outlet Alias
* Outlet Address
* TCP Socket Address

The command should accept a `--node` flag, however default to the default node if one is not provided.

Code of where outlets are created and stored can be found [here](https://github.com/build-trust/ockam/blob/65c7259a2b96e85e2745397eaaf77e7dcf427960/implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs#L257-L323).

`tcp-outlet` commands are defined [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/mod.rs).
## Expected Behavior

```sh
ockam tcp-outlet create --at /node/n1 --from /service/outlet --to 127.0.0.1:5000 --alias "My TCP Outlet"

ockam tcp-outlet list --node n1
Outlet:
  Alias: My TCP Outlet
  From Outlet: /service/outlet
  To TCP: 127.0.0.1:5000
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by h20220145** [comment]
@CAOakleyII any pointers to get started ?

**Comment by h20220145** [comment]
@CAOakleyII Can i be assigned this ? Also , any more pointers to get started ?

**Comment by caoakleyii** [comment]
> @CAOakleyII Can i be assigned this ? Also , any more pointers to get started ?

@h20220145 
Assigned to you! Thanks for checking this issue out! 

As far as where to get started, perhaps taking a look at similar commands; The `ockam tcp-connection list` command will have same [general approach](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/list.rs). 

The ockam_command crate communicates with node to gather the information it requires. 

The code that handles the request to gather information (in this case tcp-outlet information) would be handled within[ the ockam_api crate, this is already done](https://github.com/build-trust/ockam/blob/84101e27779f076adc71cec758a9ef5b62911b5f/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L567-L570).

**Comment by h20220145** [comment]
@CAOakleyII I'm getting a bit lost on how to use rpc.parse_response .

Currently I tried using

> 'response = rpc.parse_response::< OutletStatus >()?;

 and printing the response directly gives me 


>'ockam tcp-outlet list --node n1'

>OutletList { list: [OutletStatus { tcp_addr: CowStr("127.0.0.1:5000"), worker_addr: CowStr("0#outlet"), alias: CowStr("My TCP Outlet 1"), payload: None }, OutletStatus { tcp_addr: CowStr("127.0.0.1:5001"), worker_addr: CowStr("0#outlet"), alias: CowStr("My TCP Outlet 2"), payload: None }] } 

Is outlet address supposed to be "0#outlet" ?

**Comment by davide-baldo** [comment]
This is the internal address representation: 0#outlet, 0 is the protocol and stands for "local", and the address is named "outlet", the same you would get by doing Address::from_string("outlet").
When the address uses TCP transport instead, you will get something like 1#ip_address.

You can take a look at how `ockam node list` was made, it should be close enough https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/list.rs

**Comment by h20220145** [comment]
<img width="909" alt="Screenshot 2023-02-21 at 5 13 54 AM" src="https://user-images.githubusercontent.com/115618607/220213850-05301d82-878f-4add-aa4d-4c626a553600.png">

Used route_to_multiaddr on the worker_addr and it gives me the outlet address as given in the Issue's expected behavior

Is this the correct way ?

**Comment by h20220145** [comment]
@davide-baldo @CAOakleyII   ?

**Comment by etorreborre** [comment]
Hi @h20220145. Could you please share the branch for the code that you are stuck on? One possibility is also to grab the work done on listing tcp inlets and do something very similar for the outlets: https://github.com/build-trust/ockam/pull/4304

**Comment by h20220145** [comment]
@etorreborre [https://github.com/build-trust/ockam/commit/0e2850ef85e48630a7efbc9ffa06a8a82552d0e5](url) , you can check this commit . Let me know if there is anything more to be done here ?

**Comment by h20220145** [comment]
@etorreborre  , let me know if there is any more changes required in this ? Sorry for the late reply .  If it is correct , i'll send a proper PR later with the lint removed . Thanks
 https://github.com/build-trust/ockam/commit/0e2850ef85e48630a7efbc9ffa06a8a82552d0e5

**Comment by etorreborre** [comment]
@h20220145 that looks good to me, please go ahead.
