### ISSUE TITLE
Create command `ockam tcp-inlet list` to list a nodes TCP Inlets

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4229]
## Summary

A node has set of TCP Inlets. This command should retrieve those inlets with information of:
* Inlet Alias
* TCP Address
* To Outlet Address

The command should accept a `--node` flag, however default to the default node if one is not provided.

Code of where inlets are created and stored can be found [here](https://github.com/build-trust/ockam/blob/65c7259a2b96e85e2745397eaaf77e7dcf427960/implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs#L112-L249).

`tcp-inlet` commands are defined [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/mod.rs).
## Expected Behavior

```sh
ockam tcp-inlet create --at /node/n2 --from 127.0.0.1:6000 --to /node/n1/service/outlet --alias "My TCP Inlet"

ockam tcp-inlet list --node n2
Inlet:
  Alias: My TCP Inlet
  From TCP : 127.0.0.1:6000
  To Outlet: /node/n1/service/outlet 
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0xkelvin** [comment]
hello, @CAOakleyII please assign this issue to me

**Comment by caoakleyii** [comment]
> hello, @CAOakleyII please assign this issue to me

All yours @0xkelvin 👍

**Comment by 0xkelvin** [comment]
i got some promising result : 
`InletList { list: [InletStatus { bind_addr: CowStr("127.0.0.1:6000"), worker_addr: CowStr("0#925b5875dd5a8f5c933d5d4aca40a4df"), alias: CowStr("My TCP Inlet"), payload: None, outlet_route: CowStr("1#127.0.0.1:62020 => 0#outlet") }] }`


![image](https://user-images.githubusercontent.com/56182747/219040444-9fbdb335-dfd2-49a4-9325-e3907a180145.png)

**Comment by 0xkelvin** [comment]
hello @CAOakleyII @mrinalwadhwa 

from my raw result above, how to get to extract "/node/n1/service/outlet" as expected.

or i might wrong somewhere

**Comment by h20220145** [comment]
> hello @CAOakleyII @mrinalwadhwa
> 
> from my raw result above, how to get to extract "/node/n1/service/outlet" as expected.
> 
> or i might wrong somewhere

+1 , have a similar question on #4228

**Comment by davide-baldo** [comment]
You can take a look at how ockam node list was made, it should be close enough https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/list.rs

**Comment by 0xkelvin** [comment]
Hello @davide-baldo 
![image](https://user-images.githubusercontent.com/56182747/220126333-1c3b9869-bb57-4212-b129-83fc0e4f5d8b.png)

does it acceptable ?

**Comment by davide-baldo** [comment]
Looks good! :+1: 

In the "Inlet Alias", you can omit the "Inlet" part since it's already implicit

**Comment by 0xkelvin** [comment]
@davide-baldo a PR here : https://github.com/build-trust/ockam/pull/4304
please review
