### ISSUE TITLE
Elixir: credential exchange client

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#4241]
Currently Elixir implementation supprots credential exchange service `Ockam.Services.API.CredentialExchange` which allows other nodes to present credentials. But there is no support yet to present credentials from Elixir nodes to other nodes.

Presenting credentials can be implemented as a worker which can hold credential in its state and perform credential exchange similar to how `present_credential` works in https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/credential/identity.rs

**Comment by polvorin** [comment]
Credential presentation is done in secure channel handshake
