### ISSUE TITLE
Elixir: symmetrical credential exchange

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#4242]
Currently `Ockam.Services.API.CredentialExchange` only supprots accepting credentials from remote nodes but cannot present it's own credentials, so it cannot be used with `present_credential_mutual` API.

It can support symmetrical exchange by handling `actions/present_mutual` API from `present_credential_mutual` in https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/credential/identity.rs
The API is similar to `actions/present` with a difference that response body should contain a credential (binary) in the same format as the request body.

Current supported API: https://github.com/build-trust/ockam/blob/develop/documentation/reference/api/credential_exchange.md
More on credentials: https://github.com/build-trust/ockam/blob/develop/documentation/architecture/authorization/credential_authorization.md

**Comment by hairyhum** [comment]
Requesting credential from the credential authority is out of scope for this issue.
In order to present credentials `Ockam.Services.API.CredentialExchange` worker needs to posess the credential binary. It can be added using `GenServer.call` to the worker.

**Comment by polvorin** [comment]
Credential exchange is done at secure channel handshake
