### ISSUE TITLE
Update TCP Connection output of `ockam tcp-connection create`

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4245]
## Expected Behavior

The commands output should include the connection ID, while also updating the output format to remove the bulletpoints.

```
$ ockam tcp-connection create --from n1 --to 127.0.0.1:5000

  TCP Connection:
    ID: 2812c77bcc11fb1270333343aee57b93
    From: /node/n1
    To: 127.0.0.1:5000 (/ip4/127.0.0.1/tcp/5000)
```

`ockam tcp-connection create` command is found [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs).

## Current Behavior
The output currently:

```
$ ockam tcp-connection create --from n1 --to 127.0.0.1:5000

  Created TCP Connection:
  • From: /node/n1
  •   To: 127.0.0.1:5000 (/ip4/127.0.0.1/tcp/5000)
  
  Transport ID : 2812c77bcc11fb1270333343aee57b93
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by p-gentili** [comment]
@CAOakleyII are you working on this? Otherwise I would like to :)

**Comment by caoakleyii** [comment]
I am not! :)

I will assign it to you, @p-gentili

**Comment by p-gentili** [comment]
@CAOakleyII any requirement on the ID line color? Currently that's _light blue_ instead of _light magenta_ like the other two.

**Comment by mrinalwadhwa** [comment]
@p-gentili Let's make it like the other two lines. `From:` and `To:`
