### ISSUE TITLE
Generate a markdown manual from command help

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4253]
We want to generate a website that that looks like this https://cli.github.com/manual/
As a first step, let's generate markdown with an index of links, we can then use a static site generator to generate html from the markdown.

Ockam Command has very similar struct to gh command - `ockam NOUN VERB`

We use clap as our command line framework, Ockam Command source code is here
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src

It's possible to get Clap's full help output at build time
https://github.com/clap-rs/clap/discussions/4475
https://docs.rs/clap/latest/clap/

There is currently `ockam manpages` command to generate man pages, we could generate man pages first and then generate html/markdown from it using pandoc. I tried that but it gives us very little control on the rendered HTML pages. I think just generating the markdown/html ourselves would be better.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by murex971** [comment]
@mrinalwadhwa  please assign me this one.

**Comment by mrinalwadhwa** [comment]
Awesome, all yours, let us know if you have questions as you explore further.

**Comment by mrinalwadhwa** [comment]
@murex971 just wanted to jump in and see if you have any questions about this issue. Let us know if you need help

**Comment by murex971** [comment]
Got busy with other things @mrinalwadhwa. But I'm on it and would raise a PR soon.

**Comment by murex971** [comment]
@mrinalwadhwa could you provide a review on this ?
