### ISSUE TITLE
Create clap command `ockam tcp-inlet delete` to delete a TCP Inlet on a node

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4269]
## Summary

A node has set of TCP Inlets. This command should delete an inlet of a specific alias
```
ockam tcp-inlet delete [alias] --node [node-name]
```
The command should have a positional argument `[alias]` which is the alias of the tcp inlet to be deleted.  
The command should accept a `--node` flag, however default to the default node if one is not provided.

Code of where inlets are created and stored can be found [here](https://github.com/build-trust/ockam/blob/5cc9a66ba4adf9ed5742daaec119da7c590a2e87/implementations/rust/ockam/ockam_api/src/nodes/service/portals.rs#L103-L247).

`tcp-inlet` commands are defined [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/mod.rs).
## Expected Behavior

```sh
ockam tcp-inlet create --at /node/n2 --from 127.0.0.1:6000 --to /node/n1/service/outlet --alias "my-inlet"
...
ockam tcp-inlet delete my-inlet --node n1
Deleted TCP Inlet 'my-inlet' on node 'n1'
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
Hiya @CAOakleyII, I'll take a stab at this and the sibling issue https://github.com/build-trust/ockam/issues/4268. If you could assign me to those whenever possible, that'd be great!

**Comment by caoakleyii** [comment]
@nidnogg  Assigned! 

Thank you

**Comment by nidnogg** [comment]
Update on this - the TCP Outlet sibling issue should be finished/merged soon, with a PR for this TCP inlet side coming likely over the next few days.

**Comment by nidnogg** [comment]
Heya, just added a PR (https://github.com/build-trust/ockam/pull/4433) with the requested changes. Should be pretty similar to the recently merged TCP Outlet delete implementation.
