### ISSUE TITLE
Display the date and time for a Credential

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4284]
## Summary

The current display for `Credential` shows 2 fields as timestamps instead of datetimes.

## Current behaviour

At the moment, the `Display` instance for the `Credential` struct [only displays the timestamps for `created` and `expired`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/credential.rs#L66):
```
//TODO: write timestamps on human-readable format. Should we add a dependency for this?
writeln!(f, " Created: {}", u64::from(credential_data.created))?;
writeln!(f, " Expires: {}", u64::from(credential_data.expires))?;
```

## Expected behaviour

It would be a lot nicer to display a formatted ISO datetime, using a minimal time library like https://crates.io/crates/time.

Bonus points 🚀 if you:

 - refactor the code so that the existing `Display` code is actually a `Display` instance on `CredentialData`
 - create another instance of `Display` for `Credential` simply delegating to the `CredentialData` `Display` instance
 - add [a unit test for the formatting](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/credential.rs#L359)

**Comment by 0xkelvin** [comment]
hello, pls assign to me @etorreborre

**Comment by etorreborre** [comment]
Hi Kelvin, sure!

**Comment by 0xkelvin** [comment]
Hello @etorreborre 
To understand how Credential print out, i was looked at [this example](https://github.com/build-trust/ockam/blob/develop/examples/rust/get_started/examples/11-attribute-based-authentication-control-plane.rs) 
Run it, but it doesnt show me anything after waiting for awhile
![image](https://user-images.githubusercontent.com/56182747/220361571-7db57775-0c2e-4c1f-bf04-91521ac32f0d.png)


Dont know any missing or any other steps i need to do first.

**Comment by 0xkelvin** [comment]
hello @etorreborre ^^

**Comment by etorreborre** [comment]
Hi @0xkelvin, sorry I missed your message. This works for me and displays something like
```
---
 Subject: P6474cfdbf547240b6d716bff89c976810859bc3f47be8ea620df12a392ea6cb7
 Issuer: P0db4fec87ff764485f1311e68d6f474e786f1fdbafcd249a5eb73dd681fd1d5d (OCKAM_RK)
 Created: 1677153775
 Expires: 1679745775
 Attributes: {"component": "control", "project_id": "ba875b38-0042-4aea-b4a9-3772bf9506da"}

 Signature: e599f69661f4b3729944586e09ba45dbb48eff1306e6e78fdd1bbf1ecdb23934ace3d0220fe1b599e6a15038fe7a0ae01dec1096ec911ce7c695bb1c76e1ae05
---
```
However the current instructions are missing the first step which is to run `ockam enroll` in order to create a project. Have you done that? Then you need to create a `project.json` file with `ockam project information --output json  > project.json`.
The `project.json` file must be in the same directory as the directory you use to start the "control_plane" node.

That being said you don't have to do all of this. You can write a unit test where you create a `CredentialData` struct and where you call the `Display` instance for `CredentialData`. That implementation does not exist yet but you can extract it from the `Display` implementation for `Credential`. Basically what I indicated in the "bonus points" section which is actually the simplest thing I can think of to get the job done :-).

**Comment by 0xkelvin** [comment]
hello @etorreborre 
getting back on this. 

i tried to run the 'cargo test' under 'ockam_identity' folder
but there are few errors : 
![image](https://user-images.githubusercontent.com/56182747/223413910-c2fc04a1-bf3d-4a95-86b3-4f59d2f197d1.png)

i was removed 
`
use crate::alloc::borrow::ToOwned;

use crate::alloc::string::ToString;
`
then it is fine, but not so sure that we need to use above import or not ?

**Comment by SanjoDeundiak** [comment]
@0xkelvin I think [this](https://github.com/build-trust/ockam/pull/4376/commits/e5e14d46a9f1963dbca58e916762d6ffc8597def) will fix that issue

**Comment by 0xkelvin** [comment]
Hello @sanjayatpilcrow @etorreborre 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/56182747/223676763-a2c5b754-f8fe-4990-b555-28de9527f76b.png">

does it looks OK ?

**Comment by etorreborre** [comment]
@0xkelvin I would go for a ISO-8601 format: `2023-03-08T09:43:00Z`. This is standard and uses a UTC time, [as indicated by the `Z`](https://en.wikipedia.org/wiki/ISO_8601#Times))

**Comment by 0xkelvin** [comment]
> @0xkelvin I would go for a ISO-8601 format: `2023-03-08T09:43:00Z`. This is standard and uses a UTC time, [as indicated by the `Z`](https://en.wikipedia.org/wiki/ISO_8601#Times))

![image](https://user-images.githubusercontent.com/56182747/223724060-acbd913c-4e6b-4346-be20-21ccd9d93599.png)

@etorreborre , not so sure it is correct or not, i saw many zero

**Comment by etorreborre** [comment]
@0xkelvin can you please share your code? I don't know how you are producing the datetime formatting but I suspect that there must be a way to specify a less precise format.

**Comment by 0xkelvin** [comment]
@etorreborre i make a draft PR here : https://github.com/build-trust/ockam/pull/4429

please guide me if i am wrong

**Comment by etorreborre** [comment]
@0xkelvin thanks. It seems that you can configure the ISO default format and specify the precision for seconds: https://docs.rs/time/0.3.20/time/format_description/well_known/iso8601/struct.Config.html#method.set_time_precision

**Comment by 0xkelvin** [comment]
@etorreborre i see, how many number of decimal digits is good enough ?

**Comment by etorreborre** [comment]
For a credential I don't think that we need to go lower that a second, so I would say 0.

**Comment by 0xkelvin** [comment]
> For a credential I don't think that we need to go lower that a second, so I would say 0.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/56182747/223960721-09a48b92-defe-4e56-b47a-7057f8320b6e.png">

@etorreborre

**Comment by 0xkelvin** [comment]
@etorreborre 
could you please explain a bit the syntax that i highlighted: 
![image](https://user-images.githubusercontent.com/56182747/224031713-7a63ab17-44b8-40ab-bd99-27064ebcdb4d.png)
 
 i trying to understand to relationship between Credential and CredentialData

**Comment by 0xkelvin** [comment]
ah i see here : 
![image](https://user-images.githubusercontent.com/56182747/224033723-132ea4ac-da8a-4ac9-93ad-feaffd72783c.png)

**Comment by 0xkelvin** [comment]
> @etorreborre could you please explain a bit the syntax that i highlighted: ![image](https://user-images.githubusercontent.com/56182747/224031713-7a63ab17-44b8-40ab-bd99-27064ebcdb4d.png)
> 
> i trying to understand to relationship between Credential and CredentialData

ah i see the relationship here 
![image](https://user-images.githubusercontent.com/56182747/224033906-5ec5ce34-095e-48a5-8578-515fd871c87f.png)

**Comment by 0xkelvin** [comment]
@etorreborre 
regarding refactor, could you please help me look at latest commit on PR https://github.com/build-trust/ockam/pull/4429
I hope that is a right direction. 
and I also would like to seeking your guide about this issue with **decode**: 
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/56182747/224076131-fb542d0b-eef3-496d-bca8-c43a8277e563.png">

i dont know what i should do

**Comment by etorreborre** [comment]
Yes I think that this is the right direction. To solve your current issue you can use the `TryFrom` instance allowing you to go from `Credential` to `CredentialData` and write:
```rust
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    CredentialData::try_from(self).map_err(|_| fmt::Error)?.fmt(f)
}
```
(note that I'm mapping conversion errors to formatting errors [as it was done before in the code](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/credential.rs#L59))

**Comment by 0xkelvin** [comment]
> as it was done before in the code

i think it getting better on latest commit in my PR https://github.com/build-trust/ockam/pull/4429
please help review

**Comment by etorreborre** [comment]
@0xkelvin that looks good indeed. Do you need any further help?

**Comment by 0xkelvin** [comment]
> @0xkelvin that looks good indeed. Do you need any further help?

i made it as official PR https://github.com/build-trust/ockam/pull/4429
please review

i think i missing unit test for Display

**Comment by 0xkelvin** [comment]
@etorreborre can close this, since it merged

**Comment by etorreborre** [comment]
Yes, thanks a lot for your help with this!
