### ISSUE TITLE
`at` argument from `ockam tcp-inlet create` should have a default value

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4306]
## Current

The [`ockam tcp-inlet create`'s `at` argument](https://github.com/build-trust/ockam/blob/f0a16e18a77b60e0f6c1b993db699e44c478c40c/implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs#L26) is mandatory, even if there is only one node in the system, adding unnecessary complexity to the command's UX.

## Desired

The `--at` argument should default to the default node name. This can be done by adding the attribute `default_value_t = default_node_name()`.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0xkelvin** [comment]
let me do it

**Comment by 0xkelvin** [comment]
hello @adrianbenavides

**Comment by SanjoDeundiak** [comment]
@0xkelvin that would be great! Go for it

**Comment by 0xkelvin** [comment]
@SanjoDeundiak @adrianbenavides 
i added the default value for clap command , please : https://github.com/build-trust/ockam/pull/4451

**Comment by 0xkelvin** [comment]
@SanjoDeundiak @adrianbenavides 
can close this since it already merged

**Comment by adrianbenavides** [comment]
Great, thanks @0xkelvin for the heads up!
