### ISSUE TITLE
Make CI commits workflow check co-authors are in the committers list

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4309]
# Current

We have a Github Actions workflow that checks that all commit authors have accepted our CLA and have been added to our committers list
https://github.com/build-trust/ockam/blob/develop/.github/workflows/commits.yml#L176

We sometimes have Co-Authors to commits that are defined using the `Co-authored-by` method described here https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors 

# Desired

The commits workflow should also check that co-authors are in our committers list
https://github.com/build-trust/ockam/blob/develop/.github/workflows/commits.yml#L176

**Comment by waqasraz** [comment]
I'll get this done WIP

**Comment by etorreborre** [comment]
Thank you @waqasraz!

**Comment by metaclips** [comment]
Fixed in https://github.com/build-trust/ockam/pull/4405
