### ISSUE TITLE
ockam enroll command error handling

### ISSUE THREAD

**Issue by hairyhum** [build-trust/ockam#4333]
Currently `ockam enroll` command executes multiple steps https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll.rs#L53:

- authenticate with auth0
- ensure space
- ensure project
- enroll admin to the project

Those steps require communication with the orchestrator and project nodes APIs. API requests might timeout or fail with different reasons. This leaves the `enroll` process in unfinished state.

Possible ways to address that:
- Make sure that re-running `ockam enroll` commands resolves the unfinished state and  finishes the steps which were not done in the previous run (related: https://github.com/build-trust/ockam/issues/4319)
- Retry on API call timeouts (and maybe some other errors) to make sure it's less likely for this command to fail in unfinished state.

**Comment by adrianbenavides** [comment]
Fixed at https://github.com/build-trust/ockam/pull/4326/
