### ISSUE TITLE
Need for a Code of Conduct 

### ISSUE THREAD

**Issue by Anita-ihuman** [build-trust/ockam#4342]
**Describe the bug**
This is a great open source projects and I enjoyed skimming through the technical documnetation. However, I noticed that there is no Code of Conduct available.

One of the key metrics we look out for in Open source project at CHAOSS to maintain project and community healthy is the availability and accessibility of the [COC](https://chaoss.community/kb/metric-code-of-conduct-for-a-project/). 
It would be great to clearly outline this projects Code of Conduct for contributors participating.

**To Reproduce**
1. Run '...'

**Expected behavior**

**Screenshots**

**System**
 - OS: [e.g. macOS 13.1]
 - Ockam Command/Rust library version (if applicable):
 - Browser [e.g. chrome, safari] (if applicable):

**Additional context**

**Comment by BeenzSyed** [comment]
Hi @Anita-ihuman! 

Our code of conduct is here: https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md. It's at the organizational level in Github.

I hope this helps! Please let me know if you have any questions. Thank you!

**Comment by Anita-ihuman** [comment]
Thank you for pointing to the Code of conduct. 
I almost did not realise there was one. Is it possible to point to it on the ReadMe for this Repo? For easy access?

**Comment by mrinalwadhwa** [comment]
Hi Anita, super helpful feedback!

If you think another mention would be good, we would love a PR that adds it right after the Contribute to Ockam [link](https://github.com/build-trust/ockam#learn-more-about-ockam) at the bottom of the readme.



Github currently displays and links it next to the our license in the sidebar:

---

![Screenshot 2023-02-27 at 6 18 26 PM](https://user-images.githubusercontent.com/159583/221736131-70d4ae23-898b-4b44-8ccf-665893968b29.png)

---

**Comment by Anita-ihuman** [comment]
@mrinalwadhwa Thanks for pointing that.
I must have missed it.
I suppose if thats right there, I can proceed to close this issue.

**Comment by mrinalwadhwa** [comment]
@Anita-ihuman thank you for taking time to give us feedback.
