### ISSUE TITLE
Close TCP connections after use

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4364]
After merging [this](https://github.com/build-trust/ockam/pull/4172) PR we will need to track the lifecycle of TCP connection and close them after use. Currently, we never close them, but that leads to ineffective resource usage

**Comment by 0x00A5** [comment]
I can help with this, can you assign this to me please?

**Comment by SanjoDeundiak** [comment]
Hey @0x00A5 , this is a complicated task because it requires a very deep dive into each case of using TCP connections. I'll assign it to you if you want to try it!

**Comment by SanjoDeundiak** [comment]
AFAIK they're closed where needed
