### ISSUE TITLE
Add bats test for `ockam tcp-outlet list` command

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4365]
After adding `ockam tcp-outlet list` command described in [this issue](https://github.com/build-trust/ockam/issues/4228) in [this PR](https://github.com/build-trust/ockam/pull/4344) it would be great to have a test checking that command works as intended. We use bats test to test `ockam_command` binary. [This file](https://github.com/build-trust/ockam/blob/2f445439fda29dd4a297f93b9f57f075b5edfbe3/implementations/rust/ockam/ockam_command/tests/bats/unit.bats) could a great place to add the test

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by h20220145** [comment]
@SanjoDeundiak assign this issue to me , Thanks.

**Comment by h20220145** [comment]
Also @SanjoDeundiak , let me know if there's any more issues I can help out with ? I'll try and get some more done over the weekend.

**Comment by davide-baldo** [comment]
Hi @h20220145!
We do have quite a few issues tagged as https://github.com/build-trust/ockam/labels/good%20first%20issue!
Feel free to pick the ones you like most!

**Comment by nidnogg** [comment]
Whoops, I didn't see this issue at first and I figured it was an oversight that could've been patched in. Sorry @h20220145! Do feel free to add any edge cases I might've missed in that test though.
It's been added in this PR https://github.com/build-trust/ockam/pull/4446 and recently merged, so I'm afraid if another test is added it's going to be a duplicate at some form.

⚠️ @SanjoDeundiak @davide-baldo a heads up for whenever this comes up in a review

**Comment by h20220145** [comment]
if @nidnogg 's PR closes this issue , then close it, was busy with midterms and didn't have time. Will work on something else

**Comment by adrianbenavides** [comment]
We have some unassigned issues creating new commands if that's something that interests you @h20220145 . I hope you crushed the midterms, and thanks for your interest! 💪
