### ISSUE TITLE
Add bats test for `ockam tcp-inlet list` command

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4366]
After adding `ockam tcp-inlet list` command described in [this issue](https://github.com/build-trust/ockam/issues/4229) in [this PR](https://github.com/build-trust/ockam/pull/4304) it would be great to have a test checking that command works as intended. We use bats test to test `ockam_command` binary. [This file](https://github.com/build-trust/ockam/blob/2f445439fda29dd4a297f93b9f57f075b5edfbe3/implementations/rust/ockam/ockam_command/tests/bats/unit.bats) could a great place to add the test

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by etorreborre** [comment]
There is already such a test [here](https://github.com/build-trust/ockam/blob/abe0b026ecfec9e114872afb7fa9697f9304fe89/implementations/rust/ockam/ockam_command/tests/commands.bats#L341). Should it be moved? Maybe we could add a section in the README explaining how the bats tests are structured and what should go where.

**Comment by SanjoDeundiak** [comment]
Great catch. Should we then just move it? I think the idea was to move from one large `commands.bats` test file to smaller individual test files. @adrianbenavides could you please elaborate on this?

**Comment by adrianbenavides** [comment]
> Great catch. Should we then just move it? I think the idea was to move from one large `commands.bats` test file to smaller individual test files. @adrianbenavides could you please elaborate on this?

Correct, that test should be moved.

New tests should be written into one of the files under `tests/bats`. The `commands.bats` file is going to be deprecated as soon as CI uses the new `tests/bats` files.

**Comment by nidnogg** [comment]
Speaking of moving that test - I'm not sure if it's been moved but there's one in `tests/bats/unit.bats` as well. Specifically, [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/tests/bats/unit.bats#L390-L404) if anyone wants to check. It's been slightly modified in https://github.com/build-trust/ockam/pull/4446, and I'm not sure if it's the same mentioned above

**Comment by adrianbenavides** [comment]
> Speaking of moving that test - I'm not sure if it's been moved but there's one in `tests/bats/unit.bats` as well. Specifically, [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/tests/bats/unit.bats#L390-L404) if anyone wants to check. It's been slightly modified in #4446, and I'm not sure if it's the same mentioned above

Yeah, that was the test we mentioned. I think the CRUD tests should include the `list` command so we can delete the `list`  tests. But I wouldn't worry about that. The mid-term goal is to rewrite all the unit tests in rust code, so having a couple of extra bats tests won't harm.
