### ISSUE TITLE
Implement handler for `tcp-listener delete` command

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4367]
Currently, we have a stop listener command [here](https://github.com/build-trust/ockam/blob/2f445439fda29dd4a297f93b9f57f075b5edfbe3/implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs), but the corresponding [handler](https://github.com/build-trust/ockam/blob/2f445439fda29dd4a297f93b9f57f075b5edfbe3/implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs#L91) doesn't support stopping a listener, since it wasn't possible before merging [this PR](https://github.com/build-trust/ockam/pull/4172). We would like to have that support. Ideally adding this functionality should come with corresponding bats test [here](https://github.com/build-trust/ockam/blob/2f445439fda29dd4a297f93b9f57f075b5edfbe3/implementations/rust/ockam/ockam_command/tests/bats/unit.bats)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0xkelvin** [comment]
hello @SanjoDeundiak please assign to me

**Comment by SanjoDeundiak** [comment]
All yours @0xkelvin !

**Comment by 0xkelvin** [comment]
so the expect behaviour here is [shutdown listening](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_transport_tcp/src/workers/listener.rs#L59), is it ? @SanjoDeundiak @adrianbenavides

**Comment by adrianbenavides** [comment]
That's right, you can trigger the shutdown via the `Context` instance available in the `NodeManager`, using the worker address that is stored in the registry:

```rust
ctx.stop_processor(worker_address).await?;
```

**Comment by 0xkelvin** [comment]
@adrianbenavides @SanjoDeundiak 
please help me review : https://github.com/build-trust/ockam/pull/4473

i am very concern about bats test, maybe i added wrong things
