### ISSUE TITLE
Terminate nodes on SIGTERM

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#4372]
The `SIGTERM` signal is a way to politely ask a program to terminate.

What needs to be done:

Handle the `SIGTERM`  signal on ockam nodes  (both foreground running nodes and background running nodes),  and immediately terminate the process once receiving it.
This will make ockam a better citizen when running in managed environment like docker/kubernetes or as part of some supervised tree.

Using https://crates.io/crates/ctrlc is likely the easiest way to do it,  but feel free to explore other options.  

Note that a better implementation would be to wait for all in-flight work to terminate before exiting,  but that's out of scope for this issue.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by phillyphil91** [comment]
Hey @polvorin I would like to take a look at this.

**Comment by polvorin** [comment]
thanks @phillyphil91  !,  all yours.   Let us know if you have questions,   I _think_  a good candidate for where to hook this code is on [create_foreground_node()](https://github.com/build-trust/ockam/blob/abe0b026ecfec9e114872afb7fa9697f9304fe89/implementations/rust/ockam/ockam_command/src/node/create.rs#L212)  or    [embedded_node_that_is_not_stopped()](https://github.com/build-trust/ockam/blob/abe0b026ecfec9e114872afb7fa9697f9304fe89/implementations/rust/ockam/ockam_command/src/util/mod.rs#L377)   (embedded_node_that_is_not_stopped_unless_sigterm_is_received  :joy_cat: )

**Comment by polvorin** [comment]
@phillyphil91  actually,   first thing will be to check if the behavior I described is still an issue or if nothing is needed here

**Comment by adrianbenavides** [comment]
Some context here.

- Background nodes: can be stopped using `ockam node stop`. This command will take care of killing the process with either `SIGKILL` or `SIGTERM`, leaving the node's state untouched, so the user can restart it later with `ockam node start`.
- Foreground nodes: can NOT be stopped using the `ockam node stop` command, since foreground nodes do not store the `pid` in its state, so we can't figure it out from other processes. Currently, a foreground node can be manually stopped with `ctrl+c` (which is not properly handled), and [upon receiving an EOF character](https://github.com/build-trust/ockam/blob/c5954380c5725957c0076489a2677fbbe96d91a8/implementations/rust/ockam/ockam_command/src/node/create.rs#L339).

What you could try @phillyphil91 is integrating the `ctrlc` library to properly handle `ctrl+c` and `termination` signals on foreground nodes.

**Comment by adrianbenavides** [comment]
@phillyphil91 I found this comment that might be useful where I explained a little about how would I integrate `ctrlc`: https://github.com/build-trust/ockam/pull/4162#pullrequestreview-1276440384

**Comment by phillyphil91** [comment]
thanks @adrianbenavides  I will take a look

**Comment by phillyphil91** [comment]
Hi @adrianbenavides.
I have started to investigate the behavior of the commands and one thing that I am  not seeing is the following: 
> * Foreground nodes: can NOT be stopped using the `ockam node stop` command, since foreground nodes do not store the `pid` in its state, so we can't figure it out from other processes. Currently, a foreground node can be manually stopped with `ctrl+c` (which is not properly handled), and [upon receiving an EOF character](https://github.com/build-trust/ockam/blob/c5954380c5725957c0076489a2677fbbe96d91a8/implementations/rust/ockam/ockam_command/src/node/create.rs#L339).

When I run `ockam node create --foreground` it creates the node and then I run `ockam node stop` (e.g. in another terminal window) I get the message that the corresponding node that I created before is indeed stopped and in `ockam node list` I can see that the status is DOWN. The same behavior that I am seeing when terminating via `CRTL-C`.
When running `ockam node stop` I am getting an info from my shell (fish) that the `SIGTERM` signal was sent to the foreground command that I had running.

Did I misunderstand your comment or am I applying the wrong commands?

**Comment by adrianbenavides** [comment]
I could verify what you said and I found a couple of bugs:

1. The foreground node is initialized without a pid file, hence we can't stop it using the `node stop` command. BUT, after calling `node list`, the pid file is written into the node's state, which allows us to stop it afterward:

```bash
ockam node crate n1 --foreground
ockam node stop n1 # this won't do anything
ockam node list # it will list the node as UP, and will create the pid file as an undesired side effect
ockam node stop n1 # now it will stop the node
```

2. There is a bug in which you are able to start a node that already exists. Example:

```bash
ockam node crate n1 --foreground
ockam node list # to trigger the bug and persist the pid file
ockam node stop n1
# now the `n1` node is stopped, but its state is still available
ockam node create n1 --foreground # this will work and will spawn another node, and it shouldn't
```

**Comment by phillyphil91** [comment]
thanks for verifying this @adrianbenavides 
Regardless, the `crtlc` crate should still be integrated into the `ockam node crate n1 --foreground` command the way that you describe it in https://github.com/build-trust/ockam/pull/4162#pullrequestreview-1276440384, right?
Or should any of the two described bugs be solved first?

**Comment by adrianbenavides** [comment]
> thanks for verifying this @adrianbenavides Regardless, the `crtlc` crate should still be integrated into the `ockam node crate n1 --foreground` command the way that you describe it in [#4162 (review)](https://github.com/build-trust/ockam/pull/4162#pullrequestreview-1276440384), right? 

That's right!

> Or should any of the two described bugs be solved first?

You can focus on the `ctrlc` integration, I'll create a separate issue to track those two bugs.
