### ISSUE TITLE
When running the `credential store` command, validate the credential before storing it 

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4380]
## Current

ref: https://github.com/build-trust/ockam/pull/4360/files#r1122971375

When running the `credential store` command, it will store the passed credential associated with the passed issuer. This credential is not validated, so a user could store any string as a valid credential.

## Desired

Verify the credential against the issuer before storing it as it's done at [`credential verify` command](implementations/rust/ockam/ockam_command/src/credential/verify.rs).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0xkelvin** [comment]
@adrianbenavides please assign to me

**Comment by adrianbenavides** [comment]
Done! Let us know if you have any question 👍

**Comment by crajcan** [comment]
I can take this one

**Comment by davide-baldo** [comment]
@crajcan sure!
