### ISSUE TITLE
Refactor `starts_with_*` methods so they return the split MultiAddr parts

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4389]
ref: https://github.com/build-trust/ockam/pull/4172#discussion_r1119906096

### Current

The `starts_with_*` methods return the index at which the split should be applied:

```rust
let Some(pos1) = starts_with_host_tcp(addr) {
	debug!(%addr, "creating a tcp connection");
	let (a1, b1) = addr.split(pos1);
}
```

### Desired

Refactor the `starts_with_host_tcp` and `starts_with_secure` methods so they return the prefix and the rest of the MultiAddr as two separate MultiAddr instances:

```rust
impl MultiAddr {

   // split the MultiAddr into 2 MultiAddr where
   //   - the first is a multi addr is a Dns, Ipv4 or Ipv6 address
   //   - the second part is the remaining of the MultiAddr
   //  For example etc....  
   fn split_network_host(&self) -> Result<(MultiAddr, MultiAddr)> {
     ...
  }

  // split the MultiAddr into 2 MultiAddr where
  // ... 
  fn split_secure(&self) -> Result<(MultiAddr, MultiAddr)> {
}

...
let Some(host_address, rest) = addr.split_network_host() {
	debug!(%tcp_address, "creating a tcp connection");
	...
}
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0xkelvin** [comment]
@adrianbenavides please assign to me

**Comment by jamesneb** [comment]
Can I work on this?

**Comment by mrinalwadhwa** [comment]
@jamesneb of course, all yours
