### ISSUE TITLE
Move `multiaddr_to_socket_addr` method into `MultiAddr`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4390]
ref: https://github.com/build-trust/ockam/pull/4172#discussion_r1119912671

### Current

The `multiaddr_to_socket_addr` is a static function that operates on a `MultiAddr`.

### Desired

Move that function as part of the `MultiAddr` struct so we can call it as `ma.to_socket_addr()`

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hugoamalric** [comment]
Hi @adrianbenavides, I would like to work on it, can you assign me on this one ?
