### ISSUE TITLE
Move `SocketAddrV4` parsing of `TransportStatus` as an internal method

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4391]
ref: https://github.com/build-trust/ockam/pull/4172#discussion_r1120084471 

###  Current

In some commands, we are parsing the `TransportStatus` `socket_addr` field manually.

### Desired

Add a method to the `TrannsportStatus` struct to do that parsing.

```rust
impl TrannsportStatus {
	# ...
	pub fn socket_addr(&self) -> Result<SocketAddrV4> {
		self.socket_addr.parse::<SocketAddrV4>()
	}
}
```

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by hugoamalric** [comment]
Hello @adrianbenavides, I would like to work on this issue could you assign me please ?

**Comment by mrinalwadhwa** [comment]
@hugoamalric awesome, let us know if you have any questions
