### ISSUE TITLE
Replace codes used to represent the multiaddr protocols

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4392]
ref: https://github.com/build-trust/ockam/pull/4172#discussion_r1120125291

### Current

The MultiAddr custom protocols use numbers that make no actual sense, leading to unnecessary confusion.

### Desired

Replace all those numbers, using a monotonically increasing series (start from 1, and increase by 1).

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mrinalwadhwa** [comment]
closing see my note here https://github.com/build-trust/ockam/pull/4172#discussion_r1120125291
