### ISSUE TITLE
Create traits to abstract the configuration files handled by the CLI state

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4410]
### Current behavior

Currently the different resources within the CLI State are all implemented independently but share a very similar structure.

Those CLI State resources are used and defined within [here](https://github.com/build-trust/ockam/blob/1ef02c9c07603b5de776563e6861cfdf1aae3dce/implementations/rust/ockam/ockam_api/src/cli_state.rs#L60-L67).

### Desired behavior

Abstract many of the existing systems and create a common structure for the way CLI State resources are persisted and accessed.

**Comment by adrianbenavides** [comment]
@hargut made some efforts towards this not so long ago. It could be a good chance to revisit those changes. Here is the commit to keep it as a reference: https://github.com/hargut/ockam/commit/2d2044da57659fc6de4821eab734fe757fcc9383

**Comment by 0xkelvin** [comment]
i'd like to take this as well, @adrianbenavides @CAOakleyII

**Comment by adrianbenavides** [comment]
This one can be a bit challenging if you are not familiar with how traits work in rust. Let us know if we can help you along the way!

**Comment by 0xkelvin** [comment]
> This one can be a bit challenging if you are not familiar with how traits work in rust. Let us know if we can help you along the way!

i like challenges

**Comment by 0xkelvin** [comment]
back to working on it after a busy month

**Comment by adrianbenavides** [comment]
Hey @0xkelvin , I opened a PR solving this last week. I forgot to link it to the issue sorry. We have plenty of open issues if you are interested in picking another one! 👍
