### ISSUE TITLE
Create clap command to show the details of an existing TCP listener on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4419]
### Current behavior

Missing command for `tcp-listener show`.

### Desired behavior

Implement a command that retrieves from a running node the information of a `tcp-listener` given its ID.

```bash
ockam tcp-listener show [ID] --at [node-name]
```

Required args:
- ID

Optional args:
- at: defaults to the default node

Output:

```bash
TCP Listener:
  ID: {}
  Type: {}
  Mode: {}
  Socket address: {}
  Worker address: {}
```

Similar command: [`tcp-listener delete`](https://github.com/build-trust/ockam/blob/5837c73b90cfa72a76879642e727024c9e0977d0/implementations/rust/ockam/ockam_command/src/tcp/listener/delete.rs#L13)

**Comment by 0xkelvin** [comment]
i can take this one too

**Comment by mrinalwadhwa** [comment]
@0xkelvin that would be great. Let us know if you have any questions as you work on it

**Comment by 0xkelvin** [comment]
@mrinalwadhwa thanks, i am getting familiar with source code, so i want to do more and more

**Comment by 0xkelvin** [comment]
hello @adrianbenavides 
i would like to test out my implementation (https://github.com/build-trust/ockam/pull/4455)
but i dont know how to create the tcp listener, i tried below command, but i think need some more commands need to be done : 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/56182747/224748356-c4fc49ae-301f-4a66-9beb-78f6f098ec18.png">

**Comment by 0xkelvin** [comment]
hi @adrianbenavides ^^

**Comment by adrianbenavides** [comment]
@0xkelvin looks like we have a bug there! The `tcp-listener create` sends a request [to this endpoint of the NodeManager](https://github.com/build-trust/ockam/blob/ddd74729d9ee3c80c4f64b6a0d64afe7ee56ab7f/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L578) _without_ a body. If you take a look at the handler, you will see [it expects a body](https://github.com/build-trust/ockam/blob/ddd74729d9ee3c80c4f64b6a0d64afe7ee56ab7f/implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs#L36) (a CreateTransport instance).

So, to solve this you have to modify the [request here](https://github.com/build-trust/ockam/blob/ddd74729d9ee3c80c4f64b6a0d64afe7ee56ab7f/implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs#L41) so it includes a CreateTransport object in the body.

Let me know if that makes sense 👍

**Comment by 0xkelvin** [comment]
@adrianbenavides 
hmm, 
then i think the ["create"](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs#L13) command for tcp-listener needs to be updated. Because the body is requires `TransportType` `TransportMode` too (https://github.com/build-trust/ockam/blob/abe0b026ecfec9e114872afb7fa9697f9304fe89/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L18-L27) 


if it is correct, please create another issue and assign to me

**Comment by adrianbenavides** [comment]
> Because the body is requires TransportType TransportMode too

Those are known in the `tcp-listener create` context: the TransportType is TCP and the TransportMode is listener.

**Comment by 0xkelvin** [comment]
> > Because the body is requires TransportType TransportMode too
> 
> 
> 
> Those are known in the `tcp-listener create` context: the TransportType is TCP and the TransportMode is listener.
> 
> 

i see, make sense

**Comment by 0xkelvin** [comment]
@adrianbenavides 
i modified like below, it seems not correct, please guide me : 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/56182747/225060578-0a9775fb-a68f-4470-9614-a48c5796b2a2.png">

**Comment by adrianbenavides** [comment]
> @adrianbenavides i modified like below, it seems not correct, please guide me : <img alt="image" width="661" src="https://user-images.githubusercontent.com/56182747/225060578-0a9775fb-a68f-4470-9614-a48c5796b2a2.png">

That's weird, perhaps you have something wrong with your setup. I applied the same changes as you and I could create the tcp-listener. Try running:
```bash 
ockam reset --yes
ockam node create
ockam tcp-listener create 127.0.0.1:55001
``` 

If that doesn't work, please open a PR and let's continue the conversation there. It will be easier to debug.

**Comment by 0xkelvin** [comment]
@adrianbenavides
3 commands above solved the problem : 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/56182747/225070393-5f9ebda6-3e12-4cf8-8be6-c3d20b86d4be.png">

**Comment by 0xkelvin** [comment]
@adrianbenavides 

regarding to show the details of tcp listener, how does it looks : 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/56182747/225075423-ee921552-afcd-44eb-a5ca-63b645256496.png">

**Comment by adrianbenavides** [comment]
> @adrianbenavides
> 
> regarding to show the details of tcp listener, how does it looks

The output looks good 👍

**Comment by 0xkelvin** [comment]
> > @adrianbenavides
> > regarding to show the details of tcp listener, how does it looks
> 
> The output looks good 👍

ok, i make the PR, now
https://github.com/build-trust/ockam/pull/4455

**Comment by 0xkelvin** [comment]
another PR regarding : body missing when create tcp-listener 
https://github.com/build-trust/ockam/pull/4463
