### ISSUE TITLE
Create clap command to show the details of an existing TCP inlet on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4421]
### Current behavior

Missing command for `tcp-inlet show`.

### Desired behavior

Implement a command that retrieves from a running node the information of a `tcp-inlet` given its alias.

```bash
ockam tcp-inlet show [alias] --at [node-name]
```

Required args:
- alias

Optional args:
- at: defaults to the default node

Output: same as described at [`tcp-outlet list`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs#L34).

Similar command: [`tcp-outlet delete`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L14)

**Comment by nidnogg** [comment]
Could you assign this to me? I'd like to tackle its sibling issue https://github.com/build-trust/ockam/issues/4435 as well.

**Comment by adrianbenavides** [comment]
Sure, thanks @nidnogg! Let me know if you have any questions about these commands.

**Comment by nidnogg** [comment]
@adrianbenavides I've undrafted https://github.com/build-trust/ockam/pull/4446 with a solution for this and https://github.com/build-trust/ockam/issues/4421
