### ISSUE TITLE
Create clap command to show the details of an existing TCP outlet on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4435]
### Current behavior

Missing command for `tcp-outlet show`.

### Desired behavior

Implement a command that retrieves from a running node the information of a `tcp-outlet` given its alias.

```bash
ockam tcp-outlet show [alias] --node [node-name]
```

Required args:
- alias

Optional args:
- node: defaults to the default node. Use the `NodeOpts` struct to define this argument.

Output: same as described at [`tcp-outlet list`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs#L34).

Similar command: [`tcp-outlet delete`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L14)

**Comment by nidnogg** [comment]
I'll take on this one. Quick question: should I update the `tcp-outlet CRUD test` to use this as well?

**Comment by nidnogg** [comment]
I've drafted a PR https://github.com/build-trust/ockam/pull/4446 with the `tcp-outlet show` command and its corresponding test - I'd like to tackle both the inlets' and outlets' `show` commands with one PR this time around.

I'm just not sure which endpoint to use for the `show` command though - is `node/outlet/show` ok for this? Passing the portal `alias` as a `PortalAlias` payload struct like in [here](https://github.com/build-trust/ockam/pull/4446/files#diff-fee061b9c2629c91dcb8dcd8412526980626c18ba53562340f2040cab470469aR670)?

**Comment by adrianbenavides** [comment]
> should I update the tcp-outlet CRUD test to use this as well?

Yes, that would be great.

> I'm just not sure which endpoint to use for the show command though - is node/outlet/show ok for this?

In other `show` commands we send a GET request to `/{subject}` (`/node/outlet` in this case).

> Passing the portal alias as a PortalAlias payload struct like in [here](https://github.com/build-trust/ockam/pull/4446/files#diff-fee061b9c2629c91dcb8dcd8412526980626c18ba53562340f2040cab470469aR670)?

Yes, that makes sense.

**Comment by nidnogg** [comment]
Undrafted https://github.com/build-trust/ockam/pull/4446 with a solution for this and https://github.com/build-trust/ockam/issues/4421
