### ISSUE TITLE
Create clap command to show the details of an existing Forwarder on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4436]
### Current behavior

Missing command for `forwarder show`.

### Desired behavior

Implement a command that retrieves from a running node the information of a `forwarder` given its name.

```bash
ockam forwarder show [name] --at [node-name]
```

Required args:
- name

Optional args:
- at: defaults to the default node

Output: same as described at [`forwarder create`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/forwarder/create.rs#L80).

**Comment by caoakleyii** [comment]
I know we create forwarders with a name, but because of the dynamic forwarders (without an alias/name) we can create storing/access forwarders by name might not be the best option.

I was thinking we should probably create a uuid, on creation of forwarders and use that to identify forwarders instead.

@adrianbenavides

**Comment by caoakleyii** [comment]
Another thing that's important to note for this task and the [`forwarder list`](https://github.com/build-trust/ockam/issues/4441) is that we currently don't have an easy way to access the forwarders currently created for a node.

The `node_manager`'s `registry` does not store that information.

**Comment by adrianbenavides** [comment]
> I know we create forwarders with a name, but because of the dynamic forwarders (without an alias/name) we can create storing/access forwarders by name might not be the best option.

The "name" I was referring to is actually the `remote_address`, and we have that for both static and dynamic forwarders. So, for example, when creating a static forwarder, we get a remote address like `/service/fwd_to_{alias}`. In the case of a dynamic forwarder, the address will be different, but we should still be able to refer to it uniquely by that address. 

Since is that `remote_address` what we expose through the CLI, I'm not sure using an uuid will help. It would force the user to keep two values at hand for each forwarder: one to use it in the multiaddr's of other commands, and another to show/delete it.

**Comment by nidnogg** [comment]
> Another thing that's important to note for this task and the [`forwarder list`](https://github.com/build-trust/ockam/issues/4441) is that we currently don't have an easy way to access the forwarders currently created for a node.
> 
> The `node_manager`'s `registry` does not store that information.

Should the `node_manager`'s `registry` store that information? I mean, `remote_addresss` and the corresponding ID.

**Comment by adrianbenavides** [comment]
> Should the node_manager's registry store that information? I mean, remote_addresss and the corresponding ID.

Yes, I think so. The way we store this kind of information in the NodeManager is far from good, but we can tackle that separately.

**Comment by nidnogg** [comment]
Sounds good - I'll dig into it then. Since #4441 and this kind of depend on the same registry add-on I'll tackle this one as well

**Comment by nidnogg** [comment]
The recently drafted `forwarder list` & `forwarder show` PR (https://github.com/build-trust/ockam/pull/4582) has a possible solution to storing the forwarders `remote_address` fields and their corresponding info. While it only has the `list` command for now, upon feedback I'll include the `show` command as well as it can be implemented in a very similar fashion.
