### ISSUE TITLE
Create clap command to delete an existing Forwarder on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4437]
### Current behavior

Missing command for `forwarder delete`.

### Desired behavior

Implement a command that deletes a forwarder from a running node given its name.

```bash
ockam forwarder delete [name] --at [node-name]
```

Required args:
- name

Optional args:
- at: defaults to the default node

Output: show a message to confirm the deletion of the forwarder.

```bash
Deleted forwarder 'fwd-name' on node 'node-name'
```

Similar command: [`tcp-outlet delete`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L14)

**Comment by h20220145** [comment]
@adrianbenavides , can i take this ?

**Comment by adrianbenavides** [comment]
Yes, all yours!

**Comment by h20220145** [comment]
Hey , @adrianbenavides  can I get some pointers on how to write the delete_forwarder function in NodeManagerWorker ?

**Comment by adrianbenavides** [comment]
Sure, we now have a registry for the forwarders here: 

https://github.com/build-trust/ockam/blob/20e9fcabb4533707f55141b2b543ad4a2619c6a9/implementations/rust/ockam/ockam_api/src/nodes/registry.rs#L217

The `delete` function should remove the forwarder from the registry as well as stop the worker, which can be stopped using its address stored in the registry entry ([RemoteForwarderInfo](https://github.com/build-trust/ockam/blob/20e9fcabb4533707f55141b2b543ad4a2619c6a9/implementations/rust/ockam/ockam/src/remote/info.rs#L11)).

As for the command output, we are integrating a new format. It should be similar to what we have in the [`node delete` command](https://github.com/build-trust/ockam/blob/20e9fcabb4533707f55141b2b543ad4a2619c6a9/implementations/rust/ockam/ockam_command/src/node/delete.rs#L44).

Let me know if there is something else you need to know!

**Comment by h20220145** [comment]
@adrianbenavides How can i stop a forwarder using its worker address , I looked around a lot but couldn't find how to do that ?

Also can you look at the function structure and see if its okay ? Thanks.
  
       pub(super) async fn delete_forwarder(
        &mut self,
        ctx: &mut Context,
        req: &Request<'_>,
        alias: &'a str,
    ) -> Result<Vec<u8>> {
        let mut node_manager = self.node_manager.write().await; //

        debug!(alias = %req.alias(), "Handling DeleteForwarder request");

        if let Some(forwarder_to_delete) = node_manager.registry.forwarders.remove(alias) {
            debug!(%alias, "Successfully removed forwarder from node registry");

            let was_stopped = node_manager
               ///????
                .(forwarder_to_delete.worker_address.clone())
                .await
                .is_ok();

            if was_stopped{
                debug!(%alias, "Successfully stopped forwarder");
            }
            else {
                error!(%alias, "Failed to delete forwarder from node registry");

            }


        }
        else{
            error!(%alias, "Forwarder not found in the node registry");


        }

**Comment by adrianbenavides** [comment]
You can stop it with `ctx.stop_worker(worker_address)`. The function looks good, should be something along those lines.

**Comment by h20220145** [comment]
In the command format is the name argument the remote address or alias ? also in the key value of the forwarders BTreeMap which is used to get RemoteForwarderInfo

**Comment by h20220145** [comment]
im having some difficulties in creating a forwarder to test the delete command , I tried using the guide in [https://docs.ockam.io/](url) but that wasn't working . how can i set the default project to create a forwarder ?

Thanks

**Comment by adrianbenavides** [comment]
> In the command format is the name argument the remote address or alias ? also in the key value of the forwarders BTreeMap which is used to get RemoteForwarderInfo

You should look how forwarders are inserted in the registry. This is done in the [`create_forwarder` method](https://github.com/build-trust/ockam/blob/926c060e3aa675f6c1d883edb3d8b8c66a20e2ec/implementations/rust/ockam/ockam_api/src/nodes/service/forwarder.rs#L86).


> im having some difficulties in creating a forwarder to test the delete command , I tried using the guide in [https://docs.ockam.io/](https://github.com/build-trust/ockam/issues/url) but that wasn't working . how can i set the default project to create a forwarder ?

You have a bunch of examples of how to use forwarders (now called relays) in the [bats tests](https://github.com/build-trust/ockam/blob/926c060e3aa675f6c1d883edb3d8b8c66a20e2ec/implementations/rust/ockam/ockam_command/tests/bats/unit.bats#L370). You should look for those that don't need a project.

**Comment by h20220145** [comment]
Thanks , i tried the code i wrote and it deletes the forwarder successfully(on an older build)

 the issue is on the latest build when i try the create a node it shows up as "DOWN" and ockam node start does nothing so i wasn't able create a forwarder/relay between two nodes
