### ISSUE TITLE
Create clap command to delete an existing secure-channel listener on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4438]
### Current behavior

Missing command for `secure-channel-listener delete`.

### Desired behavior

Implement a command that deletes a secure channel listener from a running node given its address.

```bash
ockam secure-channel-listener delete [address] --at [node-name]
```

Required args:
- address: the listener's address

Optional args:
- at: defaults to the default node

Output: show a message to confirm the deletion of the listener.

```bash
Deleted secure-channel listener with address '/service/...' on node 'node-name'
```

Similar command: [`tcp-outlet delete`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L14)

**Comment by chanman3388** [comment]
Could this be assigned to me? I have a branch on my own fork that is nearly there?

**Comment by mrinalwadhwa** [comment]
Of course @chanman3388 all yours.

**Comment by chanman3388** [comment]
A few questions come to mind, is the `--at` flag a required flag?

**Comment by adrianbenavides** [comment]
> Optional args:
> 
> at: defaults to the default node

Yes! You can also check other commands like [this one](https://github.com/build-trust/ockam/blob/cb8be7a73146bccb64cbfe0247b5b8bd59c33981/implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs#L25) to learn how we handle it, although the wrapper struct (TCPListenerNodeOpts) is not necessary.
