### ISSUE TITLE
Create clap command to list the existing forwarders on a node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4441]
### Current behavior

Missing command for `forwarder list`.

### Desired behavior

Implement a command that retrieves from a running node the list of registered forwarders.

```bash
ockam forwarder list --at [node-name]
```

Required args: none

Optional args:
- at: defaults to the default node. Use the `NodeOpts` struct to define this argument.

Output: list of items with the same information per item as described at [`forwarder show`](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/forwarder/create.rs#L81).

Similar command: [`tcp-inlet list`](https://github.com/build-trust/ockam/blob/fba16afa8ca1a2130819737d6804480a31996a5b/implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs#L23)

**Comment by nidnogg** [comment]
I'll take this one

**Comment by nidnogg** [comment]
After looking into this, I ran into a similar question that @CAOakleyII mentioned in https://github.com/build-trust/ockam/issues/4436. Specifically,
>Another thing that's important to note for this task and the https://github.com/build-trust/ockam/issues/4441 is that we currently don't have an easy way to access the forwarders currently created for a node.
The node_manager's registry does not store that information.

If it doesn't - then where would these be fetched from? @adrianbenavides do you believe adding a new `BTreeMap`  registry would be too overkill for this? Or is there another info struct from the `node` services that could be parsed from `ockam_api`?

**Comment by adrianbenavides** [comment]
I'd go the easy way for now. We have to refactor the whole registry, but that can wait. (more context: https://github.com/build-trust/ockam/issues/4436#issuecomment-1484478350)

**Comment by nidnogg** [comment]
I've drafted a PR (https://github.com/build-trust/ockam/pull/4582) with a possible solution - however I'm not too sure about some of the changes I've had to make to get it to work. Let me know if this is more or less the way to go.
