### ISSUE TITLE
Create a struct to encapsulate the ApiTransport fields currently represented as a tuple

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4442]
ref: https://github.com/build-trust/ockam/pull/4172#discussion_r1119875952

### Current behavior

The `api_transport` field of the `NodeManagerTransportOptions` object is represented as a tuple. It contains four objects and it's hard to understand and use in its current form. 

### Desired behavior

Refactor the [`api_transport`](https://github.com/build-trust/ockam/blob/fba16afa8ca1a2130819737d6804480a31996a5b/implementations/rust/ockam/ockam_api/src/nodes/service.rs#L213) into a struct called `ApiTransport` and add docs for every field.

With this struct, refactor the [`TransportStatus::new`](https://github.com/build-trust/ockam/blob/fba16afa8ca1a2130819737d6804480a31996a5b/implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs#L161) constructor to take the `transport_id` and an `ApiTransport` instance to reduce the number of arguments and have less duplication.

**Comment by JungleTryne** [comment]
I could take this one

**Comment by adrianbenavides** [comment]
Awesome, thanks @JungleTryne, I'll review the PR later today 👍
