### ISSUE TITLE
Support for Ockam in a browser/front-end app

### ISSUE THREAD

**Issue by glenngillen** [build-trust/ockam#4458]
### Current behavior

It's not possible to use Ockam in the browser as the only programming library that is currently available is in Rust.

### Desired behavior

I'd love to build an example that is usable within a web browser. I think this probably requires javascript/typescript bindings though I don't want to assume too much about the final implementation has to look like.

**Comment by nidnogg** [comment]
Would a simple vite app fetching data from an axum backend via ockam fit the bill in this case? I'd be interested in setting up a template if so

**Comment by adrianbenavides** [comment]
@glenngillen should we close this one?
