### ISSUE TITLE
create command for tcp-listener doesn't implement the body

### ISSUE THREAD

**Issue by 0xkelvin** [build-trust/ockam#4464]
### Observed behavior

related to this https://github.com/build-trust/ockam/issues/4419#issuecomment-1467679970

### Steps to reproduce

ockam tcp-listener create [addr]

### Expected behavior

post to Node Manager with body

### Ockam Version

latest

**Comment by 0xkelvin** [comment]
PR here https://github.com/build-trust/ockam/pull/4463

**Comment by etorreborre** [comment]
fixed with https://github.com/build-trust/ockam/pull/4463
