### ISSUE TITLE
Several "use of `ok_or` followed by a function call" warnings

### ISSUE THREAD

**Issue by nidnogg** [build-trust/ockam#4472]
### Observed behavior

When running `cargo clippy`, plenty of warnings like the following show up in `ockam_vault/src` and `ockam_api/src/nodes/service/message.rs`:

```bash
warning: use of `ok_or` followed by a function call
  --> implementations/rust/ockam/ockam_vault/src/symmetric_impl.rs:75:14
   |
75 |             .ok_or(VaultError::EntryNotFound(format!("aes key {key_id:?}")))?;
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `ok_or_else(|| VaultError::EntryNotFound(format!("aes key {key_id:?}")))`
```

### Steps to reproduce

Run `cargo clippy`

### Expected behavior

No warnings shown, or perhaps having the `#[allow(clippy::or_fun_call)]` attribute added in these cases.

### Ockam Version

0.82.0

**Comment by adrianbenavides** [comment]
What version of rust are you using? With 1.68 you should only see one warning (`clippy::derive_hash_xor_eq`) which can't be fixed until we upgrade the rust version used in CI.

**Comment by nidnogg** [comment]
True enough - I was using 1.66 during testing. Closing as it seems to be OK!

**Comment by adrianbenavides** [comment]
Great, thanks for reporting it anyways!
