### ISSUE TITLE
Rename `ockam policy set/get ...` to `ockam policy create/show ...`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4488]
### Current behavior

Here's a full example of policies in action
https://docs.ockam.io/guides/use-cases/apply-fine-grained-permissions-with-attribute-based-access-control-abac#step-by-step-walkthrough

The current commands are 

```
ockam policy set ...
```

and 

```
ockam policy get ...
```

The source code is here:
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/policy

### Desired behavior

Rename the `set` command to

```
ockam policy create ...
```

Rename the `get` command to

```
ockam policy show ...
```

**Comment by MehSalhi** [comment]
I can take this one.

**Comment by davide-baldo** [comment]
:+1: All yours!
please let me know if you need some extra pointers!
