### ISSUE TITLE
Support private Kafka brokers

### ISSUE THREAD

**Issue by glenngillen** [build-trust/ockam#4490]
### Current behavior

The current `confluent` add-on allows end-to-end encryption of data through Confluent Cloud, but it can't be used for any Kafka broker that is not directly accessible from the public internet.

### Desired behavior

Allow private Kafka brokers to be configured in a similar fashion to the Confluent Cloud add-on. My initial approach on how to do this would have been to make the local/private broker available via an Ockam forwarder, but it's not possible to configure the existing add-on to point to a forwarder. 

A complete example of what I was thinking this might look like is:

```bash
ockam enroll

ockam project information --output json > project.json

export OCKAM_BROKER_TOKEN=$( \
  ockam project enroll --attribute component=kafkabroker)

ockam node create kafkrabroker \
  --project project.json \
  --enrollment-token $OCKAM_BROKER_TOKEN

ockam policy create \
  --at kafkrabroker \
  --resource tcp-outlet \
  --expression '(= subject.component "do-i-specify-the-addon-or-the-producersconsumers-here-or-both")'

ockam tcp-outlet create \
  --at /node/kafkabroker \
  --from /service/outlet \
  --to 127.0.0.1:29092

ockam forwarder create broker \
  --at /project/default \
  --to /node/kafkabroker

ockam project addon configure kafka \
  --bootstrap-server /project/default/service/forward_to_broker/secure/api/service/outlet
```

**Comment by mrinalwadhwa** [comment]
This is now supported.
We need work on some docs for this.
