### ISSUE TITLE
Typo in the tcp-inlet --help command

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4503]
### Observed behavior

We can read
```
delete  Delete a TCP Outlet
```

### Steps to reproduce

```
ockam tcp-inlet -h
```

### Expected behavior

We should read 
```
delete  Delete a TCP Inlet
```

### Ockam Version

0.82.0

**Comment by nidnogg** [comment]
Whoops, my bad from a previous PR. I'll take this one

**Comment by nidnogg** [comment]
Fixed at https://github.com/build-trust/ockam/pull/4525

**Comment by etorreborre** [comment]
Thanks @nidnogg!
