### ISSUE TITLE
Update `delete` commands output according to our new output template

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4512]
### Current behavior

The output of the `delete` commands is not consistent.

### Desired behavior

For each of the described commands:
1. Update the output following the output template
2. If necessary (most likely not), update the tests to handle the new output format

There are some complex tests that rely on the current output format of multiple commands, so it is recommended to open one PR for each command to make the transition as safe and painless as possible.

### Output template

In this section we describe the template to be used to write the output. The `subject`, `identifier_name` and `identifier` depend on the command and are described in the next section.

As an example, you can see how to apply the new format at https://github.com/build-trust/ockam/pull/4248, [code](https://github.com/build-trust/ockam/pull/4248/files#diff-056b7ff3db2714e9c9b6257bda648e18bf11ca71360c2176d6a41d91dada74b7R38-R47).

#### Plain

The `✔︎` must be colored in green: `"✔︎".light_green()`.

```bash
✔︎ {subject} with {identifier_name} {identifier} has been deleted.
```

#### Machine

```bash
{identifier}
```

#### JSON

```bash
{
  <subject>: {
    <identifier_name>: <identifier>
  }
}
```

### Commands to update

- [x] node delete: `subject`: `Node`; `identifier_name`: `name`; `identifier`: the name of the node. This was done as an example at https://github.com/build-trust/ockam/pull/4248
- [x] tcp-listener delete: `subject`: `TCP listener`; `identifier_name`: `ID`; `identifier`: the ID of the TCP listener stored in the NodeManager registry 
- [x] tcp-connection delete: `subject`: `TCP connection`; `identifier_name`: `ID`; `identifier`: the ID of the TCP connection stored in the NodeManager registry 
- [x] tcp-inlet delete: `subject`: `TCP inlet`; `identifier_name`: `alias`; `identifier`: the alias of the TCP inlet stored in the NodeManager registry 
- [x] tcp-outlet delete: `subject`: `TCP outlet`; `identifier_name`: `alias`; `identifier`: the alias of the TCP outlet stored in the NodeManager registry 
- [x] vault delete: `subject`: `Vault`; `identifier_name`: `name`; `identifier`: the name of the vault 
- [x] identity delete: `subject`: `Identity`; `identifier_name`: `name`; `identifier`: the name of the identity 
- [x] secure-channel-listener delete: `subject`: `Secure channel listener`; `identifier_name`: `address`; `identifier`: the address of the secure channel
- [x] secure-channel delete: `subject`: `Secure channel`; `identifier_name`: `address`; `identifier`: the address of the secure channel
- [x] space: `subject`: `Space`; `identifier_name`: `name`; `identifier`: the name of the space 
- [x] project: `subject`: `Project`; `identifier_name`: `name`; `identifier`: the name of the project

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by MehSalhi** [comment]
I will look into that one.

**Comment by adrianbenavides** [comment]
Sure, if you want, you can leave a comment here with the command you want to modify, so other people interested in this issue don't pick the same.

Let us know if you have any question 👍

**Comment by MehSalhi** [comment]
I will start with  tcp-listener and tcp-connection and update my progress here if anyone wants to start with other commands.

**Comment by nidnogg** [comment]
Since I worked on `tcp-outlet` and `tcp-inlet` recently, I'll format them accordingly

**Comment by nidnogg** [comment]
BTW, could this maybe be abstracted/contained away in an `util.rs` function? I foresee a lot of boilerplate resulting from all these commands

**Comment by nidnogg** [comment]
Added `tcp-inlet delete` and `tcp-outlet delete` at https://github.com/build-trust/ockam/pull/4525

**Comment by MehSalhi** [comment]
> I will start with tcp-listener and tcp-connection and update my progress here if anyone wants to start with other commands.

Actually, I still lack understanding on how tcp-listener and tcp-connection work and am unable to create / delete them for now so I won't be able to test the delete commands.

I will start with space, vault and project in the meantime.

If anyone can give me a minimum working setup example for tcp-listener and tcp-connection (couldn't find in the documentation) or modify the delete command themselves, you're welcome to do so.

**Comment by adrianbenavides** [comment]
> BTW, could this maybe be abstracted/contained away in an `util.rs` function? I foresee a lot of boilerplate resulting from all these commands

I thought about that and my conclusion was that it's just too soon for that. We are still trying to define the full content of the output messages and they may be different for each command. I prefer to have the ability to just modify only the file of the command I want to change, rather than having a function that tries to adapt to all the possible cases and that could result in breaking changes in all the commands using it when updating it.

**Comment by MehSalhi** [comment]
I opened the PR #4530 to fix vault, project and space. 

For the other commands (identity,secure-channel-listener, tcp-listener, tcp-connection, secure-channel) I am unable to use the create command to test the deletion. I receive errors. 

For exemple, the following command: 

`ockam secure-channel-listener create --at m1 127.0.0.1:7000`

Output:

`IO error. Caused by: No such file or directory (os error 2)`

I don't know the prerequisite to use these commands so in the meantime anyone can fix them while I try to understand how this works.

**Comment by MehSalhi** [comment]
I opened the PR #4531 that will fix the following command :

- project delete
- space delete
- vault delete

For the remaining ones (tcps and secure), I am unable to use the create command so I can't test the deletion. I don't know the requirements to be able to create a tcp-listener or a secure-channel listener and I receive IO errors when I try to do so.

If anyone wants to implement them you're welcome to do so.

**Comment by chanman3388** [comment]
I'll update the secure-channel-listener seeing as how I worked on that recently.

**Comment by adrianbenavides** [comment]
Most of the work of this issue has been done. I'll open specific issues for any missing detail we have left.
