### ISSUE TITLE
Replace Ockam Hub mentions in the codebase with appropriate terms

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4520]
### Current behavior

We have mentioned Ockam Hub in the codebase a lot, while Ockam Hub as a term doesn't exist anymore. This includes doc comments as well as variable names (e.g. `hub_route`)

### Desired behavior

Rename with Ockam Orchestrator / Ockam Orchestrator Project 

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by mrinalwadhwa** [comment]
@SanjoDeundiak is this still relevant?

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa yes

**Comment by PsychoPunkSage** [comment]
Hi @SanjoDeundiak 
Can I work on this issue. it seems no one is working on it. Can I have a look at this?

**Comment by SanjoDeundiak** [comment]
@PsychoPunkSage sure, go ahead!

**Comment by PsychoPunkSage** [comment]
@SanjoDeundiak 
you can have a look at the PR... I tried to replace all the instances.
Thank You
