### ISSUE TITLE
Pin Telegraf dockerfile images

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4521]
### Current behavior

We currently use a versioned image of telegraf https://github.com/build-trust/ockam/blob/1b7d42a3e870e4bdef20fff7e3ead302edfb1d6b/demos/influxdb-telegraf/telegraf/Dockerfile#L1-L1

### Desired behavior

We should pin images used by us with their SHA equivalent e.g 
```dockerfile
FROM telegraf@sha256_some_valid_sha_version
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by zacck** [comment]
@metaclips  shouldn't this be closed since it's PR was merged?

**Comment by metaclips** [comment]
Yeah, it should.
