### ISSUE TITLE
Use pre-installed version of commit lint in `ockam-builder` docker image

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4522]
### Current behavior

To lint commit, we currently install commit-lint for every lint_commit job run which increases time for CI test to complete https://github.com/build-trust/ockam/blob/1b7d42a3e870e4bdef20fff7e3ead302edfb1d6b/.github/workflows/all.yml#L90-L91 

### Desired behavior

We now have commit-lint pre-installed into our [builder image](https://github.com/build-trust/ockam-artifacts/pkgs/container/ockam-builder) https://github.com/build-trust/ockam/blob/1b7d42a3e870e4bdef20fff7e3ead302edfb1d6b/tools/docker/builder/Dockerfile#L80-L81
we should use our builder image as our default image in the `lint_commits job`.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by chanman3388** [comment]
May I take this?

**Comment by etorreborre** [comment]
@chanman3388 absolutely, you're welcome!

**Comment by chanman3388** [comment]
Something I needed to ask, are you expecting the docker image for ockam-builder to be built during the workflow? Or do you have a registry that you want the image pulled from?

Or does a job need to be created to build the builder image a bit like this workflow? https://github.com/build-trust/ockam/actions/runs/854017429/jobs/836428411

**Comment by metaclips** [comment]
> Something I needed to ask, are you expecting the docker image for ockam-builder to be built during the workflow? Or do you have a registry that you want the image pulled from?
> 
> Or does a job need to be created to build the builder image a bit like this workflow? https://github.com/build-trust/ockam/actions/runs/854017429/jobs/836428411

We don't need to build the image as that has already been done, the recent `ockam-builder` image https://github.com/build-trust/ockam/blob/a111ea94bcbf4f0df31887b08e839deb06e3c5ba/.github/workflows/rust.yml#L55 already has support for commitlint.

**Comment by itsajay1029** [comment]
Can I work on this @etorreborre @metaclips ?

**Comment by metaclips** [comment]
> Can I work on this @etorreborre @metaclips ?

@chanman3388 are you still taking this up?

**Comment by chanman3388** [comment]
> > Can I work on this @etorreborre @metaclips ?
> 
> @chanman3388 are you still taking this up?

No I'm not, you're welcome to it!

**Comment by metaclips** [comment]
@itsajay1029 assigned to you, do ask if you need more clarification

**Comment by nazmulidris** [comment]
@itsajay1029 Thank you for taking the time to look at this issue. Since you’ve not had a chance we’re opening the issue up for other contributors.

**Comment by Salonikansal2** [comment]
I have submitted by pr for this issue .please check @metaclips
