### ISSUE TITLE
Pin Influxdbdockerfile images #4521

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4523]
### Current behavior

We currently use a versioned image of influxdb https://github.com/build-trust/ockam/blob/1b7d42a3e870e4bdef20fff7e3ead302edfb1d6b/demos/influxdb-telegraf/influxdb/Dockerfile#L1-L1

### Desired behavior

We should pin images used by us with their SHA equivalent e.g 
```dockerfile
FROM influxdb@sha256:some_valid_sha_version
```

**Comment by mrinalwadhwa** [comment]
This added in https://github.com/build-trust/ockam/pull/4573
