### ISSUE TITLE
Refactor the processing of environment variables

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4549]
### Current behavior

Environment variables are processed in a dozen of places and could benefit from a more consistent treatment (see [this PR comment](https://github.com/build-trust/ockam/pull/4548#discussion_r1148944486) for an example)

### Desired behavior

Refactor the access to environment variables as a function 
```rust
pub fn get_env<T: FromString>(var_name: &str, default_value: T): Result<T>
```

where

 - `FromString` is a trait used to parse strings into values, with implementations for `String`, comma-separated list of strings, `bool`, `u8`, etc... (it cannot be `FromStr` because we want to accept values like `TRUE` or `1` for booleans)
 - `default_value` is returned if the variable is missing
 - an `Err` is returned if the value cannot be parsed

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by JungleTryne** [comment]
I could take that

**Comment by etorreborre** [comment]
That would be great, thanks! Please don't hesitate to ask questions if you need more directions.

**Comment by JungleTryne** [comment]
I have a couple of questions to clarify the implementation details:
1) What is the best place to declare this function?
2) Is it basically "try to get env with name `var_name`, if it doesn't exist, then return the default value"?

**Comment by JungleTryne** [comment]
And also,
3. Where can I find implementation of `FromString` trait? Or do I need to implement it myself?

**Comment by etorreborre** [comment]
@ JungleTryne `FromString` would be a new trait with default implementations. Let me try to write a more complete specification for this feature :-):

**Function** 

Signature
```rust
pub fn get_env<T: FromString>(var_name: &str, default_value: T): ockam_core::Result<T>
```
This function must be available with unit tests in `ockam_core/src/env.rs`

 - if an env. var does not exist the default value is returned
 - if an env. var exists, decode it with the corresponding `FromString` instance
   - if its value cannot be decoded, this is an `Err` which should specify: the erroneous value and the expected type

**FromString trait**

```rust
trait FromString<T> {
   fn from_string(str: String): ockam_core::Result<T>
}
```

This trait must be available in `ockam_core/src/env.rs`

The `FromString` behaviour for the following types is:

 - `bool` accepts `true` or `false` whether they are capitalized or not, accepts `1` for `true` and `0` for `false`
 - `u<n>` accepts any string representing a `u<n>` (where `n` is `8, 16, 32, 64, size`)
 - `char` is accepted if the string is just one character
 - `String` is accepted as it is
 - `Vec<T>` is accepted if it is a comma-delimited list of strings where each string represents a `T: FromString`

**Scope**

All the code that is currently using `std::env::var` or `std::env::var_os` (16 matches) should be retrofitted to use that function.

**Comment by JungleTryne** [comment]
Thanks for the great explanation! What do you think would be the best way to test get_env? Do I just set env variables in the unit tests by env::set_var, or there is a way to mock it properly?

**Comment by etorreborre** [comment]
Good question. Ideally, at some stage, I would like to have interfaces and mocks for all the IO in the library: to read environment variables, but also to read/write files. In the meantime I suggest that you indeed use `env::set_var` (with a dummy variable name to avoid possible clashes with other tests, like `OCKAM_TEST_ENV_VAR`).  There are mostly 3 tests to do:

 - the env var is found and can be parsed
 - the env var is found but cannot be parsed
 - the env var is not found

The other tests are pure unit tests on the `FromString` instances.

**Comment by JungleTryne** [comment]
I noticed that in some places when the env var value is not found an error is returned. There are several ways to handle this case:

* Make `default_value` optional. And if `default_value` is not specified then the function with return an error:
```Rust
pub fn get_env<T: FromString>(var_name: &str, default_value: impl Into<Option<T>>): Result<T>
```

* Make `default_value` optional the other way
```Rust
let result = get_env::<String>("SOME_VAR")
    .with_default("Hello")
    .done()
```

I would apprericate if you could help me figure it out!

**Comment by etorreborre** [comment]
Good point. I propose a variation to avoid the option and give some flexibility to the client of `get_env`

 - `get_env` which returns a `Result<Option<T>>`, and `Ok(None)` if the variable is not found to let the client decide what to do with it (maybe access another variable or raise an error). We keep the `Result` only for parsing errors
 - `get_env_with_default` which returns `Result<T>` and uses a default value if the environment variable is not set
