### ISSUE TITLE
Cannot cargo build versions 0.78 to 0.82 (latest)

### ISSUE THREAD

**Issue by maxcurzi** [build-trust/ockam#4550]
### Observed behavior

On Rust 1.68.1  (  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.68.1 (8460ca823 2023-03-20) )

Follow the basic tutorial instructions https://docs.ockam.io/reference/libraries/rust

`cargo new --lib hello_ockam && cd hello_ockam && mkdir examples  && cargo add ockam && cargo build`

```
 cargo build                                                                                                                             
   Compiling ockam_vault v0.72.0
error[E0432]: unresolved import `p256::ecdsa::__self`
  --> /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/ockam_vault-0.72.0/src/signer_impl.rs:72:43
   |
72 |                         use p256::ecdsa::{self, signature::Signer as _};
   |                                           ^^^^ no `__self` in `ecdsa`

error[E0433]: failed to resolve: use of undeclared crate or module `ecdsa`
  --> /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/ockam_vault-0.72.0/src/signer_impl.rs:76:34
   |
76 |                         let sig: ecdsa::Signature = sec.sign(data);
   |                                  ^^^^^ use of undeclared crate or module `ecdsa`

error[E0433]: failed to resolve: use of undeclared crate or module `ecdsa`
  --> /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/ockam_vault-0.72.0/src/signer_impl.rs:74:35
   |
74 |                         let sec = ecdsa::SigningKey::from_pkcs8_der(key).map_err(from_pkcs8)?;
   |                                   ^^^^^ use of undeclared crate or module `ecdsa`
   |
help: consider importing this type alias
   |
1  | use p256::ecdsa::SigningKey;
   |
help: if you import `SigningKey`, refer to it directly
   |
74 -                         let sec = ecdsa::SigningKey::from_pkcs8_der(key).map_err(from_pkcs8)?;
74 +                         let sec = SigningKey::from_pkcs8_der(key).map_err(from_pkcs8)?;
   |

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `ockam_vault` due to 3 previous errors
```

### Steps to reproduce

cargo new --lib hello_ockam && cd hello_ockam && mkdir examples  && cargo add ockam && cargo build

### Expected behavior

Example should build

### Ockam Version

0.78.0, 0.79.0, 0.80.0, 0.81.0, 0.82.0

**Comment by maxcurzi** [comment]
Note that this only happens on crates with ockam as a dependency.
The code in repository builds and runs just fine

**Comment by etorreborre** [comment]
Hi @maxcurzi I think we had an issue with `cargo update`. I think you possibly need [this commit](https://github.com/build-trust/ockam/commit/4c55d285be4f52bbe819631d275accf675e28405) to fix the situation.

**Comment by maxcurzi** [comment]
Thanks @etorreborre for this workaround. The commit worked just fine. 

Regarding the error as a crate user, should I post it to the [discussion section](https://github.com/build-trust/ockam/discussions) and close this issue?

**Comment by etorreborre** [comment]
Yes, this is a great idea, thanks!
