### ISSUE TITLE
Display the available environment variables in the ockam command help

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4554]
### Current behavior

There are a few environment variables which can be used to control the behaviour of the `ockam` command. For example `OCKAM_LOG`, `OCKAM_HELP_RENDER_MARKDOWN`, `OCKAM_HELP_SHOW_HIDDEN` etc... (see [here](https://github.com/build-trust/ockam/pull/4548#discussion_r1149397266))

### Desired behavior

We could add a section to the full help displaying each variable on a line and showing:
 
 - its meaning
 - its expected type (bool, string, int, ...)
 - its default value (when the environment variable is not defined)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by murex971** [comment]
I'd like to take this one.

**Comment by etorreborre** [comment]
Hi @murex971, please do! I'm cc-ing @CAOakleyII and @adrianbenavides who know more than me about the structure and documentation of the command-line UI

**Comment by zacck** [comment]
@murex971  are you still on this?

**Comment by murex971** [comment]
@zacck no, i have been busy with some other work.

**Comment by zacck** [comment]
@murex971  mind if I try and tackle it?

**Comment by murex971** [comment]
go ahead!

**Comment by zacck** [comment]
Thanks, @CAOakleyII @adrianbenavides  any pointers on how one could get started with this would be mightly appreciated.

**Comment by adrianbenavides** [comment]
Hey @zacck! You could start adding the content in this constant: https://github.com/build-trust/ockam/blob/a111ea94bcbf4f0df31887b08e839deb06e3c5ba/implementations/rust/ockam/ockam_command/src/docs.rs#L15 We will move it to its own file in the near future, but let's keep it simple for this issue. 

As for the available env vars, you will find most of them, if not all, if you `ctrl+f` "env::var" in the `ockam_command` and `ockam_api` crates. A bunch of them have documentation in the code; those that doesn't are easy to understand by their context, but let us know if you find any that you don't understand or if you have any other question!

**Comment by zacck** [comment]
@adrianbenavides thank you so much! I'll start here.

**Comment by zacck** [comment]
@adrianbenavides I have #4596 going does this look good and any more info on the couple of command missing and the meanings?
