### ISSUE TITLE
update `ockam tcp-outlet create` clap command to have defined default arguments

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4598]
### Current behavior
The `ockam tcp-outlet create` command is defined [here.](https://github.com/build-trust/ockam/blob/a2d0bb0e5974c133483fdb3bc72ae4f697001927/implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs#L18)

When creating a tcp-outlet these are the currently required parameters.

```sh
ockam tcp-outlet create --at /node/influxdb --from /service/outlet --to 127.0.0.1:8086
```

```sh
--at # requires a node address
--from # requires a service outlet address on the node
--to # dictates a port on the loopback address
```
We can infer and use defaults for most of these values

### Desired behavior

The desired state for a default command to create a tcp-outlet looks like this:

```sh
ockam tcp-outlet create --to 8086
```

This assumes:
--at uses the default node; this is already implemented [here.](https://github.com/build-trust/ockam/blob/a2d0bb0e5974c133483fdb3bc72ae4f697001927/implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs#L20)
--from uses the default service outlet address (/service/outlet)
--to accepts (IP:PORT) or (PORT) 
     * if only a port is provided - it assumes the address will always be on a loopback address (127.0.0.1)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by zacck** [comment]
I'd like to try and tackle this one as well. Could you please assign this to me.

**Comment by SanjoDeundiak** [comment]
All yours @zacck , thank you!

**Comment by etorreborre** [comment]
This has eventually been implemented in this PR: https://github.com/build-trust/ockam/pull/4721
