### ISSUE TITLE
rename `ockam forwarder` clap commands to `ockam relay` 

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4609]
### Current behavior

[Currently there are several `ockam forwarder` commands](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/forwarder/mod.rs)

```sh
ockam forwarder create
ockam forwarder list
ockam forwader show
```

As well as documentation, code examples, and bats integration tests that refer to these commands.

### Desired behavior

Update the naming of these commands to `ockam relay`

```sh
ockam relay create
ockam relay list
ockam relay show
```
and surrounding documentation, code examples, and bats integration test

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by lvllvl** [comment]
Do I need to be assigned to this before I can submit? I'd like to try this out.

**Comment by mrinalwadhwa** [comment]
@lvllvl it looks like there is already some work started on this in #4661 .. would you be interested in picking up a different issue?
