### ISSUE TITLE
create a default node and identity when a user runs`ockam enroll` and `ockam project authenticate` in an empty environment

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4611]
### Current behavior

Currently when using `ockam enroll` and `ockam project authenticate` no nodes or identities are created

### Desired behavior

[`ockam enroll`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll.rs)

[`ockam project authenticate`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/auth.rs)

Should both create a [`node`](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/node/create.rs#L492) and [`identity`](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/identity/create.rs#L44-L77) when the commands are successful and the environment does not have a node and/or identity.

The node should include the project information that the user just enrolled or authenticated to.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by adrianbenavides** [comment]
The `enroll` command doesn't create a node on purpose, as it relies only on an embedded/temporary node that is deleted after the command finishes. When creating that node, a default identity is created and persisted.

Same with the `project authenticate` command.

Do we need a background node for some reason in these commands?

**Comment by caoakleyii** [comment]
> The `enroll` command doesn't create a node on purpose, as it relies only on an embedded/temporary node that is deleted after the command finishes. When creating that node, a default identity is created and persisted.
> 
> Same with the `project authenticate` command.
> 
> Do we need a background node for some reason in these commands?

Yes, @adrianbenavides, we want the UX to be that when a user enrolls to a project; they will have a default environment setting with a node & identity already constructed for them.

**Comment by mrinalwadhwa** [comment]
It would be better to create a node on the first command that needs a node. enroll and project authenticate need an identity so those can be automatically created.

**Comment by caoakleyii** [comment]
PR approach to create a node when a command first needs it - https://github.com/build-trust/ockam/pull/4656

edit: PR now encompasses identity use case as well.

**Comment by polvorin** [comment]
@CAOakleyII  I think we can close this now?

**Comment by etorreborre** [comment]
yes, that has been fixed with https://github.com/build-trust/ockam/pull/4788
