### ISSUE TITLE
update `ockam service start kafka-producer/consumer` clap command to combine arguments `bootstrap-server-ip` and `bootstrap-server-port`

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4614]
### Current behavior

Currently when starting a kafka producer and consumer service, the [arguments to indicate the ip and port](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/service/start.rs#L62-L98) are separate such as:

```sh
ockam service start kafka-producer --node producer1 --project-route /project/default \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 5000 \
  --brokers-port-range 5001-5100
  ```
  
  ```
  ockam service start kafka-consumer --node consumer --project-route /project/default \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 4000 \
  --brokers-port-range 4001-4100
  ```

### Desired behavior

Update this command to allow for one singular argument, named `bootstrap-server` that accepts an `{IP}:{PORT}` or just `{PORT}` 

In the case of just a `PORT`, the ip address will should be the loopback address, `127.0.0.1`

```sh
ockam service start kafka-producer --node producer1 --project-route /project/default \
  --bootstrap-server 192.168.0.51:5000 \
  --brokers-port-range 5001-5100
```

```sh
ockam service start kafka-producer --node producer1 --project-route /project/default \
  --bootstrap-server 5000 \
  --brokers-port-range 5001-5100
```

```sh
ockam service start kafka-consumer --node consumer --project-route /project/default \
  --bootstrap-server 192.168.0.50:4000 \
  --brokers-port-range 4001-4100
```

```sh
ockam service start kafka-consumer --node consumer --project-route /project/default \
  --bootstrap-server 4000 \
  --brokers-port-range 4001-4100
```

Dev Notes
---

The commands implementation to use the [arguments](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/service/start.rs#L62-L98) are found [here](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L182-L233).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by nidnogg** [comment]
I'll take this one

**Comment by SanjoDeundiak** [comment]
Thank you, all yours @nidnogg !

**Comment by nidnogg** [comment]
I've put up a [draft PR](https://github.com/build-trust/ockam/pull/4648) for this as I have not yet been able to test this without a local Kafka installation (not sure if it's needed yet). LMK if it's headed in the right direction!
