### ISSUE TITLE
update `ockam service start kafka-consumer/producer` clap commands so that `--project-route` uses the default project 

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4615]
### Current behavior

Currently kafka consumer and producers require a project-route such as

```sh
ockam service start kafka-consumer --node consumer --project-route /project/default \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 4000 \
  --brokers-port-range 4001-4100
 ```
 
 ```sh
 ockam service start kafka-producer --node producer1 --project-route /project/default \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 5000 \
  --brokers-port-range 5001-5100
  ```

### Desired behavior

Add a default value, so that if the argument `--project-route`  is not passed, it should use `/project/default`

[Kafka Consumer Argument](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L77-L78)

[Kafka Producer Argument](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L95-L96)

Clap arguments have a macro to set the default value, example of this [here](https://github.com/build-trust/ockam/blob/af78ca3f6a971aa24ea8e5ff544bc17388f0dfab/implementations/rust/ockam/ockam_command/src/service/start.rs#L85).

```sh
ockam service start kafka-consumer --node consumer \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 4000 \
  --brokers-port-range 4001-4100
 ```
 
  ```sh
 ockam service start kafka-producer --node producer1  \
  --bootstrap-server-ip 127.0.0.1 --bootstrap-server-port 5000 \
  --brokers-port-range 5001-5100
  ```
  
  ---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0xkelvin** [comment]
hi @CAOakleyII i am working on this

draft PR here https://github.com/build-trust/ockam/pull/4616

**Comment by etorreborre** [comment]
This has eventually been implemented in this PR: https://github.com/build-trust/ockam/pull/4788
