### ISSUE TITLE
Create GitHub Action To Builld `ockam-healthcheck` Docker Image

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4638]
We have an elixir package called [ockam_healthcheck](https://github.com/build-trust/ockam/tree/develop/implementations/elixir/ockam/ockam_healthcheck) with a dockerfile in the [tools/docker/healthcheck/Dockerfile](https://github.com/build-trust/ockam/blob/develop/tools/docker/healthcheck/Dockerfile) file, we need to build the docker image with name `ockam-healthcheck` for every update to the `elixir/ockam_healthcheck` codebase.

**Comment by Guilospanck** [comment]
Hi, I wanna work (am working) on this one!

**Comment by metaclips** [comment]
Nice. Assigned task to you. Do ask here, or on your PR if you have any question.
