### ISSUE TITLE
Create GitHub Action To Build Ockam Command Artifact Image For Every Rust Code Merge To Develop Branch

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4639]
For every update to the [implementations/rust/ockam path](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam), we want to build an Artifact image (ockam-artifact) of ockam-command using this [dockerfile](https://github.com/build-trust/ockam/tree/develop/tools/docker/ockam)

**Comment by JBic9832** [comment]
so you want to use the docker file not a github actions config?
Edit: Nevermind I understand what you mean.

**Comment by metaclips** [comment]
> so you want to use the docker file not a github actions config?
> Edit: Nevermind I understand what you mean.

Nice, thanks. Feel free to ask questions if it’s unclear.

**Comment by itsajay1029** [comment]
Can you explain the issue please @metaclips ?
I'd like to contribute and also please assign this issue to me

**Comment by metaclips** [comment]
@JBic9832 still taking up the issue?

**Comment by metaclips** [comment]
> Can you explain the issue please @metaclips ?
> I'd like to contribute and also please assign this issue to me

We need to build artifact images of ockam-command for every merge to develop, we have a dockerfile already we need to create a GitHub action that will build the image.

**Comment by rghdrizzle** [comment]
@metaclips hey I would like to work on this if no one is working on this or if collaboration is open . So let me say what I understood , we have to create a pipeline where on every update in [implementations/rust/ockam](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam) it should trigger the pipeline to build the docker image and push it to the container registry ?

**Comment by metaclips** [comment]
> @metaclips hey I would like to work on this if no one is working on this or if collaboration is open . So let me say what I understood , we have to create a pipeline where on every update in [implementations/rust/ockam](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam) it should trigger the pipeline to build the docker image and push it to the container registry ?

Yes 💯. I'll be assigning the issue to you now, please ask here or on your PR if you have questions

**Comment by rghdrizzle** [comment]
> > @metaclips hey I would like to work on this if no one is working on this or if collaboration is open . So let me say what I understood , we have to create a pipeline where on every update in [implementations/rust/ockam](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam) it should trigger the pipeline to build the docker image and push it to the container registry ?
> 
> Yes 💯. I'll be assigning the issue to you now, please ask here or on your PR if you have questions

Thank you for assigning me . I have a few questions :
1. Do I have to create a new workflow in this[ .github/workflows](https://github.com/rghdrizzle/ockam/tree/action/.github/workflows)?
2. What about the container registry ? is it docker hub or somewhere private ? and what are the environment variables for them?

**Comment by metaclips** [comment]
1. Yes, lets name the workflow `docker-ockam-command-artifact`
2. We use GHCR, here's a workflow that builds our healthcheck image https://github.com/build-trust/ockam/blob/develop/.github/workflows/ockam-healthcheck.yml

**Comment by rghdrizzle** [comment]
@metaclips we can close this issue since it has been resolved.

**Comment by metaclips** [comment]
Yes we can. Thanks
