### ISSUE TITLE
Create an `osv-scanner` Toml File To Ignore Vulnerable Dependency That Does Not Affect Our Crates

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#4651]
We use [osv-scanner](https://github.com/google/osv-scanner) to check for vulnerable dependencies in our libraries, we need to add an `osv-scanner.toml` file in the root path and also [ignore certain vulnerability ID that don't affect our crates ](https://google.github.io/osv-scanner/configuration/#ignore-vulnerabilities-by-id)

These are the vulnerability in our crate we want to ignore and the reasons why
RUSTSEC-2021-0145 - Affects windows OS which we don't support currently
RUSTSEC-2021-0127 - Unmaintained crate pulled-in by cddl-cat which is used for validating CDDL schema conformance in tests
RUSTSEC-2022-0048 - xml-rs unmaintained crate pulled in from a transitive dependency serde-xml-rs

**Comment by itsajay1029** [comment]
Can you assign this issue to me @metaclips ? I'd love to work on this. Also, please ellaborate on the issue

**Comment by metaclips** [comment]
> Can you assign this issue to me @metaclips ? I'd love to work on this. Also, please ellaborate on the issue

Nice, assigning to you now.
We need a default osv-scanner config, in the config file we should ignore crates that are specified as `unmaintained`, I specified the crates we want to ignore in the main post. To ignore crates you can check here https://google.github.io/osv-scanner/configuration/#ignore-vulnerabilities-by-id.

**Comment by itsajay1029** [comment]
Please check the PR #4882  @metaclips
