### ISSUE TITLE
Remove `rustcrypto` feature from `ockam_vault`

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4704]
`rustcrypto` feature allows us to enable/disable P256 support. However, extra effort is needed to make it usable, as disabling it will result in a failed compilation and causes other problems ([see here](https://github.com/build-trust/ockam/issues/3661#issuecomment-1508089713)). The short-term solution is to remove that feature and make P256 support non-optional (always enabled). A long-term solution could be either:
1. Make P256 `SecretType` optional under the feature flag as well
2. Change `compile_error!` to a runtime error
Also, disabling this feature should disable corresponding crate dependencies, which is not implemented atm.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by EliKalter** [comment]
I am interested in collaborating with someone on their project so I can learn the language while they get a  sidekick.
Let me Know if this is something that could work for you.
I Would need you to explain and guide me through my first steps in the language (I already started learning) and set the standard for me in code reviews but after a short while I'm sure I'll become an asset to the project.
(I have some experience in Typescript and Java and have learned C a few years ago).

**Comment by mrinalwadhwa** [comment]
@eliKalter 👋 we just added a collection of issues that are simple additions to our command line CLI documentation https://github.com/build-trust/ockam/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

Have a look and give one of them a try. We'd love to help you with any questions as you have along the way.

**Comment by etorreborre** [comment]
Hi @EliKalter, I am currently addressing this issue as part of a large `Vault` refactoring so we can close it now. Please use the link that Mrinal posted to pick another issue, we have plenty to choose from and will be happy to support you!
