### ISSUE TITLE
`ockam identity show a` prints unwanted `%` in the end

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4707]
### Observed behavior

`ockam identity show a` prints unwanted `%` in the end

### Steps to reproduce

sanjo@Oleksandrs-MBP ockam % ockam identity create a
Default vault created: 5224c211
Identity created: P1d976ac05d6f1c50ff568a1404b1d5363714e76d67b4a285eefdd3c21408abd4
sanjo@Oleksandrs-MBP ockam % ockam identity show a
P1d976ac05d6f1c50ff568a1404b1d5363714e76d67b4a285eefdd3c21408abd4%

### Expected behavior

`%` shouldn't be there

### Ockam Version

0.83.0

### Possible Solution
After replacing `print_output` with `println_output`, the problem goes away. Maybe there are more places like that to be fixed
[here](https://github.com/build-trust/ockam/blob/43d2ecf6c5d6da8d8a86ebfcf9576d619f9d8650/implementations/rust/ockam/ockam_command/src/identity/show.rs#L61)

**Comment by SamantaTarun** [comment]
I'd like to work on this issue

**Comment by mrinalwadhwa** [comment]
@tarunsamanta2k20 thats great, all yours

**Comment by itsajay1029** [comment]
Can I work on this @mrinalwadhwa @SanjoDeundiak ?

**Comment by mrinalwadhwa** [comment]
@itsajay1029 looks like @tarunsamanta2k20 is already working toward it ... do you want to try one of the ones here https://github.com/build-trust/ockam/contribute

I plan on adding a few more later today.

**Comment by polvorin** [comment]
Fix was merged
