### ISSUE TITLE
`ockam status --all` could list more of the available nouns 

### ISSUE THREAD

**Issue by shanesveller** [build-trust/ockam#4719]
### Current behavior

At the time of writing `ockam status --all` appears to only list identities, and linked nodes with names and status. Other resources, local or otherwise, do not appear.

### Desired behavior

It would be useful if `ockam status --all` could prove an overview-level lists of more (local) resources. The question I was hoping to answer was "What kind of background processes have `ockam` commands started on my behalf, are they still running, and what kind of shape are they in?"

Initial requested behavior is to list out instances of each noun that already has a `list` subcommand implemented, including but not limited to:
- [ ] forwarder
- [ ] identity
- [ ] tcp-listener
- [ ] tcp-inlet
- [ ] tcp-outlet
- [ ] vault
- [ ] worker

Design/UX input will be needed for whether this behavior should be opt-in, opt-out, a distinct flag from `--all`, etc. but the desire is that more than one category of information will be displayed as the output of one single command invocation.

Prior art that I would compare the idea to would be things like `docker ps -a`, `kubectl get all -n ...`, [kubectl tree](https://github.com/ahmetb/kubectl-tree#demo) plugin, etc. 

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by EliKalter** [comment]
I am interested in collaborating with someone on their project so I can learn the language while they get a  sidekick.
Let me Know if this is something that could work for you.
I Would need you to explain and guide me through my first steps in the language (I already started learning) and set the standard for me in code reviews but after a short while I'm sure I'll become an asset to the project.
(I have some experience in Typescript and Java and have learned C a few years ago).

**Comment by shanesveller** [comment]
@EliKalter Hi Eli, if you're looking for a little more active mentorship on making your first Rust contributions, you might try asking in our community Discord chat here, which is also linked to on our website footer:

https://discord.gg/RAbjRr3kds

I can't guarantee that someone will be available to take you under their wing. We are still a small team, and distributed across multiple timezones. If it seems like no one is able to offer the style of help you're looking for, there are also several other Rust community chats available as well. You can find those listed on https://www.rust-lang.org/community under "Chat platforms".

It's also very welcome for community members to read up on our [recent PRs](https://github.com/build-trust/ockam/pulse) or [issues marked "good first issue"](https://github.com/build-trust/ockam/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22), join our [Discussions](https://github.com/build-trust/ockam/discussions) page, or even just read through the existing code, and leave us some comments to ask for clarification on changes or code that you'd like to know more about. That's a great low-pressure way to get involved while you're still learning. A lot of our codebase makes use of asynchronous Rust and Tokio, which can be both be pretty big topics in their own right. I really enjoyed the [Tokio tutorial](https://tokio.rs/tokio/tutorial) when I was first getting used to the library.

I hope at least something I mentioned is helpful to you! 🚀

**Comment by EliKalter** [comment]
@shanesveller Thank you so much!
A lot of what you said was sin fact useful!
I am already contributing to a rust project but it is kinda slow,
I'll watch your project as well and start trying to figure out what is going on,
I'll also follow the rest of your suggestions,
The main problem for me when coming to a new project is being introduced to.the way the project works and to the key technologies and libraries etc that I'm not familiar with, for example in your project I don't know at all how to work with cli interfaces, it's an entire thing I'm completely foreign to (on the development side of things, I can use a cli).
