### ISSUE TITLE
build: Cargo Target directory is inflating GitHub Actions cache size

### ISSUE THREAD

**Issue by shanesveller** [build-trust/ockam#4746]
### Observed behavior

(Raised for discussion by @SanjoDeundiak )

A [recent GHA run](https://github.com/build-trust/ockam/actions/runs/4734705189/jobs/8403999349?pr=4742) spent just about 4 full minutes restoring this cache step. Our [cache metrics](https://github.com/build-trust/ockam/actions/caches) currently report:

> Approaching total cache storage limit (56.31 GB of 10 GB Used) 

Spot-checking the cache entries after filtering by "cargo-target" varies from 400MB-1200MB on the first page or two, with at least one outlier at 4.1GB on the `develop` branch. This may reflect the possibility for our caching strategy to generate unbounded data growth over time.

### Steps to reproduce

Ongoing behavior as part of CI configuration.

### Expected behavior

We should consider adding local GHA logic, or possibly adopting an external utility such as [cargo-sweep](https://github.com/holmgr/cargo-sweep), to cull the Cargo target directory prior to persisting any refreshed cache data, to ensure that it does not accumulate data that is no longer relevant to recent builds.

### Ockam Version

N/A

**Comment by shanesveller** [comment]
On a personal level, I have had good luck with `cargo-sweep`, though I find it was more predictable and less likely to remove useful data when run using the `--time` argument (or perhaps `--maxsize`). The `--stamp`/`--file` combination is conceptually attractive, but in my usage would sometimes remove intermediate artifacts that would then immediately get rebuilt on my next Cargo invocation, though this may have been an oddity of my local environment or filesystem.

Another possible strategy would be to incorporate our most recent Git tag or Cargo package version as part of the cache identifier, so that it is intrinsically invalidated on each new Ockam release and not taking on additional complexity unless this option does not help enough.

**Comment by shanesveller** [comment]
Some existing considerations are already part of the CI suite:
https://github.com/build-trust/ockam/blob/36980e707214d48d1a18f800648429807c4fc171/.github/actions/cargo_target_dir_pre_cache/action.yml#L7-L17

**Comment by etorreborre** [comment]
@metaclips is this still the case?

**Comment by metaclips** [comment]
We now use [Swantinem/rust-cache](https://github.com/Swatinem/rust-cache) to accurately cache our dependencies, I'll be closing this issue now.
