### ISSUE TITLE
Improve CLI manual documentation

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4759]
### Current behavior

The CLI documentation is lacking information.

### Desired behavior

Update [CLI manual](https://command.ockam.io/manual/) for all existing commands to match the information available in the [ockam docs](https://docs.ockam.io/reference/command/nodes).

You can also leverage the power of the [AI-based search engine available in the docs](https://docs.ockam.io/?q=). Try asking the questions you want to get answered in the CLI manual.

The documentation must include:
- What the command does in detail
- What does the command create/update/modify/show
- Why the user would want to execute it (i.e. expected outcome, context)
- If applicable, simple code examples to showcase their usage

### How to modify the CLI manual

The CLI manual is updated after each release running the `ockam markdown` command. This command feeds from the same content that is used when passing either the `-h` or the `--help` flags. This content is wirten in [the `txt` files that can be found under the `static` directories](https://github.com/build-trust/ockam/blob/9e4c55ee7db1a9c7d043b44e9f77bf776df65bb9/implementations/rust/ockam/ockam_command/src/node/static/after_long_help.txt) that are available for each command.

Note that, even though we use the same base content, we apply some minimal transformations to enrich the markdown format. The capabilites are limited though, and the written content must be rendered correctly in both formats.

The documentation for a command is divided in three sections:
1. [The `short about` text](https://github.com/build-trust/ockam/blob/9e4c55ee7db1a9c7d043b44e9f77bf776df65bb9/implementations/rust/ockam/ockam_command/src/node/create.rs#L52): the doc string above the command struct. This is shown when passing the `-h` flag or always in the first line of the markdown file.
2. [The `long about` text](https://github.com/build-trust/ockam/blob/9e4c55ee7db1a9c7d043b44e9f77bf776df65bb9/implementations/rust/ockam/ockam_command/src/node/static/start/long_about.txt): shown when passing the `--help` flag or always after the short about text of the markdown file.
3. [The `after long about` text](https://github.com/build-trust/ockam/blob/9e4c55ee7db1a9c7d043b44e9f77bf776df65bb9/implementations/rust/ockam/ockam_command/src/node/static/start/after_long_help.txt): this is used to include code examples. 

### Tracked issues

Here is the list of all the tracked issues:

- [x] #4760
- [x] #4761
- [x] #4762
- [x] #4763
- [x] #4764
- [x] #4765
- [x] #4766
- [x] #4767
- [x] #4768
- [x] #4769
- [x] #4770
- [x] #4774
- [x] #4776
- [x] #4777
- [x] #4775
- [x] #4773
- [x] #4778
- [x] #4771

**Comment by munnokd** [comment]
Hey @adrianbenavides can you assign this issue to me?
