### ISSUE TITLE
Update CLI documentation for `space` commands

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4761]
Details of what the documentation should include can be found at https://github.com/build-trust/ockam/issues/4759

**Comment by munnokd** [comment]
Hey @adrianbenavides  can you assign this issue to me?

**Comment by adrianbenavides** [comment]
Sure! All yours @munnokd. Here is a good starting point: https://docs.ockam.io/reference/command/nodes#spaces

Let us know if you have any questions along the way 👍
