### ISSUE TITLE
Update CLI documentation for `identity` commands

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4777]
Details of what the documentation should include can be found at https://github.com/build-trust/ockam/issues/4759

**Comment by itsajay1029** [comment]
Can you assign this to me @adrianbenavides ? Also please ellaborate on the issue so that I can get started

**Comment by adrianbenavides** [comment]
Hey @itsajay1029 , thanks for your interest! I currently have a WIP PR for this issue. The `identity` commands are probably not the best commands to start, as they require some context to fully understand what they do.

I would recommend you though to start with this one: https://github.com/build-trust/ockam/issues/4771

Let me know if you are interested and I'll point you to the next step 👍
