### ISSUE TITLE
`ockam node delete` on non-existing node results in success message

### ISSUE THREAD

**Issue by h20220145** [build-trust/ockam#4810]
### Observed behavior

On current build of ockam , using`ockam node delete` on an non-existing node results in a success message.

### Steps to reproduce

1. run `ockam node list` to list all existing nodes
2. run `ockam node delete` with argument as  a node name not in list
3. A success message ' ✔︎ Node with name 'NAME' has been deleted.' will be shown

<img width="772" alt="Screenshot 2023-04-27 at 9 23 19 PM" src="https://user-images.githubusercontent.com/115618607/234917801-9478e8e4-0b9b-49dd-b4f9-f0e8949f9ba1.png">

### Expected behavior

running `ockam node delete` on an non-existing node should result in an error message indicating that the node given does not exist.

### Ockam Version

0.84.0

**Comment by mrinalwadhwa** [comment]
@h20220145 Thank you for reporting this.

**Comment by saputkin** [comment]
Hi @mrinalwadhwa, I would like to fix it!

**Comment by mrinalwadhwa** [comment]
@saputkin awesome, thank you.
Here's a good starting point https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs

Let us know if you have any questions along the way.
