### ISSUE TITLE
Test for replacer Sessions

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4811]
### Current behavior

We have a [mechanism](https://github.com/build-trust/ockam/blob/a3b87e724ed15bdfa6a575fba23f29f3277b7e07/implementations/rust/ockam/ockam_api/src/session/mod.rs) for restarting the topology (tcp connections, secure channels, etc.) for Relays and Inlets, which works roughly following an algorithm:
1. Whenever a Relay or an Inlet is created through the `ockam_command`, a new `Session` is added to the `Sessions` object to be monitored
2. `Sessions` object monitors each `Sessions` by sending periodic ping messages through a route that the corresponding Relay or Inlet uses.
3. If an outage is detected, the whole route and a Relay or an Inlet are recreated, while old ones are deleted

### Desired behavior

We want Integration and/or Unit tests for that functionality on CI since it's only possible to test it manually.

**Comment by Alef-gabriel** [comment]
I can take this?

**Comment by mrinalwadhwa** [comment]
@Alef-gabriel of course, all yours. Let us know if you have questions as you explore.

**Comment by davide-baldo** [comment]
close in PR https://github.com/build-trust/ockam/pull/5143
