### ISSUE TITLE
Keep improving the CLI State traits

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4829]
### Current behavior

There are some problems with the current implementation:
- https://github.com/build-trust/ockam/pull/4795#discussion_r1181479684
- https://github.com/build-trust/ockam/pull/4795#discussion_r1181482942
- https://github.com/build-trust/ockam/pull/4795#discussion_r1181487646
- https://github.com/build-trust/ockam/pull/4795#discussion_r1181493501

### Desired behavior

To discuss

**Comment by 0xkelvin** [comment]
hello @adrianbenavides 
could you please elaborate what should we improve

**Comment by etorreborre** [comment]
@0xkelvin please have a look at the comments that @adrianbenavides linked. The first one for example proposes to remove a function from the `StateItemTrait`. If you do that you will see that the behaviour checking when an identity can be delete needs to move somewhere else, at a higher level, where we can access both the identity state _and_ the node state without the need for the identity state to know about the node state.

**Comment by etorreborre** [comment]
@0xkelvin I actually had to tackle the issue I was describing before in this PR: https://github.com/build-trust/ockam/pull/4947

**Comment by etorreborre** [comment]
I propose to close this issue, especially with the [upcoming refactoring work on all the CLI state with a DB backend](https://github.com/build-trust/ockam/issues/5801).
