### ISSUE TITLE
Remove `LONG_TESTS` variable

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4830]
`LONG_TESTS` env variable was used to optionally disable bats tests that take a lot of time to complete, but it looks like we don't have such tests anymore, so it's unused. Therefore, we should remove any usage and dependencies on that variable

**Comment by saputkin** [comment]
Hi, I would love to do that

**Comment by etorreborre** [comment]
Please go ahead!

**Comment by polvorin** [comment]
The work for this was merged
