### ISSUE TITLE
Creating a node with an invalid `--project-path` value should return an error

### ISSUE THREAD

**Issue by davide-baldo** [build-trust/ockam#4868]
### Observed behavior

When creating a node with an invalid project path, the node is created but not started and no error about the path is reported

### Steps to reproduce

$ ockam node create green --project-path /invalid/path

Node:
  Name: green (Default)
  Status: DOWN
  Route To Node:
    Short: /node/green

### Expected behavior

$ ockam node create green --project-path /invalid/path
× file not found "/invalid/path"

### Ockam Version

9eadf7f0f6dc034fdc1694ab17bf1a9b10ad2b0d

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by StreakInTheSky** [comment]
I’d like to try this

**Comment by davide-baldo** [comment]
@StreakInTheSky Sure!

**Comment by nazmulidris** [comment]
@StreakInTheSky Thank you for taking the time to look at this issue. Since you’ve not had a chance we’re opening the issue up for other contributors.

**Comment by mexirica** [comment]
Hey, can i try to solve this ?

**Comment by nazmulidris** [comment]
@mexirica That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by adrianbenavides** [comment]
This issue is no longer valid since we removed the `project-path` parameter in a recent PR.
