### ISSUE TITLE
`ockam space delete` has no output and exits 0 if space already does not exist

### ISSUE THREAD

**Issue by shanesveller** [build-trust/ockam#4880]
### Observed behavior

Repeating a `ockam space delete` command twice, or running it with a space name that has never existed, has no terminal output and exits 0.

### Steps to reproduce

1. `ockam space create shanesveller-example-123`
2. `ockam space delete shanesveller-example-123`
     output: `✔ Space with name 'shanesveller-example-123' has been deleted.`
3. `ockam space delete shanesveller-example-123 && echo "false success"`
     output: "false success"

### Expected behavior

On the second repetition in my example above, we should emit a message similar in spirit to `space "shanesveller-example-123" not found` and exit with a non-zero status.

### Ockam Version

0.86.0

**Comment by itsajay1029** [comment]
Can you assign this to me @shanesveller ? Also please ellaborate the bug ??

**Comment by shanesveller** [comment]
@itsajay1029 Thanks for jumping in! I've assigned it to you. Please do let us know if you need to pause your work for any reason, which you aren't required/expected to elaborate with us. That way we can adjust the assignment accordingly.

Most of the changes at the CLI level will begin primarily in [ockam_command/src/space/delete.rs](https://github.com/build-trust/ockam/blob/ea73413848fb092e474f2edf91dc08311df67f5c/implementations/rust/ockam/ockam_command/src/space/delete.rs#L44). The backend API this particular command requests against is closed source, but designed to be idempotent, and so unfortunately it doesn't return anything in its response to distinguish that a deletion call was actually a no-op. The backend will always return an apparent success in that case. Most likely this means that to provide the proposed CLI feedback, this CLI command should perform a `api::space::show` RPC request first and determine how to proceed next based on what that returns. 

Alternately, you could also use `api::space::list` RPC request, which would leave us a future opportunity to suggest similarly-spelled Spaces that do exist if the target Space is not found. This could be handled similarly to how Clap handles misspelled arguments:

```shell
$ ockam spacee list
error: unrecognized subcommand 'spacee'

  tip: a similar subcommand exists: 'space'
``` 

(I do not consider the fuzzy suggestion in scope for this issue, just pondering on the potential.)

As a last bit of suggestion, I didn't specify what the non-zero status should actually be. Well-formed CLIs out in the wild tend to have more than one possible exit status at different integers to distinguish different outcomes, and we're no different. Ours are defined [here](https://github.com/build-trust/ockam/blob/ea73413848fb092e474f2edf91dc08311df67f5c/implementations/rust/ockam/ockam_command/src/util/exitcode.rs), and you can see a number of example uses in e.g. the [node create](https://github.com/build-trust/ockam/blob/ea73413848fb092e474f2edf91dc08311df67f5c/implementations/rust/ockam/ockam_command/src/node/create.rs) subcommand. If you don't feel any of the existing exit codes are well-suited to the situation being described, please feel free to propose a new entry with an incremented number.

> Also please ellaborate the bug ??

In this case I used our `bug` label to represent that the exit status portion of this is a (minor) correctness issue, as exiting with 0 status is not fully accurate if no changes were actually made. The overall concern is largely lack of functionality rather than a true flaw.

**Comment by itsajay1029** [comment]
Can you arrange for a discord server or Google meet for me if I need some help @shanesveller ?

**Comment by itsajay1029** [comment]
please check #4893 @shanesveller

**Comment by shanesveller** [comment]
@itsajay1029 Ockam has a community Discord linked to from our website footer, if you'd like to join there and ask  questions or request feedback:

https://discord.gg/RAbjRr3kds

We're a globally distributed team, so depending on the time of day it will vary whether anyone is active. It may take some time for someone to respond. GitHub PRs are probably the best place to consolidate discussions around a particular code change, if possible.

**Comment by Sparrownor1** [comment]
Hey, is this still being worked on? Happy to pick this up

**Comment by itsajay1029** [comment]
I am still working on it @Sparrownor1

**Comment by adrianbenavides** [comment]
Fixed at https://github.com/build-trust/ockam/pull/5289/
