### ISSUE TITLE
Allow binary messages in ockam message send

### ISSUE THREAD

**Issue by davide-baldo** [build-trust/ockam#4918]
### Current behavior

Only text messages can be sent via `ockam message send` command.
Occasionally, it's useful to be able to send binary messages, for example testing a decryptor.

### Desired behavior

Allow to send binary messages specifying the `--hex` flag.
When this flag is used, both message and response are hex-encoded.

```
ockam message send --from node1 --to /service/echo --hex 00aabbff
00aabbff
```

**Comment by Neruelin** [comment]
I'm going to give this a try.
