### ISSUE TITLE
Move CLI environment variables `help` text to its own command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4928]
### Current behavior

Some commands show the env variables as part of their help text, making it too long and not very user-friendly.

### Desired behavior

Create a new CLI command `ockam environment` that will just print the environment variable text that we have [here](https://github.com/build-trust/ockam/blob/3dd6623881c5374fc709e76b3cc7551857b35c72/implementations/rust/ockam/ockam_command/src/docs.rs#L16).

Also, that piece of static text should be moved to its own file, similar to how we handle [other command's help texts](https://github.com/build-trust/ockam/blob/3dd6623881c5374fc709e76b3cc7551857b35c72/implementations/rust/ockam/ockam_command/src/node/default.rs#L6).

Finally, the environment variables help text should not be rendered as part of any other command. To do that, [this line](https://github.com/build-trust/ockam/blob/3dd6623881c5374fc709e76b3cc7551857b35c72/implementations/rust/ockam/ockam_command/src/docs.rs#L91) should be removed.

**Comment by p-gentili** [comment]
Can I work on this? 😄

**Comment by adrianbenavides** [comment]
Absolutely, let me know if you need any help!
