### ISSUE TITLE
Stop Encryptor and Decryptor Workers together

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#4933]
### Observed behavior

Currently, we only return the Encryptor address to the client, so when we stop it, for example [here](https://github.com/build-trust/ockam/blob/ebe30fa3e0410a48cee1bd62bfa946548f1cfade/implementations/rust/ockam/ockam_api/src/cloud/mod.rs#L219). The Decryptor Worker remains running. We should consider mechanisms to stop them together. The easiest approach atm may be for Encryptor to stop the Decryptor in its `shutdown` function

**Comment by Alef-gabriel** [comment]
I can take this?

**Comment by etorreborre** [comment]
@Alef-gabriel please do. Note that in the latest version of the code there are actually 2 workers that are active:

 - the [`HandshakeWorker`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/secure_channel/handshake/handshake_worker.rs) which serves as a decryptor worker once the handshake is done
 - the [`EncryptorWorker`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_identity/src/secure_channel/encryptor_worker.rs)

**Comment by Alef-gabriel** [comment]
PR open :+1:

**Comment by etorreborre** [comment]
This issue has been fixed with https://github.com/build-trust/ockam/pull/5162
