### ISSUE TITLE
Rename `ockam project authenticate` clap command to `ockam project enroll`

### ISSUE THREAD

**Issue by caoakleyii** [build-trust/ockam#4940]
### Current behavior

```sh
ockam project authenticate
```

### Desired behavior

```sh
ockam project enroll
```
Depends on issue https://github.com/build-trust/ockam/issues/4939 being completed first

Update `authenticate` command which can be found [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/authenticate.rs#L0-L1)

Update examples found [within here](https://github.com/build-trust/ockam/tree/develop/examples/rust/get_started/examples)

Update bats testings found [within here](https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/tests/bats)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by leafoliage** [comment]
@CAOakleyII Hi! I would like to work on this issue.

**Comment by mrinalwadhwa** [comment]
@leafoliage awesome, all yours.

Please note that @fsmiamoto started https://github.com/build-trust/ockam/pull/4946 for the related issue https://github.com/build-trust/ockam/issues/4939

Let us know if you have questions along the way.

**Comment by leafoliage** [comment]
@mrinalwadhwa Hi! I'm have a problem with bats tests. I've followed `BATS.md` in `implementations/rust/ockam/ockam_command/tests/bats` to install bats packages. According to that md, I shouldn't need any pre-setups, but when I run `bats implementations/rust/ockam/ockam_command/tests/bats`, it says:
```
... bats/setup_suite.bash: line 6: ockam: command not found
```
Did I miss any step?

**Comment by mrinalwadhwa** [comment]
Hmm, we should double check those instructions, in the meantime, try placing the binary that was compiled with `cargo build` to a path that is in your shell's $PATH variable. 

For example:

```
cp target/release/ockam ~/.local/bin
```

assuming `~/.local/bin` is in your shell's $PATH.

You may also need to run:

```
ockam enroll
```

for the bats tests to pass.
