### ISSUE TITLE
Enable pnpm support in dependabot

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4961]
# Current

We have a pnpm workspace here
https://github.com/build-trust/ockam/tree/develop/implementations/typescript

Github just shipped support for pnpm in dependabot
https://github.com/dependabot/dependabot-core/pull/7081
https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/

# Desired

Remove npm and enable pnpm support in dependabot here:
https://github.com/build-trust/ockam/blob/develop/.github/dependabot.yml#L27-L36

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by rghdrizzle** [comment]
Hey , I could work on this but I have a doubt. The yaml value for pnpm is the same as npm in the configuration (https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#pnpm) so how do I actually remove npm and then add pnpm for the dependabot?

**Comment by metaclips** [comment]
Thanks @rghdrizzle pnpm dependabot config is pretty much same as npm so I don’t think there’s any thing we need to change. I’ll be closing this issue now.
