### ISSUE TITLE
Define json output for `ockam node create`

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#4967]
### Current behavior

This does not output json

```
» ockam node create --output json

Node:
  Name: 74096240
  Status: UP
  Route To Node:
    Short: /node/74096240
    Verbose: /dnsaddr/localhost/tcp/53783
...
```

### Desired behavior

Change the code here:

https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/create.rs

to output json describing the node.

We want to start using this in the [typescript wrapper](trust/ockam/blob/ec7268aeef9b59bb22f3ae36a7515bd03ec09a4b/implementations/typescript/ockam/ockam_command/src/node.ts#L26) around command, so as a start json output showing the generated name of the node would be very useful.

Would allow us to make name here optional:

https://github.com/build-trust/ockam/blob/develop/implementations/typescript/ockam/ockam_command/src/node.ts#L26

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mrinalwadhwa** [comment]
@CAOakleyII @adrianbenavides could you add some instructions here on how json outputs should handled, so someone looking at the issue can pick it up.

**Comment by adrianbenavides** [comment]
The output of this command is built in the [`print_node_info`](https://github.com/build-trust/ockam/blob/1b0bd88e2ccbd833e2cc9502cb0634a236aa8c3e/implementations/rust/ockam/ockam_command/src/node/show.rs#L61) function.

To make this work quickly, we could pass a `CommandGlobalOpts` reference to this function. It should be added as the first argument like: `opts: &CommandGlobalOpts`. With that object, then we can add the following snippet at the start of the function:

```rust
if opts.global_args.output_format == OutputFormat::Json {
    opts.terminal
        .stdout()
        .json(serde_json::json!({ "node": { "name": &node_name } }))
        .write_line()
        .expect("Failed to write to stdout");
    return;
}
```

**Comment by gautamprikshit1** [comment]
How do I test it?

**Comment by davide-baldo** [comment]
Probably the best option is checking the JSON contains the field values you expect, i would store the output in a temporary file (or variable) and process it using [jq](https://jqlang.github.io/jq/)
