### ISSUE TITLE
Do not print that a secure channel listener was successfully deleted when it is not the case

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4972]
### Observed behavior

`ockam` reports that a secure channel listener has been deleted even if it does not exist

### Steps to reproduce

While the `_missing_` secure channel listener does not exist the console still prints out that the listener has been deleted:
```
Deleted secure-channel listener with address '/service/_missing_' on node 'n1'
```

### Expected behavior

`ockam` should display a message saying that the secure channel address has not been found and only display that the secure channel listener has been deleted when the deletion is successful.

### Diagnostic

The `delete` command for secure channels listeners is implemented:

 - [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/listener/delete.rs#L40) for sending a request to the node
 - and [there](https://github.com/build-trust/ockam/blob/55b53a95c3fec34ce60c3ec700fcca9248e9bc87/implementations/rust/ockam/ockam_api/src/nodes/service/secure_channel.rs#L477) for building the response

However we can see that:

 - the function in `ockam_api` does not consider the case where the listener might not exist. It should return `Ok(NotFound)`
 - the function in `ockam_command` prints the same successful answer whether the action was successful or not

### Ockam Version

0.87.0

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by i-b-o-t** [comment]
Hi there!

What am I missing? The API does not get called. Is there more of a bug than this issue?

```
./target/debug/ockam enroll
./target/debug/ockam node create s --project-path default-project.json
./target/debug/ockam secure-channel-listener -v -v -v  delete --at s notthere
```

**Comment by etorreborre** [comment]
Hi @i-b-o-t I am sorry but I don't understand your question. What do you mean by "The API does not get called"? In response to which command? In which part of the code?

**Comment by i-b-o-t** [comment]
In response to requesting to delete the listener, the side that is "building the response"  (the code linked to in above description) apparently never runs. Can you confirm that you see (or not see) any of the log messages therein?

**Comment by davide-baldo** [comment]
Hi! @i-b-o-t 

I confirmed it gets executed, you can find this line of log:
```
2023-06-06T11:17:50.542353Z  INFO ockam_api::nodes::service::secure_channel: Handling request to delete secure channel listener: 0#_missing_
```
when executing
```
ockam secure-channel-listener delete _missing_ --at s
```

The code gets executed inside the node you created named `s`.
To debug it, I suggest using the trace log level (by adding `-vvv` in the node create command), and by reading the log file in  `~/.ockam/nodes/s/stdout.log`
