### ISSUE TITLE
Do not show `options` section in root commands when generating the markdown docs

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5028]
# Observed behavior

Root commands (commands that group a set of subcommands, e.g [project addon](https://command.ockam.io/manual/ockam-project-addon.html)) should not show the `options` section.

This section is rendered because a root command can have global arguments that will be inherited by its subcommands.

# Expected behavior

We want to omit that section in the markdown generated docs. To do that, we should branch the logic [here](https://github.com/build-trust/ockam/blob/ceaffbd367c5eab72b600db9687f47f8152ec442/implementations/rust/ockam/ockam_command/src/markdown/mod.rs#L174) in two:

```rust
if cmd.get_subcommands().next().is_some() {
    // Subcommands list
} else {
    // Arguments
    // Options
}

// After help: print either the long or the short version
// make a .md file and add the buffer to it
```

**Comment by Alef-gabriel** [comment]
I can take this?

**Comment by mrinalwadhwa** [comment]
@Alef-gabriel of course.
If you have questions, as your work on your PR, ask them here or join us on the contributors discord channel https://discord.gg/bewvnm6zqS

**Comment by Alef-gabriel** [comment]
@mrinalwadhwa sure. thank you
