### ISSUE TITLE
TrustContextOpts: add `value_name="PROJECT_NAME"` to `project` argument

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5029]
We have another argument called `--project-path` used by other commands and it can confuse the user to see an argument called just `project`.

Here is the argument to be modified:
https://github.com/build-trust/ockam/blob/ceaffbd367c5eab72b600db9687f47f8152ec442/implementations/rust/ockam/ockam_command/src/util/api.rs#L368

**Comment by Alef-gabriel** [comment]
i can take this?

**Comment by adrianbenavides** [comment]
Sure, all yours!

**Comment by etorreborre** [comment]
@Alef-gabriel are you still working on this?

**Comment by etorreborre** [comment]
Fixed via https://github.com/build-trust/ockam/pull/5076
