### ISSUE TITLE
Remove hardcoded `required` and `optional` text from arguments' description

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5030]
This is implicit from `<ARG>` (required) and `[ARG]` (optional), so we don't need to manually write that information as part of the arguments descriptions. An example of this can be found [here](https://github.com/build-trust/ockam/blob/663e686b2ffe60778292dcfdd4f17716bbc0fa21/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs#L31).

Here is the full list of commands that need to be fixed:

Remove the `required` string from:
- [ ] `ockam tcp-connection create`
- [ ] `ockam secure-channel create`
- [ ] `ockam secure-channel-listener delete`
- [ ] `ockam worker list`

Remove the `optional` string from:
- [ ] `ockam node create`
- [ ] `ockam authority create`
- [ ] `ockam relate create`

**Comment by BradLewis** [comment]
If this still needs to be worked on I could do it real quick, along with the linked issue.

**Comment by adrianbenavides** [comment]
> If this still needs to be worked on I could do it real quick, along with the linked issue.

That would be great!
