### ISSUE TITLE
Change `name`-like arguments' value names across CLI commands

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5031]
For example: instead of `IDENTITY`, we want to show `IDENTITY_NAME` to avoid confusion with other arguments like `IDENTITY_ID`. 

Also, replace generic `NAME` value names with their full value (e.g `VAULT_NAME` instead of `VAULT`). Non-exhaustive list of arguments to look for: node, identity, vault, project, space, trust-context

Here is a list of some subtasks I identified:
- [ ] Replace [CloudOpts](https://github.com/build-trust/ockam/blob/a12893f7c629107c5d18c77a9c9ab3d7acec3568/implementations/rust/ockam/ockam_command/src/util/api.rs#L348) `value_name` from `IDENTITY` to `IDENTITY_NAME`
- [ ] Add `vault_name = VAULT_NAME` to [`ockam identity create` argument](https://github.com/build-trust/ockam/blob/a12893f7c629107c5d18c77a9c9ab3d7acec3568/implementations/rust/ockam/ockam_command/src/identity/create.rs#L23)
- [ ] Add `project_name = PROJECT_NAME` to [TrustContextOpts project argument](https://github.com/build-trust/ockam/blob/a12893f7c629107c5d18c77a9c9ab3d7acec3568/implementations/rust/ockam/ockam_command/src/util/api.rs#L366)
- [ ] Add `space_name = SPACE_NAME` to `space` commands (e.g. [`create` here](https://github.com/build-trust/ockam/blob/a12893f7c629107c5d18c77a9c9ab3d7acec3568/implementations/rust/ockam/ockam_command/src/space/create.rs#L25))
- [ ] Remove `value_name` from flag arguments (bools): [example](https://github.com/build-trust/ockam/blob/a12893f7c629107c5d18c77a9c9ab3d7acec3568/implementations/rust/ockam/ockam_command/src/authority/create.rs#L60)

Feel free to include more similar fixes like the mentioned above if you want to explore the codebase!

**Comment by rjtch** [comment]
Hey i would like to take this task. is it possible?

**Comment by mrinalwadhwa** [comment]
@rjtch of course, all yours

If you have questions, as your work on your PR, join us on the contributors discord channel https://discord.gg/bewvnm6zqS

**Comment by rjtch** [comment]
is vault_name = PROJECT_NAME the wright value? I thought it should be something like value_name = PROJECT_NAME?
same for vault_name = SPACE_NAME? Or you want it all to be related to the vault project and space commands?

**Comment by adrianbenavides** [comment]
@rjtch my bad! copy-paste classic error 🤦 I've updated the description

**Comment by etorreborre** [comment]
Fixed with https://github.com/build-trust/ockam/pull/5076
