### ISSUE TITLE
CLI commands with `--force` argument should offer the short version `-f`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5032]
Add `short` version to [`node stop`](https://github.com/build-trust/ockam/blob/a12893f7c629107c5d18c77a9c9ab3d7acec3568/implementations/rust/ockam/ockam_command/src/node/stop.rs#L22)

**Comment by StreakInTheSky** [comment]
I'd like to do this. And just want to make sure, this is just adding the `short` arg in `StopCommand`? The only other command I found that uses `--force` was for `DeleteCommand` which already has it.

**Comment by adrianbenavides** [comment]
> I'd like to do this. And just want to make sure, this is just adding the `short` arg in `StopCommand`? The only other command I found that uses `--force` was for `DeleteCommand` which already has it.

Yeah exactly. When I created this issue we had more stuff on the requirements list, but we ended up removing most of it.
