### ISSUE TITLE
Add `--yes` flag to `delete` commands to prevent unintentional deletions

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5041]
### Current behavior

For example, the `vault delete` command will ask for confirmation on tty's, but won't prevent the user from deleting a vault on non-tty's.

### Desired behavior

We should add a `--yes` flag to `delete` commands so that:

- TTY: ask for confirmation if `--yes` is not passed
- Non TTY: fail if `--yes` is not passed

A similar approach is done in the [`ockam reset` command](https://github.com/build-trust/ockam/blob/ff206feb32be2c248fb5d1970f0f314721093335/implementations/rust/ockam/ockam_command/src/reset.rs#L24).

**Comment by rjtch** [comment]
Can i take this task?

**Comment by davide-baldo** [comment]
@rjtch Sure! it's all yours!

**Comment by rjtch** [comment]
I added the --yes flag to all delete methods of all commands. Or are  there  any specific delete where i should add the flag to?

**Comment by adrianbenavides** [comment]
Adding the `--yes` flag to all existing `delete` methods is fine. We don't have any special case in any specific delete command right now.

**Comment by etorreborre** [comment]
Fixed with https://github.com/build-trust/ockam/pull/5289
