### ISSUE TITLE
Fix typo in name displayed in github workflow

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5114]
Fix the name, change it to `Rust - lint_cargo_deny`

https://github.com/build-trust/ockam/blob/0ff0ff41d70900d9c559b9f9be9ffa4cc82cbf28/.github/workflows/rust.yml#L109-L111

**Comment by queenkatherinecodes** [comment]
Hi I am looking to contribute to this awesome project and I am happy to fix this for you (:
