### ISSUE TITLE
OCK500 connection peer not found error

### ISSUE THREAD

**Issue by Alef-gabriel** [build-trust/ockam#5130]
### Observed behavior

I expected to be displayed without any errors.

### Steps to reproduce

ockam node create n1
ockam secure-channel-listener show _missing_ --at n1

### Expected behavior

Instead, I received the following error message:

OCK500 connection peer was not found (origin: Transport, kind: Misuse, source location: /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/convert/mod.rs:726:9)

### Ockam Version

0.89.0

**Comment by mrinalwadhwa** [comment]
@Alef-gabriel that's a good issue, I think we should explore a fix. Thank you for taking time to report it.

Did you see some reason that makes it not an issue?

**Comment by Alef-gabriel** [comment]
@mrinalwadhwa of course. I created a new node and run again but I'm don't received error message. Then I though the node have a expiration time or something like that.

**Comment by adrianbenavides** [comment]
Hi @Alef-gabriel , I'm currently working on improving the errors of the commands, particularly the `secure-channel` subcommands, so this report is really helpful. I tried to replicate your issue but I couldn't. Could you share exactly what commands did you run?

**Comment by Alef-gabriel** [comment]
Hi @adrianbenavides, try this

into ockam_command dir.
`cargo run node create n1`
`cargo run secure-channel-listener show missing --at n1`

**Comment by Alef-gabriel** [comment]
@adrianbenavides 
![image](https://github.com/build-trust/ockam/assets/63974787/b1590307-3e82-4fc5-93ef-66bcf2986522)
this error is correct, node already exists.
![image](https://github.com/build-trust/ockam/assets/63974787/13188977-ddaf-46ef-b06f-f86d338e1f7c)
but this output It was to be  ´/service/_missing_´

**Comment by adrianbenavides** [comment]
Great, thanks! I'll keep this in mind while I work on this.

**Comment by etorreborre** [comment]
Like many other "not found" errors, the reporting could be way better. But we now display
```
❯ ockam secure-channel-listener show _missing_ --at n1                                                                                                                                                                                                                                                                                                                                                  OCK500

  × An error occurred while processing the request. Status code: 404 NotFound. Message: Secure Channel Listener, 0#_missing_, not found.
```

Now the message says "Secure Channel Listener, 0#_missing_, not found"
