### ISSUE TITLE
Display a user-friendly error message when listing resources on a stopped node

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5146]
### Observed behavior

The `list` commands should show a more descriptive error message when the node that is being queried is not running.

### Steps to reproduce

```sh
ockam node create n
ockam service list --at n # works as expected
ockam node stop n
ockam service list --at n # throws the error below

× connection peer was not found (origin: Transport, kind: Misuse, source location: /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/convert/mod.rs:727:9)
```

### Expected behavior

The error message should be user-friendly. Something like: `The node n is not running`.

### Ockam Version

0.89

### Proposed solution

Right after parsing the node name, check whether the node is running or not:

```rust
let node_name = parse_node_name(&node_name)?;
if !opts.state.nodes.get(&node_name)?.is_running() {
    return Err(miette!("The node {node_name} is not running"));
}
```

### Commands to fix

If you want to help with this issue, feel free to pick one of the commands below and apply the fix!

- [ ] `ockam node list`
- [ ] `ockam service list`
- [ ] `ockam tcp listener list`
- [ ] `ockam credential list`
- [ ] `ockam identity list`
- [ ] `ockam lease list`
- [ ] `ockam policy list`
- [ ] `ockam project list`
- [ ] `ockam project addon list`
- [ ] `ockam relay list`
- [ ] `ockam secure-channel list`
- [ ] `ockam space list`
- [ ] `ockam trust-context list`
- [ ] `ockam vault list`
- [ ] `ockam worker list`
- [ ] `ockam kafka-consumer list`
- [ ] `ockam kafka-producer list`

**Comment by BradLewis** [comment]
Mind if I give this a go?

**Comment by mrinalwadhwa** [comment]
@BradLewis we'd love that. All yours
