### ISSUE TITLE
Add an "optional" tag to commands arguments' description when generating markdown docs

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5158]
### Current behavior

Although there is an implicit differentiation between required/optional args (`<ARG>` for required args and `[ARG]` for optional), but we can't assume every user knows that. This is done automatically when showing the `--help` in the terminal, but not in the markdown docs (all arguments are shown as `<ARG>`), which creates an inconsistency.

We need to improve the markdown docs generation to include that information more explicitly. 

### Desired behavior

Related to https://github.com/build-trust/ockam/issues/5030 (they can be completed in parallel).

We should add a piece of text to optional arguments so the user can easily differentiate between required/optional arguments.

To do so, the `markdown` command must be updated as follows. In the [`generate_arg_markdown`](https://github.com/build-trust/ockam/blob/663e686b2ffe60778292dcfdd4f17716bbc0fa21/implementations/rust/ockam/ockam_command/src/markdown/mod.rs#L251) function, the `value_name` is always written as "\`<{value_name}>\`". This should be changed so that:
- if `arg.is_required_set()` is true, print it as "\`<{value_name}>\`"
- else, print it as "\`[{value_name}]\`, (optional)"

**Comment by Alef-gabriel** [comment]
Hi @adrianbenavides, i can take this?

**Comment by adrianbenavides** [comment]
@Alef-gabriel looks like @BradLewis already created a PR for this, sorry! I'll try to create more issues soon 🙏

**Comment by BradLewis** [comment]
Ah sorry Alef, I didn't see that you had also commented on this. My bad!

**Comment by Alef-gabriel** [comment]
@BradLewis No problem.
