### ISSUE TITLE
Change argument for `ockam credential issue` command from Identity to IdentityIdentifier

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5225]
### Current behavior

The `ockam credential issue` [command](https://github.com/build-trust/ockam/tree/344c4736e31c3b104bdc1a31f133603b4377138e/implementations/rust/ockam/ockam_command/src/credential/issue.rs#L23) expects the full identity of the subject as the `for` argument.

### Desired behavior

We can use the `IdentityIdentifier` instead of the full `Identity` as the `for` argument. 

Instead of decoding the `Identity` [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/credential/issue.rs#L54C18-L54C26) we can simply read the `for` argument as an `IdentityIdentifier` (using a `value_parser`, [like this is done for a `SocketAddr`](https://github.com/build-trust/ockam/blob/344c4736e31c3b104bdc1a31f133603b4377138e/implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs#L38) for example).

Then as we can see on [this line](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/credential/issue.rs#L95) we just use the identifier so that line can be simplified.

documentation needs to be updated as well.

**Comment by GabrielBarbosaGV** [comment]
Hello! I would like to take this issue, if possible.

**Comment by etorreborre** [comment]
Hi @GabrielBarbosaGV, please do!

**Comment by GabrielBarbosaGV** [comment]
@etorreborre  As the function that converts the given identity identifier into an Identity struct is async, is there a way to use it in a value_parser? I naively tried to create an async parser, but it was not accepted, due to the incompatibility between the expected Result type and the actual returned impl Future.

**Comment by etorreborre** [comment]
@GabrielBarbosaGV for this issue you shouldn't have to create an identity anywhere.

We currently read and decode an `Identity` from the command line, just to later on take its `IdentityIdentifier` and pass it to the `CredentialData::from_attributes` function:
```rust
CredentialData::from_attributes(cmd.identity().await?.identifier(), issuer.clone(), attrs)
```

You should be able to implement a `value_parser` for `IdentifierIdentity` from the `IdentityIdentifier::from_hex` function and  then pass it directly to the `CredentialData::from_attributes` function.

**Comment by GabrielBarbosaGV** [comment]
@etorreborre Hello again! I have code that passes cargo check, but I have been unable to execute cargo test, as I run out of memory before completion. I only have 16GB of RAM for the foreseeable future - do you think that impedes me from continuing development related to Ockam? Or is there a way to go around this issue?

If you'd like to see whether the code I've written is appropriate, it is located in the [decoding-avoidance branch in my fork of Ockam](https://github.com/GabrielBarbosaGV/ockam/tree/decoding-avoidance). The file that is the main point of interest is the one for the [issue command](https://github.com/GabrielBarbosaGV/ockam/blob/decoding-avoidance/implementations/rust/ockam/ockam_command/src/credential/issue.rs).

Many thanks for your help and attention!

**Comment by SanjoDeundiak** [comment]
@GabrielBarbosaGV, that's weird. I have 16Gb of RAM (Apple silicon), and there is plenty free when I run, build, or test ockam. Also, AFAIK GitHub VMs used to run our CI have only 7Gb of RAM, and everything works pretty well

**Comment by GabrielBarbosaGV** [comment]
@SanjoDeundiak Weird, I keep getting the ld process killed - I've been using WSL, and recently found out that it does not use the full RAM of the PC. I had it set to 8GB, but then changed it to 12GB, which, unfortunately, did not solve the problem yet. I will try increasing it further, after analyzing how that would impact the memory usage alongside Windows.

**Comment by GabrielBarbosaGV** [comment]
@etorreborre @SanjoDeundiak Just to update - this Thursday I will be switching computers, and the new one will have Linux installed, albeit with the same amount of RAM. I do believe, however, that this will be enough to solve the problem.

I apologize for making you wait, and thank you for your patience - I will keep you updated.

**Comment by GabrielBarbosaGV** [comment]
@etorreborre @SanjoDeundiak Good day! I have linked a PR, as all tests pass, although I believe more thorough validation is in order. How might I investigate that the command remains behaving as it did prior? To work with Ockam, I have mostly relied on using a Linode with which to pair outlets with local inlets.
