### ISSUE TITLE
Create a desktop application to share services

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5228]
### Current behavior

It is current difficult to share documents and services from the machine of one user to the machine of another user in a perfectly secure way. Yet the `ockam` provides all the tools to make this a very easy process!

### Desired behavior

The purpose of this feature is to make a desktop application to allow users to:

 - enroll and create a project (as they would with `ockam enroll`)
 - share some services (and files) on their machine (for example [a Postgres database](https://docs.ockam.io/guides/use-cases/secure-database-access)) by inviting other users to connect to those services
  - use an invitation to connect to a shared service

The following picture gives an idea of what the application could look like:

![image](https://github.com/build-trust/ockam/assets/10988/57b0eeed-cef2-4563-81bc-f738df6ca334)

**Comment by waqasraz** [comment]
This could be another option. As it kinda matches projects and services in Ockam. 

<img width="511" alt="image" src="https://github.com/build-trust/ockam/assets/1761304/8d90307f-a20c-4482-87aa-08e99de65450">

It's possible either with the same stack as JetBrains or if we stick with Tauri and then load on the system tray icon and click the load window with Webapp.

**Comment by etorreborre** [comment]
I am closing this issue now since it is better covered by ongoing epics and stories
