### ISSUE TITLE
Parse `Duration` arguments with custom units (ms, s, m)

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5255]
### Current behavior

Most of the duration-related arguments used in the Ockam Command are integers that we later use in code to build a `Duration` instance. We explicit in the arguments' description the expected units, using that assumption to build the `Duration::from_secs()`.

### Desired behavior

We would like to give the user the flexibility to express the units as part of the argument. For example:

```
$ ockam message send --to n --timeout 10s
```

Some formats that we would like to support:
- `10`: seconds (the default unit in case none is provided)
- `10s`: seconds
- `10ms`: milliseconds
- `10m`: minutes

### How to do it

There are various libraries implementing this already, but we would like to avoid them because they have too many features that we are not interested in. We can do this with a simple regex to support the few cases we are targeting.

We need to refactor the duration-related arguments so they are parsed with a custom function that does the transformation from a human-duration value to a `Duration` instance. For example, in the [`message send`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/message/send.rs#L43) command:

```rust
/// Override default timeout (in seconds)
#[arg(long, value_name = "TIMEOUT", default_value = "10")]
pub timeout: u64,
```

should be 

```rust
/// Override default timeout
#[arg(long, value_name = "TIMEOUT", default_value = "10", value_parser = human_duration_parser)]
pub timeout: Duration,
```

**Comment by MFAlexandru** [comment]
Hello, I am a first time contributor, I would like to look into this, is it still open ?

**Comment by etorreborre** [comment]
Hi @MFAlexandru. Absolutely, please create [a PR in the `ockam-contributors` repository](https://github.com/build-trust/ockam-contributors/pulls?q=is%3Apr+is%3Aclosed) if you are contributing for the first time and it's all yours!

**Comment by hlieberman** [comment]
Hi @MFAlexandru!  Are you still interested in working on this? I was taking a look at it myself, but I don't want to step on work you've done if it's something you're working on.

**Comment by MFAlexandru** [comment]
No, it is all yours

**Comment by etorreborre** [comment]
Hi @hlieberman, please go ahead!

**Comment by etorreborre** [comment]
This has now been done with the latest work on it in https://github.com/build-trust/ockam/pull/5677
