### ISSUE TITLE
The rust project does not build out of the box

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5297]
The new `ockam_app` crate is introducing some build failures when running `cargo build`:
```
error: proc macro panicked
  --> implementations/rust/ockam/ockam_app/src/lib.rs:15:16
   |
15 |         .build(tauri::generate_context!())
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: The `devPath` configuration is set to `"../../../typescript/ockam/ockam_app/build"` but this path doesn't exist
```
☝️ this error says that a directory is missing for example.

**Comment by mrinalwadhwa** [comment]
```
cd implementations/typescript
pnpm install
pnpm build
cd -
cargo build
```

This is needed currently.

**Comment by metaclips** [comment]
There is a PR here https://github.com/build-trust/ockam/pull/5266 that should allow us build with Gradle.

**Comment by SanjoDeundiak** [comment]
@mrinalwadhwa @etorreborre can we consider not building `ockam_app` by default? I think the expected experience for rust users is that `cargo build` works without any manual actions.

**Comment by etorreborre** [comment]
@SanjoDeundiak here is an idea on how to fix the issue: https://github.com/build-trust/ockam/pull/5315

**Comment by metaclips** [comment]
Fixed in https://github.com/build-trust/ockam/pull/5315. Thanks @etorreborre
