### ISSUE TITLE
Verify if a user is properly enrolled when starting the desktop app

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5338]
At the moment we only rely on a default identity to exist when determining if a user is enrolled or not.
We should extend this check to:

 1. check the `is_enrolled` field inside the `~/.ockam/identities/default.json` file
 2. check if the default space exists
 3. check if the default project exists

The code for `is_enrolled` is [here](https://github.com/build-trust/ockam/blob/01dc1703a274c153ef2ba14eef42d07056fe5b3f/implementations/rust/ockam/ockam_app/src/app/app_state.rs#L138).

The purpose of this feature is to:

 - detect a possible corruption of the enrollment process
 - ask the user to reset in that case

### Have `is_enrolled` return a `Result<bool>`

Have `is_enrolled` return a `Result<bool>` instead of just a `bool`. If any of the 3 conditions below is not met, raise an error asking the user to press `Reset` and enroll again.

The code deciding if `Reset` should be displayed is [here](https://github.com/build-trust/ockam/blob/01dc1703a274c153ef2ba14eef42d07056fe5b3f/implementations/rust/ockam/ockam_app/src/options/tray_menu.rs#L13). 

That code should now make sure that the user can either reset or quit in case of an error for `is_enrolled` and should have an additional `CustomMenuItem` with:

 - a label saying that "the application state is corrupted, please reset or quit the application"
 - an icon with a caution sign on MacOS (see an example of a native image in [`build_enroll_section`](https://github.com/build-trust/ockam/blob/01dc1703a274c153ef2ba14eef42d07056fe5b3f/implementations/rust/ockam/ockam_app/src/enroll/tray_menu.rs#L24)
```rust
#[cfg(target_os = "macos")]
let item = item.native_image(NativeImage::Caution);
```

All other sections of the menu should not be displayed.

### Check 3 conditions

We need check 3 conditions in `is_enrolled` to make sure that the user has been properly enrolled:
```rust
// is the `is_enrolled` flag set to true
// This expression deserves a `is_enrolled` function on `IdentityState` directly instead of having to navigate to the `is_enrolled` field
self.state().await.identities.get_or_default(None).unwrap().config().
            enrollment_status.map(|s| s.is_enrolled).unwrap_or(false);

// check if the default space has been set
self.state().await.spaces.default()?

// check if the default project has been set
self.state().await.projects.default()?
```

**Comment by qxtaiba** [comment]
@etorreborre I'm happy to take a stab at this. Do you mind pointing me to where exactly we want to determine if a user is enrolled or not? Is this supposed to happen in the `retrieve_user_project` fn?

**Comment by etorreborre** [comment]
@qxtaiba please hold-off a bit. I should push a PR soon that is changing quite a few things in that area.

**Comment by etorreborre** [comment]
Hi @qxtaiba now that things have stabilized a bit I have updated the description for this issue. Please ask me is something is unclear

**Comment by qxtaiba** [comment]
Thanks - I'll try to find some time to spend on this.

**Comment by qxtaiba** [comment]
Hey @etorreborre, I'm tracking this in #5459
