### ISSUE TITLE
Use a PKCE flow for enrolling a new user

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5339]
The desktop application introduces [a new way to enroll a user via a PKCE flow](https://github.com/build-trust/ockam/pull/5336) (see a description [here](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce)).

The purpose of this issue is to add the possibility to use this flow when using the command line, with a new `--authorization-code-flow` option:
```
ockam enroll --authorization-code-flow 
```

Here are some directions to get started:

 - the command and its options is defined [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/command.rs#L38).
 - the main change to implement is how we get the OIDC token. We currently get it with [this call](https://github.com/build-trust/ockam/blob/7c63b18ec6aff2cf2e055a0859c5f2799c5eecce/implementations/rust/ockam/ockam_command/src/project/enroll.rs#L196), whereas with the new flow we need to use [this method](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/auth0_service.rs#L114) instead

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by etorreborre** [comment]
Fixed via #5336

**Comment by alcolmenar** [comment]
@etorreborre I'd like to take this one on if possible

**Comment by mrinalwadhwa** [comment]
@alcolmenar that would be great. All yours, please let us know if you have any questions as you explore.

**Comment by etorreborre** [comment]
Done with #5467
