### ISSUE TITLE
Add netstat to our builder image 

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#5350]
### Observed behavior

Add netstat to our [builder image](https://github.com/build-trust/ockam/blob/develop/tools/docker/builder/Dockerfile) so that we can [appropriately handle unused port](https://github.com/build-trust/ockam/actions/runs/5553214271/jobs/10141494923#step:8:59) allocation during bats test

### Steps to reproduce

Error during port allocation [can be found here](https://github.com/build-trust/ockam/actions/runs/5553214271/jobs/10141494923#step:8:59)

### Expected behavior

Netstat command should run correctly

### Ockam Version

Version 0.90.0, hash: 8a77aa9dec024b05d9da00f4e75acd188ff6e785

**Comment by alcolmenar** [comment]
@metaclips can I take this one?

**Comment by metaclips** [comment]
All yours!

**Comment by alcolmenar** [comment]
@metaclips put up a PR for the addition. I'm assuming the builder image is pushed manually or is there a job? I can put another PR to update all the jobs to use the new image as well

**Comment by metaclips** [comment]
> @metaclips put up a PR for the addition. I'm assuming the builder image is pushed manually or is there a job? I can put another PR to update all the jobs to use the new image as well

I just kickstarted build, should take few hours. I'll comment here when it's done.

**Comment by metaclips** [comment]
Thanks @alcolmenar for getting this done
