### ISSUE TITLE
Remove the `...` at the end of the `Reset...` menu item

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5359]
# Observed behavior

We're building a Desktop System Tray app, see https://github.com/build-trust/ockam/issues/5228

The current `Reset...` menu shows three dots. According to macOS design guideline the three dots are for cases where something will open and action won't immediately happen. Change it to `Reset`.

<img width="227" alt="Screenshot 2023-07-15 at 5 23 46 PM" src="https://github.com/build-trust/ockam/assets/159583/09a0191c-441d-4360-9278-204ce468a97d">

# Steps to reproduce

```
cd implementations/typescript
pnpm install
pnpm build

cd ../../implementations/rust/ockam/ockam_app
cargo tauri dev
```

# Expected behavior

Change to `Reset`.

# Source Code

The code is here

- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app/src/enroll/menu_items.rs#L21

**Comment by Ankit8848** [comment]
Here, Just have to remove ... at the end of the Reset... from 21st line ?  As I am beginner here, please, guide me . @mrinalwadhwa

**Comment by mrinalwadhwa** [comment]
@Ankit8848 thank you for spending time on this .. yes that should do it.

Be sure to read our contribution guidelines. Looking forward to you pull request

**Comment by mrinalwadhwa** [comment]
Fixed in https://github.com/build-trust/ockam/pull/5361. Thank you @Ankit8848 🥳

**Comment by Ankit8848** [comment]
Thank you @mrinalwadhwa , for mentoring .
