### ISSUE TITLE
change ci elixir setup to use setup-elixir action 

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#536]
the setup-elixir action was having trouble with our ubuntu-20.04 github hosted runner.
they have a bug logged here https://github.com/actions/setup-elixir/issues/31

for now I've worked around it by scripting the install in our workflows.
https://github.com/ockam-network/ockam/pull/531/commits/95bceba2b8d365650fad18f475eac170c479bfa7

we should fix this when the upstream action is fixed

**Comment by davide-baldo** [comment]
@hairyhum By checking the code this issue doesn't seem relevant anymore, can I close it?

**Comment by hairyhum** [comment]
No longer relevant.
