### ISSUE TITLE
Remove all menu items before enroll, add them after enroll succeeds.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5362]
# Current

We're building a Desktop System Tray app for Ockam, see https://github.com/build-trust/ockam/issues/5228

When we first start the app the menu currently looks like this:

<img width="167" alt="Screenshot 2023-07-16 at 7 51 58 AM" src="https://github.com/build-trust/ockam/assets/159583/e32d0987-2bd1-4042-be67-486d4b03e0d2">

# Desired

Before enroll, the menu should look like this:

```
Enroll...
-------------
Please Enroll.
-------------
Quit
```

All other items should appear after enroll.

# Steps to reproduce

You can run the app as follows:

```
cd implementations/typescript
pnpm install
pnpm build

cd ../../implementations/rust/ockam/ockam_app
cargo tauri dev
```

# Source Code

The code for this is here:

- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app
- https://github.com/build-trust/ockam/blob/develop/implementations/typescript/ockam/ockam_app

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081) or join us on [discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, checkout labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by aleksandarskrbic** [comment]
I would like to take this one! @mrinalwadhwa

**Comment by mrinalwadhwa** [comment]
That would be awesome.. all yours
