### ISSUE TITLE
Rename `Quit` menu to `Quit Ockam` in desktop system tray app.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5363]
# Current

We're building a Desktop System Tray app, see https://github.com/build-trust/ockam/issues/5228

The current `Quit` menu looks like this:

<img width="170" alt="Screenshot 2023-07-16 at 8 16 01 AM" src="https://github.com/build-trust/ockam/assets/159583/f881a37d-ee7b-4efd-8a5d-6c2e18994188">

# Desired

According to Apple's design guidelines, Quit menus should show the name of the app.
We want to change it to `Quit Ockam`

# Steps to reproduce

You can run the app as follows:

```
cd implementations/typescript
pnpm install
pnpm build

cd ../../implementations/rust/ockam/ockam_app
cargo tauri dev
```

# Source Code

The code is here

- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app/src/quit/menu_items.rs#L13

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081) or join us on [discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, checkout labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Ankit8848** [comment]
@mrinalwadhwa let me do it .

**Comment by mrinalwadhwa** [comment]
Reopening this issue, since it seems we have some regression back to `Quit` in the latest develop. cc: @adrianbenavides @etorreborre
