### ISSUE TITLE
Investigate if the macOS toggle is possible in system tray app build with Tauri

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5364]
We're building a Desktop System Tray app for Ockam, see https://github.com/build-trust/ockam/issues/5228

Here are two ways we could design the UI for an Ockam node running in the background.

1. With a toggle, this is the more modern macOS approach:

<img width="302" alt="Screenshot 2023-07-16 at 8 24 12 AM" src="https://github.com/build-trust/ockam/assets/159583/683dd001-4568-4e01-9781-96e9475ceabd">

2. A status menu item (like Docker is running) combined with menu items to start and stop.

<img width="260" alt="Screenshot 2023-07-16 at 8 24 26 AM" src="https://github.com/build-trust/ockam/assets/159583/6d407d85-ae8a-4590-9de3-595353a4b565">

We should investigate if the toggle is possible with Tauri/Tao/Muda
https://github.com/tauri-apps/tauri
https://github.com/tauri-apps/tao/tree/muda
https://github.com/tauri-apps/muda

I imagine that the rendering is delegated to macOS so makes sense for it to be possible somehow.

# Run

You can run the current version of the app as follows:

```
cd implementations/typescript
pnpm install
pnpm build

cd ../../implementations/rust/ockam/ockam_app
cargo tauri dev
```

# Source Code

The code for this is here:

- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app
- https://github.com/build-trust/ockam/blob/develop/implementations/typescript/ockam/ockam_app

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081) or join us on [discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, checkout labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by tusharxoxoxo** [comment]
on it

**Comment by davide-baldo** [comment]
@tusharxoxoxo Thanks! please let us know if you have any question!

**Comment by etorreborre** [comment]
@nazmulidris should we still keep this issue open as such or is it included in another piece of work?

**Comment by mrinalwadhwa** [comment]
I think we can close it, it's included in @davide-baldo's work with https://github.com/build-trust/ockam/issues/5774
