### ISSUE TITLE
Improve spacing in output when calling `ockam node list`

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#5384]
### Observed behavior

Calling the below
```bash
ockam node create n1
ockam node create n2
```
and then calling `ockam node list` give inconsistent output
```
       ┌───────────────────┐
       │       Nodes       │
       └───────────────────┘
     │ Node n1 (default) UP
     │ Process id 57293

     │ Node n2  UP
     │ Process id 57405
```
`Node n2  UP` adds an extra unneeded space

### Expected behavior

On calling `ockam node list` we should not get irregular spacing in output

### Ockam Version

ockam v0.90.0

**Comment by GabrielBarbosaGV** [comment]
Hello! Hope you're doing well.

I would like to work on this issue, however, I am new to both open-source and Ockam, and came across this issue through "This Week in Rust". Would it be OK for me to work on this, even so?

If so, I would just like to ask if I understand the issue properly - is it simply that the output should have the "Nodes" header slightly to the left of where it is presented, or, besides that, should it have equal width to the output that follows?

Many thanks!

**Comment by mrinalwadhwa** [comment]
@GabrielBarbosaGV 👋 You're very welcome to work on it!

the issue is in these lines:

```
Node n1 (default) UP
Node n2  UP
```

`n2  UP` should have only one space between, currently it has two.

Here's the code for the node commands
https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command/src/node

**Comment by mrinalwadhwa** [comment]
Actually looks like someone has already sent a Pull Request addressing this
https://github.com/build-trust/ockam/pull/5394

Please explore other issues with this label https://github.com/build-trust/ockam/labels/good%20first%20issue and let us know if any of those are interesting.

**Comment by GabrielBarbosaGV** [comment]
@mrinalwadhwa Oh, ok - thank you for pointing it out! I will just finish getting started with Ockam, and will seek out another issue I might work on. Many thanks!

**Comment by mrinalwadhwa** [comment]
Great, if you have questions, as you explore, join us on the contributors discord channel https://discord.gg/bewvnm6zqS
