### ISSUE TITLE
Rename the `Auth0` traits and structs to `Oidc`

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5436]
The current naming of some traits and structs used to enroll users is incorrect. Some names contain `Auth0` when we really mean `OAuth` (for OAuth 2.0) or `Oidc` (for OIDC - OpenID Connect). The authentication flows using Auth0 or Okta are specific cases of an OIDC flow.

**Note:** 

 - OpenID Connect includes a couple of extra things on top of OAuth 2.0: an ID Token and a /userinfo endpoint
 - We rely on `/userinfo` to get authenticated attributes (eg. email) so we’re using OpenID Connect.

The purpose of this issue is to rename `Auth0` to `Oidc` in the following traits, structs, and associated modules:

 - [`Auth0Provider`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/auth0_provider.rs)
 - [`Auth0Token`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/cloud/enroll.rs#L180)
 - [`AuthenticateAuth0Token`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_api/src/cloud/enroll.rs#L201)
 - [`Auth0Service`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/auth0_service.rs)

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by aleksandarskrbic** [comment]
I would like to take this one!

**Comment by etorreborre** [comment]
@aleksandarskrbic please do.

**Comment by etorreborre** [comment]
Done with #5444
