### ISSUE TITLE
Add an option to enroll without creating a space nor a project

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5452]
# Description

The current `ockam enroll` command is very practical because it does 3 things at once:

 1. it executes an authentication flow to enroll a user (you can think about that as "create an account on the Orchestrator")
 2. it creates a default `Space` for the user (a `Space` is a collection of `Projects` at the level of an organization)
 3. it creates a default `Project` in that `Space` for the user

Independent commands actually exist to create a `Space` and create a `Project` for a given user, and could be executed independently of `ockam enroll`. This can be particularly useful to test the creation of user accounts in test scenarios since the creation of space and specifically projects involve the time-consuming deployment of nodes inside the Orchestrator.

# Feature

The purpose of this feature is add an option to `ockam enroll` so that only the first step is executed:
```
ockam enroll --user-account-only
```
(please @mrinalwadhwa propose another flag name if you have a better idea)

# Implementation notes

 - the `Enroll` command and its options is defined [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/command.rs#L40).
 - the code retrieving and / or creating a `Space` and a `Project` is defined [`here`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/command.rs#L86). Note that we just want to skip space/project creation. If they already exist for a given user they should still be retrieved and be set as its defaults

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by aleksandarskrbic** [comment]
I would like to take this one :)

**Comment by etorreborre** [comment]
@aleksandarskrbic all yours!

**Comment by polvorin** [comment]
hi @aleksandarskrbic  :wave:  are you still interesting on working on this issue?,  do you need guidance?

**Comment by nazmulidris** [comment]
Hi @aleksandarskrbic 👋 . Thank you, since you’ve not had a chance we’re opening the issue up for other contributors.

**Comment by haruska** [comment]
I was going to take a stab at this as a first contribution. If someone else is attempting, let me know.

**Comment by nazmulidris** [comment]
@haruska That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
