### ISSUE TITLE
Investigate how to create a richer system tray UI with Rust / Tauri

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5453]
Our [vision for the Ockam desktop application](https://github.com/build-trust/ockam/issues/5228) is to provide a system tray with a visually rich UI containing:

 - menu items triggering async actions
 - images
 - native icons
 - text with variable fonts
 - progress or status indicators
 - [large on/off switch button](https://github.com/build-trust/ockam/issues/5364)
 - modal windows for complex input data

We've started implementing the application on top of [`tauri`](https://tauri.app) since it provides some of this functionality out of the box:

 - a system tray
 - menu items with actions
 - native icons (MacOS only)
 - modal windows

This is unfortunately limited and we want to explore richer alternatives:

 - either other libraries
 - or extensions to the `tauri` underlying libraries, [`tao`](https://github.com/tauri-apps/tao) and [`muda`](https://github.com/tauri-apps/muda), [`tray_icon`](https://github.com/tauri-apps/tray-icon)

**Comment by mrinalwadhwa** [comment]
@etorreborre this looks interesting
https://crates.io/crates/cocoa

Here's an example of someone calling the [MacOS AppKit](https://developer.apple.com/documentation/appkit)
https://github.com/olback/tray-item-rs/blob/master/src/api/macos/mod.rs

**Comment by mrinalwadhwa** [comment]
Tao and Muda seem to be using the same approach as the [above example](https://github.com/build-trust/ockam/issues/5453#issuecomment-1655520212)

https://github.com/tauri-apps/tao/blob/b31cb692df2b0a03d2fbdf2fbf7ba82591678e24/src/platform_impl/macos/system_tray.rs#L20

https://github.com/tauri-apps/muda/blob/e5324b76840dbe7414107ad4a1ea35296a63b425/src/platform_impl/macos/mod.rs#L62

**Comment by etorreborre** [comment]
@nazmulidris is this issue now part of a specific story?

**Comment by nazmulidris** [comment]
I think this can be closed. It is part of this https://github.com/build-trust/ockam/issues/5774
