### ISSUE TITLE
Display the user name and email in the desktop application

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5469]
# Observed behavior

## Authenticating with Github

The desktop application currently displays the user name and nickname when logged in with Github:

<img width="293" alt="image" src="https://github.com/build-trust/ockam/assets/10988/2aa6c04c-af04-40ec-9069-9208799302fb">

The purpose of this issue is to display the user email instead of the user nickname instead.

## Authenticating with an email / password

There is a twist though. If the user authenticates with an email address and a password then the authenticated data that is returned will contain the user email as its name:

<img width="348" alt="image" src="https://github.com/build-trust/ockam/assets/10988/4f0cd138-5952-4425-bf55-9066ea7e682e">

Indeed the user information returned by `Auth0` is:
```
{ 
  sub: "auth0|64a3dddaae098e4df833967e", 
  nickname: "etorreborre", 
  name: "etorreborre@gmail.com", 
  picture: "https://s.gravatar.com/avatar/c3ca58d450c7ba8118337d02bff5060f? s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fet.png", 
  updated_at: "2023-08-01T08:45:06.468Z", 
  email: "etorreborre@gmail.com", 
  email_verified: true 
}
```

# Feature

We want to display the user information as `Name (email)`. This requires to deal with 2 cases:

 1. Github authentication: display `${user_info.name} (${user_info.email})`
 2. Email authentication: display `${user_info.nickname} (${user_info.email})`

The second case can be tested with a condition like `if user_info.email == user_info.name....`

# Implementation notes

The code displaying the user information can be found [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app/src/enroll/tray_menu.rs#L21). Please extract the new logic as a separate function and add a unit test for that function.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by mehboobali98** [comment]
Hey, can I work on this?

**Comment by etorreborre** [comment]
Hi @mehboobali98 yes please do.

**Comment by mrinalwadhwa** [comment]
@mehboobali98 @etorreborre I was thinking about this. I think it would be better to only show email since we consistently have that information. Let's go with that route.

@mehboobali98 I hope that doesn't add any confusion. Let us know if you have any questions.

Looking forward to your pull request.

**Comment by adrianbenavides** [comment]
We have landed a couple of PR's modifying how we display this information. Should we close this issue and reopen it if it needs further attention?

**Comment by etorreborre** [comment]
This can be closed now
