### ISSUE TITLE
Make the ockam relay commands more consistent

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5472]
# Observed behavior

The command to create a relay specifies that a relay can be created `at` a node and relay traffic `to` a node:
```
Usage: ockam relay create [OPTIONS] [RELAY_NAME]

Arguments:
  [RELAY_NAME]  Name of the relay

Options:
      --at <ROUTE>               Route to the node at which to create the relay [default:
                                 /project/default]
      --authorized <AUTHORIZED>  Authorized identity for secure channel connection
      --to <NODE>                Node for which to create the relay
```

However the command to list relays allows to specify a node for which there exists some relays:
```
Usage: ockam relay list [OPTIONS]

Options:
      --at <NODE>  Node to list relays from
```

This is not very consistent and it would be better to keep the same `to` argument in both cases.

# Expected behavior

The `ockam relay list` should have a `to` argument with the following help text:
```
      --to <NODE>  List all the relays relaying traffic to the specified node
```

# Implementation notes

The code listing relays can be found [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/list.rs#L30) and the help text is extracted from [this comment](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/list.rs#L28).

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by Qeyphen** [comment]
@etorreborre I'd like to work on this.

**Comment by etorreborre** [comment]
Hi @0xphen, please do.
