### ISSUE TITLE
Setup nix cache

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5499]
https://github.com/DeterminateSystems/magic-nix-cache-action

**Comment by shanesveller** [comment]
I've successfully used this action on my open-source Nix library for installing BEAM toolchains, and as advertised it produces much better results than caching `/nix/store`. You can see the implementation details in a worked example at https://github.com/shanesveller/nix-beam-flakes/pull/6. The Cachix steps are not necessary to include on this repo at this time.

For anyone who plans on working on this, please also CC myself and @etorreborre as additional reviewers.
