### ISSUE TITLE
[FEAT]: Dark Mode along with Toggle Theme Switch

### ISSUE THREAD

**Issue by SaketKaswa20** [build-trust/ockam#5522]
### Current behavior

Dark theme should be added for the whole website along with this a toggle switch should be provided to switch between the themes.

### Desired behavior

When the switch is clicked, the website should be in dark/light mode.

**Comment by mrinalwadhwa** [comment]
@SaketKaswa20 thank you for sharing that you felt the need for that.
Are you referring to [ockam.io](https://ockam.io) or [docs.ockam.io](https://docs.ockam.io) or both?

They both have their independent repos
https://github.com/build-trust/ockam-website
https://github.com/build-trust/ockam-documentation

Would you mind opening the issues on those repos instead?

**Comment by SaketKaswa20** [comment]
I am referring to ockam.io.
Sure, I will raise the issue in that repository.
Thank you

**Comment by mrinalwadhwa** [comment]
Thank you.
