### ISSUE TITLE
Good First Issue: Give user feedback on Ockam Command

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5523]
# Seeking feedback

We are seeking feedback on the below QuickStart section of our project's readme. 
Our goal here is to learn if people have a good experience trying out this first example. Does it make sense? How can we improve it to make it more clear?

If you are looking for a way to contribute to Ockam this is a great place to start. If you can record your screen when trying this example that would be extremely helpful. Share with us any thoughts or questions that come to mind as you try this example out. If you feel confused at some point share that. If you have a question at some point share that. Share your inner monologue as you try the below QuickStart section.

Share any links to videos or notes as reply to this thread or in a [Github Discussion](https://github.com/build-trust/ockam/discussions)

---

Such a contribution of your time is just as valuable as a code contribution. So please add yourself to [ockam-contributors](https://github.com/build-trust/ockam-contributors) list by accepting the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md). Add your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified. 

---
# The thing we want feedback on:

## Quick Start

Let's build a solution for a very common secure communication topology that applies to many real world use cases. We'll build our first example using [Ockam Command](https://docs.ockam.io/reference/command) but it is just as easy to build end-to-end trustful communication using [Ockam Programming Libraries](https://docs.ockam.io/reference/libraries/rust)

An application service and an application client running in two private networks wish to securely communicate with each other without exposing ports on the Internet. In a few simple commands, we’ll make them safely talk to each other through an End-to-End Encrypted Cloud Relay.

## Install Ockam Command

On Linux and MacOS systems you can install Ockam using curl.

```bash
curl --proto '=https' --tlsv1.2 -sSf \
    https://raw.githubusercontent.com/build-trust/ockam/develop/install.sh | bash
```

### End-to-end encrypted and mutually authenticated communication

Next, step through the following commands to setup secure and private
communication between an application service and an application client.

```bash
# Check that everything was installed correctly by enrolling with Ockam Orchestrator.
#
# This will create a Space and Project for you in Ockam Orchestrator and provision an
# End-to-End Encrypted Cloud Relay service in your `default` project at `/project/default`.
ockam enroll

# -- APPLICATION SERVICE --

# Start an application service, listening on a local IP and port, that clients would access
# through the cloud encrypted relay. We'll use a simple HTTP server for this first example
# but this could be any other application service.
python3 -m http.server --bind 127.0.0.1 6000

# In a new terminal window, setup a tcp-outlet that makes a TCP service available at the given
# address `6000`. We can use this to send raw TCP traffic to the HTTP server on port `6000`.
# Finally create a relay in your default Orchestrator project. Relays make it possible to
# establish end-to-end protocols with services operating in a remote private networks, without
# requiring a remote service to expose listening ports to an outside hostile network like the
# Internet.
ockam tcp-outlet create --to 6000
ockam relay create

# -- APPLICATION CLIENT --

# If you are running this on a completely separate machine, run ockam enroll again.
# If its the same machine no need to run ockam enroll again
ockam enroll

# Setup a a local tcp-inlet to allow raw TCP traffic to be received on port `7000` before
# it is forwarded. A TCP inlet is a way of defining where a node should be listening for
# connections, and where it should forward that traffic to.
ockam tcp-inlet create --from 7000

# Access the application service, that may be in a remote private network though
# the end-to-end encrypted secure channel, via your private and encrypted cloud relay.
curl --head 127.0.0.1:7000

# -- RESET --
# Reset everything on each machine
ockam reset
```

### Private and secure by design

In the example above, we’ve created two nodes and established an end-to-end secure channel between them through an encrypted cloud relay. For the sake of simplicity, we ran both ends on a single machine but they could also be run on completely separate machines with the same result: an end-to-end encrypted and mutually authenticated secure channel.

Distributed applications that are connected in this way can communicate without the risk of spoofing, tampering, or eavesdropping attacks irrespective of transport protocols, communication topologies, and network configuration. As application data flows across data centers, through queues and caches, via gateways and brokers - these intermediaries, like the cloud relay in the above example, can facilitate communication but cannot eavesdrop or tamper data.

You can establish secure channels across networks and clouds over multi-hop, multi-protocol routes to build private and secure by design distributed applications that have a small vulnerability surface and full control over data authenticity, integrity, and confidentiality.

### Trust for data-in-motion

Behind the scenes, the above commands generated unique cryptographically provable identities and saved corresponding keys in a vault. Your orchestrator project was provisioned with a managed credential authority and every node was setup to anchor trust in credentials issued by this authority. Identities were issued project membership credentials and these cryptographically verifiable credentials were then combined with attribute based access control policies to setup a mutually authenticated and authorized end-to-end secure channel.

Your applications can make granular access control decisions at every request because they can be certain about the source and integrity of all data and instructions. You place zero implicit trust in network boundaries and intermediaries to build applications that have end-to-end application layer trust for all data in motion.

---

What did you think? Did it makes sense? How could the quickstart be better?
Thank you for you thoughts and feedback.

**Comment by adiSuper94** [comment]
>Modern applications are distributed and have an unwieldy number of interconnections that must trustfully exchange data. To trust data-in-motion, applications need end-to-end guarantees of data authenticity, integrity, and confidentiality. To be private and secure by-design, applications must have granular control over every trust and access decision. Ockam allows you to add these controls and guarantees to any application.

As someone with very little practical cryptography knowledge, the first question that I pops in my head is "isn't HTTPS enough ? If it isn't, then how ?"
I understand that answering this question might be out the the scope of this readme, or users might be expected to know the answer. But it would be nice if there was a document explaining that, or at least links to resources explaining that. 


While following the quick start guide. It took some slow reading to understand and visualize what the `--to` and `--from` meant.

![248915447-d7fe6249-f796-449c-9a8d-ffa8e170875e](https://github.com/build-trust/ockam/assets/8631902/528f83b9-4eff-4440-8071-fab6b8fb6d53)
This picture is really helpful to visually show what is happening. So maybe including something like this would be nice.

Ultra Nit: reordering the code to configure the inlet first and then outlet might also help.

**Comment by mrinalwadhwa** [comment]
That's great feedback! Thank you.
I'll keep that in mind as we iterate on the guide.

> reordering the code to configure the inlet first and then outlet might also help.

That part is unfortunately not possible. TCP Outlets must exist first for a TCP Inlet to connect to.

**Comment by nazmulidris** [comment]
@adiSuper94 Thanks for the great feedback. I am glad that the picture was helpful. 

Re: Is HTTPS enough? 
- This section in the following blog post touches upon the risk of just relying on HTTPS (transport layer security): https://www.ockam.io/blog/routing#mitigating-risk
- Does this help w/ understanding why HTTPS might not be enough in many use cases? 😄 Or do you think more concrete use case & diagrams might help clarify that section?

**Comment by adiSuper94** [comment]
> This section in the following blog post touches upon the risk of just relying on HTTPS (transport layer security): https://www.ockam.io/blog/routing#mitigating-risk

@nazmulidris, Intriguing. This made me realize that I am blissfully unaware of possible points of attack!

>Does this help w/ understanding why HTTPS might not be enough in many use cases? 😄 Or do you think more concrete use case & diagrams might help clarify that section?

This definitely helps, and as far as this quick start guide is concerned, either a link to this doc/blog or a few lines pointing out that HTTPS "sorta breaks" at hop should be a good intro to the risk.

But this still leaves *me* wanting to see and setup a toy use case where HTTPS isn't enough and see the vulnerability.
I realize this might not be very easy, as we need to view the data at different points along its route to the destination.
This might be new blog idea maybe ??

**Comment by adiSuper94** [comment]
@nazmulidris I am following the routing blog that you linked in you previous comment.
I tried out the 'simple-example'  and created the `Echoer` & `Hopper` worker before starting the [complex-example](https://www.ockam.io/blog/routing#complex-example). It refers to a worked called `Forwarder` which I couldn't find find anywhere.

**Comment by nazmulidris** [comment]
@adiSuper94 Good catch. I've added the missing file in the blog post (`/src/forwarder.rs`). You can find it here: https://www.ockam.io/blog/routing#middle-node
