### ISSUE TITLE
`ockam tcp-outlet create` should support `HOSTNAME:PORT` format

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5563]
Currently, `ockam tcp-outlet create` command located [here](https://github.com/build-trust/ockam/blob/c0ebe05dd644c271ba394b61d8b58edf8e0a31ee/implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs) only supports `--to` argument in the form of `SocketAddr` (`IP:PORT`). However, supporting the `HOSTNAME:PORT` format is sometimes required (e.g., in containerized environments).  Therefore, `ockam tcp-outlet create` should support `HOSTNAME:PORT` arguments as well.

As an example, `ockam tcp-connection create` command [here](https://github.com/build-trust/ockam/blob/c0ebe05dd644c271ba394b61d8b58edf8e0a31ee/implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs) supports such format.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by alcolmenar** [comment]
hey @SanjoDeundiak, can I take this one on?

**Comment by SanjoDeundiak** [comment]
@alcolmenar sure

**Comment by mrinalwadhwa** [comment]
@alcolmenar thank you for spending time on this .. everywhere we accept a socket address we want to support all three of these:

1. IP:PORT
2. HOSTNAME:PORT
3. PORT (this assumes IP is 127.0.0.1)

**Comment by alcolmenar** [comment]
@mrinalwadhwa sure thing. ok I'll see what I can do

**Comment by mrinalwadhwa** [comment]
Awesome, thank you.

**Comment by alcolmenar** [comment]
@mrinalwadhwa @SanjoDeundiak Question, in regards to the enabling `HOSTNAME:PORT` for all places SocketAddr is used, there are some cases a bind is being created on the machine running the ockam command, e.g. tcp-inlet where a socket address would be needed usually 127.0.0.1 or 0.0.0.0. I'm thinking to only change areas of the code where a hostname can be used?
