### ISSUE TITLE
Remove unused `Error` enum members and avoid appearing of such members in the future

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5564]
Our current design has different `Error` enums to indicate different types of errors. Usually, there is one enum per crate (but it's not a requirement). Also, as a rule, Errors defined in a crate can be returned only from that crate. But the enum should be public so that users of that code could handle those Errors correctly. Over time, many unused enum members appeared, and the compiler can't figure out they are unused since they're public and can, theoretically, be used from other crates. Those members should be deleted. [Here](https://github.com/build-trust/ockam/blob/c0ebe05dd644c271ba394b61d8b58edf8e0a31ee/implementations/rust/ockam/ockam/src/error.rs#L17) is the example of such enum and a member that is no longer used.

Also, ideas on preventing such members from appearing in the future without needing us to check it manually are welcome.

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by jatinderjit** [comment]
There are a few error enums that are marked `pub`, but probably don't need to be.

The [`OckamError`](https://github.com/build-trust/ockam/blob/ee679cf90307c739599a3588e76adb48dfb0a75b/implementations/rust/ockam/ockam/src/error.rs#L14) enum is a good example. It is never directly returned from any public interface, but is returned as `ockam_core::Error` ([example](https://github.com/build-trust/ockam/blob/ee679cf90307c739599a3588e76adb48dfb0a75b/implementations/rust/ockam/ockam/src/system/mod.rs#L114)).

Such enums can be marked as `pub(crate)`, which will enable the `dead_code` warnings for the unused enum members.

This does not work for every case though. [`VaultError`](https://github.com/build-trust/ockam/blob/ee679cf90307c739599a3588e76adb48dfb0a75b/implementations/rust/ockam/ockam_vault/src/vault/vault_error.rs#L11) has unused members as well, and is never emitted from any `pub` function. But it needs to be pub for a single [cross-crate dependency](https://github.com/build-trust/ockam/blob/ee679cf90307c739599a3588e76adb48dfb0a75b/implementations/rust/ockam/ockam_vault_aws/src/vault/aws_security_module.rs#L86), where it is again returned as `ockam_core::Error`. So it can't trivially be marked as `pub(crate)`.

But it does work for a few more cases.
@SanjoDeundiak does this approach work for you? I'll create a PR if it does.

**Comment by SanjoDeundiak** [comment]
Hey @jatinderjit. What you wrote makes sense to me. However, there is a known issue with our error design. As you probably noticed, those enum members are not directly returned from any function, instead, they get wrapped in `ockam_core::Error`. After that, it's impossible to conveniently and reliably figure out what enum member was used to return the error initially. That's what we would like to fix eventually. For now, making those enums `pub(crate)` would be a change in the opposite direction from that. Does that make sense to you?

**Comment by jatinderjit** [comment]
Yes, makes sense.

I could think of a convoluted solution to enable the dead code warnings for unused members - use private error enums everywhere in the code, and use macros to generate `pub` copies of these enums that will instead be exposed to the users of the libraries. Also generate the `From` impl for easier conversions. But it would be overkill (and probably impractical) for this job.

Meanwhile, I had removed the unused enum members after I changed the error enums to `pub(crate)`. Do you want me to create a PR just for that? This will just remove the currently unused members, which can still pop up in the future though.

**Comment by SanjoDeundiak** [comment]
@jatinderjit Yeah, I agree that the suggested approach is overkill. Maybe running some kind of script with a check on the CI would be simpler.

Please submit the PR with removed unused members, that would be wonderful!
