### ISSUE TITLE
Improve documentation of `ockam completion` command to specify how to use it properly

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5565]
### Current behavior

The documentation of `ockam completion` is vague and doesn't work out of the box for the platforms we support (Linux, MacOS).

### Desired behavior

The documentation should include:
1. The steps to build the completion file
2. Where to store it
3. Explain what's the expected result

Proposed changes for the [`after_long_help.txt` file](https://github.com/build-trust/ockam/blob/c9d3b68b4d4d3dc7d4e51597d4e158d8b2a4ff1e/implementations/rust/ockam/ockam_command/src/completion/static/after_long_help.txt):

----

First off, you need a valid directory to store the completions file based on your OS and shell. One way to do that is to observe the `FPATH` environment variable. Usually, you will find one of the following:

- Bash: `/usr/share/bash-completion/completions`
- ZSH: `/usr/local/share/zsh/site-functions`
- Fish: `~/.config/fish/completions`

Now, make sure the directory exists running `mkdir -p {dir}` and execute the command to generate the completion file. Note that the file name must be exactly as shown below.

```sh
$ ockam completion --shell bash > /usr/share/bash-completion/completions/ockam.bash
$ ockam completion --shell zsh > /usr/local/share/zsh/site-functions/_ockam
$ ockam completion --shell fish > ~/.config/fish/completions/ockam.fish
```

Finally, run `compinit` to rebuild the completion of your shell.

---

This is the expected result

[![asciicast](https://asciinema.org/a/C2uwlW1soMpDxW3tPK34Z6Xot.svg)](https://asciinema.org/a/C2uwlW1soMpDxW3tPK34Z6Xot)

**Comment by iakev** [comment]
Hi, I would like to help out on this issue. Since it's a good first issue for someone currently learning Rust like me.

**Comment by mrinalwadhwa** [comment]
@iakev that would be awesome. All yours
