### ISSUE TITLE
Add icons to the `Name`, `Reset` and `Quit Ockam` menu items

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5566]
# Current

We're building a Desktop System Tray app for Ockam using Tauri, see https://github.com/build-trust/ockam/issues/5228

When we start the app in macOS the context menu on the top right the `Name`, `Reset` and `Quit Ockam` menu items look like this:
 
![Screenshot 2023-08-09 at 7 00 45 AM](https://github.com/build-trust/ockam/assets/6513916/9112b9e3-368a-4ee9-b1aa-6b9a2ee27604)

But should look like this:

![Screenshot 2023-08-09 at 7 00 58 AM](https://github.com/build-trust/ockam/assets/6513916/f26e3299-88f8-4d05-b16b-5902278ca81f)

# Desired

Add corresponding icons to the `Name`, `Reset` and `Quit Ockam` rows

# Steps to reproduce

You can run the app as follows:

```
cd implementations/typescript
pnpm install
pnpm build

cd ../../implementations/rust/ockam/ockam_app
cargo tauri dev
```

# Source Code

The code for this is here:

- https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app
- https://github.com/build-trust/ockam/blob/develop/implementations/typescript/ockam/ockam_app

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081) or join us on [discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, checkout labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by SanjoDeundiak** [comment]
This one is related https://github.com/build-trust/ockam/issues/5469#issuecomment-1664138733

**Comment by SanjoDeundiak** [comment]
Icons:
https://icons.getbootstrap.com/icons/power/
https://icons.getbootstrap.com/icons/recycle/
https://icons.getbootstrap.com/icons/person-circle/

**Comment by titanventura** [comment]
Would like to take this up!

**Comment by mrinalwadhwa** [comment]
@titanventura that's awesome. Let us know if you have any questions.

**Comment by etorreborre** [comment]
As far as I know [those are the only images](https://github.com/tauri-apps/tao/blob/33195d79001f73781aeac722f7014ae4df8899d6/src/platform/macos.rs#L110) we can use, at the moment, as icons on Mac (I don't know where is the most recent version of that file).

Maybe @nazmulidris has something to add on the subject?

**Comment by nazmulidris** [comment]
I'm using icons in my design and from what I've seen w/ a demo that @adrianbenavides shared 2 weeks ago (I think) that we can use icons that are png files.

**Comment by etorreborre** [comment]
That's great news!

**Comment by nazmulidris** [comment]
@etorreborre Here's a mock of some screens that have icons now 😄 
![image](https://github.com/build-trust/ockam/assets/2966499/b89bb2ee-f505-458e-9f37-baa550876642)
