### ISSUE TITLE
Check key/secret size before casting as a fixed-length array

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5631]
### Current behavior

At [`vault_kms.rs`](https://github.com/build-trust/ockam/blob/4072da26ad22fec2da6ae8823e5cf934325ce404/implementations/rust/ockam/ockam_vault/src/vault/vault_kms/vault_kms.rs), the data size is not being checked before casting it as a fixed-length array, which would cause an unexpected panic in case of mismatch.

### Desired behavior

We need to check the data has the correct size before creating the fixed-length array so we can return a proper error. [Here](https://github.com/build-trust/ockam/blob/4072da26ad22fec2da6ae8823e5cf934325ce404/implementations/rust/ockam/ockam_vault/src/vault/vault_kms/vault_kms.rs#L80) is an example of how we should do the check.

The functions we need to review are (every branch where use `array_ref`):
- `compute_public_key_from_secret`
- `sign_with_secret`
- `compute_key_id`

**Comment by rjtch** [comment]
Hey i would like to take this task

**Comment by adrianbenavides** [comment]
Sure, go ahead! Please let us know if you have any questions 👍

**Comment by etorreborre** [comment]
Fixed with #5765
