### ISSUE TITLE
simplify key usage during noise handshake

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#5654]
### Current behavior

[here](https://github.com/build-trust/ockam/blob/bd95cea787f1ef138717d2db340253069cd2ef2b/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex#L259-L262)   and [here](https://github.com/build-trust/ockam/blob/bd95cea787f1ef138717d2db340253069cd2ef2b/implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex#L269-L272)    we are exporting the key from the vault just to import it back as a 'aes'  key.     This part of the code is old, and is likely a leftover,    the `k`  is already an aes key,  and we can use it directly.

### Desired behavior

* Remove the export/import steps
* Use the existing `k` directly
* Remove the `secret_destroy` call as we aren't creating a transient one anymore

**Comment by BobbieBarker** [comment]
I added a PR for this issue. Please let me know if I misunderstood anything about the request/issue and I will work to resolve it asap. 

I'm noticing it looks like GH thinks the PR is unverified even though I signed it. I didn't realize that I needed to use the same email address on my signature as I do on my GH account. Let me know if this is a problem and I will work to resolve it.
