### ISSUE TITLE
rename --ticket-ttl  argument to --expires-in

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#5673]
### Observed behavior

The `project ticket`  command accepts a  `ticket-ttl`  [argument](https://github.com/build-trust/ockam/blob/2513cc701aacc9ccb32c715b096aa7d093abd1bd/implementations/rust/ockam/ockam_command/src/project/ticket.rs#L54) that is the time-to-live of the generated ticket,  in seconds.
Rename that argument for `expires-in`

### Steps to reproduce

`$ ockam project ticket -h`

### Expected behavior

an `--expires-in` argument replace the existing `--ticket-ttl`

### Ockam Version

develop

**Comment by seve-martinez** [comment]
👋 I'd like to take this one
