### ISSUE TITLE
ockam_command hangs when calling `lease` on an uninitialized project

### ISSUE THREAD

**Issue by seve-martinez** [build-trust/ockam#5674]
### Observed behavior

If you run `ockam lease --token_id 1234` before a project has been initialized, it will panic.  However since the panic happens within an async task, the program hangs rather than shutting down.

Specifically here:
https://github.com/build-trust/ockam/blob/3c06be25cd02794016562af33d2e55f765142539/implementations/rust/ockam/ockam_command/src/util/orchestrator_api.rs#L210

A crtl-C is required to return to the terminal prompt.

The printed message is
```
thread 'tokio-runtime-worker' panicked at 'A default project or project parameter is required: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

This is somewhat related to #5633 

### Steps to reproduce

1. remove `~/.ockam`
2. run `ockam lease --token_id 1234`

### Expected behavior

The application should return an Error to notify the user that a project must be initialized prior to calling `lease` and shutdown gracefully.

### Ockam Version

0.90.0

**Comment by seve-martinez** [comment]
Happy to submit a PR on this. After some code review, it looks like this could be mitigated by returning a [CLIStateError](https://github.com/build-trust/ockam/blob/2513cc701aacc9ccb32c715b096aa7d093abd1bd/implementations/rust/ockam/ockam_api/src/cli_state.rs#L33) back up the call stack with additional context.

**Comment by etorreborre** [comment]
Hi @seve-martinez, please do. I think we need an error with a specific message telling the user that they should enroll first so that the default project exists
