### ISSUE TITLE
In the `Share a service` window, the `Port` should be renamed to `Address` and support such format

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5685]
## Current

The `Share a service` window only allows the user to define the service port.

![image](https://github.com/build-trust/ockam/assets/12375782/3717776b-f3c7-4454-ac79-0d0e9ac323a7)

## Desired

The user should be able to define the whole address. To achieve that, we need to:
- Replace the `Port` field name to `Address`
- We should support the formats `Host:Port`, `IP:Port` and `Port` (defaulting to 127.0.0.1)
- Adapt the [app backend](https://github.com/build-trust/ockam/blob/9cbae5419888e55ceecd3cd6cd9cfeff88158b01/implementations/rust/ockam/ockam_app/src/shared_service/tcp_outlet/create.rs#L38) to parse the address correctly.
---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by 0x61nas** [comment]
> The user should be able to define the whole address.

so you want to rename it and make it contain both of address and port in this format `ADDRESS:PORT`, did I get it right?

**Comment by etorreborre** [comment]
@0x61nas yes and `PORT` only. And in that case we set `ADDRESS=127.0.0.1`

**Comment by 0x61nas** [comment]
cool, in this case, I think that I can work on this, Please assign this issue to me if you don't mind
