### ISSUE TITLE
Use a user-friendly name for the shared services to show it in the tray menu

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5686]
## Current

In the tray menu, we show the TCP Outlet's worker address and socket address for each shared service.

![image](https://github.com/build-trust/ockam/assets/12375782/cfd04777-2562-4021-9e92-c5e6440fc369)

## Desired

Replace the current `{worker_address} to {socket_address}` identifier, [which is built here](https://github.com/build-trust/ockam/blob/9cbae5419888e55ceecd3cd6cd9cfeff88158b01/implementations/rust/ockam/ockam_app/src/shared_service/tray_menu.rs#L68), to a more user-friendly one:
- If the user has one space and one project: `/{email}/{service_name}`
- If the user has one space and multiple projects: `/{email}/{project_name}/{service_name}`
- If the user has multiple spaces and projects: `/{email}/{space}/{project_name}/{service_name}`

The email, spaces, and projects can be obtained from the `AppState`: 
```rust
let user_info = app_state.model(|m| m.get_user_info()).await?;
let spaces = app_state.state().await.spaces.list()?;
let projects = app_state.state().await.projects.list()?;
```

---

_We love helping new contributors!_
_If you have questions or need help as you work on your first Ockam contribution, please leave a comment on [this discussion](https://github.com/ockam-network/ockam/discussions/1081)._
_If you're looking for other issues to contribute to, checkout [this discussion](https://github.com/build-trust/ockam/discussions/3206) and labels -  https://github.com/build-trust/ockam/labels/good%20first%20issue or https://github.com/build-trust/ockam/labels/help%20wanted_

**Comment by GPadley** [comment]
I was interested in working on this, but from what I can see, `AppState` only has a singular `Spaces` and `Projects` value which wouldn't allow this kind of mapping that you are desiring so doesn't have a `list` method from what I can see.

**Comment by etorreborre** [comment]
This is fixed now
