### ISSUE TITLE
Investigate how to keep CLI and App synchronized when enrolling

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#5700]

**Comment by etorreborre** [comment]
@adrianbenavides could you please describe the issue a bit more? What is at risk of being desynchronized? Is it still the case now that we have some persistence for `UserInfo`?

**Comment by adrianbenavides** [comment]
>  Is it still the case now that we have some persistence for UserInfo?

It was about persisting the `UserInfo`, yes. I forgot to link the PR to close it automatically.
