### ISSUE TITLE
The correct default project must be retrieved in the desktop application

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5704]
When the desktop application starts up it retrieves the first project that the current user, alice, can access, based on the name `default`. This project might have been created by another user, bob who invited alice in order to share a service (with a role = Service).

Alice will then not be able to create enrollment tickets with that project since she is not an administrator of bob's project.

The fix consists in [filtering the list of retrieved projects](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_app/src/enroll/enroll_user.rs#L127) based on the `UserInfo` retrieved when the user authenticates:
```rust
// get the user email from the application state
let user_email = app_state
        .model(|m| m.get_user_info())
        .await
        .map(|u| u.email)
        .unwrap_or_default();

// only keep the projects where the user is an Admin
let project = match projects
        .iter()
        .filter(|p| {
            p.user_roles
                .iter()
                .any(|r| r.role == RoleInShare::Admin && r.email == user_email)
        })
        .find(|p| p.name == *PROJECT_NAME)
    {
....
```

Note: the code above can be refactored with  a `Project::is_admin(user_info: UserInfo) -> bool` function.

**Comment by shanesveller** [comment]
ℹ  The ordering returned by the backend for project listings is stable request-to-request as of last week - previously the SQL ordering was unspecified and would ultimately be decided by Postgres implementation details.
