### ISSUE TITLE
The user information must be displayed when enrolling with `ockam` then opening the desktop application

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#5705]
# Observed behavior

The user information is not displayed in the application: 
<img width="254" alt="image" src="https://github.com/build-trust/ockam/assets/10988/ef64ea5d-7cdf-48af-b2a1-eacf41b05951">

# Steps to reproduce

1. `ockam reset -y`
2. `ockam enroll --authorization-code-flow`
3. start the desktop application

# Expected behavior

The user information should be retrieved and displayed

# Work around 

Reset with the desktop application and enroll again.

**Comment by adrianbenavides** [comment]
The missing piece here is that `user_info` is not stored in the `CliState`. If we do that, we could solve this without any workaround. Although we should start doing the migration of the CliState to sqlite as soon as possible. 

Should we proceed and add the `user_info` to the `CliState` anyways?

**Comment by etorreborre** [comment]
> Although we should start doing the migration of the CliState to sqlite as soon as possible.

This will happen but we need to plan for it and design it a little bit
