### ISSUE TITLE
Investigate a failing test - ockam_identity v2::identities::tests::test_invalid_signature 

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5732]
Investigate why the following test run failed. It succeeded when run again.

https://github.com/build-trust/ockam/actions/runs/5956290923/job/16156743654#step:6:336

**Comment by mrinalwadhwa** [comment]
cc @SanjoDeundiak

**Comment by SanjoDeundiak** [comment]
I don't see another possible reason except the actual timeout because of the long execution. That will be fixed in the new version as I changed the number of iterations from 100 to 1
