### ISSUE TITLE
App - paper cuts in enroll, share, invite, connect experience have been removed - second pass.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5780]
- https://github.com/build-trust/ockam/issues/5710
- https://github.com/build-trust/ockam/issues/5685
- https://github.com/build-trust/ockam/issues/5850
- https://github.com/build-trust/ockam/issues/5903
- https://github.com/build-trust/ockam/issues/5919

**Comment by mrinalwadhwa** [comment]
@adrianbenavides let's close this Epic with whatever is landing in the release this week and more anything that is in progress to the next iteration https://github.com/build-trust/ockam/issues/5927

**Comment by adrianbenavides** [comment]
Got it!
