### ISSUE TITLE
Investigate failing semgrep github actions check

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5874]
https://github.com/build-trust/ockam/actions/runs/6054869372/job/16434834952

**Comment by itsajay1029** [comment]
I'd like to fix it. Will get back to you asap

**Comment by mrinalwadhwa** [comment]
That would be great @itsajay1029 thank you.

**Comment by itsajay1029** [comment]
On the latest attempts, it's working fine @mrinalwadhwa  https://github.com/build-trust/ockam/actions/runs/6054869372

**Comment by mrinalwadhwa** [comment]
Thank you for looking into it @itsajay1029 🙏
Closing this for now, until we experience the error again. Really appreciate your help.
