### ISSUE TITLE
Investigate Github API error in github actions workflows that use nix

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5895]
https://github.com/build-trust/ockam/actions/runs/6078148278/job/16488934201?pr=5888#step:5:17

```
disabling binary cache 'http://127.0.0.1:37515/' for 60 seconds
error: unable to download 'http://[12](https://github.com/build-trust/ockam/actions/runs/6078148278/job/16488934201?pr=5888#step:5:13)7.0.0.1:37515/qd3i5ak8y7wqi5cm9ra66i8nhfazywkg.narinfo': HTTP error 418

       response body:

       GitHub API error: API error (429 Too Many Requests): StructuredApiError { message: "Request was blocked due to exceeding usage of resource 'Count' in namespace ''." }
copying path '/nix/store/fc0ajx4015sh8i65iwb8qd3vap3wswpr-source' from 'https://cache.nixos.org'...
copying path '/nix/store/i4ginw25yf2q0shnzvzjjwa58srbjhw7-source' from 'https://cache.nixos.org'...
error:
       … while evaluating the attribute 'optionalValue.value'

         at /nix/store/fc0ajx4015sh8i65iwb8qd3vap3wswpr-source/lib/modules.nix:815:5:

          8[14](https://github.com/build-trust/ockam/actions/runs/6078148278/job/16488934201?pr=5888#step:5:15)|
          8[15](https://github.com/build-trust/ockam/actions/runs/6078148278/job/16488934201?pr=5888#step:5:16)|     optionalValue =
             |     ^
          8[16](https://github.com/build-trust/ockam/actions/runs/6078148278/job/16488934201?pr=5888#step:5:17)|       if isDefined then { value = mergedValue; }

       … while evaluating a branch condition

         at /nix/store/fc0ajx4015sh8i65iwb8qd3vap3wswpr-source/lib/modules.nix:816:7:

          815|     optionalValue =
          816|       if isDefined then { value = mergedValue; }
             |       ^
          8[17](https://github.com/build-trust/ockam/actions/runs/6078148278/job/16488934201?pr=5888#step:5:18)|       else {};

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: failed to extract archive (truncated gzip input)
```

---

We love helping new contributors! ❤️ 

- If you have questions or need help as you work on your Ockam contribution, please join us on the contributors [Discord channel](https://discord.gg/bewvnm6zqS).

- Take a look at our [contributor guide](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md) before making a PR, to get information on writing commit messages, branch names, code of conduct, CLA, our PR workflow.

- If you're looking for other issues to contribute to, checkout these labels [good first issue](https://github.com/build-trust/ockam/labels/good%20first%20issue) or [help wanted](https://github.com/build-trust/ockam/labels/help%20wanted).

**Comment by etorreborre** [comment]
This is unexpected since the `magic-nix-cache` github action [is supposed to handle this behaviour gracefully](https://github.com/marketplace/actions/magic-nix-cache#usage-notes).

**Comment by haraldh** [comment]
github was behaving odd yesterday and delivered incomplete tarballs. Experienced that and had to remove `~/.cache/nix` on my machine to fix it.

**Comment by metaclips** [comment]
Closing this issue now as it's Github related. Please re-open if event still occurs.
