### ISSUE TITLE
`ockam_core::Error` should report the correct location where the error occurred

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#5914]
### Observed behavior

The following snippet shows the standard way we return errors in most of the crates.

```rs
use ockam_core::errcode::{Kind, Origin};
use ockam_core::{Error, Result};

#[derive(Clone, Copy, Debug)]
pub enum SpecificDomainError {
    SomethingBadHappened,
}

impl ockam_core::compat::error::Error for SpecificDomainError {}
impl core::fmt::Display for SpecificDomainError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        core::fmt::Debug::fmt(self, f)
    }
}

impl From<SpecificDomainError> for Error {
    fn from(value: SpecificDomainError) -> Self {
        Self::new(Origin::Application, Kind::Internal, value)
    }
}

pub fn foo() -> Result<()> {
    return Err(SpecificDomainError::SomethingBadHappened.into());
}

#[test]
fn test_error() {
    let res = foo();
    res.unwrap();
}
```

Part of the output of such an executable would be the following:
```
called `Result::unwrap()` on an `Err` value: Ockam Error [origin: Application, kind: Internal] at [SOURCE_FILE_PATH]:18:9
```
Line 18 points to the implementation of the conversion from `SpecificDomainError` to `Error`. This is not useful since whenever `SpecificDomainError` occurs somewhere in the code, the location will always point to that conversion function. 

### Expected behavior

A much better approach would be to return the location where the error occurred. In this example, the desired location would be the line 23, inside the `foo()` function.

### Possible solutions

If `#[track_caller]` attribute is added to `from` function, the location then points to `library/core/src/convert/mod.rs:717:9`. That makes sense since this is where the generic implementation of `Into` lives for the structs implementing `From` trait.

There are two simple solutions to that problem I know:

#### A
  - Add `#[track_caller]` to all implementations of `From<ErrorType> for ockam_core::Error` in the codebase (there are not many of them, some of them already have that attribute)
  - Switch from using `.into()` when converting to `ockam_core::Error` everywhere in the codebase (there are many of them, and there is no way to avoid them appearing in the future)

#### B
  - Switch from implementing `From<ErrorType> for ockam_core::Error` to implementing `Into<ockam_core::Error> for ErrorType` (there are roughly a dozen of them)
  - Make sure each of them has `#[track_caller]` attribute

I would say that the option B is better unless I don't know something or there is another good solution to the problem.

**Comment by Qeyphen** [comment]
@SanjoDeundiak how do I re-produce this error in the code ?

**Comment by SanjoDeundiak** [comment]
@0xphen please try the snippet above

**Comment by Qeyphen** [comment]
@SanjoDeundiak I was able to re-produce this using the provided code snippet. From your suggested solution `B` which involves switching from implementing `From` to `Into` - the main difference between `From` and `Into` is the direction of conversion. Could you please help me understand why the need to switch from `From` to `Into` ?

Btw, I'd like to work on this.

**Comment by SanjoDeundiak** [comment]
@0xphen the difference is that in our codebase, we usually use `.into()` when returning an error. But if we implement `From` for the type, the `Into` implementation will be generated for us automatically. That implementation is a function that calls `from`, and it's present on the stack, so the location of the error (file and line where it occurred) will, unfortunately, point to that function instead of the actual calling location. Does that make sense? You can try it by playing around with the snippet.

**Comment by Qeyphen** [comment]
> ...That implementation is a function that calls from, and it's present on the stack, so the location of the error (file and line where it occurred) will, unfortunately, point to that function instead of the actual calling location. Does that make sense? 

@SanjoDeundiak  this makes sense. I played around with implementing the Into trait and having the `#[track_caller]` added to the `into` function. When an error occurs, the location points to the line the `.into()` call was made.

```javascript
pub fn foo() -> Result<()> {
    return Err(SpecificDomainError::SomethingBadHappened.into());
}
```
From the above code snippet, it points to this line `return Err(SpecificDomainError::SomethingBadHappened.into())`

**Comment by SanjoDeundiak** [comment]
@0xphen nice, that's the goal

**Comment by Qeyphen** [comment]
@SanjoDeundiak while working on this issue, I have noticed that switching from `From` to `Into` breaks some part of the code ([here](https://github.com/0xphen/ockam/blob/93947862d47b4dc1a901dccc9176fd0c380435a8/implementations/rust/ockam/ockam_api/src/kafka/secure_channel_map.rs#L364) for example). This is cause the `?` is used in some parts and the it relies on the `From` trait for error conversion; there is no built-in mechanism to make it use the Into trait for this purpose. So, I'm having to convert the `Result<T, SpecificDomainError >` to `Result<T, Error >` before chaining `?`.

**Comment by SanjoDeundiak** [comment]
@0xphen could you please push your work into your fork so I could take a quick look?

**Comment by Qeyphen** [comment]
@SanjoDeundiak  apologies for the late reply. Here are the 2 Into traits I implemented:

- https://github.com/0xphen/ockam/blob/69c535609e49ea5fa1ad1c04cc7b7f695993936f/implementations/rust/ockam/ockam_multiaddr/src/error.rs#L97

- https://github.com/0xphen/ockam/blob/69c535609e49ea5fa1ad1c04cc7b7f695993936f/implementations/rust/ockam/ockam_api/src/cli_state/mod.rs#L89

![image](https://github.com/build-trust/ockam/assets/127856072/803f25a4-1135-4b06-a5bc-d9ed67479106)

**Comment by SanjoDeundiak** [comment]
Hey @0xphen , sorry for the very late response 😅
Apparently, `From` is used with Rust's `?` operator (didn't know that) and there is nothing we can do to change. I think the only option we have here, is to start using `From` instead of `Into` ourselves. So, the state we want to be in, looks like that:

1. Every error type `T` implements `From<T> for ockam_core::Error`. Which should be the state we are in already. The only thing to check is that `#[track_caller]` attribute is present everywhere.
    ```rs
    impl From<SpecificDomainError> for Error {
        #[track_caller]
        fn from(value: SpecificDomainError) -> Self {
            Self::new(Origin::Application, Kind::Internal, value)
        }
    }
    ```

2. Start using `From` when we return an error from a function. This is what probably touches hundreds lines of our code. So, from this
    ```rs
    pub fn foo() -> Result<()> {
        return Err(SpecificDomainError::SomethingBadHappened.into());
    }
    ```

     We want to go to this:

    ```rs
    pub fn foo() -> Result<()> {
        return Err(From::from(SpecificDomainError::SomethingBadHappened));
    }
    ```


That would be a big change, tell me if you still want to work on it.

**Comment by SanjoDeundiak** [comment]
@0xphen I think I just found even simpler way to do the same:

```rs
pub fn foo() -> Result<()> {
    return Err(SpecificDomainError::SomethingBadHappened)?;
}
```

**Comment by SanjoDeundiak** [comment]
Potentially, you can write a regex to fix most of such places

**Comment by SanjoDeundiak** [comment]
Hey @0xphen , do you plan to get back to this issue?
