### ISSUE TITLE
Change the app's name to "Ockam" and not "Ockam App"

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#5918]
Currently the app is called "Ockam App". Should be "Ockam".

![image](https://github.com/build-trust/ockam/assets/2966499/2d89b43b-26bf-4a41-983c-0caf904bbdfd)

**Comment by 0x61nas** [comment]
am available in case you want help with this,

**Comment by nazmulidris** [comment]
@0x61nas Thank you for your offer to help on this one. @adrianbenavides is already working on this. Please take a look at the other open issues for [Ockam app](https://github.com/build-trust/ockam/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+App%22) to see if they pique your interest 🙏🏽 .

**Comment by adrianbenavides** [comment]
Fixed at https://github.com/build-trust/ockam/issues/5918
