### ISSUE TITLE
Rust - Investigate and fix breaking changes in upgrading from nix crate 0.26.2 to 0.27.1

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#5936]
The dependabot upgrade is failing because the new version has some breaking changes
https://github.com/build-trust/ockam/actions/runs/6121859822/job/16616475655?pr=5838#step:6:1951

**Comment by hseeberger** [comment]
I can take this one.

**Comment by hseeberger** [comment]
@mrinalwadhwa, fixed in #5974.

**Comment by hseeberger** [comment]
Fixed by #6006.

**Comment by mrinalwadhwa** [comment]
Thank you @hseeberger 🥳
