### ISSUE TITLE
Vault - Support NXP EdgeLock SE050

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#60]
https://www.nxp.com/products/security-and-authentication/authentication/edgelock-se050-plug-trust-secure-element-family-enhanced-iot-security-with-maximum-flexibility:SE050

### Datasheets
https://www.nxp.com/docs/en/data-sheet/SE050-DATASHEET.pdf

**Comment by mtm0183** [comment]
Support should include the following: 
-Random number generation
-Private key generation/Public key retrieval (Curve25519 & P256)
-ECDH
-SHA2-256
-HKDF
-AES GCM 128
