### ISSUE TITLE
Run cargo build --release as a build test in CI

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6045]
We currently do not run `cargo build in release mode` allowing breakages in our Rust code to slip in which could be caused by e.g. conditional compilation [debug_assertion](https://doc.rust-lang.org/reference/conditional-compilation.html#debug_assertions), we should update our [rust workflow](https://github.com/build-trust/ockam/blob/63d710b6a38b865b5a950b480e20a9d8a7d8b506/.github/workflows/rust.yml#L83) to also run `cargo build --release`

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by rghdrizzle** [comment]
Hey , so do we just have to run a command `cargo build --release` and default values for profile.release in the toml file ?

**Comment by metaclips** [comment]
@rghdrizzle we need to run build in release mode in this Github action job https://github.com/build-trust/ockam/blob/656f03e53415267ae9017f37dca8f44a04113b95/.github/workflows/rust.yml#L83
There is a makefile command to run cargo build release https://github.com/build-trust/ockam/blob/656f03e53415267ae9017f37dca8f44a04113b95/implementations/rust/Makefile#L7-L8
I believe adding a new matrix with `make_name` called `build_release` should just be sufficient https://github.com/build-trust/ockam/blob/656f03e53415267ae9017f37dca8f44a04113b95/.github/workflows/rust.yml#L88-L97

**Comment by rghdrizzle** [comment]
> @rghdrizzle we need to run build in release mode in this Github action job
> 
> https://github.com/build-trust/ockam/blob/656f03e53415267ae9017f37dca8f44a04113b95/.github/workflows/rust.yml#L83
> 
> There is a makefile command to run cargo build release
> 
> https://github.com/build-trust/ockam/blob/656f03e53415267ae9017f37dca8f44a04113b95/implementations/rust/Makefile#L7-L8
> 
> I believe adding a new matrix with `make_name` called `build_release` should just be sufficient
> 
> https://github.com/build-trust/ockam/blob/656f03e53415267ae9017f37dca8f44a04113b95/.github/workflows/rust.yml#L88-L97

alright then , I'll make this simple change right away

**Comment by metaclips** [comment]
Nice. I just assigned you @rghdrizzle
