### ISSUE TITLE
Investigate why command manual generation is failing.

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#6047]
This script to generate our manual is failing
https://github.com/build-trust/ockam-documentation/blob/command/manual/template/mdbook/build.sh

```
thread 'main' panicked at 'Failed to load the local Ockam configuration: Serde(Error("data did not match any variant of untagged enum IdentityConfigs", line: 0, column: 0))', implementations/rust/ockam/ockam_command/src/lib.rs:241:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mrinalwadhwa** [comment]
It works after a reset which is needed because of changes in release `v0.93.0`

**Comment by waqasraz** [comment]
I just did a fresh install on Ubuntu and got the same error.
`ockam enroll
thread 'main' panicked at 'Failed to load the local Ockam configuration: Serde(Error("data did not match any variant of untagged enum IdentityConfigs", line: 0, column: 0))', implementations/rust/ockam/ockam_command/src/lib.rs:241:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by mrinalwadhwa** [comment]
Thank you for telling us.

Did you try an `ockam reset`? Many objects we serialize changed in this release.

**Comment by waqasraz** [comment]
yes, even reset command throw same thing
```
sonic@waqas:~$ ockam enroll
thread 'main' panicked at 'Failed to load the local Ockam configuration: Serde(Error("data did not match any variant of untagged enum IdentityConfigs", line: 0, column: 0))', implementations/rust/ockam/ockam_command/src/lib.rs:241:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sonic@waqas:~$ ockam reset
thread 'main' panicked at 'Failed to load the local Ockam configuration: Serde(Error("data did not match any variant of untagged enum IdentityConfigs", line: 0, column: 0))', implementations/rust/ockam/ockam_command/src/lib.rs:241:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by mrinalwadhwa** [comment]
Try `rm -rf ~/.ockam`

**Comment by waqasraz** [comment]
That worked, this time I didn't set the env `source "$HOME/.ockam/env"`

**Comment by mrinalwadhwa** [comment]
That likely means the reset sub command should be even more forgiving of failures to parse existing config files. Could you file another issue please, so we can track a fix. cc: @adrianbenavides @nazmulidris

**Comment by nazmulidris** [comment]
FYI, here is a link to the PR for the fix: https://github.com/build-trust/ockam/pull/6071
