### ISSUE TITLE
Improve `ockam enroll —-help` text by changing the first paragraph of help text

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6053]
## Context
When a user types `ockam enroll —-help` in their terminal, they are presented with long help text. You can improve this text content by specifying that `enroll` command will do something with the Ockam Orchestrator, the SaaS service.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Current behavior
1. When you run `ockam enroll --help` in your terminal you will see the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/41022fd1-56c8-4a79-b52c-cd390fe767ea)

## Suggested fix
The first paragraph should say: “When you run this command for the first time, it creates a space for you in Ockam Orchestrator, the SaaS service. This is where you host your projects, as well as a default project for you within this space.” 

File that needs to be changed: [/src/enroll/static/long_about.txt](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/static/long_about.txt#L1).

Once the fix is applied, it should look like the following.

![Image](https://github.com/build-trust/ockam/assets/2966499/d103518b-22a9-49dd-bf5c-cb012ab68c4b)

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by Salonikansal2** [comment]
assign

**Comment by mrinalwadhwa** [comment]
@Salonikansal2 I missed assigning this earlier today, all yours.
