### ISSUE TITLE
Improve `ockam enroll —-help` text by adding doc comment for `identity` flag (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6054]
## Context
When a user types `ockam enroll —-help` in their terminal, they are presented with long help text. You can improve this text content by adding the help information for `--identity`, which is currently missing.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Current behavior
1. When you run `ockam enroll --help` in your terminal you will see the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/9a0bc17c-c90c-4256-a66e-3fc63b68c944)

## Suggested fix
A doc comment needs to be added to the `EnrollCommand::identity` field.
```rust
/// Existing identity identifier to enroll
```

File that needs to be modified: [/src/enroll/command.rs#L39](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/command.rs#L39).

Once the fix is applied, it should look like the following.

![Image](https://github.com/build-trust/ockam/assets/2966499/f32fce0d-fcfa-460d-a3b5-e9de2a4ce4de)

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by Lumexralph** [comment]
Hi @nazmulidris is this issue still open?

**Comment by nazmulidris** [comment]
@Lumexralph That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by nazmulidris** [comment]
@Lumexralph Hi 👋 Just checking to see if you are still interesting in working on this issue.

**Comment by Lumexralph** [comment]
A PR has been made already, I think it was merged, not sure
