### ISSUE TITLE
Improve `ockam enroll —-help` text by adding doc comment for `verbose` flag

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6055]
## Context
When a user types `ockam enroll —-help` in their terminal, they are presented with long help text. You can improve this text content by adding the help information for the `--verbose` flag, which is confusing right now.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Current behavior
1. When you run `ockam enroll --help` in your terminal you will see the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/ba64fa18-8acc-42f9-b01d-5cf606cfb8fa)

## Suggested fix
Add doc comment to `GlobalArgs::verbose` field:
```rust
/// Increase verbosity of trace messages by repeating the flag. Learn more at https://crates.io/crates/clap-verbosity-flag”
```

Make the change to `GlobalArgs` in this file: [/ockam_command/src/lib.rs#L159](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/lib.rs#L159).

Once the fix is applied, it should look like the following.

![Image](https://github.com/build-trust/ockam/assets/2966499/09f06896-0505-4c51-9bdc-9ed4388ea2b5)

---

We love helping new contributors! 

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by rjtch** [comment]
Hey @nazmulidris  i want to work on this task and this one https://github.com/build-trust/ockam/issues/6064

**Comment by nazmulidris** [comment]
@rjtch Awesome, this is all yours. Let us know if you have any questions as you explore.

**Comment by nazmulidris** [comment]
@rjtch In order to be able to assign you to the other issue #6064 , please make a comment on that issue and I will be able to do so 👍🏽
