### ISSUE TITLE
Improve `ockam enroll —-help` text by adding a “Troubleshoot:” section

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6056]
## Context
When a user types `ockam enroll —-help` in their terminal, they are presented with long help text. You can improve this text content by adding a “Troubleshoot” section. 

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).
## Current behavior
1. When you run `ockam enroll --help` in your terminal you will see the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/eaa0ba8b-dd77-40be-926d-009bc7546963)

## Suggested fix

Add a “Troubleshoot:” section at the end of the `after_long_help.txt` file:
```rust
Troubleshoot:

If you have problems with your enrollment then you can run `ockam reset -y && ockam enroll` to delete your local state and start again.

```

File that needs to be changed: [/src/enroll/static/after_long_help.txt](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/static/after_long_help.txt#L8). 

Once the fix is applied, it should look like the following.

![Image](https://github.com/build-trust/ockam/assets/2966499/a705c465-37dd-46c3-b5d8-c09e8e6a73c0)

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by Salonikansal2** [comment]
Please assign

**Comment by nazmulidris** [comment]
@Salonikansal2 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
