### ISSUE TITLE
Improve `ockam enroll —-help` text by updating the “Feedback:” section

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6057]
## Context
When a user types `ockam enroll —-help` in their terminal, they are presented with long help text. You can improve this text content by changing the “Feedback:” section (which is at the bottom of the help text). It currently currently provides a link to start a GitHub discussion, but it should provide a link to go to Discord instead.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Current behavior
1. When you run `ockam enroll --help` in your terminal you will see the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/95848032-9a5f-4721-b614-efebcaa6761c)

## Suggested fix

Update the value of the `FOOTER` constant and change the `Feedback:` section to the following:

```rust
Feedback:

If you have questions, as you explore, join us on the contributors
discord channel https://discord.gg/bewvnm6zqS
```

This is the file that needs to be modified: [/ockam_command/src/docs.rs](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/docs.rs#L16).

Once the fix is applied, it should look like the following.

![Image](https://github.com/build-trust/ockam/assets/2966499/26403e89-4eba-40fe-8325-b3aa19d6938e)

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by Salonikansal2** [comment]
Please assign

**Comment by nazmulidris** [comment]
@Salonikansal2 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
