### ISSUE TITLE
Improve `ockam enroll` by copying the one-time code to the clipboard

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6059]
## Current behavior
1. When a user runs `ockam enroll` they are presented with a prompt where they have to press <kbd>Enter</kbd> which opens a browser. 
1. Then they have to type in a code that they see in the terminal.
1. Then they have to paste this code into their browser. 

The following screenshot shows where the one-time code is displayed in the terminal.
![Image](https://github.com/build-trust/ockam/assets/2966499/24c675cc-002b-4584-bb6c-f3f6814cd3a6)
This video shows the entire enrollment process for your context: https://asciinema.org/a/608023?t=0:34

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).
## Suggested improvement
Instead of simply showing the one-time code in terminal, we should try and copy this code to the clipboard. We can make this process easier by copying the code into the clipboard to help the user paste it into their browser.

If we are able to copy it (in some cases, this might not be possible, for eg, if you are in an SSH session to a remote host) then we should display a prompt that says something like the following: 

```text
Your one-time code: XXXX-YYYY has been copied to the clipboard 🎉 
Press ENTER to open https://account.ockam.io/activate in your browser.
```

If we unable to copy to the clipboard, then leave things as they currently are.

The function you might want to modify is `get_token_interactively()` in this file [/src/enroll/oidc_service.rs](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/oidc_service.rs#L51).

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by halfbro** [comment]
I'd like to take on this issue, if nobody's done it yet.

**Comment by mrinalwadhwa** [comment]
@halfbro awesome! All yours, let us know if you have questions as you explore
