### ISSUE TITLE
Make `ockam enroll` project configuration step more robust

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6061]
## Current behavior
When a user runs `ockam enroll` and they don't have a project already created in their account on Ockam Orchestrator, then it might take ~ 2 minutes for this process to complete. During this time `ockam enroll` displays a [progress spinner](https://docs.rs/indicatif/latest/indicatif/struct.ProgressBar.html#method.new_spinner) and "Configuring project..." text in the terminal. Here's a [video at timestamp 1:04](https://asciinema.org/a/608023?t=1:04) that display this. 

This file creates a new spinner and manages display it: [rust/ockam/ockam_command/src/project/util.rs](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/util.rs#L157)

![Image](https://github.com/build-trust/ockam/assets/2966499/8ee4f7d0-b240-4ecd-a22e-def1fcb36c6c)

During this time, if the user presses <kbd>Ctrl+C</kbd> then it terminates the `ockam` process. This is not desirable since it leaves the local state in an inconsistent state. And they have to recover from this by running `ockam reset -y` and then run `ockam enroll` again.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

## Desired behavior
1. If the user presses <kbd>Ctrl+C</kbd>, detect this signal and prompt them that enrollment is currently in progress, but don't stop enrollment. In the prompt mention that if they would like to exit anyway they should press <kbd>Ctrl+C</kbd> again. Here's an example of the prompt copy: "ockam enroll is still in progress. If you would like to stop the enrollment process, press Ctrl+C again".

1. If they press <kbd>Ctrl+C</kbd> again, then we should exit, but before exiting the current process, remove the local state (the equivalent of running `ockam reset -y`).

## Implementation details
- In the <kbd>Ctrl+C</kbd> handler, we could check if the enrollment process is running and prevent the process from shutting down, showing the user a message like "Press Ctrl+C again if you really want to stop the enrollment process". 
- The next time we intercept the <kbd>Ctrl+C</kbd> signal, we actually try and stop the enrollment process, do cleanup, and exit. This prevents the need for the user to run `ockam reset -y` to clean up invalid local state from an interrupted enrollment.

## Open design discussion
Here are some notes on the codebase that will be useful to figure out how to implement this:
- This is the [CTRL+C handler](https://github.com/build-trust/ockam/blob/d74d6e8ad6e4da75d3dfbb199a5da47e85dc5cbb/implementations/rust/ockam/ockam_command/src/shutdown.rs#L26).
- In the `Implementation` details above, we mention that we need to introduce new functionality to `check if the enrollment process is running`. This is not currently implemented. One approach is to storing some information, when the enrollment process is underway, as a temp file in the `~/.ockam` directory. It is then possible to check whether this temp file exists, and if so, it means that enrollment is probably in progress.
- If you choose to work on this, you can collaborate w/ the Ockam team members to figure what the best approach is to implement this.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by adiSuper94** [comment]
@nazmulidris I'd like to work on this one, because I have personally faced this issue while trying out the Ockam Quick Start Guide.

#5972 is about a different facet of the same problem.

**Comment by nazmulidris** [comment]
@adiSuper94 Awesome! You have been assigned! 👍🏽

**Comment by adiSuper94** [comment]
> In the Implementation details above, we mention that we need to introduce new functionality to check if the enrollment process is running. This is not currently implemented. One approach is to storing some information, when the enrollment process is underway, as a temp file in the ~/.ockam directory. It is then possible to check whether this temp file exists, and if so, it means that enrollment is probably in progress.

This seems like a good approach to me, as we need to check if enroll is running across multiple processes.

> This is the [CTRL+C handler](https://github.com/build-trust/ockam/blob/d74d6e8ad6e4da75d3dfbb199a5da47e85dc5cbb/implementations/rust/ockam/ockam_command/src/shutdown.rs#L26).

I am assuming this just to be used as a reference. And the checks & action should not be added here. 

FYI:  this function sets the handler  waits for `CTRL-C` and returns.

**Comment by adiSuper94** [comment]
@nazmulidris, I have made changes to get the desired behavior. 
I am sure it needs some changes, but we can use this as a starting point to discuss any details
