### ISSUE TITLE
Rust - Investigate and fix breaking changes in upgrading dialoguer crate from 0.10.4 to 0.11.0

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#6062]
Investigate why this dependabot PR is failing
https://github.com/build-trust/ockam/pull/6039

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by denisyao101** [comment]
Hello @mrinalwadhwa,
I want to work on this issue.

**Comment by mrinalwadhwa** [comment]
@denisyao101 awesome, all yours. Let us know if you have questions as you explore

**Comment by denisyao101** [comment]
Hello @mrinalwadhwa,
I found the issue and resolve it. The code compile on my local computer.
Should I create a new PR or simply add a commit to this branch / PR ?
thanks
