### ISSUE TITLE
`ockam status` should provide more user friendly information when a user is *not* enrolled

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6064]
# Current behavior

When a user is not enrolled (they have not run `ockam enroll` yet), and they run `ockam status` they currently get an error message of the empty local state. This information is not very useful. Here's a screenshot of what this looks like.

![Image](https://github.com/build-trust/ockam/assets/2966499/11ac9350-f8f2-46da-bd7b-929e97148b53)

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

# Desired behavior

If a user is not enrolled, and they run `ockam status`, they should see a helpful message such as “No identities are found. Consider running `ockam enroll` to enroll an identity.” instead of just an error message.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by rjtch** [comment]
Hey @nazmulidris i want to work on this task

**Comment by nazmulidris** [comment]
@rjtch Excellent, I just assigned it to you! 👍🏽
