### ISSUE TITLE
Improve `ockam reset` by allowing it to unenroll from Orchestrator if they are already enrolled

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6065]
# Current behavior
After a user runs `ockam enroll` to successfully enroll to Orchestrator, they are able to run `ockam reset -y` and delete all "local" state information. The local state information is all the data that is stored in the `~/.ockam` folder once the `ockam enroll` command completes successfully.

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

# Desired behavior
There should be an option that can be passed to `ockam reset` that allows the data in the Ockam cloud to be deleted (as well as the local state information). Something like `ockam reset --cloud-resources -y`. Running this command would also reset the local data for the user. If the user does not pass the `-y` option then they need to be prompted just like `ockam reset` does today.

---

We love helping new contributors! ❤️ 

- If you have questions or need help as you work on your Ockam contribution, please join us on the contributors [Discord channel](https://discord.gg/bewvnm6zqS).

- Take a look at our [contributor guide](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md) before making a PR, to get information on writing commit messages, branch names, code of conduct, CLA, our PR workflow.

- If you're looking for other issues to contribute to, checkout these labels [good first issue](https://github.com/build-trust/ockam/labels/good%20first%20issue) or [help wanted](https://github.com/build-trust/ockam/labels/help%20wanted).

**Comment by adiSuper94** [comment]
@nazmulidris I'd like to take a crack at this.

**Comment by nazmulidris** [comment]
Hi @adiSuper94 👋🏽 Thank you for your interest in this issue. Unfortunately I did some research and just found out that we don't have an un-enrollment API to allow this to happen at the moment. I am going to close this issue; please feel free to take at other ones we have open, and we are adding more every day 👍🏽

**Comment by adiSuper94** [comment]
@nazmulidris will do 😁
