### ISSUE TITLE
Improve `ockam reset` output if the user has not enrolled yet

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6066]
# Current behavior
Currently if a user has not enrolled (ie, they have not run `ockam enroll` yet) and they run `ockam reset` or `ockam reset -y` they get a prompt confirming that their local state information has been deleted. 

The following screenshot shows this behavior when running these commands when a user has not enrolled.

![Image](https://github.com/build-trust/ockam/assets/2966499/fb8a7d0a-d5d4-4e24-af6d-777e010c3350)

> To install Ockam command from a prebuilt binary or from source, please take a look at this [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

# Desired behavior

When a user has not enrolled, and they run `ockam reset` or `ockam reset -y`, instead of displaying information indicating that the command successfully ran, it should instead:
- Display information letting the user know that there is no local state to delete. Local state can be created even whether enrollment has not happened.  
- And also ask them if they want to enroll by running `ockam enroll` in the prompt, if they have not enrolled (using `ockam enroll`).

> There could be state even if the user has not been enrolled. Enrolling is not a requirement to use the CLI, and creating an identity or a node will add some state. If they are not enrolled then displaying a prompt to enroll might be useful.

---

We love helping new contributors! ❤️ 

- If you have questions or need help as you work on your Ockam contribution, please join us on the contributors [Discord channel](https://discord.gg/bewvnm6zqS).

- Take a look at our [contributor guide](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md) before making a PR, to get information on writing commit messages, branch names, code of conduct, CLA, our PR workflow.

- If you're looking for other issues to contribute to, checkout these labels [good first issue](https://github.com/build-trust/ockam/labels/good%20first%20issue) or [help wanted](https://github.com/build-trust/ockam/labels/help%20wanted).

**Comment by kriogenia** [comment]
Hi, I would love to take on this one

**Comment by mrinalwadhwa** [comment]
@kriogenia awesome, all yours. Let us know if you have any questions as you explore

**Comment by nazmulidris** [comment]
Hi @kriogenia 👋🏽 . Thank you for spending time on this issue. Unfortunately, after some investigation, I realized that there are some problems with how this issue is scoped, and some implementation details that are not matching up with it. 

I am going to close this PR and the issue. Sorry that you have spent your time working on this issue. Please take a look at all the other issues we currently have open [here](https://github.com/build-trust/ockam/contribute). Thank you 👍🏽 .
