### ISSUE TITLE
Can't run `reset` with latest version (0.94.0)

### ISSUE THREAD

**Issue by glenngillen** [build-trust/ockam#6069]
### Observed behavior

I've just upgraded to the latest release, and I'm unable to run any commands. I assume it's something to do with schema differences between versions. The release notes call out that you'll need to `ockam reset` for the new version, but it's not possible to run even that command after upgrading: 

```shell
❯ RUST_BACKTRACE=1 ockam reset
thread 'main' panicked at 'Failed to load the local Ockam configuration: Serde(Error("data did not match any variant of untagged enum IdentityConfigs", line: 0, column: 0))', implementations/rust/ockam/ockam_command/src/lib.rs:241:44
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: ockam_command::CommandGlobalOpts::new
   4: ockam_command::OckamCommand::run
   5: ockam_command::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running `rm -rf ~/.ockam/` first resolves the issue.

### Steps to reproduce

1. Have an existing configuration from a previous version
2. Upgrade to v0.94.0
3. Run `ockam reset`

### Expected behavior

`reset` to always work to allow someone to get back to a working state

### Ockam Version

0.94.0

**Comment by mrinalwadhwa** [comment]
@waqasraz observed the same behavior here https://github.com/build-trust/ockam/issues/6047#issuecomment-1732391233

**Comment by mrinalwadhwa** [comment]
cc @adrianbenavides

**Comment by nazmulidris** [comment]
@glenngillen Closing this issue since this PR will fix this: https://github.com/build-trust/ockam/pull/6071 👍🏽
