### ISSUE TITLE
Investigate - why tokio-tungstenite update from from 0.20.0 to 0.20.1 is failing

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#6090]
Investigate why tokio-tungstenite update from from 0.20.0 to 0.20.1 dependabot PR failing

https://github.com/build-trust/ockam/pull/6087
https://github.com/build-trust/ockam/pull/6092

https://github.com/build-trust/ockam/actions/runs/6303560068/job/17113060248?pr=6087

**Comment by adiSuper94** [comment]
@mrinalwadhwa  https://github.com/snapview/tungstenite-rs/compare/v0.20.0...v0.20.1

New Tungstenite error added, which signifies a possible DoS  attack,
https://github.com/advisories/GHSA-9mcr-873m-xcxp

the match on tungsten error [here](https://github.com/build-trust/ockam/blob/04cf2be086f2d796a050792323eca183aef6532f/implementations/rust/ockam/ockam_transport_websocket/src/error.rs#L45) in not exhaustive anymore.

**Comment by mrinalwadhwa** [comment]
@adiSuper94 thank you for looking into it!

**Comment by mrinalwadhwa** [comment]
@adiSuper94 I noticed you're considering picking a pull request to start as a first contribution. A fix to the above would be a great one to start with if that seems interesting to you.

**Comment by adiSuper94** [comment]
@mrinalwadhwa, Sure I can start with this one.

**Comment by SanjoDeundiak** [comment]
@adiSuper94 please
