### ISSUE TITLE
Use the `names` crate to provide a function to make it easy to generate human readable random strings

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6096]
Use the names crate (https://lib.rs/crates/names) to:
- generate a utility function to make it easy to generate readable random ids / strings / names that will used everywhere, eg: `ockam identity create`

![Image](https://github.com/build-trust/ockam/assets/2966499/30581a3d-a5e4-49de-99b9-ea23146b6025)

# Suggested usages

- `ockam node create`

# Action item: 
- [ ] Once this is done, create hacktoberfest issues to apply this template to all the commands that currently auto generate ids / strings

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by adrianbenavides** [comment]
I'd suggest to modify this method so we can easily centralize the calls:

https://github.com/build-trust/ockam/blob/2556c31a8cba3dcec3419dfeccb625af1902fa9c/implementations/rust/ockam/ockam_api/src/cli_state/mod.rs#L376
