### ISSUE TITLE
Investigate and fix - rust error panicked at 'attempt to subtract with overflow' 

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#6115]
https://github.com/build-trust/ockam/actions/runs/6329983244/job/17191393169?pr=6110#step:6:711

![Screenshot 2023-09-27 at 12 42 25 PM](https://github.com/build-trust/ockam/assets/159583/703727ac-d371-4c3e-bbe8-eef3a5de9714)

**Comment by SanjoDeundiak** [comment]
That happens in very recent code, I was quite surprised seeing this and decided to investigate and fix myself.
