### ISSUE TITLE
Improve `ockam enroll --output json` by making it fail right away

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6119]
# Current behavior

When you run `ockam enroll --output json` whether you have enrolled (using `ockam enroll`) or not, it looks like the following screenshot.

![Image](https://github.com/build-trust/ockam/assets/2966499/0e1e4568-9fc3-4aa9-9be3-5050975b1c5a)

- It does not show a one-time code
- But it spawns a local browser
- Since no code is shown there is no way to type in the correct code in the browser

# Desired behavior

When `ockam enroll --output json` is passed it, it should exit immediately and report that this is an invalid flag that can't be passed in.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/enroll/command.rs#L38).

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by adrianbenavides** [comment]
Instead of failing, couldn't we just ignore it and overwrite the output format to plain, so that the user doesn't have to be bothered?

**Comment by nazmulidris** [comment]
@adrianbenavides I think it is more transparent to let the user know that the output --json should not work in this scenario. Silently changing the value of an argument might be misleading them, and might educate them that this behavior might be acceptable in other commands.

**Comment by adrianbenavides** [comment]
Good point, let's do that then, thanks!

**Comment by kriogenia** [comment]
Hi, I can take care of this one

**Comment by mrinalwadhwa** [comment]
@kriogenia awesome! all yours.
