### ISSUE TITLE
Add `--output json` support to `ockam identity list`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6122]
# Current behavior

Currently running `ockam identity list --output json` produces an error like the following:

![Image](https://github.com/build-trust/ockam/assets/2966499/404541f6-0a82-4713-8cf9-a914fc69091e)

# Desired behavior

However it should provide a list of identity information in JSON format.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/list.rs#L27) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by kriogenia** [comment]
I have a little of free time to tackle another issue and this is similar to the issue I have in review right now so if it's ok I would like to take it.

**Comment by nazmulidris** [comment]
@kriogenia That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
