### ISSUE TITLE
Improve `CloudOpts` argument `--identity` with better help text

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6123]
Improve `CloudOpts` argument `--identity` with better help text

# Current behavior

The command `ockam space show --identity <IDENTITY_NAME>` runs the command with the given identity name. And this is what you see when you run `ockam space show --help`.

![Image](https://github.com/build-trust/ockam/assets/2966499/9cd527df-69f5-4745-99ed-44d72da950fa)

There are many other commands which end up using the same `CloudOpts` argument struct. And here are some of them:
- `ockam space list --help`
- `ockam space delete --help`
- `ockam project ticket --help`

# Desired behavior

The `ockam space list --help` command should provide some more information on the `--identity` flag. So should all the other commands in the list above.

To do this:
- Add a comment to the field describing what it is: `/// Run the command as the given identity name`.
- To make this change take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/api.rs#L392). Add a doc comment w/ the text above to the `CloudOpts::identity` field.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by 0scvr** [comment]
I can work on this issue. Please assign it me, thanks.

**Comment by ironspec07** [comment]
I have already started working on the issue. Can you please assign it to me?

**Comment by nazmulidris** [comment]
@0scvr I just assigned this issue to you.

@ironspec07 I just assigned the issue to @0scvr. How far along are you in working on this issue? We have plenty of other issues for you to look at if you haven't spent too much time on this 👍🏽 . Do you have a PR raised against it?

**Comment by ironspec07** [comment]
ok no problem. I'll find another issue, Thanks

**Comment by nazmulidris** [comment]
@ironspec07 Awesome! Thank you 👍🏽
