### ISSUE TITLE
Improve `ockam space create` by add missing argument `--identity` (`clap` command) 

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6125]
# Current behavior

Currently `ockam space [list, delete, show]` commands all take an `--identity` flag. However the `ockam space create` does not, and it should. This argument allows this command to be run as the given identity name.

# Desired behavior

Add the [`CloudOpts` struct](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/util/api.rs#L392) to the clap arguments list that the `create` command takes.

You can find the file to change [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/space/create.rs#L1). 

Check to see that the help text is updated when you run `ockam space create --help`.

Note that the current tests (bats and Rust) are probably not going to be affected by this change since they use a default identity. Might need to update bats tests and other tests as well.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by tamalCodes** [comment]
Hi @nazmulidris , can i work on this issue ?

**Comment by nazmulidris** [comment]
@tamalCodes 👋🏽 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by nazmulidris** [comment]
This issue is open for anyone else to work on 👍🏽

**Comment by axd99** [comment]
Hi @nazmulidris ,

Could you assign this one to me?

**Comment by mrinalwadhwa** [comment]
@axd99 of course, all yours

**Comment by axd99** [comment]
@mrinalwadhwa . Thank you.

**Comment by axd99** [comment]
Created pull request #6437.
