### ISSUE TITLE
Improve `ockam project ticket` by removing deprecation description from `--project-path`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6126]
# Current behavior

When you run `ockam project ticket --help`, you will get the following output as shown below.

![Image](https://github.com/build-trust/ockam/assets/2966499/6d81e315-02e1-4720-8640-cc2f30b023b5)

The `--project-path` argument is listed as "DEPRECATED".

# Desired behavior

This argument is required and should not be marked as "DEPRECATED". It is needed in some cases and not in others. In use cases that involve working with Ockam Orchestrator, this argument is not needed. However, in cases where you [start your own authority node](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/tests/bats/authority.bats#L99) then it is needed.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/ticket.rs#L21) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by 0scvr** [comment]
I could work on this.

**Comment by nazmulidris** [comment]
@0scvr That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
