### ISSUE TITLE
Add `--output json` support to `ockam node list`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6128]
# Current behavior

Currently running `ockam node list --output json` produces an error like the following:

![Image](https://github.com/build-trust/ockam/assets/2966499/bf734548-2fde-4e9c-aa17-f64b29cda61d)

It also shows a spinner before it displays the error message.

# Desired behavior

~~It should not display a spinner while it is working. (updated: sep 29 2023)~~ 

It should provide a list of node information in JSON format.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/list.rs#L28) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by solidiquis** [comment]
Hello! How does this output look? Do you have any other preferences for how it should be formatted? Does it need color?

<img width="688" alt="Screen Shot 2023-09-28 at 6 16 40 PM" src="https://github.com/build-trust/ockam/assets/45523555/07442dbf-09b3-49d2-b7bc-7ad09d741e0b">

**Comment by mrinalwadhwa** [comment]
@solidiquis the format looks great, we don't want to color this output since we want it to be readable by other programs. For example `jq`

**Comment by solidiquis** [comment]
Thanks @mrinalwadhwa! I'll open a PR shortly.

**Comment by solidiquis** [comment]
@mrinalwadhwa Looks like this issue we closed prematurely due to my mention of it in a different PR. Would you mind reopening it until my PR gets merged?

Additionally, regarding the desire to remove the spinner, I noticed that there was a separate issue for it and it's already being tackled: https://github.com/build-trust/ockam/issues/6147

Hence I decided not to remove the spinner in this PR. Let me know if that's okay.

**Comment by nazmulidris** [comment]
@solidiquis The requirement to remove the spinner has been dropped (in this issue https://github.com/build-trust/ockam/issues/6147). So this PR is scoped well! 👍🏽
