### ISSUE TITLE
Add docs for `--full` to improve `ockam identity show --help`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6129]
# Current behavior 

Currently when you run `ockam identity show` you can pass a flag `--full`. This flag is currently does not have any help docs as you can see below.

![Image](https://github.com/build-trust/ockam/assets/2966499/fb02b911-d628-4d2b-9737-d2e11fd49127)

# Desired behavior

Add the doc comment `/// Show the full identity history, and not just the identifier or the name`. Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/show.rs#L27) to make changes.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by doriancodes** [comment]
hi ! I'd like to work on this :)

**Comment by nazmulidris** [comment]
@doriancodes Thank you for your interest. This issue is closed, but there are many similar ones that you can work on in this list: https://github.com/build-trust/ockam/issues?q=is%3Aopen+label%3A%22Component%3A+Command%22+label%3A%22hacktoberfest%22

Please let us know which open issue you are interested in and we will assign it to you 👍🏽
