### ISSUE TITLE
Improve `ockam identity show` with `--output json` and `--full` flag

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6130]
# Current behavior

`ockam identity show --output json --full` currently does not output JSON that has keys and values, it is just a array of numbers.

![Image](https://github.com/build-trust/ockam/assets/2966499/727b5442-8770-41f7-b96e-026a01522afd)

# Desired behavior

It should output JSON data that is useful for scripting or CI/CD environments. Please take a look at the output of `ockam identity show --full --encoding plain` to see what useful information should be emitted.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/show.rs#L51) to make changes.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by kriogenia** [comment]
Hi, I think I can take on this one.

**Comment by nazmulidris** [comment]
@kriogenia That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
