### ISSUE TITLE
Improve `ockam identity delete` with `--output json` (`clap` command) to fail right away if no confirmation is provide as an argument

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6133]
# Current behavior

If you run `ockam identity delete <IDENTITY_NAME> --output json` without `-y` / `--yes` flag then it prompts the user and asks for confirmation whether they should delete it or not. 

This behavior is normally desirable (in interactive mode /w a user) except that `--output json` implies that this is meant to be run in a scripted environment where user interaction is unavailable.

Here's an example of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/dbc10224-4e4c-4aa2-acd3-fe8ea6b02a07)

# Desired behavior

Instead, if you run the above command without `-y` / `--yes` flag then the command should produce an error and exit with a non zero exit code.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/delete.rs#L19) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by adrianbenavides** [comment]
> This behavior is normally desirable (in interactive mode /w a user) except that --output json implies that this is meant to be run in a scripted environment where user interaction is unavailable.

This part is not entirely correct. User interaction is detected by [other means](https://github.com/build-trust/ockam/blob/091da5d0f39090b50935a8533dd06ce975d9e75e/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255), and I'm not 100% sold on the assumption that using `--output json` implies that we are on a non-tty env. The user could just include the [`--no-input` argument](https://clig.dev/#interactivity) to not being prompted.
