### ISSUE TITLE
Improve `ockam vault create` by moving the `-p` / `--path` argument

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6134]
# Current behavior

If a user runs `ockam vault create --p FOO` then the path `FOO` is ignored in the vault creation process.

# Desired behavior

This argument is deprecated and should be removed, so it doesn't show up in the help or the arguments list.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/vault/create.rs#L27) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by brehen** [comment]
@nazmulidris 
I'd love to take a shot at this if you'd assign this to me? 😄

**Comment by nazmulidris** [comment]
@brehen That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
