### ISSUE TITLE
Improve `ockam vault list` to mark the default vault

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6137]
# Current behavior

If you have multiple vaults and run `ockam vault list`, it currently does not show which one is the default vault. The screenshot below shows this.

![Image](https://github.com/build-trust/ockam/assets/2966499/d04e78e8-0706-47bb-89ef-109bc59eaeb6)

# Desired behavior

The default vault (which you can get by running `ockam vault show`) should be marked with a suffix `(default)` so that it is easy to see which one is the default.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by postmeback** [comment]
Is this available?
 If yes, please assign it to me.

**Comment by nazmulidris** [comment]
@postmeback That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by postmeback** [comment]
Facing installation problem issues in windows 11 machine. Hence, unassigning myself.

Thanks  :)

**Comment by nazmulidris** [comment]
@postmeback We don't currently support Windows, only macOS & Linux. 

However, if you have WSL 2 on Windows 11 it should work in Ubuntu. 

You just have to install the rust toolchain in the WSL container w/ Ubuntu, then fork our repo, and then build `ockam_command`. 

Here is more information on how to build it: https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_command

**Comment by melissa-kun-li** [comment]
Can I be assigned to this?

**Comment by mrinalwadhwa** [comment]
@melissa-kun-li of course, all yours.

Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
