### ISSUE TITLE
Improve `ockam vault delete` with `--output json` to fail right away if no confirmation is provide as an arg (`-y` or `--yes`)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6140]
# Current behavior

If you run `ockam vault delete <VAULT_NAME> --output json` without `-y` / `--yes` flag then it prompts the user and asks for confirmation whether they should delete it or not. This behavior is desirable except that `--output json` implies that this is meant to be run in a scripted environment where user interaction is probably unavailable.

![Image](https://github.com/build-trust/ockam/assets/2966499/545a2280-427e-4da6-aa7e-23e1e6f2f0f2)

# Desired behavior

If you run `ockam vault delete <VAULT_NAME> --output json` without `-y` / `--yes` flag then the command should produce an error and exit with a non zero exit code.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by petersooley** [comment]
Hi @nazmulidris I'd like to give this one a shot. :hand:

**Comment by mrinalwadhwa** [comment]
@petersooley That's awesome, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by nazmulidris** [comment]
Hi @petersooley 👋 Thank you for spending time on this issue. Unfortunately, after some investigation, we realized that there are some problems with how this issue is scoped, and some implementation details that are not matching up with it. I am going to close this PR and the issue and give you `hacktoberfest-accepted` credit. Sorry that you have spent your time working on this issue. Please feel free to take at other ones we have open, and we are adding more every day 👍.
