### ISSUE TITLE
Improve `ockam node default` by displaying the default node name when no argument is passed in

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6141]
# Current behavior

If you run `ockam node default <NODE_NAME>` then you can currently only *set* the default node. If you run `ockam node default` without any other arguments it results in an error like this:

![Image](https://github.com/build-trust/ockam/assets/2966499/923b0aa8-8c0c-4374-973f-b4d1ae45fa35)

# Desired behavior

When no arguments are passed, it should display the default node name.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/default.rs) to get started.

Please make sure that the bats tests and other Rust tests work after this change.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by MaheshMoholkar** [comment]
Hey nazmulidris! I'm still learning rust but i would like to work on this issue.

**Comment by nazmulidris** [comment]
@MaheshMoholkar That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
