### ISSUE TITLE
Improve `ockam node show --output json` by including more information

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6142]
# Current behavior

If you run `ockam node show --output json` it currently does not show much information. Here's a screenshot.

![Image](https://github.com/build-trust/ockam/assets/2966499/88b48ef6-2530-4ee3-839b-c108c872b417)

# Desired behavior

It should display information that is available when running the command with plain text output `ockam node show`.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/show.rs#L78) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by kriogenia** [comment]
Hello again, can I take on this one?

**Comment by mrinalwadhwa** [comment]
@kriogenia of course, all yours.
Please let us know if your have any questions as you explore.

**Comment by kriogenia** [comment]
@mrinalwadhwa It looks like there's a TODO in that file about reducing the number of parameters of the printing function. I was thinking on tackling that task too. I was thinking about creating a struct to implement Serialize and build the JSON to return that way and that struct could be the input parameter of the function. Is it ok? 

Another question I have is: part of the info that we are displaying are structs like `TransportStatus` that belong to the `ockam_api` package. Deriving Serialize on those fields would ease the implementation but maybe you prefer me to restrain to `ockam_command` and manually add functions to serialize those types. What approach would you prefer?

**Comment by adrianbenavides** [comment]
@kriogenia I just saw your comment here, sorry about that. Now that you have the PR almost ready, you have those questions already solved right?
