### ISSUE TITLE
Improve `ockam relay list` when there are no relays (user is not enrolled)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6144]
# Current behavior

When there is no local state (e.g. after you run `ockam reset -y`) and you run `ockam relay list` the following error is shown.

![Image](https://github.com/build-trust/ockam/assets/2966499/a0ba8607-78d7-48e4-9073-7fd1e9f89ca5)

# Desired behavior

It should display a message saying that local state is empty and there are no relays. 

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by k1nho** [comment]
@nazmulidris  Thanks for the update on #6147. Yeah, after exploring a bit more, I agree with the comments made in the issue. I'll pick this one.

**Comment by nazmulidris** [comment]
@k1nho That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
