### ISSUE TITLE
Improve `ockam space list` when there are no spaces in Ockam Orchestrator

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6145]
# Current behavior

When there is no local state (e.g. after you run `ockam reset -y`) and you run `ockam space list` the following error is shown.

![Image](https://github.com/build-trust/ockam/assets/2966499/67077257-f38e-4166-9730-c743e535592b)

# Desired behavior

It should display a message saying that local state is empty and there are no spaces in Ockam Orchestrator. The output can also provide text instructing the user to use `ockam enroll` to create a default project.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by k1nho** [comment]
@nazmulidris I'll take this one.

**Comment by nazmulidris** [comment]
@k1nho That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by adrianbenavides** [comment]
As noted by @k1nho , there's still a problem where the user will get an ugly error message when running this command if the default identity is not enrolled. The linked PR solved the problem when no spaces were available.

I've created a PR adding an utility function to fix that problem: https://github.com/build-trust/ockam/pull/6315

Once that is landed, we should start using that function in every command that needs to contact the controller.

**Comment by nazmulidris** [comment]
@adrianbenavides should this issue be re-opened?

**Comment by adrianbenavides** [comment]
No, I'll create new ones now that we have this merged: 

- https://github.com/build-trust/ockam/pull/6315
