### ISSUE TITLE
Improve `ockam project list --output json` by removing the spinner

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6147]
# Current behavior

When you run `ockam project list --output json` it outputs JSON correctly but it also draws a spinner before it generates this output. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/441bb6a2-5157-4e3c-a3b7-e78124684d47)

# Desired behavior
This is not desirable, since the `--output json` flag signals the intent that this command is to be used in a scripting environment or CI/CD environment where user interaction is not possible.

The spinner shouldn't appear when running with this flag.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/list.rs#L61) to make changes.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by friendlymatthew** [comment]
Hi @nazmulidris -- I would like to work on this issue :)

**Comment by k1nho** [comment]
Hi 👋 @nazmulidris, I would like to try tackling this issue.

**Comment by nazmulidris** [comment]
@k1nho Hi 👋🏽. Awesome, this is all yours. Let us know if you have any questions as you explore.

**Comment by etorreborre** [comment]
Hi @solidiquis. In which scenario is this really causing a problem?

The spinner is only displayed in the interactive terminal but is not part of `stdout` (it goes to `stderr`). This means that you can still use the command in a scripting scenario:
```
> ockam project list --output json > projects.json
> cat projects.json

[
  {
    "id": "cc67bc80-aa3b-4e28-8eee-c1c0b3a46c69",
    "name": "default",
    "space_name": "39023a31",
....
]
```

**Comment by solidiquis** [comment]
Hi @etorreborre — I didn't actually do anything related to the spinner. The other issue redundantly mentioned the removal of the spinner when doing `--output json`, so i said that I would leave it alone since this issue already exists.

But I agree with you that for scripting scenarios where stderr is not a tty the spinner shouldn't really cause any problems.

**Comment by etorreborre** [comment]
Something I forgot to mention is that we can also use the `--quiet` flag to suppress the spinner:
```
ockam project list --quiet --output json > test.json
```
So maybe it's time for @nazmulidris to revisit this issue :-)?

**Comment by nazmulidris** [comment]
Hi @k1nho 👋🏽 Thank you for spending time on this issue. Unfortunately, after some investigation, I realized that there are some problems with how this issue is scoped, and some implementation details that are not matching up with it.

I am going to close this issue. Sorry that you have spent your time working on this issue. Please feel free to take at other ones we have open, and we are adding more every day 👍🏽.
