### ISSUE TITLE
Improve `ockam vault attach-key` into `ockam identity` as an argument

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6148]
# Current behavior

The command `ockam vault attach-key` should be removed. Currently it allows you to create an identity given a specific key. 

# Desired behavior

The `ockam identity create` should have an option that accepts a specific key, in order to create an identity. This argument can be named `--with-key-id` and take a specific key as a value.

- Please take a look at this [file](https://github.com/build-trust/ockam/blob/5f386a5fada10d853a77163f7920e70a972c22a7/implementations/rust/ockam/ockam_command/src/vault/attach_key.rs#L44-L61) to see what this command currently does.

- You can modify this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/create.rs#L45) for the `identity create` command.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by adiSuper94** [comment]
@nazmulidris  I'd like to take this issue.

**Comment by nazmulidris** [comment]
@adiSuper94 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
