### ISSUE TITLE
Improve `ockam reset` by display information about what exact has been deleted

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6149]
# Current behavior

When a user runs `ockam reset -y` or just `ockam reset` exactly what types of information are deleted isn't shown currently. Here are some screenshots.

![Image](https://github.com/build-trust/ockam/assets/2966499/e6504bbc-7261-468e-8b65-1b5cfa58b1b9)

![Image](https://github.com/build-trust/ockam/assets/2966499/a24e75c3-6864-4cfa-9dc4-93cc7f320e99)

# Expected behavior

Instead it would be more useful to a user if the types of information being deleted would be listed with a checkbox beside them indicating that their deletion / removal is successful. 

Here's an example that  illustrates the issue:

![Image](https://github.com/build-trust/ockam/assets/2966499/65ff10a0-aaed-4a7e-bd1f-f4719c6d4b0b)

In the above screenshot it shows that there where at least 1 vault, 2 identities and 1 node on the system. But `ockam reset` doesn't print information about what it actually deletes. The goal of the ticket is to change that so `ockam reset` prints to stdout all items that it has deleted.

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/reset.rs#L22) to get started.

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by Abhicodes-crypto** [comment]
Hi @nazmulidris , I'd like to work on this as well.

**Comment by nazmulidris** [comment]
@Abhicodes-crypto That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by nazmulidris** [comment]
@Abhicodes-crypto Continuing our chat from Discord, I am closing this issue. 

Thank you for taking a look at this issue 🙏🏽 . Sorry we had to close it. There are many that are still open if you want to take a look 👍🏽
https://github.com/build-trust/ockam/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest

More info (captured from Discord convo): 
> @adrianbenavides : This one is a little bit tricky and I'm not sure it has a clear solution right now. The code that handles the state deletion doesn't know anything about stdout/stderr and from the command side we don't want to know the details about how the state is deleted (we just call CliState::delete()). Since the Terminal struct (the object we use to handle stdout/stderr) lives in ockam_command and CliState lives in ockam_api, we can't pass the Terminal object to CliState::delete(), so we are basically in a dead end here.
