### ISSUE TITLE
`ockam status --all` outputs controller version as `unset`

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6151]
### Observed behavior

`ockam status --all` outputs controller version as `unset`

### Steps to reproduce

```bash
$ ockam status --all
Controller version: unset
Project version: 0.4.0
Identity[0]
...
```

### Expected behavior

Controller version should be accurately shown

### Ockam Version

ockam v0.94.0

**Comment by rjtch** [comment]
Hey I want to work on this task!

**Comment by mrinalwadhwa** [comment]
@rjtch all yours.

**Comment by rjtch** [comment]
@mrinalwadhwa could you give me more infos about this ticket? I have seen that the ockam version can be found in the changelog file but not sure why the version does not come from the get_orchestrator_version()

**Comment by adrianbenavides** [comment]
Fixed on the elixir side was already merged.
