### ISSUE TITLE
Scope typos workflow permission to `contents: read`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6176]
# Current behavior
Currently [We have a workflow that checks for typos in our repository](https://github.com/build-trust/ockam/blob/1273a6f413c7c237aecd963db83677a9dc14dd19/.github/workflows/typos.yml#L1) 

# Desired behavior
Instead we should scope the Github permission to `contents: read` https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by tharun634** [comment]
Hey, I'd like to take this issue up!

**Comment by mrinalwadhwa** [comment]
@tharun634 That's awesome, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by mrinalwadhwa** [comment]
Ah, I noticed that you are already digging into #6177. Let's land that one before you take on another. Looking forward to your first pull request!

**Comment by mrinalwadhwa** [comment]
@tharun634 while we review/merge the other PRs, if you want please go ahead and take this one as well. Please keep the PRs for each issue separate.
