### ISSUE TITLE
Remove the `contents: write` permission from `ockam-package.yml workflow`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6178]
[Remove the `contents: write` permission from the ockam-package workflow](https://github.com/build-trust/ockam/blob/1273a6f413c7c237aecd963db83677a9dc14dd19/.github/workflows/ockam-package.yml#L39) as we only write to packages in the `build-and-publish-artifact` job

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by tharun634** [comment]
Hey, I'd like to take this issue up!

**Comment by metaclips** [comment]
Hello @tharun634 I have assigned you to https://github.com/build-trust/ockam/issues/6177, we can assign you to this issue when the former is done and closed

**Comment by mrinalwadhwa** [comment]
@tharun634 assigning this to you now. Thank you.
