### ISSUE TITLE
Move the `packages:write` permission in the ockam-healthcheck workflow

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6179]
Move the `packages:write` permission in the ockam-healthcheck from workflow-scope to the `build_ockam_healthcheck` job-scope

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by tharun634** [comment]
Hey, I'd like to take this issue up!

**Comment by metaclips** [comment]
Hello @tharun634 I have assigned you to https://github.com/build-trust/ockam/issues/6177, we can assign you to this issue when the former is done and closed

**Comment by mrinalwadhwa** [comment]
@tharun634 while we review/merge the other PRs, if you want please go ahead and take this one as well. Please keep the PRs for each issue separate
