### ISSUE TITLE
elixir release is not portable

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#618]
the changes in https://github.com/ockam-network/ockam/pull/617/commits/b8fb047132346ffdbc4dc79eed930e827e7834a3 hack around the problem by copying the whole build instead of the release into the container.

**Comment by etorreborre** [comment]
@hairyhum is this issue still up to date?

**Comment by hairyhum** [comment]
It's relevant in that it's not portable, but for a different reason and in different issue
