### ISSUE TITLE
Run osv-scanner in our github workflow

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6181]
Add support to run osv-scanner as a github workflow on every pull-request and push. Instructions on running the action tool can be found [here](https://github.com/google/osv-scanner/blob/main/docs/github-action.md#instructions)

---

<i>We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).</i>

**Comment by mrinalwadhwa** [comment]
@metaclips interesting, what extra information will this give us in addition to the other  scanners we have turned on? I know the scorecard action has some relation to osv-scanner.

**Comment by metaclips** [comment]
Using osv-scanner tool in Github action should alert us if a PR brings in a vulnerable dependency, on PR/push across different programming languages.

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign it to me.

**Comment by mrinalwadhwa** [comment]
@milinddethe15 That's awesome, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by milinddethe15** [comment]
Hi @metaclips @mrinalwadhwa, can you please add HACKTOBERFEST-ACCEPTED tag?

**Comment by metaclips** [comment]
@milinddethe15 I added the label on your PR https://github.com/build-trust/ockam/pull/6210
