### ISSUE TITLE
Make the commit lint workflow a reusable workflow across all build-trust repositories

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6238]
We have a workflow that checks commits when a pull request is created, it entails
- Checking if users sign their commits
- Checking if users commit messages follows a naming convention
- Checking if users PR have a linear commit history

The workflow file can be found [here](https://github.com/build-trust/ockam/blob/develop/.github/workflows/all.yml) in the ockam repository and [here](https://github.com/build-trust/ockam-website/blob/develop/.github/workflows/commits.yml) in the ockam-website repository, we should create a parent workflow which we can reuse across the two repository, so that we do not repeat code

**Comment by printf-ana** [comment]
Hey, I'm participating of Hacktoberfest and I would like to take this issue, can you assign to me, please?

**Comment by milinddethe15** [comment]
Hi @metaclips, will parent workflow be stored in a new repository?

**Comment by metaclips** [comment]
> Hi @metaclips, will parent workflow be stored in a new repository?
> 
> 

It'll be stored in this repository

**Comment by milinddethe15** [comment]
Ok. I am working on this. Assign it to me.

**Comment by metaclips** [comment]
Nice. Done, please ask if anything

**Comment by milinddethe15** [comment]
Hi @metaclips, how should I set common jobs from both of repo in parent workflow file?

**Comment by metaclips** [comment]
> Hi @metaclips, how should I set common jobs from both of repo in parent workflow file?

We can create a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) in the ockam repository that we can reuse
