### ISSUE TITLE
`identity` argument value name on `ockam authority create` should be `IDENTITY_NAME`. The doc string should also be updated

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6245]
## Current behavior

The `identity` argument value name on `ockam authority create` is `IDENTITY`.
## Desired behavior

The `identity` argument value name on `ockam authority create` should be `IDENTITY_NAME` and the doc string should be updated to `Name of the Identity that the authority will use`.
## Implementation details

This is the path to the argument that must be changed:

https://github.com/build-trust/ockam/blob/d5d3cafbec9fad4f5354c8549fee6da2b00b440d/implementations/rust/ockam/ockam_command/src/authority/create.rs#L99-L101

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by 0scvr** [comment]
I'm on it.

**Comment by 0scvr** [comment]
I think this issue can be closed now.
