### ISSUE TITLE
`identity` argument value name on `ockam node create` should be `IDENTITY_NAME`. The doc string should also be updated

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6246]
## Current behavior

The `identity` argument value name on `ockam node create` is `IDENTITY`.
## Desired behavior

The `identity` argument value name on `ockam node create` should be `IDENTITY_NAME` and a doc string should be added 
with the contents `Name of the Identity that the node will use`.

## Implementation details

This is the argument that must be changed:

https://github.com/build-trust/ockam/blob/59f52a66cc84ad682d9f4ea5715057f97f8eb7a3/implementations/rust/ockam/ockam_command/src/node/create.rs#L100-L101

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by AnshKumar200** [comment]
I'm interested in working on this issue.

**Comment by adrianbenavides** [comment]
Sure, go ahead 👍

**Comment by AnshKumar200** [comment]
Thank You!
