### ISSUE TITLE
`identity` argument value name on `ockam secure-channel-listener create` should be `IDENTITY_NAME`. The doc string should also be updated

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6247]
## Current behavior

The `identity` argument value name on `ockam secure-channel-listener create` is `IDENTITY`.

## Desired behavior

The `identity` argument value name on `ockam secure-channel-listener create` should be `IDENTITY_NAME` and a doc string should be added with the contents `Name of the Identity that the secure-channel listener will use`.

## Implementation details

This is the argument that must be changed:

https://github.com/build-trust/ockam/blob/9c49e470a574d91854aa24628584eda4554aaad0/implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs#L40-L41

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by AnshKumar200** [comment]
I would like to give it a try! Can I get it assigned?

**Comment by adrianbenavides** [comment]
All yours! Let us know if you have any question 👍

**Comment by AnshKumar200** [comment]
Sure! Thank You
