### ISSUE TITLE
`issuer` argument value name on `ockam credential store` should be `HEX_ENCODED_FULL_IDENTITY`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6250]
## Current behavior

The `issuer` argument value name on `ockam credential store` is not set.

## Desired behavior

The `issuer` argument value name on `ockam credential store` should be `HEX_ENCODED_FULL_IDENTITY` and a doc string should be added 
with the contents `The full hex-encoded Identity that was used to issue the credential`.

## Implementation details

This is the argument that must be changed:

https://github.com/build-trust/ockam/blob/c0db0ce89a69991a46b3872a5464c1ff9da15432/implementations/rust/ockam/ockam_command/src/credential/store.rs#L20-L21

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by brehen** [comment]
Please assign this to me :)

**Comment by brehen** [comment]
There's a mismatch in the title of this issue and the "Desired behavior" section. Should the value_name be set to `IDENTITY_NAME` or `HEX_ENCODED_FULL_IDENTITY`?

**Comment by nazmulidris** [comment]
@brehen That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by nazmulidris** [comment]
> There's a mismatch in the title of this issue and the "Desired behavior" section. Should the value_name be set to `IDENTITY_NAME` or `HEX_ENCODED_FULL_IDENTITY`?

@brehen We are looking into this right now and will get back to you as soon as we have an answer.

**Comment by adrianbenavides** [comment]
Sorry about that, it's fixed now!
