### ISSUE TITLE
Improve `ockam relay create` (with no args) when user is not enrolled

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6295]
# Current behavior

- When the user has not enrolled into Ockam Orchestrator (by running `ockam enroll`) 
- and / or they have just reset their local state (by running `ockam reset -y`)
- and then they try to run `ockam relay create`, they are presented with this error.

![Image](https://github.com/build-trust/ockam/assets/2966499/08f4f5c5-7bf1-4fa8-b410-874b21956aa0)

# Desired behavior

Instead of generating this error, it would be better to check whether the user is currently enrolled or not. If they are not enrolled, then instead of displaying the error message (above) another message can be provided:

```
Without being enrolled, it is not possible to create a Relay in the default project in Orchestrator. To enroll please run 'ockam enroll'
```

# Implementation details

To get started, please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/create.rs).

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by 0scvr** [comment]
I'd like to try working on this issue.

**Comment by nazmulidris** [comment]
@0scvr That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by nazmulidris** [comment]
*Oct 6 2023*
Hi @0scvr  👋🏽 We realized that there are some problems with how this issue is scoped, and some implementation details that are not matching up with it. I just unassigned you from this and am closing it.

Fortunately, we caught it right before you started working on it. Please feel free to take at other ones we have open, and we are adding more every day 👍🏽.

https://github.com/build-trust/ockam/contribute

---
*Update on Oct 9*
We re-opened this issue and this PR lands the fix https://github.com/build-trust/ockam/pull/6327

**Comment by nazmulidris** [comment]
I am re-opening this issue. And this PR fixes it https://github.com/build-trust/ockam/pull/6327
cc: @adrianbenavides @0scvr @paulozulato

**Comment by paulozulato** [comment]
sorry, guys, I didn't see this discussion when I started working on this issue. 🫣

**Comment by nazmulidris** [comment]
@paulozulato You are all set to work on this issue. And your PR https://github.com/build-trust/ockam/pull/6327 addresses it. Sorry about the confusion, I just assigned you to it.

**Comment by nazmulidris** [comment]
@adrianbenavides Capturing more context (for the future) on helping to understand the limitations of the `is_enrolled` and how users can access a project without being enrolled (more info in this PR: https://github.com/build-trust/ockam/pull/6442
