### ISSUE TITLE
Improve `ockam relay list --help` by mentioning it works w/ Orchestrator enrollment by default

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6297]
# Current behavior

When a user runs `ockam relay list --help` the example in the help text can be improved. This is show in this screenshot.

![Image](https://github.com/build-trust/ockam/assets/2966499/9ea7c33b-e46b-4f16-8f5f-99bfd4157381)

# Desired behaviors

1) The help text for the command says `List Relays`, leave that as is (this is the short help text). Add a long help text that says: `List Relays on your default node. If you pass '--to <NODE>' then it lists the Relays at the given node`

2) Change the help for the `--to` argument to be: `Get the list of Relays at the given node`

3) The help text example says to run ~~`$ ockam relay list --at n2`~~
Instead, it should say `$ ockam relay list --to n2`

# Implementation details

> Here's an example of using the `long_about` attribute in another file:
> 
> https://github.com/build-trust/ockam/blob/59f52a66cc84ad682d9f4ea5715057f97f8eb7a3/implementations/rust/ockam/ockam_command/src/node/create.rs#L50-L52

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/list.rs#L26) to get started.

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by 0scvr** [comment]
I'll work on this if still up for grabs 😊

**Comment by nazmulidris** [comment]
@0scvr That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

Also, please associate your PR and issue using this technique: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
