### ISSUE TITLE
Improve `ockam relay list` when there are no relays (user *is* enrolled)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6298]
# Current behavior

When there is no local state (`ockam reset -y` or `rm -rf ~/.ockam`) and then the user enrolls using `ockam enroll`, running `ockam relay list` produces an error message. 

> This is similar to its behavior when the user is NOT enrolled ([#6144](https://github.com/build-trust/ockam/issues/6144))

![Image](https://github.com/build-trust/ockam/assets/2966499/44c1f2d7-f9f2-4493-bf74-53c10b617f6c)

> Note that this command works when the user has enrolled into Ockam Orchestrator and has created a relay there by running `ockam relay create`.
> ![Image](https://github.com/build-trust/ockam/assets/2966499/6d6e5165-2bb2-4631-8654-3b5aaf187cae)

# Desired behavior

When the user runs `ockam relay list` and this is a fresh enrollment and there are no relays available, then it should just report that, instead of producing an error.

# Implementation details

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/list.rs#L24) to get started.

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Celeo** [comment]
Pushing PR soon.
