### ISSUE TITLE
Improve `ockam relay show <RELAY_ROUTE> --output json` by generating JSON output

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6299]
# Current behavior

After a user has enrolled and created a relay using the following commands
```
ockam enroll
ockam tcp-outlet create --to 6000
ockam relay create
```

And they run `ockam relay show <RELAY_ROUTE> --output json` where `<RELAY_ROUTE>` is something like `forward_to_default`, then plain text output is generated and not JSON. You can see this in the screenshot below.

![Image](https://github.com/build-trust/ockam/assets/2966499/2e488911-ce06-4bf8-bd1e-b5fe0e4b3fa1)

# Desired behavior

Instead of plain text output, JSON output should be generated for this command and argument combination.

# Implementation details

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/show.rs#L43) to get started.

---
<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. In the PR description, include the issue that's being solved 
1. Run `cargo fmt`. You can configure the editor to run it automatically every time a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by 0x61nas** [comment]
If there is no one working on this issue, please assign it to me. I would love to work on it.

**Comment by mrinalwadhwa** [comment]
@0x61nas awesome! Thank you, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
