### ISSUE TITLE
Improve `ockam tcp-inlet --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6337]
# Current behavior

When a user runs `ockam tcp-inlet --help` they are presented with the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/a238c615-8c66-42b1-8932-3932b9fa4841)

# Desired behavior

It should instead display the following long help text.

```
A TCP inlet is a way of defining where a node should be listening for connections, and where it should forward that traffic to. It is one end (tcp-outlet being the other) of a portal, which receives TCP data, chunks and wraps them into Ockam Routing messages and sends them along the supplied route.
```

# Implementation details

Please take a look at this [file](
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/static/long_about.txt#L1) to get started.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Zapix** [comment]
Hello. I want to try to help you with this issue.

**Comment by nazmulidris** [comment]
@Zapix That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
