### ISSUE TITLE
Improve `ockam tcp-inlet show --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6338]
# Current behavior
When a user runs `ockam tcp-inlet show --help` they see the following screenshot.

![Image](https://github.com/build-trust/ockam/assets/2966499/fcc57fe6-bb97-4f9d-b5df-da65cef7d2c5)

# Desired behavior
Instead the help text should display `Show information about a TCP Inlet`

# Implementation details

To make the change, please change the Rust doc comment for the `ShowCommand` struct, in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/show.rs#L25).

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Zapix** [comment]
@nazmulidris can I take this issue?

**Comment by mrinalwadhwa** [comment]
@Zapix of course, all yours

**Comment by Zapix** [comment]
@mrinalwadhwa Looks like it was fixed  https://github.com/build-trust/ockam/commit/f9d72257
