### ISSUE TITLE
Improve `ockam tcp-outlet --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6339]
# Current behavior

When the user runs `ockam tcp-outlet --help` they are presented with the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/49821324-d726-4e81-934a-9e16d2d61ad5)

# Desired behavior

We want the help text to be changed to say the following:

```
A TCP Outlet makes a TCP service available on a worker address (allows data to be transmitted to a listener on a TCP address). It is one end of a portal (tcp-inlet being the other), which receives Ockam Routing messages, unwraps them to extract TCP data and sends that data along to the target service.
```

# Implementation details

Please take a look at this [file](
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/static/long_about.txt#L1) to make changes.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by AnshKumar200** [comment]
Can I start working on this issue ?

**Comment by mrinalwadhwa** [comment]
@AnshKumar200 of course, all yours

**Comment by AnshKumar200** [comment]
Thank You!
