### ISSUE TITLE
Improve `ockam tcp-outlet list --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6342]
# Current behavior

When a user runs `ockam tcp-outlet list --help` they are shown the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/87e66227-37dc-46eb-b4a2-df1cb6381339)

# Desired behavior

Instead, they should be presented with the following help text for the command `List TCP Outlets on the default node`. 

The `--at` argument help text also should be added: `Perform the command on the given NODE_NAME`

After you've made your changes the output of this command should look like this screenshot below.

![Image](https://github.com/build-trust/ockam/assets/2966499/36271cc0-6ed9-4238-8aaa-dff5f4990203)

# Implementation details

1) Replace the Rust doc comment for the `ListCommand` struct with the following: `List TCP Outlets on the default node` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/list.rs#L21)

2) Add the following attribute to the `NodeOpts` struct: `long_help = "Perform the command on the given NODE_NAME"`. You can find this struct in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/mod.rs#L78)

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by 0scvr** [comment]
I'd like to grab this issue 😊
