### ISSUE TITLE
Improve `ockam tcp-outlet show` by implementing `--output json`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6344]
# Current behavior

When a user runs `ockam tcp-outlet show <MY_ALIAS> --output json` and `<MY_ALIAS>` exists, then the output is dumped in plain text and not JSON. Here is a screenshot to demonstrate this.

![Image](https://github.com/build-trust/ockam/assets/2966499/1788386f-3826-409e-a010-5fc96a585c3f)

# Expected behavior

Instead of plain text output, this command should produce JSON output.

# Implementation details

Take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/show.rs#L24) to get started.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by guha-rahul** [comment]
Can i work on this? I suppose we need to get assigned by the maintainer before submitting a pr.

**Comment by adrianbenavides** [comment]
Sure, all yours!

**Comment by guha-rahul** [comment]
![image](https://github.com/build-trust/ockam/assets/52607971/54603116-6591-47fe-a62c-f822f5b38609)
When i run  `ockam relay create` why does it give me this error?
