### ISSUE TITLE
Improve `ockam tcp-outlet delete --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6345]
# Current behavior

When a user runs `ockam tcp-outlet delete --help` then the following output is displayed.

![Image](https://github.com/build-trust/ockam/assets/2966499/67c03875-8ec8-4dd8-a06c-85008bd1256e)

# Desired behavior

Change the help text for the `<ALIAS>` argument to say: `Delete the outlet with this alias name`

# Implementation details

Change the Rust doc comment for the `DeleteCommand::alias` field in this [file](
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L18)

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by makeittotop** [comment]
@nazmulidris can I work on it please?

**Comment by nazmulidris** [comment]
@makeittotop That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by makeittotop** [comment]
Although the issue was assigned to me, I see that someone else has also created similar PR @nazmulidris . However, my PR is here - #6371

**Comment by nazmulidris** [comment]
@makeittotop We will make sure that you will get credit (hacktoberfest accepted label on your PR) regardless of which of the 2 PRs end up being merged 👍🏽 Thanks for letting us know 🙏🏽
