### ISSUE TITLE
Improve `ockam tcp-outlet delete <ALIAS>` when `<ALIAS>` does not exist

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6347]
# Current behavior

When a user runs `ockam tcp-outlet delete <ALIAS>` and `<ALIAS>` does not exist, then they get a prompt, asking them to confirm whether this command should proceed or not. Then they are shown an error stating that `404 NotFound`.

![Image](https://github.com/build-trust/ockam/assets/2966499/f39cd6eb-c5cf-4264-911e-bc7f463aa4df)

# Desired behavior

Instead of asking the user for a confirmation prompt, it would be better to first check to see whether `<ALIAS>` even exists. 

1) If it does *not*, then the user should be notified that this alias name doesn't exist and can't be deleted. This can be an error.

2) If it does exist, then the user should be prompted, to confirm whether this destructive operation should proceed. If that operation fails for some reason then an error should be displayed with information on what went wrong (which is the current behavior).

# Implementation details

Take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/outlet/delete.rs#L39) to get started.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by PanGan21** [comment]
Hi! I am interested to contribute to this issue! One quick question only. 
Figuring out if the alias exists or not could be done using `Request::delete(format!("/node/outlet/{alias}")`?

**Comment by 0x61nas** [comment]
Hi, If there's no one working on this issue, please assign it to me. I would love to work on it.

**Comment by nazmulidris** [comment]
@0x61nas That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
