### ISSUE TITLE
Replace `ORCHESTRATOR_AWAIT_TIMEOUT_MS` type to `Duration`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6376]
## Current behavior

The `ORCHESTRATOR_AWAIT_TIMEOUT_MS` constant is of type `u64`.

## Desired behavior

The `ORCHESTRATOR_AWAIT_TIMEOUT_MS` constant should be of type `Duration` and should default to 180 seconds. The doc string should read as `Timeout for Orchestrator's long-running operations`. 

Also, rename the constant to `ORCHESTRATOR_LONG_OPERATIONS_TIMEOUT`.

## Implementation details

This is the consant that must be changed to `Duration::from_secs(60 * 10)`:

https://github.com/build-trust/ockam/blob/f8ad8209d8b46658848d0681d0f47ba110ed7103/implementations/rust/ockam/ockam_api/src/cloud/secure_clients.rs#L29

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by tibormichel1** [comment]
Hello can i also get assigned this issue ? (working on #6374)

**Comment by nazmulidris** [comment]
@tibormichel1 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by postmeback** [comment]
I see this issue has been idle for a long time, so I implemented the changes. Requesting for evaluation
