### ISSUE TITLE
Use the `random_name` function on the `project_name` argument of the `project create` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6379]
## Current behavior

The `project_name` argument of the `ockam project create` command is calling `hex::encode()` to generate the random name in the `default_value_t` attribute.

## Desired behavior

The `project_name` argument of the `ockam project create` command should be calling the [`random_name()`](https://github.com/build-trust/ockam/blob/75fa2e3ece6c8ece4a89056e5360d3b1ca19ddeb/implementations/rust/ockam/ockam_api/src/cli_state/mod.rs#L421) function.

## Implementation details

Don't forget to import the `random_name()` function with `use ockam_api::cli_state::random_name;`.

This is the argument that must be changed, where `default_value_t = random_name()`:

https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_command/src/project/create.rs#L30-L31

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
2. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
3. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
4. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Dhanush0369** [comment]
Please assign it to me. I can do it.

**Comment by Dhanush0369** [comment]
I tried to run cargo clippy , but getting error as failed to select version for `tauri-utils`. In the repository we have `tauri-macros v2.0.0-alpha.8` but its is saying `tauri-macros = "v2.0.0-alpha.7"` satisfies. What should i do?

**Comment by adrianbenavides** [comment]
Can you try installing these dependencies? https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux

```
sudo apt update
sudo apt install libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    file \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev
```

I'm trying to confirm with another contributor if this is the root cause of this problem.

Once you have that, please try:

```
cargo build -p ockam_command
cargo clippy -p ockam_command
```
