### ISSUE TITLE
Use the `random_name` function on the `space_name` argument of the `space create` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6380]
## Current behavior

The `space_name` argument of the `ockam space create` command is calling `hex::encode()` to generate the random name in the `default_value_t` attribute.

## Desired behavior

The `space_name` argument of the `ockam space create` command should be calling the [`random_name()`](https://github.com/build-trust/ockam/blob/75fa2e3ece6c8ece4a89056e5360d3b1ca19ddeb/implementations/rust/ockam/ockam_api/src/cli_state/mod.rs#L421) function.

## Implementation details

Don't forget to import the `random_name()` function with `use ockam_api::cli_state::random_name;`.

This is the argument that must be changed, where `default_value_t = random_name()`:

https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_command/src/space/create.rs#L25-L26

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
2. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
3. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
4. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by dhruvmehtaaa** [comment]
I want to work on this issue, can you please assign it to me

**Comment by Asymtode712** [comment]
I want to work on this issue. Please assign me

**Comment by nazmulidris** [comment]
@Asymtode712 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
