### ISSUE TITLE
Use the `random_name` function in the `Default` implementation of `NodeManagerDefaults`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6382]
## Current behavior

The `node_name` field of the `Default` implementation of the `NodeManagerDefaults` struct is calling `hex::encode()` to generate a random name.

## Desired behavior

The `node_name` field of the `Default` implementation of the `NodeManagerDefaults` struct should be calling the [`random_name()`](https://github.com/build-trust/ockam/blob/75fa2e3ece6c8ece4a89056e5360d3b1ca19ddeb/implementations/rust/ockam/ockam_api/src/cli_state/mod.rs#L421) function.

## Implementation details

This is the field that must be changed:

https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_api/src/nodes/service/in_memory_node.rs#L178

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
2. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
3. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
4. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Virtual4087** [comment]
can you assign me?
