### ISSUE TITLE
In `CreateSecureChannelListenerRequest`, the `vault` parameter should be renamed to `vault_name`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6391]
## Current behavior

The `vault` field of the `CreateSecureChannelListenerRequest` struct is not named properly.

## Desired behavior

The `vault` field of the `CreateSecureChannelListenerRequest` struct should be `vault_name` and all its uses should be fixed accordingly to use the new field name.

## Implementation details

This is the argument that must be changed:

https://github.com/build-trust/ockam/blob/3bccb9d66b5ff8fe08d0eba351aeec2aced52281/implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs#L79

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Asymtode712** [comment]
I want to contribute. Please assign me

**Comment by Technmad** [comment]
Please assign to me
