### ISSUE TITLE
In dialog boxes where the user is required to type things, disable autocorrect

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6431]
# Observed behavior

When using this version of Ockam.app https://github.com/build-trust/ockam/releases/tag/ockam_v0.97.0 and the following steps are taken:

1) User A opens the Ockam app and enrolls
2) User A creates a service, they are presented w/ a dialog box that has text fields in it that try to autocorrect the service name, host:port etc.

# Desired behavior

It would be better to disable this type of auto correct, and auto capitalization behavior, since the service name, hostname and port don't need it.

**Comment by adincebic** [comment]
I can tackle this one too.
