### ISSUE TITLE
Make `ockam node delete` (no args) interactive by asking the user to choose from a list of nodes to delete (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6450]
# Current behavior

When a user runs `ockam node delete` without any arguments, currently they are prompted to delete the default node. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/3fdc1a39-c3bb-4e45-a2d9-3e06ac6cbe53)

# Desired behavior

Instead of deleting the default node, change the behavior of this command so that it becomes interactive with the user. Note that this can only be allowed to happen if:
- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.
1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of node names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that a destructive operation is about to take place with the node names they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then delete each selected node, and display a success / failure message for each node that got deleted. 
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- If it hasn't been added already, please add the [tuify](https://crates.io/crates/r3bl_tuify) crate the `Cargo.toml` file [here](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/Cargo.toml#L55) by adding this line `r3bl_tuify = "0.1.16"` to the `[dependencies]` section.
- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/delete.rs#L43) you can look at to see where the `ockam node delete` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by mickm3n** [comment]
I'd like to work on this. Please assign this issue to me.

**Comment by mrinalwadhwa** [comment]
@mickm3n That's awesome, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by mickm3n** [comment]
@mrinalwadhwa 
I have a question about the desired behavior. In `delete all nodes,` it would also delete multiple nodes. Should we align the output of `delete all nodes` and `delete selected nodes`? With the same rule:
> If an operation succeeds then use the ✅ emoji as a prefix for the message.
> And if it fails, then use the ⚠️ emoji as a prefix for the message.

**Comment by mickm3n** [comment]
@mrinalwadhwa 
Another question: what's the desired behavior when the terminal is not interactive? Deleting the default node or displaying an error message to the user?

**Comment by nazmulidris** [comment]
> I have a question about the desired behavior. In `delete all nodes,` it would also delete multiple nodes. Should we align the output of `delete all nodes` and `delete selected nodes`? With the same rule:
> 
> > If an operation succeeds then use the ✅ emoji as a prefix for the message.
> > And if it fails, then use the ⚠️ emoji as a prefix for the message.

@mickm3n The scope of `ockam node delete --all` is not part of this issue, so it is best not to change that in this PR. We can create a new issue for that after this PR is landed.



> Another question: what's the desired behavior when the terminal is not interactive? Deleting the default node or displaying an error message to the user?


Retain the current behavior when the terminal is not interactive.
