### ISSUE TITLE
Make `ockam space delete` (no args) interactive by asking the user to choose from a list of spaces to delete (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6460]
# Current behavior

When a user runs `ockam space delete` without any arguments, currently they are shown help text output. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/ec622653-1809-4476-888e-0e20dd263d55)

# Desired behavior

Instead of showing the help text, change this command so that it becomes interactive with the user. Note that this can only be allowed to happen if:
- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.
1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of space names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that a destructive operation is about to take place with the space names they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then delete each selected space, and display a success / failure message for each space that got deleted. 
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/space/delete.rs#L47) you can look at to see where the `ockam space delete` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Tashuuuu** [comment]
Can I work on this?

**Comment by nazmulidris** [comment]
@Tashuuuu That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by Lumexralph** [comment]
@nazmulidris does this issue still need working on?

**Comment by nazmulidris** [comment]
@Lumexralph That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by Lumexralph** [comment]
@nazmulidris Do you have any ockam command issue that needs to be made interactive you can assign to me?

I would like to work on more before taking issues with different domain contexts.

**Comment by nazmulidris** [comment]
@Lumexralph The following issues seem to be abandoned.
1) https://github.com/build-trust/ockam/issues/6477
2) https://github.com/build-trust/ockam/issues/6461
3) https://github.com/build-trust/ockam/issues/6478

If you comment on each of them, then I can assign them to you 👍🏽
