### ISSUE TITLE
Make `ockam relay delete` (no args) interactive by asking the user to choose from a list of relay names to delete (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6464]
# Current behavior

When a user runs `ockam relay delete` without any arguments, currently they are presented with an error & help text. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/2dfe158e-1cb3-4304-ab1a-98dbac147312)

# Desired behavior

Instead of displaying help text, change the behavior of this command so that it becomes interactive with the user. Note that this can only be allowed to happen if:
- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of relay names, at the default node. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that a destructive operation is about to take place with the relay names they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then delete each selected relay, and display a success / failure message for each relay that got deleted. 
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/delete.rs#L42) you can look at to see where the `ockam relay delete` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by 0x61nas** [comment]
I've taken https://github.com/build-trust/ockam/issues/6466 which is very similar to this (at least in the functionality). So I think it will be better if you can assign this to me too, so I can implement them in one PR and maintain on the constantly across the project.

**Comment by nazmulidris** [comment]
@0x61nas Once you land the PR for https://github.com/build-trust/ockam/issues/6466 you can pick the next issue after that 👍🏽

**Comment by PanGan21** [comment]
Hi! I would like to contribute to the project and I am wondering if I could pick up this issue? :)

**Comment by nazmulidris** [comment]
@PanGan21 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by nazmulidris** [comment]
@PanGan21 Since you started working on this issue, here's some new information that's become available that might help you w/ your PR.

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480
