### ISSUE TITLE
Make `ockam project show` (no args) interactive by asking the user to choose from a list of projects to show (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6473]
# Current behavior

When a user runs `ockam project show` without any arguments, currently they are shown an error & some help text. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/d32dcb7f-13dd-4ca9-9c2b-3cea905ed5c6)

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of project names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), then run `show` for each selected project, and display the results of the `show` command for each project that they've selected.
   - They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/project/show.rs#L44) you can look at to see where the `ockam project show` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Tashuuuu** [comment]
Can you please assign this to me?

**Comment by nazmulidris** [comment]
@Tashuuuu I've assigned https://github.com/build-trust/ockam/issues/6460 to you and not this one. I noticed that you currently have 5 PRs (at least) in review. Good job on taking the initiative. However, once you've landed the open PRs (and have gone through the review process), then it would be a good time to take on another new issue 👍🏽

**Comment by Darioazzali** [comment]
May i take this too please?

**Comment by nazmulidris** [comment]
@Darioazzali That's awesome, this is all yours. Also, please checkout the `tui.rs` file that Adrian added to help you implement this: https://github.com/build-trust/ockam/pull/6884

Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
