### ISSUE TITLE
Make `ockam vault show` (no args) interactive by asking the user to choose from a list of vaults to show (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6474]
# Current behavior

When a user runs `ockam vault show` without any arguments, currently they are shown an error if there are no vaults:

![Image](https://github.com/build-trust/ockam/assets/2966499/2770badc-4789-4aec-a07f-4586e09d603b)

Or the default vault if there is a default one:

![Image](https://github.com/build-trust/ockam/assets/2966499/50210ea8-d857-4f62-9cca-31fff97010c3)

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of vault names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), then run `show` for each selected vault, and display the results of the `show` command for each vault that they've selected.
   - They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/vault/show.rs#L33) you can look at to see where the `ockam vault show` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Tashuuuu** [comment]
Can I take this on?

**Comment by nazmulidris** [comment]
@Tashuuuu I've assigned https://github.com/build-trust/ockam/issues/6460 to you and not this one. I noticed that you currently have 5 PRs (at least) in review. Good job on taking the initiative. However, once you've landed the open PRs (and have gone through the review process), then it would be a good time to take on another new issue 👍🏽

**Comment by abhiramtilakiiit** [comment]
Can you assign this to me?

**Comment by mrinalwadhwa** [comment]
@abhiramtilakiiit of course, all yours.

Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
