### ISSUE TITLE
Make `ockam identity show` (no args) interactive by asking the user to choose from a list of identities to show (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6475]
# Current behavior

When a user runs `ockam identity show` without any arguments, currently they are shown a default identity if one exists. Note that this command creates a default identity if one does not exist at the time this command is run. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/89151c55-2596-4fcb-8e4c-6a091fa5da76)

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of identity names. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), then run `show` for each selected identity, and display the results of the `show` command for each identity that they've selected.
   - They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/identity/show.rs#L44) you can look at to see where the `ockam identity show` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by axd99** [comment]
Hello @nazmulidris, I'd like to give this one a go. Could you assign it to me?

**Comment by nazmulidris** [comment]
@axd99 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by axd99** [comment]
Thank you @nazmulidris.

I'd love to join the discord channel, however access is still being denied :(

**Comment by nazmulidris** [comment]
@axd99 I am not sure how you blocked out of Discord 😞 . If you have any questions, please ask them here and we will get back to you 👍🏽

**Comment by axd99** [comment]
Hi @nazmulidris,

I raised a ticket with discord's support and they reckon it is likely my IP address is banned from the server. They suggest asking one of the moderators to clear all bans in' Server Settings > Bans'. Is this something that you guys can do?

Another option is that a moderation bot has my Discord Tag in its blacklist.

Thank you for your help with this @nazmulidris  👍🏽

**Comment by mrinalwadhwa** [comment]
@axd99 I looked at `Server Settings > Bans` and its empty 🤔 Could you share your discord username and I'll try to invite you directly.

**Comment by axd99** [comment]
Hello

Thanks for taking the time doing this.

My discord username is arno7549

Thanks.



15 Oct 2023, 18:00 by ***@***.***:

**Comment by mrinalwadhwa** [comment]
@axd99 i sent you a request on discord. After you accept I think I might be able to add you our discord server directly

**Comment by axd99** [comment]
Hi @nazmulidris. I have created this pull request:  #6547 .

**Comment by nazmulidris** [comment]
@axd99 Since you created your PR here's some new information that might affect your PR:
- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

**Comment by axd99** [comment]
Hi @nazmulidris,  @adrianbenavides  suggested the same yesterday

> Hi @axd99, thanks for submitting this PR! We recently merged the first PR related to making some commands interactive at https://github.com/build-trust/ockam/pull/6480 


My last commit ( https://github.com/build-trust/ockam/pull/6547/commits/6084abe523ee3413f305b6d03317460f8889fcc5) does that.  

Let me know if it is how you'd expect it.

Thank you.
