### ISSUE TITLE
Make `ockam relay show` (no args) interactive by asking the user to choose from a list of relays to show (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6476]
# Current behavior

When a user runs `ockam relay show` without any arguments, currently they are shown an error & some help text. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/863f923f-9b04-42f8-9c27-88ac73721112)

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode. 

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of relays, at the default node. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), then run `show` for each selected relay name / remote address at the given node, and display the results of the `show` command for each relay that they've selected.
   - They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/relay/show.rs#L40) you can look at to see where the `ockam relay show` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Tashuuuu** [comment]
Can I work on this?

**Comment by nazmulidris** [comment]
@Tashuuuu I've assigned https://github.com/build-trust/ockam/issues/6460 to you and not this one. I noticed that you currently have 5 PRs (at least) in review. Good job on taking the initiative. However, once you've landed the open PRs (and have gone through the review process), then it would be a good time to take on another new issue 👍🏽

**Comment by axd99** [comment]
Hi @nazmulidris, could you assign this one to me?

**Comment by mrinalwadhwa** [comment]
@axd99 All yours!

**Comment by axd99** [comment]
Since we do want the ability to pass no argument at all,  the remote address should then become optional.

At the moment is it this:
```
    /// Name assigned to relay that will be shown (prefixed with forward_to_<name>)
    #[arg(display_order = 900, required = true)]
    remote_address: String,
```

I reckon it should be changed to something like this: 

```
    /// Name assigned to relay that will be shown (prefixed with forward_to_<name>)
    #[arg(display_order = 900]
    remote_address: Option<String>,
```

This changes the interface to the show command slightly.
Is this ok?

**Comment by adrianbenavides** [comment]
> This changes the interface to the show command slightly.

Correct! You'll need to make that change 👍

**Comment by axd99** [comment]
Thank you.

**Comment by nazmulidris** [comment]
@axd99 We made a minor UX (user experience) update to the issue today. Instead of asking a user for confirmation once they've made their selection, we can just skip that and allow them to perform the action. Since the action is not destructive, it results in a better UX for the user.

**Comment by axd99** [comment]
@nazmulidris yes, sure. That makes sense.

**Comment by axd99** [comment]
Created PR #6746.

**Comment by axd99** [comment]
The second commit is a small code tidy. No behaviour changes.
