### ISSUE TITLE
Flatten json output for `vault create` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6481]
## Current behavior

The `json` output format for `vault create` is not correct because it has an unnecessary nested level.

## Desired behavior

The `vault` key should be removed so that the command outputs a flat object.

## Implementation details

The following line should be modified to produce the described output:

https://github.com/build-trust/ockam/blob/3655e8cd8ea2f9634dc354992325790359abfed4/implementations/rust/ockam/ockam_command/src/vault/create.rs#L60

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by nabeel001** [comment]
@adrianbenavides , i would like to work on this issue, can you pls assign this to me.

**Comment by mrinalwadhwa** [comment]
@nabeel001 there is a PR open for this https://github.com/build-trust/ockam/pull/6500
Please have a look at some of the other open issues https://github.com/build-trust/ockam/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest
