### ISSUE TITLE
Flatten json output for `space delete` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6484]
## Current behavior

The `json` output format for `space delete` is not correct because it has an unnecessary nested level.

## Desired behavior

The `space` key should be removed so that the command outputs a flat object.

## Implementation details

The following line should be modified to produce the described output:

https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_command/src/space/delete.rs#L68

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by nabeel001** [comment]
@adrianbenavides, i would like to work on this issue, can you pls assign this to me.

**Comment by nazmulidris** [comment]
@nabeel001 There's already a PR open against this issue by @Tashuuuu https://github.com/build-trust/ockam/pull/6493

**Comment by nazmulidris** [comment]
@Tashuuuu In the future, please add a comment asking to be assigned to an issue before raising a PR against it 🙏🏽 
1) It gives us a chance to assign the issue to you 
2) Makes it easier to track what PR closes the issue
3) Let's others know that this issue is being actively worked on by someone 👍🏽 

Thank you for your contributions! ❤️

**Comment by Tashuuuu** [comment]
Okay. I'll keep that in mind
