### ISSUE TITLE
Flatten json output for `identity list` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6486]
## Current behavior

The `json` output format for `identity list` is not correct because it has an unnecessary nested level.

## Desired behavior

The `identities` key should be removed so that the command outputs a flat object.

## Implementation details

The following line should be modified to produce the described output:

https://github.com/build-trust/ockam/blob/61f6031870f6e8d1db5cc13d6dd353f4543b77cd/implementations/rust/ockam/ockam_command/src/identity/list.rs#L79

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `git merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Tashuuuu** [comment]
Can I work on this issue?

**Comment by nazmulidris** [comment]
@Tashuuuu That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
