### ISSUE TITLE
Use `Terminal` to print output instead of `println` in the `tcp-listener show` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6487]
## Current behavior

The `tcp-listener show` command is using `println` to print the command's output, which is a strategy that is being deprecated.

## Desired behavior

Instead, the `Terminal` struct should be used to handle the output of every command.

## Implementation details

The following snippet should be refactored:

https://github.com/build-trust/ockam/blob/9c49e470a574d91854aa24628584eda4554aaad0/implementations/rust/ockam/ockam_command/src/tcp/listener/show.rs#L50-L55

As an example, the `tcp-inlet show` command uses `formatdoc!` to prepare the `plain` output:

https://github.com/build-trust/ockam/blob/f9d722579eb543d0f327e34bccaa4bd7b3fc1555/implementations/rust/ockam/ockam_command/src/tcp/inlet/show.rs#L59-L64

Then, you have to use the `Terminal` struct as follows to print the command output:

```rust
opts.terminal
    .stdout()
    .plain(plain)
    .write_line()?;
```

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Zapix** [comment]
Hey. Can I take care on this issue?

**Comment by mrinalwadhwa** [comment]
@Zapix of course, all yours

**Comment by Tashuuuu** [comment]
Can I also work on this issue?

**Comment by Tashuuuu** [comment]
Pardon me, I know this issue has not been yet assigned to me but I thought I could resolve the issue, so I gave it a try.
