### ISSUE TITLE
Use `Terminal` to print output instead of `println` in the `space show` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6488]
## Current behavior

The `space show` command is using `println` to print the command's output, which is a strategy that is being deprecated.

## Desired behavior

Instead, the `Terminal` struct should be used to handle the output of every command.

## Implementation details

The following snippet should be refactored:

https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_command/src/space/show.rs#L50

You have to use the `Terminal` struct as follows to print the command output:

```rust
opts.terminal
    .stdout()
    .plain(space.output()?)
    .json(serde_json::to_string_pretty(&space))
    .write_line()?;
```

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Zapix** [comment]
Hey Can I take this issue?

**Comment by nazmulidris** [comment]
@Zapix That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by Tashuuuu** [comment]
Can I please take this issue?

**Comment by Tashuuuu** [comment]
Pardon me, I know this issue has not been yet assigned to me but I thought I could resolve the issue, so I gave it a try.

**Comment by nazmulidris** [comment]
@Tashuuuu This issue has already been assigned to @Zapix. There are plenty of other open issues that you would like to take a look.
