### ISSUE TITLE
Use `Terminal` to print output instead of `println` in the `project info` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6491]
## Current behavior

The `project info` command is using `println` to print the command's output, which is a strategy that is being deprecated.

## Desired behavior

Instead, the `Terminal` struct should be used to handle the output of every command.

## Implementation details

The following snippet should be refactored:

https://github.com/build-trust/ockam/blob/140a8bd71183754d70ec1e4bc1a5c962062fa0a9/implementations/rust/ockam/ockam_command/src/project/info.rs#L54

You have to use the `Terminal` struct as follows to print the command output:

```rust
opts.terminal
    .stdout()
    .plain(info.output()?)
    .json(serde_json::to_string_pretty(&info))
    .write_line()?;
```

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by mrkirthi-24** [comment]
Hi @adrianbenavides I would like to work on this issue

**Comment by adrianbenavides** [comment]
All yours!
