### ISSUE TITLE
Increase of timeout of rust test

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6502]
Increase timeout of the [producer__flow_with_mock_kafka__content_encryption_and_decryption](https://github.com/build-trust/ockam/blob/44d4d658465676e8f2d1f23c282e385a44444f67/implementations/rust/ockam/ockam_api/src/kafka/integration_test.rs#L113-L114) test from 5s to a minute

**Comment by sayyedarib** [comment]
hey @metaclips I would like to work on this issue

**Comment by mrinalwadhwa** [comment]
@sayyedarib That's awesome, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
