### ISSUE TITLE
CI - Reduce GitHub actions cache size across all workflows

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6504]
We currently use up x10 of the [cache size limit by Github](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speedhttps://github.com/build-trust/ockam/actions/caches-up-workflows#usage-limits-and-eviction-policy) we need to ensure we are creating and re-using cache efficiently

**Comment by metaclips** [comment]
From this [documentation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), caches created by pull requests are private only to that pull request, since these cache are still stored it increases our cache storage with irrelevant data, we should only save cache when the workflow is run from the default (develop) branch as caches created and saved on the default branch are re-useable across. I'll be creating multiple hacktoberfest issues on this.

**Comment by Lumexralph** [comment]
@metaclips I don't know if you still want to provide more information about this but I would like to give it a try

**Comment by nazmulidris** [comment]
@Lumexralph That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by metaclips** [comment]
Hello @Lumexralph I divided this issue into subsets to make this issue easier to close
- https://github.com/build-trust/ockam/issues/6550
- https://github.com/build-trust/ockam/issues/6551
- https://github.com/build-trust/ockam/issues/6552
- https://github.com/build-trust/ockam/issues/6553
- https://github.com/build-trust/ockam/issues/6554
- https://github.com/build-trust/ockam/issues/6555
- https://github.com/build-trust/ockam/issues/6556
- https://github.com/build-trust/ockam/issues/6557
- https://github.com/build-trust/ockam/issues/6558
- https://github.com/build-trust/ockam/issues/6559
- https://github.com/build-trust/ockam/issues/6560
- https://github.com/build-trust/ockam/issues/6561
- https://github.com/build-trust/ockam/issues/6562
- https://github.com/build-trust/ockam/issues/6564

Please indicate if you want to take up any of them and I'll assign you to them

**Comment by metaclips** [comment]
@nazmulidris @Lumexralph this issue is a parent issue so we'll be assigning from the child issues created

**Comment by metaclips** [comment]
Thanks @Lucif3r-in @Lumexralph @DIlkhush00 @ironspec07 @volcov @mickm3n for getting this issue closed🕺🏽 we also have a [discord community](https://discord.gg/bewvnm6zqS) where we discuss all things Ockam, would be expecting you all there.
