### ISSUE TITLE
CI - Split the elixir cache composite action to a restore and save action

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6508]
We have a [composite action that caches our Elixir dependencies](https://github.com/build-trust/ockam/blob/develop/.github/actions/elixir_cache/action.yml), we should split this action to support [saving](https://github.com/actions/cache/blob/main/save/README.md) and [restoring](https://github.com/actions/cache/blob/main/restore/README.md) distinctively, we should `only` save cache `if and only if` the branch is from the default (develop) branch so that we can [cache efficiently](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows), to allow this

- Only use [the `actions/cache` action](https://github.com/build-trust/ockam/blob/353f4be70d0d9455437ce20044e6208e268d306b/.github/actions/elixir_cache/action.yml#L12) (which saves and restore cache) only when the workflow is run as a cron job by adding a [conditional](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) to ensure that the  [event_name that triggered the workflow](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) `${{ github.event_name == 'schedule' }}`
- If worklfow is not run from a scheduler, we should use only [restore cache action](https://github.com/actions/cache/blob/main/restore/README.md)

---

<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by ashutosh-rath02** [comment]
Hey @metaclips working on it can you please assign it to me😊?

**Comment by ashutosh-rath02** [comment]
Also can you specify the time for the cron job?
