### ISSUE TITLE
CI - rename the elixir_cache composite action to cache_elixir

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6520]
Rename the [elixir_cache composite action](https://github.com/build-trust/ockam/tree/develop/.github/actions/elixir_cache) to `cache_elixir`

**Comment by Ritish134** [comment]
Hi there excited to contribute . Can you assign me this issue :)

**Comment by mrinalwadhwa** [comment]
@Ritish134 That's awesome, all yours.

Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
