### ISSUE TITLE
CI - rename the nix_installer_and_cache composite action to cache_nix

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6521]
Rename the [nix_installer_and_cache composite action](https://github.com/build-trust/ockam/tree/develop/.github/actions/nix_installer_and_cache) to cache_nix

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Suraj-kumar00** [comment]
Hi @metaclips, How are you doing?
I'm Suraj can pick up this issue if yes please assign this to me and can I know more about this issue in order to understand it better and solve this issue?

**Comment by metaclips** [comment]
All yours @Suraj-kumar00

**Comment by Suraj-kumar00** [comment]
So I just have to replace the nix_installer_and_cache composite action with cache_nix ?
Like can you please elaborate little bit?

**Comment by metaclips** [comment]
Hello @Suraj-kumar00 you need to rename the folder [nix_installer_and_cache ](https://github.com/build-trust/ockam/tree/develop/.github/actions/nix_installer_and_cache) to `cache_nix`

**Comment by Suraj-kumar00** [comment]
Hi @metaclips, How are you doing?
I changed the folder name and created a pull request, please review...

**Comment by metaclips** [comment]
Thanks @Suraj-kumar00 for getting this closed, we also have a [discord community](https://discord.gg/bewvnm6zqS) where we discuss Ockam stuffs, happy to hangout there.

**Comment by Suraj-kumar00** [comment]
> Thanks @Suraj-kumar00 for getting this closed, we also have a [discord community](https://discord.gg/bewvnm6zqS) where we discuss Ockam stuffs, happy to hangout there.

Thanks for having me 😌
