### ISSUE TITLE
CI - Split the nix cache composite action to a restore and save action

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6522]
We have a [composite action that caches our nix dependencies and binary](https://github.com/build-trust/ockam/blob/353f4be70d0d9455437ce20044e6208e268d306b/.github/actions/nix_installer_and_cache/action.yml#L17-L23), we should split this action to support [saving](https://github.com/actions/cache/blob/main/save/README.md) and [restoring](https://github.com/actions/cache/blob/main/restore/README.md) distinctively, we should only save cache if and only if the branch is from the default (develop) branch so that we can [cache efficiently](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows), to allow this

- Only use [the actions/cache action](https://github.com/build-trust/ockam/blob/353f4be70d0d9455437ce20044e6208e268d306b/.github/actions/nix_installer_and_cache/action.yml#L17-L23) (which saves and restore cache) only when the workflow is run as a cron job by adding a [conditional](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) to ensure that the [event_name that triggered the workflow](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) `${{ github.event_name == 'schedule' }}`
- If worklfow is not run from a scheduler, we should use only [restore cache action](https://github.com/actions/cache/blob/main/restore/README.md)

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by nabeel001** [comment]
@metaclips I would like to work on this issue

**Comment by metaclips** [comment]
Nice assigning you now. Do indicate if anything is unclear, would love to help

**Comment by metaclips** [comment]
Hello @nabeel001 checking up on this issue, are you still working on it?

**Comment by nabeel001** [comment]
Yes I'm on it

**Comment by nabeel001** [comment]
@metaclips, kindly review it

**Comment by metaclips** [comment]
Reviewed
