### ISSUE TITLE
CI - rename `nix_installer_and_cache` to `cache_nix` in elixir workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6550]
We recently renamed composite action that caches our Nix dependencies in this pull request https://github.com/build-trust/ockam/pull/6532, we should also rename the [elixir workflow that uses cache action](https://github.com/build-trust/ockam/blob/develop/.github/workflows/elixir.yml#L62) from 
```yaml
- uses: ./.github/actions/nix_installer_and_cache
```
to
```yaml
- uses: ./.github/actions/cache_nix
```
---

<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by DIlkhush00** [comment]
Hi @metaclips, I want to work on this issue. Can you assign it to me?

**Comment by metaclips** [comment]
All yours @DIlkhush00
