### ISSUE TITLE
CI - rename `nix_installer_and_cache` to `cache_nix` in make workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6551]
We recently renamed composite action that caches our Nix dependencies in this pull request https://github.com/build-trust/ockam/pull/6532, we should also rename the [make workflow that uses cache action](https://github.com/build-trust/ockam/blob/develop/.github/workflows/make.yml#L48) from 
```yaml
- uses: ./.github/actions/nix_installer_and_cache
```
to
```yaml
- uses: ./.github/actions/cache_nix
```

---

<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Lumexralph** [comment]
@metaclips  Please, can you assign this to me?

**Comment by metaclips** [comment]
All yours
