### ISSUE TITLE
CI - rename `nix_installer_and_cache` to `cache_nix` in rust workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6552]
We recently renamed composite action that caches our Nix dependencies in this pull request https://github.com/build-trust/ockam/pull/6532, we should also rename the [rust workflow](https://github.com/build-trust/ockam/blob/develop/.github/workflows/rust.yml) that uses the old action which is in the directory `.github/actions/nix_installer_and_cache` to use the new action in directory `./.github/actions/cache_nix`, example of one of the old action usage is https://github.com/build-trust/ockam/blob/e6fc609e327aa9d17dee1296e115a6119c2902a8/.github/workflows/rust.yml#L69

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Lumexralph** [comment]
@metaclips I would like to work on this.

**Comment by metaclips** [comment]
Hello @Lumexralph there are two issues assigned to you https://github.com/build-trust/ockam/issues/6551 and https://github.com/build-trust/ockam/issues/6538 can we close those two before assigning any other issue to you?

**Comment by Lumexralph** [comment]
That's fine, they all look similar, that was why I wanted them assigned to me.

**Comment by ironspec07** [comment]
Sounds interesting, can i work on this ? @metaclips

**Comment by metaclips** [comment]
All yours @ironspec07
