### ISSUE TITLE
CI - rename `nix_installer_and_cache` to `cache_nix` in shell workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6553]
We recently renamed composite action that caches our Nix dependencies in this pull request https://github.com/build-trust/ockam/pull/6532, we should also rename the [shell workflow that uses cache action](https://github.com/build-trust/ockam/blob/develop/.github/workflows/shell.yml#L57) from 
```yaml
- uses: ./.github/actions/nix_installer_and_cache
```
to
```yaml
- uses: ./.github/actions/cache_nix
```
---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by Lumexralph** [comment]
@metaclips I would like to work on this.

**Comment by metaclips** [comment]
Hello @Lumexralph there are two issues assigned to you https://github.com/build-trust/ockam/issues/6551 and https://github.com/build-trust/ockam/issues/6538 can we close those two before assigning any other issue to you?

**Comment by Technmad** [comment]
@metaclips i would like to work on it, please assign me the issue

**Comment by metaclips** [comment]
All yours @Technmad

**Comment by metaclips** [comment]
Hello @Technmad, pinging you on this issue, are you still taking it?
