### ISSUE TITLE
CI - rename `elixir_cache` to `cache_elixir` in make workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6554]
We recently renamed composite action that caches our elixir dependencies in this pull request https://github.com/build-trust/ockam/pull/6525, we should also rename the [make workflow that uses cache action](https://github.com/build-trust/ockam/blob/e6fc609e327aa9d17dee1296e115a6119c2902a8/.github/workflows/make.yml#L53) from 
```yaml
- uses: ./.github/actions/elixir_cache
```
to
```yaml
- uses: ./.github/actions/cache_elixir
```

---

<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by nishantdub37** [comment]
@metaclips can u assign this issue to me?

**Comment by metaclips** [comment]
All yours @nishantdub37

**Comment by metaclips** [comment]
Hello @nishantdub37 ping you on this issue, are you still taking it up?

**Comment by ashutosh-rath02** [comment]
@metaclips Can I work on it?

**Comment by metaclips** [comment]
Yes, all yours @Lucif3r-in

**Comment by metaclips** [comment]
Thanks @Lucif3r-in for closing this issue
