### ISSUE TITLE
CI - rename `elixir_cache` to `cache_elixir` in elixir workflow

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#6555]
We recently renamed composite action that caches our elixir dependencies in this pull request https://github.com/build-trust/ockam/pull/6525, we should also rename the [elixir workflow that uses cache action](https://github.com/build-trust/ockam/blob/e6fc609e327aa9d17dee1296e115a6119c2902a8/.github/workflows/elixir.yml#L62) from 
```yaml
- uses: ./.github/actions/elixir_cache
```
to
```yaml
- uses: ./.github/actions/cache_elixir
```
---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by volcov** [comment]
Hello @metaclips, how are you?
Can I handle this one?

**Comment by metaclips** [comment]
All yours @volcov
