### ISSUE TITLE
Use `Terminal` to print output instead of `println` in the `tcp-listener create` command

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6570]
## Current behavior

The `tcp-listener create` command is using `println` to print the command's output, which is a strategy that is being deprecated.

## Desired behavior

Instead, the `Terminal` struct should be used to handle the output of every command.

## Implementation details

The following snippet should be refactored:

https://github.com/build-trust/ockam/blob/9c49e470a574d91854aa24628584eda4554aaad0/implementations/rust/ockam/ockam_command/src/tcp/listener/create.rs#L57

As an example, the `tcp-inlet show` command uses `formatdoc!` to prepare the `plain` output:

https://github.com/build-trust/ockam/blob/9c49e470a574d91854aa24628584eda4554aaad0/implementations/rust/ockam/ockam_command/src/tcp/outlet/create.rs#L127-L142

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by nazmulidris** [comment]
@cyberdad68 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
