### ISSUE TITLE
Add new CBOR encoding option for elixir structs

### ISSUE THREAD

**Issue by polvorin** [build-trust/ockam#6614]
### Current behavior

In ockam we use CBOR as the underling encoding for several of the data types sent on the wire.    To encode non-primitive cbor types (like structs or enums) we follow what https://docs.rs/minicbor-derive/0.13.0/minicbor_derive/index.html# produces for the corresponding rust structure (you don't need to understand that for addressing this issue).   

Currently,  all structs are encoded as a map of `{integer => value}` ,  where the type of the value is given by the type of the corresponding field, and the map' index is specified as part of the schema. 

See  https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam_typed_cbor/lib/typed_cbor.ex
```
      iex> to_cbor_term({:struct, %{a1: %{key: 1, schema: :string, required: true},
      ...>                          a2: %{key: 2, schema: {:enum, [a: 0, b: 1]}}}},
      ...>              %{a1: "aa", a2: nil})
      %{1 => "aa"}

      iex> from_cbor_term({:struct, %{a1: %{key: 1, schema: :string, required: true},
      ...>                            a2: %{key: 2, schema: {:enum, [a: 0, b: 1]}}}},
      ...>                 to_cbor_term({:struct, %{a1: %{key: 1, schema: :string, required: true},
      ...>                                         a2: %{key: 2, schema: {:enum, [a: 0, b: 1]}}}},
      ...>                              %{a1: "aa", a2: nil}))
      %{a1: "aa"}
```

* `to_cbor_term/2`  takes a schema definition and a value,  and returns an erlang term ready to be encoded by the [underling cbor library](https://hexdocs.pm/cbor/readme.html). 
* `from_cbor_term` is the inverse operation

There are different schemas supported, above example shows the one for `:struct` that maps elixir Structs and maps into cbor' maps. 

This `:struct` schema is generally used through a macro,  see the [example](https://github.com/build-trust/ockam/blob/develop/implementations/elixir/ockam/ockam_typed_cbor/test/plugin_test.exs#L8) to get a better idea.

### Desired behavior

What we want is to add a _new_  encoding for structs,   that encodes into a CBOR array.  As:

```
    iex> to_cbor_term({:packed_struct, %{a1: %{key: 1, schema: :string, required: true},
      ...>                          a2: %{key: 2, schema: {:enum, [a: 0, b: 1]}}}},
      ...>              %{a1: "aa", a2: nil})
      [nil, "aa", nil]
```
The indices of the array are taken from the schema'  key attribute.   unused indexes are left as nil.   `:packed_struct` might mot be the best name so you are welcome to come with a better term.

Success criteria:
*  New clauses are added to `to_cbor_term/2`  and `from_cbor_term/2` term to support the new `packed_struct` schema
* An option is added to `Ockam.TypedCBOR.Plugin` ,  to let the user choose if the structure is to be encoded using the `:struct` or the new  `:packed_struct` method.   Refer to the [official documentation](https://hexdocs.pm/typed_struct/TypedStruct.Plugin.html) on how to give options at plugin init time
* Add test cases for for the base  `to_cbor_term/2`  and `from_cbor_term/2` functions, and for the  plugin.

**Comment by priyanshu9899** [comment]
assign me this issue i wanna contribute on this issue

**Comment by polvorin** [comment]
hi, sure @priyanshu9899  thanks!.
If you have any questions or need any clarification, please feel free to reach out to us

**Comment by mrinalwadhwa** [comment]
@priyanshu9899 thank you for spending time on this. If your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
