### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mikelodder7** [build-trust/ockam#662]
Change errors to be similar to 

```rust
pub struct Error {
    #[cfg(feature = "std")]
    inner: … enum ...,
    #[cfg(not(feature = "std"))]
    code: u32,
}

#[cfg(not(feature = "std"))]
pub mod ErrorCode {
    pub const SUCCESS: u32 = 0;
    pub const VAULTKEY_ERROR: u32 = 1;
    ....
}
```

The error codes would be in a single crate that is shared across the core crates. The reason for this is to avoid the problem of constantly converting between errors for many of the different crates.

For example, Channels wrap Key establishment which wraps Vault. Converting between errors all the way up the stack is painful. By having errors be strings or u32, the errors can simply bubble to the top and the traits all share a common error type without having to handle 1-2 error types per crate.

**Comment by etorreborre** [comment]
Errors have been normalized here: https://github.com/build-trust/ockam/blob/2fdbb0c0e3554e735ecf6591d8d68d2bd1c6fe39/implementations/rust/ockam/ockam_core/src/error/mod.rs#L25
