### ISSUE TITLE
Improve `ockam tcp-inlet list --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6644]
# Current behavior

When a user runs `ockam tcp-inlet list --help` they are shown the following help text.

![Image](https://github.com/build-trust/ockam/assets/2966499/4e9acba9-d452-4ed9-874a-963d9d1795a4)

# Desired behavior

Instead, they should be presented with the following help text for the command `List TCP Inlets on the default node`. 

# Implementation details

1) Replace the Rust doc comment for the `ListCommand` struct with the following: `List TCP Inlets on the default node` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/list.rs#L21)

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by priyanshu9899** [comment]
assign me this issue i would like to work on this

**Comment by nazmulidris** [comment]
@priyanshu9899 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
