### ISSUE TITLE
Improve `ockam tcp-inlet delete --help` text (`clap` command)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6645]
# Current behavior

When a user runs `ockam tcp-inlet delete --help` then the following output is displayed.

![Image](https://github.com/build-trust/ockam/assets/2966499/5f5b57a4-d3e7-4f81-b025-2c677aa0889b)

# Desired behavior

Change the help text for the `<ALIAS>` argument to say: `Delete the inlet with this alias name`

# Implementation details

Change the Rust doc comment for the `DeleteCommand::alias` field in this [file](
https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs#L18)

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Michaelin007** [comment]
can I work on this?

**Comment by Michaelin007** [comment]
I created a PR for this already. You can review

**Comment by ashutosh-rath02** [comment]
@Michaelin007 It will be great if you mention the issue in the PR.
