### ISSUE TITLE
Improve `ockam tcp-inlet delete <ALIAS>` when `<ALIAS>` does not exist

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6647]
# Current behavior

When a user runs `ockam tcp-inlet delete <ALIAS>` and `<ALIAS>` does not exist, then they get a prompt, asking them to confirm whether this command should proceed or not. Then they are shown an error stating that `400 BadRequest`.

![Image](https://github.com/build-trust/ockam/assets/2966499/9cc86d04-17bf-472a-b85a-a28d2419d5a7)

# Desired behavior

Instead of asking the user for a confirmation prompt, it would be better to first check to see whether `<ALIAS>` even exists. 

1) If it does *not*, then the user should be notified that this alias name doesn't exist and can't be deleted. This can be an error.

2) If it does exist, then the user should be prompted, to confirm whether this destructive operation should proceed. If that operation fails for some reason then an error should be displayed with information on what went wrong (which is the current behavior).

# Implementation details

- Take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/tcp/inlet/delete.rs#L39) to get started.

- This is a similar issue https://github.com/build-trust/ockam/pull/6494/files
---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Lumexralph** [comment]
@nazmulidris I want to give a go at this, please, can you assign it to me?

**Comment by nazmulidris** [comment]
@Lumexralph That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by Lumexralph** [comment]
@nazmulidris I can't reproduce the same error displayed on the issue.

Do you have an idea, of how I can do this?

**Comment by nazmulidris** [comment]
@Lumexralph How are you running `ockam` command? Are you building from source or are you using the version on brew. Can you provide a screenshot of what you are getting when you run the command?

**Comment by Lumexralph** [comment]
I built from source and ran it

<img width="713" alt="Screenshot 2023-10-20 at 07 03 55" src="https://github.com/build-trust/ockam/assets/12391886/adda4a44-5cd2-482e-9429-c2306646e44c">

**Comment by nazmulidris** [comment]
@Lumexralph I think the feature for this issue has already been implemented in a different PR that I wasn't aware of. Thank you for bringing this to my attention. I will close this issue and thank you for taking the time to look at it. Feel free to take a look at some of our other open issues 🙏🏽
