### ISSUE TITLE
Improve `ockam node logs` by adding `--output json`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6658]
# Observed behavior

When a user runs `ockam node logs --output json` they get the following error.

![Image](https://github.com/build-trust/ockam/assets/2966499/7f970e42-9edc-4806-be04-3def1b2e1f4e)

# Desired behavior

Instead provide JSON output containing the same information you get with `--output plain`.

# Implementation details

Please take a look at this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/logs.rs#L33) to get started.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by axd99** [comment]
Could you assign this one to me @nazmulidris?

**Comment by nazmulidris** [comment]
@axd99 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by axd99** [comment]
When running the with `--output plain` we only get a path:
```
$ target/debug/ockam node logs n1 --output plain
/home/axd99/.ockam/nodes/n1/stdout.log
```
The output is not a data structure (no key -> value), simply a a string. Changing this to json requires a key of some kind for the path
eg.
```
 $ target/debug/ockam node logs n1 --output json
{ "stdout_log": "/home/axd99/.ockam/nodes/n1/stdout.log"}
```
Is this acceptable?

**Comment by nazmulidris** [comment]
@axd99 Great question. @adrianbenavides What do you think?

**Comment by axd99** [comment]
Thank you @nazmulidris.
@adrianbenavides , The code only outputs `machine`.
It could be that `plain` is also required, and would display both the key and the value.

**Comment by adrianbenavides** [comment]
>```
> $ target/debug/ockam node logs n1 --output json
> { "stdout_log": "/home/axd99/.ockam/nodes/n1/stdout.log"}
> ```
> Is this acceptable?

I'd say the key name should be "path".

The `machine` output should be the path, so we can pipe it to other commands. As for the `plain` output, you could use the `fmt_ok!` macro and add a human-friendly message like "The path for the stdout logs is: {path}".

**Comment by axd99** [comment]
I've created this PR #6810 in the hope that it answers the questions I have raised above.

One question I have about the output is about `machine`. What purpose does it serve?
I can't run something like
```
$ target/debug/ockam node logs n1 --output machine
error: invalid value 'machine' for '--output <OUTPUT_FORMAT>'
  [possible values: plain, json]
```

**Comment by axd99** [comment]
@adrianbenavides . I'll amend as per your comments. Thank you.

**Comment by axd99** [comment]
Amendments pushed back.
