### ISSUE TITLE
Make `ockam node start` (no args) interactive by asking the user to choose from a list of nodes to start (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6659]
# Current behavior

When a user runs `ockam node start` without any arguments, currently they are shown help text. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/126e2746-9003-4ef4-8728-478e3909895b)

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of nodes that have not been started. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that `start` is about to be called with the nodes they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then run `start` for each selected nodes, and display the results of the `start` command for each nodes that they've selected.
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/start.rs#L41) you can look at to see where the `ockam node start` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Darioazzali** [comment]
Hello, may I take this issue?

**Comment by mrinalwadhwa** [comment]
@Darioazzali of course, all yours!

Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by Darioazzali** [comment]
Good morning. I have some questions:
1. About the specific output that should be displayed to the user in case of multiple selection.
2. About output node verbosity.
3. What to display in case of *interactive terminal* and no argument is passed.


## 1. About the specific output that should be displayed to the user in case of multiple selection.
When multiple node are selected how the output should be reported?

1. Print simply the result with tick status
```sh
✔︎ kind-mongoose started 
✔︎ integral-adjutant started 
⚠️ firm-bustard encountered problems!
```

And then print the errors for the failed nodes (in addition at the end of the list)?
Optionally:
```sh
✗ Errors:
✗ firm-bustard: {error type}
```


2. Print the node list (like in the `show` subcommand ) sequentially with the status tick just in front of the list element


```sh
    ⚠️ kind-mongoose wont start
Node:
  Name: integral-adjutant
  Status: UP
  Route To Node:
    Short: /node/integral-adjutant
    Verbose: /dnsaddr/localhost/tcp/38079
  Identity: I09ab4eee641f8a8e4dd1dc7d0b040374ecf0e1ca
  Transports:
    Transport:
      Type: TCP
      Mode: Listening
      Socket: 127.0.0.1:38079
      Worker: <none>
  Secure Channel Listeners:
    Listener:
      Address: /service/api
  Inlets:
  Outlets:
  Services:
    Service:
      Type: uppercase
      Address: /service/uppercase
    Service:
      Type: echo
      Address: /service/echo

     ✔︎ integral-adjutant


```

maybe with a pager (additionally)?

## 2. About output node verbosity
In the original implementation the verbosity was chosen by the node configuration.
In case of showing the list of all nodes should the verbosity be choose differently for every single node?
```rust
let node_setup = node_state.config().setup();
opts.global_args.verbose = node_setup.verbose;
```
## 3. What to do in case of *interactive terminal* and no argument is passed.
What should the program do in that case? Like in the `stop subcommand` simply give the result of starting the default node?



Additionally I've made a user flow diagram, is that correct o am I missing something?
```mermaid
%%{ init: { 'flowchart': { 'curve': 'stepAfter' } } }%%
flowchart TD
    A(ockam node start < NODE >) 
    A --> B{1. NODE?}
    B -- no --> P{2. terminal interactive?}
    P -- no --> Q["3. DISPLAY HELP? .
Exit with no error."]
    C -- yes -->D["4 print 
 '> All jobs are actually started.'
 Exit with no error"]
    C --no -->E[5. display selection]
    E --> F{6. user select something?}
    F --no -->G["7. print:
 '> no jobs selected, exiting gratefully'.
 Exit with no error"]
    F -- yes --> H[8. ask for confirmation]
    H --> I{9. confirm?}
    I -- no --> M["10. print
 '> no jobs selected, nothing to do, exiting gratefully.' 
exit with no error"]
    I -- yes --> N["11. Run all jobs.
Display the list as result with a check mark or a triangle.
Then show all the nodes status
 or simply list the error report
about those failed.
"]
    P -- yes --> C{12. All jobs already started?}
    B -- yes --> O{13. NODE is actually started?}
    O --yes --> Z["14. print
  '✗The node xxx is already running. 
If you want to restart it you can call `ockam node stop xxxx`
 and then `ockam node start xxxx`
     Exit with no error"] 
     O -- no --> Y["15. start the node. "]
       Y ----> U{"16. Success?. "}
U -- no --> T["17. Report the error."]
U -- no --> S["17. Show the node"]
```

Thanks for your patience.

**Comment by adrianbenavides** [comment]
Hi @Darioazzali !

> 1. About the specific output that should be displayed to the user in case of multiple selection.

I'd go for the first approach (`Print simply the result with tick status`) and optionally print the errors at the end. The error details will probably be too noisy to show them here, so maybe you could tell the user about a potential "next action" like: `You can check the status of failed nodes using the command `ockam node show` or check the logs with the command `ockam node logs`.

> 2. About output node verbosity

Not 100% sure about the internals, but the node configuration should be honored.

> 3. What to do in case of interactive terminal and no argument is passed.

> Like in the stop subcommand simply give the result of starting the default node?

Exactly, unless there is no default node, which in that case you should throw an error.

> Additionally I've made a user flow diagram, is that correct o am I missing something?

Not 100% sure either. Perhaps this PR can help with those edge cases: https://github.com/build-trust/ockam/pull/6547
