### ISSUE TITLE
Make `ockam node stop` (no args) interactive by asking the user to choose from a list of nodes to start (tuify)

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#6660]
# Current behavior

When a user runs `ockam node stop` without any arguments, currently they are shown help text. Here's a screenshot of this.

![Image](https://github.com/build-trust/ockam/assets/2966499/b1f11c44-34e4-4c90-9485-65862f377fcd)

# Desired behavior

Change the behavior of this command so that it becomes interactive with the user when no arguments are passed. Note that this can only be allowed to happen if:

- the terminal is interactive, and,
- the [`--no-input`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L265) or `--quiet` flags have *not* been passed, and,
- no arguments have been passed in to the command.

This what the user flow should look like in interactive mode.

1) Use the [tuify](https://crates.io/crates/r3bl_tuify) crate's `select_from_list()` function to ask the user to select from a list of nodes that have been started. They should be able to make multiple selections. If there are none, then simply display a message saying that none exist (not an error) and exit.

2) Once the user has made their selection(s), display a confirmation prompt letting the user know that that `stop` is about to be called with the nodes they have selected. Use `select_from_list()` to display this prompt. They should be able to make a single selection.
   - If they have made no selections then exit by displaying a message to the user letting them know they did not make any selection.

3) If they choose "YES", then run `stop` for each selected nodes, and display the results of the `stop` command for each nodes that they've selected.
   - If an operation succeeds then use the ✅ emoji as a prefix for the message. 
   - And if it fails, then use the ⚠️ emoji as a prefix for the message.

> The following is a video showing a generic user flow that shows the user experience when a user is asked to choose a from a list of "things". Then an action is performed on each "thing". Finally status information is reported for each action that is performed on each "thing". Please note that this flow is *not* specific to this issue. 
> ![Image](https://github.com/build-trust/ockam/assets/2966499/19efea08-4bad-433a-bf8d-b1e709f69a15)
>  https://asciinema.org/a/612547

# Implementation details

- Please use the functions `select_multiple`, and `confirm_interactively` in this [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L281).

- Here's a similar PR to get some ideas from: https://github.com/build-trust/ockam/pull/6480

- You can learn more about how to use the `select_from_list()` in the tuify crate [here](https://docs.rs/r3bl_tuify/latest/r3bl_tuify/). Here is an [example](https://github.com/r3bl-org/r3bl_rs_utils/blob/ockam-demo/tuify/examples/main_interactive.rs) that is very similar to the steps you might have to take for this issue.
- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L255) you can look at to detect when a terminal is interactive or not.

- Here's a [file](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/node/stop.rs#L41) you can look at to see where the `ockam node start` command is implemented.

---
<i>

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).
</i>

**Comment by Lumexralph** [comment]
@nazmulidris I'll like to attempt this, please, can you assign it to me?

**Comment by nazmulidris** [comment]
@Lumexralph That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by Lumexralph** [comment]
@nazmulidris  I think I have finished working on this but I need to run it to check it out.

Is there a way I can do this?

**Comment by nazmulidris** [comment]
@Lumexralph You can follow the instructions [here](https://docs.ockam.io/#end-to-end-encrypted-and-mutually-authenticated-communication) to create some nodes and then start / stop them. 

You can also follow this manual [here](https://command.ockam.io/manual/ockam-node.html) to create nodes so that you can play w/ starting and stopping them.

To build and run Ockam command from source, you can check this out: [README.md](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/README.md#instructions-on-how-to-install-ockam-command).

**Comment by Lumexralph** [comment]
thanks @nazmulidris

**Comment by nazmulidris** [comment]
@Lumexralph You are most welcome. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds 👍🏽
