### ISSUE TITLE
Build output of `lease show` implementing the `Output` trait instead of using `termimad`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6677]
## Current behavior

The [`lease show` command](https://github.com/build-trust/ockam/blob/da8e3a5e109ed2ed265cdbac05a9f9e890e21451/implementations/rust/ockam/ockam_command/src/lease/show.rs) uses `termimad` to format and print its output.

## Desired behavior

The command output should be formatted with `formatdoc` and printed with `opts.terminal.stdout()`.

## Implementation details

Since `Token` already implements the `Output` trait, you could write something like:

```rust
opts.terminal
    .stdout()
    .plain(&token)
    .json(serde_json::json!(&token))
    .write_line()?;
```

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by zacharyftw** [comment]
@adrianbenavides i can work on this issue since i've worked on rust projects previously

**Comment by mrinalwadhwa** [comment]
@KekmaTime That's awesome, all yours.
Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
