### ISSUE TITLE
Build output of `authenticated` commands implementing the `Output` trait instead of using `termimad`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6678]
## Current behavior

The [`authenticated` commands](https://github.com/build-trust/ockam/blob/02f62ab5fdc9ab7508c5a148a8f9d97325acc92c/implementations/rust/ockam/ockam_command/src/authenticated.rs#L64) uses `termimad` to format and print its output.

## Desired behavior

The command output should be formatted with `formatdoc` and printed with `opts.terminal.stdout()`.

## Implementation details

The `get` and `list` commands are using the function `print_entries` to build the output, which uses a list of `identifier, attribute` pairs. Consider creating a custom struct to represent that pair and implement the `Output` trait for it so that you can build the output as follows:

```rust
opts.terminal
    .stdout()
    .plain(&attribute) // use `opts.terminal.build_list(&attributes, ...)` to build the output for the `list` command
    .json(serde_json::json!(&attribute))
    .write_line()?;
```

Check the [`lease list` command](https://github.com/build-trust/ockam/blob/da8e3a5e109ed2ed265cdbac05a9f9e890e21451/implementations/rust/ockam/ockam_command/src/lease/list.rs#L57) to see an example of how to do this.

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by zacharyftw** [comment]
@mrinalwadhwa can you assign me this issue i would like to work on it

**Comment by nazmulidris** [comment]
@KekmaTime That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
