### ISSUE TITLE
Remove `is_tty` utility function from `ockam_command`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6679]
## Current behavior

We use the [`is_tty` function](https://github.com/build-trust/ockam/blob/ad7b5910eecdc230b5da138317429105c4b7c4a0/implementations/rust/ockam/ockam_command/src/util/mod.rs#L267) in several places. This function forces us to keep an additional dependency that we would like to remove.

## Desired behavior

The [`is_tty` function](https://github.com/build-trust/ockam/blob/ad7b5910eecdc230b5da138317429105c4b7c4a0/implementations/rust/ockam/ockam_command/src/util/mod.rs#L267) should be deprecated in favor of the one defined in the [`TerminalWriter` trait](https://github.com/build-trust/ockam/blob/2a2843eb3c57c5e91819c837df0804664f30e2c6/implementations/rust/ockam/ockam_command/src/terminal/mod.rs#L197), which is generally available through `opts.terminal.is_tty()`.

Once the `is_tty` function is removed, the `is-terminal` and `io-lifetimes` dependencies should be removed from `ockam_command`.

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by a6ar55** [comment]
Hey, can i work on it.

**Comment by nazmulidris** [comment]
@a6ar55 That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by TropicalDog17** [comment]
@nazmulidris Hi, it seems that this issue has been open for a while, and there hasn't been much progress from the assignee's side. I would appreciate it if my PR could be considered. Thank you.

**Comment by nazmulidris** [comment]
@TropicalDog17 Thanks for working on this issue.

**Comment by nazmulidris** [comment]
@TropicalDog17 Thanks for working on this issue. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
