### ISSUE TITLE
Remove unused `Output` implementations for `Vec<Project>` and `Vec<Space>`

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#6680]
## Current behavior

The `Output` implementation for `Vec<Project>` and `Vec<Space>` uses `cli_table` and is not used.

## Desired behavior

Remove the [`Vec<Project>`](https://github.com/build-trust/ockam/blob/a858be5038aa780dca56599a8ba3665f127d3e92/implementations/rust/ockam/ockam_command/src/output/output.rs#L200) and [`Vec<Space>`](https://github.com/build-trust/ockam/blob/a858be5038aa780dca56599a8ba3665f127d3e92/implementations/rust/ockam/ockam_command/src/output/output.rs#L117) implementations of the `Output` trait.

Once the `is_tty` function is removed, the `cli-table` dependency should be removed from `ockam_command`.

---

<i>

Some tips for newcomers:
1. Create a new branch for the issue you are working on (don't push directly to your fork's `develop` branch)
1. Run `cargo fmt`. You can configure the editor to run it automatically everytime a file is saved
1. Run `cargo clippy` to make sure the code compiles + follows rust standards/best practices
1. You don't need to keep your branch updated with `develop` until there is a merge conflict. If you still want to update it, use `git rebase develop` instead of `gir merge develop` 

We love helping new contributors! ❤️
If you have questions or need help as you explore, please join us on [Discord](https://discord.gg/bewvnm6zqS). If you're looking for other issues to contribute to, please checkout our [good first issues](https://github.com/build-trust/ockam/labels/good%20first%20issue).

</i>

**Comment by ronaldvimal** [comment]
Please assign this to me

**Comment by nazmulidris** [comment]
@ronaldvimal That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds
