### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by PiyushDive** [build-trust/ockam#6804]
### Current behavior

There is no contribution guide on this project.

### Desired behavior

This project should have a contributing guide to help people know how to contribute in this project. 
Assign this issue to me, I would like to work on it!

**Comment by mrinalwadhwa** [comment]
@PiyushDive Thank you for checking. We have an organization wide contributing guide
https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md

Its linked from our README and is displayed by Github when you create a new issue or pull request:

README:
---
<img width="414" alt="Screenshot 2023-10-29 at 10 54 24 PM" src="https://github.com/build-trust/ockam/assets/159583/aba50024-24a8-432e-8302-2733e49ed813">

NEW ISSUE or Pull Request
---
<img width="284" alt="Screenshot 2023-10-29 at 10 54 08 PM" src="https://github.com/build-trust/ockam/assets/159583/86872fde-7336-4131-9679-3aea2b43c1a0">

Please read and try to follow it to make a contribution, we would love to hear suggestions on how it could be better. Closing this issue in the meantime.
