### ISSUE TITLE
Consider Zig / Zigler to remove NIF boilerplate 

### ISSUE THREAD

**Issue by mrinalwadhwa** [build-trust/ockam#682]
I came across some interesting posts from @ityonemo recently about using Zig for NIFs

https://twitter.com/DNAutics/status/1332130318107643905
https://twitter.com/DNAutics/status/1333296040754069504
https://github.com/ityonemo/zigler
https://github.com/ityonemo/zigler/blob/36c2fce9c83f113b59ec1bced7d60cd35a7936b0/test/integration/strategies/yielding_nif_test.exs#L11-L21

We should consider using it to remove our NIF boilerplate that invokes Rust
https://github.com/ockam-network/ockam/blob/develop/implementations/elixir/ockam/ockam_vault_software/native/vault/software/nifs.c

The use of `sigil_Z` is interesting and there is builtin support for "yielding NIFs" which is nice in case we end up with NIFs that take too long.

**Comment by mrinalwadhwa** [comment]
https://twitter.com/DNAutics/status/1348433701214904320?s=20

**Comment by SanjoDeundiak** [comment]
I think currently the decision is to go with rustler, which was done by @polvorin
