### ISSUE TITLE
Use explicit column list in `SELECT` SQL statements

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#6947]
In [this PR](https://github.com/build-trust/ockam/pull/6913) SQL support is introduced. We would like to use an explicit set of columns in every `SELECT` statements, since this helps to prevent mistakes

**Comment by MatthewLeboffe** [comment]
I'd like to work on this, please consider assigning it to me!

**Comment by YuheMa702** [comment]
Hello, Matthew and I are teammates. We are CMU students who need to contribute to an open-source project as part of our final project. If no other person is working on this issue yet, please consider assigning it to us. Thank you!

**Comment by mrinalwadhwa** [comment]
@MatthewLeboffe That's awesome, all yours.

Please let us know if your have any questions as you explore. You can also ask questions on the contributors discord https://discord.ockam.io

**Comment by Sweetsuro** [comment]
Hi! I'm working along with Matthew and Yuhe (issues 6947 and 6949) to help contribute to an open source project.

I had one question about this issue: is this more or less a refactoring change where every query of the form "SELECT *" should be changed to specify relevant columns? Would anything else be in scope?

**Comment by etorreborre** [comment]
Hi @Sweetsuro, yes that's it. Note that the persistence PR has now been merge on `develop`.
