### ISSUE TITLE
Rename `ockam reset --with-orchestrator` to `ockam reset --all`

### ISSUE THREAD

**Issue by nazmulidris** [build-trust/ockam#7013]
Running `ockam reset --with-orchestrator` deletes the local data as well as data in the Orchestrator cloud.

Rename the option name from `--with-orchestrator` to `--all`.

Here's a link to the source file: 

https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/reset.rs#L21

**Comment by rbran** [comment]
The PR https://github.com/build-trust/ockam/pull/7021 fix this. It's also possible to include `visible_alias = "with_orchestrator"` or `alias = "with_orchestrator"` so scripts using the old command continue to work.

**Comment by nazmulidris** [comment]
@rbran I just assigned this issue to you! 🙏🏽 Thank for raising:
- a PR w/ the fix https://github.com/build-trust/ockam/pull/7021
- and another PR to accept the CLA https://github.com/build-trust/ockam/pull/7022/files

You can also ask questions on the contributors discord https://discord.gg/RAbjRr3kds

**Comment by adrianbenavides** [comment]
> The PR https://github.com/build-trust/ockam/pull/7021 fix this. It's also possible to include visible_alias = "with_orchestrator" or alias = "with_orchestrator" so scripts using the old command continue to work.

Interesting, I didn't know about that attribute! For now, it's OK just to replace the argument name, as we haven't released the first stable `ockam command` version yet.

**Comment by mrinalwadhwa** [comment]
This was merged, thank you for an awesome first contribution @rbran 🥳
