### ISSUE TITLE
CI - Unable to run `enroll` command using published ockam docker image 

### ISSUE THREAD

**Issue by snandam** [build-trust/ockam#7034]
### Observed behavior

Version tested:  0.105.0

Running docker image hangs when trying to activate the browser. Not sure if this is supposed to work, but logging a bug here for awareness when someone tries to use the docker image to run commands specified in the documentation

### Steps to reproduce

```
> docker run ghcr.io/build-trust/ockam:0.105.0 "enroll"
Iabad3d0bf2347a800a0c67fdfa1dcc64e0fe3f73
     │ Then press  ENTER ↵  to open https://account.ockam.io/activate in your browser.
```

### Expected behavior

docker image is able to act as ockam command and run all supported commands

### Ockam Version

0.105.0

**Comment by metaclips** [comment]
To enroll using docker, you'll need to call `docker run` in interactive terminal mode, the command below enrolls and also project list
```bash
$: docker run -it -v $HOME/.ockam:/root/.ockam ghcr.io/build-trust/ockam:0.116.0 enroll
$: docker run -it -v $HOME/.ockam:/root/.ockam ghcr.io/build-trust/ockam:0.116.0 project list
```

**Comment by metaclips** [comment]
Closing this now
