### ISSUE TITLE
The `upgrade.json` file is not included in the release

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#7113]
### Observed behavior

We check [this file](https://github.com/build-trust/ockam/blob/f1cc52b5e336e34e224ef2c31ffb087acbf7a68c/implementations/rust/ockam/ockam_command/src/upgrade.rs#L27) in the command let the user know if there is an update available, but that file is not currently being included in the releases.

**Comment by metaclips** [comment]
We now use github api to get the latest release, closing now
