### ISSUE TITLE
Fix a typo in the "Provisioning a project" notification text  in the App

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#7266]
### Observer behavior

<img width="366" alt="Screenshot 2023-12-20 at 18 27 18" src="https://github.com/build-trust/ockam/assets/6513916/91d89f07-cd08-4f0e-9fad-90a56aed9f52">

### Steps to reproduce
Enroll with a new account and inspect macos notifications

### Expected behavior
Should be "up to 3 minutes."

### Ockam Version

0.114.0

**Comment by Ankit8848** [comment]
@mrinalwadhwa I want to work on it, Can you please assign it to me?

**Comment by mrinalwadhwa** [comment]
@Ankit8848 awesome, all yours.
