### ISSUE TITLE
`ockam node create --identity X` should fail if `X` doesn't exist

### ISSUE THREAD

**Issue by SanjoDeundiak** [build-trust/ockam#7625]
### Observed behavior

```
sanjo@mac ~ % ockam node create alice --identity alice
       Creating Node alice...

     ✔ Node alice created successfully

       To see more details on this node, run:
       ockam node show
```

### Steps to reproduce

Run
```
node create alice --identity alice
```
From a clean state

### Desired behavior

Node creation should fail and report a useful error to the user

### Ockam Version

0.116.0

**Comment by oguseynov** [comment]
Hi, I would like to give it try. could you please assign to me?

**Comment by nazmulidris** [comment]
@oguseynov That's awesome, this is all yours. Please let us know if you have any questions as you explore. You can also ask questions on the contributors discord https://discord.ockam.io

**Comment by oguseynov** [comment]
cla accepted in this [pr](https://github.com/build-trust/ockam/pull/7703)
fix in mentioned above.

**Comment by oguseynov** [comment]
@nazmulidris should I do something else to get forward with my pr's?

**Comment by etorreborre** [comment]
@oguseynov the CLA commit was signed with a github noreply address. I am trying to confirm if it is still valid since the commits in this PR are signed with your other email address. If you could sign the CLA PR commit with your regular email address I could approve it right away. and then we could proceed with your PRs.

**Comment by oguseynov** [comment]
@etorreborre sure, done for both pr's, signed with regular email address and re-pushed

**Comment by etorreborre** [comment]
Thanks a lot, I just approved the CLA PR
