### ISSUE TITLE
Report unused dependencies in CI

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#7809]
We should ensure that unused dependencies are reported and flagged in CI for every PR run, there are tools that checks for unused Rust dependencies e.g. https://github.com/bnjbvr/cargo-machete, we should check if it's a viable option or if there are better alternatives

**Comment by andor0** [comment]
I can do it.

**Comment by kaep** [comment]
Hi, this issue seems to be quite fixed despite being open. Can you confirm?
