### ISSUE TITLE
Update all CI runner image from ubuntu-20 to ubuntu-22

### ISSUE THREAD

**Issue by metaclips** [build-trust/ockam#8695]
[Ubuntu 20 will be deprecated in April 1, 2025](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-20-image-is-closing-down), we should update all CI workflows that use ubuntu-20.04 to ubuntu-22.04

**Comment by ilyaaay** [comment]
Hello. I want to take this issue

**Comment by metaclips** [comment]
All yours @ilyaaay

**Comment by ilyaaay** [comment]
I also have been updating all configs which used old ubuntu version. https://github.com/build-trust/ockam/pull/8702

**Comment by ilyaaay** [comment]
When I tested with new image version, I caught an error at **lint_commit** stage. 
![image](https://github.com/user-attachments/assets/65667758-5079-4bde-baa5-dbc4b9980a43)

**Comment by ilyaaay** [comment]
@metaclips  https://github.com/build-trust/ockam/pull/8709
