### ISSUE TITLE
Elixir: Attach outgoing connections to Ranch and implement Ockam.Worker on the handler

### ISSUE THREAD

**Issue by mjc** [build-trust/ockam#923]
Attaching outgoing connections to `:ranch` and implementing `Ockam.Worker` on the ranch handler will allow us to use the same handler for incoming and outgoing connections.

This has the side benefit of allowing us to use return routing to send responses back over the same connection as the original message.

**Comment by hairyhum** [comment]
Mixing TCP handlers and clients in the same implementation is not a good idea.

`Ockam.Worker` still can be implemented for TCP handlers.
